Repository berty/berty, pull requests merged in 2020-08, with the labels that each got.

#2197 feat: setup android bridge protocol
  .buildkite/pipeline.yml
  js/Makefile
  js/gen.sum
  js/packages/berty-app/android/app/build.gradle
  js/packages/berty-app/android/app/src/main/AndroidManifest.xml
  js/packages/berty-app/android/app/src/main/java/tech/berty/app/MainApplication.java
  js/packages/berty-app/android/app/src/main/res/xml/network_security_config.xml
  js/packages/berty-app/android/settings.gradle
  js/packages/berty-app/ios/Podfile.lock
  js/packages/berty-app/package.json
  js/packages/components/Onboarding.tsx
  js/packages/components/chat/ChatGroup.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/shared-components/Chat.tsx
  js/packages/components/main/HomeModal.tsx
  js/packages/components/modals/ManageDeepLink.tsx
  js/packages/components/package.json
  js/packages/components/settings/EditProfile.tsx
  js/packages/components/shared-components/BlurView.android.tsx
  js/packages/components/shared-components/BlurView.tsx
  js/packages/components/shared-components/Modal.tsx
  js/packages/go-bridge/android/src/main/java/tech/berty/gobridge/GoBridgeModule.java
  js/packages/go-bridge/android/src/main/java/tech/berty/gobridge/LoggerDriver.java
  js/packages/go-bridge/android/src/main/java/tech/berty/gobridge/LoggerLevel.java
  js/packages/go-bridge/ios/GoBridge.swift
  js/packages/go-bridge/types.ts
  js/packages/store/protocol/client.js
  js/packages/storybook-mobile/package.json
  js/yarn.lock
  tool/berty-mini-local-helper/Makefile
  tool/build/shell/release-android.sh
Labels: enhancement, 🔍 Ready for Review

#2184 fix(messenger): handle group invitation message in 1to1 conv
  js/packages/components/chat/ChatGroup.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/shared-components/Chat.tsx
  js/packages/components/chat/shared-components/Message.tsx
  js/packages/components/faker.js
  js/packages/components/main/CreateGroupFinalize.tsx
  js/packages/hooks/conversation.ts
  js/packages/store/groups.js
  js/packages/store/messenger/contact.js
  js/packages/store/messenger/conversation.js
Labels: bug, ✅ Approved

#2202 feat: start moving store logic from JS to Go
  api/bertymessenger.proto
  api/bertymessenger.yaml
  docs/gen.sum
  docs/messenger/api.md
  docs/messenger/bertymessenger.swagger.json
  go.mod
  go.sum
  go/cmd/berty/daemon.go
  go/cmd/berty/mini/main.go
  go/cmd/berty/mini/view_group.go
  go/cmd/berty/mini/view_group_outgoing.go
  go/cmd/berty/shareinvite.go
  go/cmd/berty/systeminfo.go
  go/framework/bertybridge/bridge_protocol.go
  go/framework/bertybridge/bridge_test.go
  go/framework/bertybridge/testing_test.go
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/bertymessenger.pb.gw.go
  go/pkg/bertymessenger/bertymessenger_type.go
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/error.go
  go/pkg/bertymessenger/handlers.go
  go/pkg/bertymessenger/notifiee.go
  go/pkg/bertymessenger/notifiee_test.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertymessenger/service_test.go
  go/pkg/bertymessenger/testing.go
  go/pkg/bertymessenger/testing_test.go
  js/gen.sum
  js/packages/api/index.gen.js
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/codegen/index.gen.js
  js/packages/components/faker.gen.tsx
  js/packages/go-bridge/android/src/main/java/tech/berty/gobridge/GoBridgeModule.java
  js/packages/go-bridge/ios/GoBridge.swift
  js/packages/store/messenger/MessengerServiceSagaClient.gen.js
  js/packages/store/messenger/client.gen.js
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb.d.ts
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb.js
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb_service.d.ts
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb_service.js
Labels: enhancement, 🔍 Ready for Review

#2175 fix: scenario tests related bugs
  api/errcode.proto
  docs/gen.sum
  go.mod
  go.sum
  go/cmd/berty/daemon.go
  go/cmd/berty/main.go
  go/cmd/berty/mini/main.go
  go/cmd/berty/mini/view_group.go
  go/cmd/berty/shareinvite.go
  go/cmd/berty/systeminfo.go
  go/framework/bertybridge/bridge.go
  go/framework/bertybridge/bridge_protocol.go
  go/framework/bertybridge/bridge_test.go
  go/framework/bertybridge/client.go
  go/framework/bertybridge/testing_test.go
  go/gen.sum
  go/internal/grpcutil/buf_listener.go
  go/internal/handshake/handshake_test.go
  go/internal/handshake/handshake_util_test.go
  go/internal/ipfsutil/conn_logger.go
  go/internal/ipfsutil/mdns_discovery.go
  go/internal/ipfsutil/testing.go
  go/internal/multipeer-connectivity-transport/discovery.go
  go/pkg/bertymessenger/api_test.go
  go/pkg/bertyprotocol/api_event.go
  go/pkg/bertyprotocol/blackbox_test.go
  go/pkg/bertyprotocol/client.go
  go/pkg/bertyprotocol/contact_request_manager.go
  go/pkg/bertyprotocol/keystore_message.go
  go/pkg/bertyprotocol/keystore_message_utils_test.go
  go/pkg/bertyprotocol/orbitdb_test.go
  go/pkg/bertyprotocol/orbitdb_utils_test.go
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertyprotocol/store_metadata.go
  go/pkg/bertyprotocol/testing.go
  go/pkg/bertyprotocol/testing_test.go
  go/pkg/bertyprotocol/tinder_swiper.go
  go/pkg/bertyprotocol/tinder_swiper_test.go
  go/pkg/errcode/errcode.pb.go
Labels: bug, 🔍 Ready for Review

#2207 fix(messenger): textinput message
  js/packages/components/chat/ChatGroup.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/shared-components/Chat.tsx
Labels: bug, 🔍 Ready for Review

#2201 feat: add native grpc bridge
  .github/workflows/go.yml
  api/bertybridge.proto
  api/bertymessenger.proto
  api/bertymessenger.yaml
  docs/gen.sum
  docs/messenger/api.md
  docs/messenger/bertymessenger.swagger.json
  go/Makefile
  go/framework/bertybridge/bridge.go
  go/framework/bertybridge/bridge_service.go
  go/framework/bertybridge/client.go
  go/framework/bertybridge/internal/bridgepb/bertybridge.pb.go
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/bertymessenger.pb.gw.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/bertyprotocol/testing_test.go
  js/Makefile
  js/gen.sum
  js/packages/api/index.gen.js
  js/packages/api/index.gen.js.hbs
  js/packages/api/index.js
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/berty-app/ios/Podfile.lock
  js/packages/codegen/index.gen.js
  js/packages/components/faker.gen.tsx
  js/packages/components/settings/DevTools.tsx
  js/packages/go-bridge/ios/GoBridge.m
  js/packages/go-bridge/ios/GoBridge.swift
  js/packages/go-bridge/ios/GoBridge.xcodeproj/project.pbxproj
  js/packages/go-bridge/ios/PromiseBlock.swift
  js/packages/grpc-bridge/index.ts
  js/packages/grpc-bridge/middleware/example/example.js
  js/packages/grpc-bridge/middleware/example/index.js
  js/packages/grpc-bridge/middleware/index.js
  js/packages/grpc-bridge/middleware/logs/index.js
  js/packages/grpc-bridge/middleware/logs/logs.js
  js/packages/grpc-bridge/middleware/middleware.js
  js/packages/grpc-bridge/rpc/index.js
  js/packages/grpc-bridge/rpc/rpc.bridge.js
  js/packages/grpc-bridge/rpc/rpc.grpcweb.ts
  js/packages/grpc-bridge/rpc/rpc.native.js
  js/packages/grpc-bridge/rpc/rpc.noop.js
  js/packages/grpc-bridge/rpc/utils.js
  js/packages/grpc-bridge/service.js
  js/packages/store/messenger/MessengerServiceSagaClient.gen.js
  js/packages/store/messenger/client.gen.js
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb.d.ts
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb.js
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb_service.d.ts
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb_service.js
Labels: enhancement, ✅ Approved

#2205 chore: bump go@1.14.7
  .github/workflows/go.yml
  .github/workflows/release.yml
  Dockerfile
  tool/docker-build-go/Dockerfile
  tool/docker-build-go/Makefile
Labels: chore, 🔍 Ready for Review

#2206 chore: fix tool/mini-local-helper makefile
  tool/berty-mini-local-helper/Makefile
Labels: chore, 🔍 Ready for Review

#2214 stability fixes
  go.mod
  go.sum
  go/pkg/bertymessenger/service_test.go
  go/pkg/bertyprotocol/api_event.go
  go/pkg/bertyprotocol/group.go
  go/pkg/bertyprotocol/keystore_message.go
  go/pkg/bertyprotocol/keystore_message_utils.go
  go/pkg/bertyprotocol/keystore_message_utils_test.go
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/bertyprotocol/store_message.go
  go/pkg/bertyprotocol/store_metadata.go
Labels: ✅ Approved, 🔍 Ready for Review

#2215 chore: add new linguist-generated files to .gitattributes
  .gitattributes
Labels: chore, 🔍 Ready for Review

#2212 chore: adding unit tests for cryptoutil
  go/internal/cryptoutil/cryptoutil_test.go
Labels: chore, ✅ Approved

#2208 continue moving the app's logic to golang
  .gitignore
  api/bertymessenger.proto
  api/bertymessenger.yaml
  docs/gen.sum
  docs/messenger/api.md
  docs/messenger/bertymessenger.swagger.json
  go/gen.sum
  go/internal/testutil/logging.go
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/app_handlers.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/bertymessenger.pb.gw.go
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/handlers.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertymessenger/service_test.go
  go/pkg/bertymessenger/testing.go
  go/pkg/bertyprotocol/contact_request_manager_test.go
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/bertyprotocol/testing.go
  go/pkg/bertyprotocol/testing_test.go
  js/gen.sum
  js/packages/api/index.gen.js
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/berty-app/ios/Podfile.lock
  js/packages/codegen/index.gen.js
  js/packages/components/faker.gen.tsx
  js/packages/components/faker.js
  js/packages/components/shared-components/BlurView.tsx
  js/packages/grpc-bridge/middleware/index.js
  js/packages/grpc-bridge/service.js
  js/packages/store/groups.js
  js/packages/store/messenger/MessengerServiceSagaClient.gen.js
  js/packages/store/messenger/client.gen.js
  js/packages/store/messenger/index.js
  js/packages/store/protocol/client.js
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb.d.ts
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb.js
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb_service.d.ts
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb_service.js
  js/packages/store/utils.js
  js/packages/web-dev-app/config/webpack.config.js
  js/packages/web-dev-app/package.json
  js/packages/web-dev-app/src/App.tsx
  js/packages/web-dev-app/src/context.js
  js/packages/web-dev-app/src/index.js
  js/yarn.lock
Labels: messenger, ✅ Approved

#2217 chore: get rid of 'go mod vendor' (vendor/ dir)
  .buildkite/pipeline.yml
  .gitattributes
  .github/workflows/protobuf.yml
  api/bertybridge.proto
  api/bertymessenger.proto
  api/bertytypes.proto
  api/errcode.proto
  api/go-internal/handshake.proto
  api/go-internal/records.proto
  docs/Makefile
  docs/gen.sum
  go.sum
  go/.dockerignore
  go/Makefile
  go/framework/bertybridge/internal/bridgepb/bertybridge.pb.go
  go/gen.sum
  go/internal/handshake/handshake.pb.go
  go/internal/tinder/records.pb.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertytypes/bertytypes.pb.go
  go/pkg/errcode/errcode.pb.go
  js/Makefile
  js/gen.sum
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb.d.ts
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb.js
  js/packages/store/protocol/grpc-web-gen/bertytypes_pb.d.ts
  js/packages/store/protocol/grpc-web-gen/bertytypes_pb.js
  js/packages/store/protocol/grpc-web-gen/github.com/gogo/protobuf/gogoproto/gogo_pb_service.d.ts
  js/packages/store/protocol/grpc-web-gen/github.com/gogo/protobuf/gogoproto/gogo_pb_service.js
  js/packages/store/protocol/grpc-web-gen/gogoproto/gogo_pb.d.ts
  js/packages/store/protocol/grpc-web-gen/gogoproto/gogo_pb.js
  js/packages/store/protocol/grpc-web-gen/gogoproto/gogo_pb_service.d.ts
  js/packages/store/protocol/grpc-web-gen/gogoproto/gogo_pb_service.js
Labels: chore, ✅ Approved

#2221 chore: improve Makefile reliability on various systems
  docs/Makefile
  docs/gen.sum
  go/Makefile
  go/gen.sum
  js/Makefile
  js/gen.sum
Labels: chore, 🔍 Ready for Review

#2220 chore: refactor berty messenger
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/api_test.go
  go/pkg/bertymessenger/app_handlers.go
  go/pkg/bertymessenger/error.go
  go/pkg/bertymessenger/handlers.go
  go/pkg/bertymessenger/notifiee.go
  go/pkg/bertymessenger/notifiee_test.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertymessenger/service_test.go
  go/pkg/bertymessenger/types.go
  go/pkg/bertymessenger/util.go
  go/pkg/bertyprotocol/scenario_test.go
Labels: chore, ✅ Approved

#2222 fully port web-dev-app to go store
  js/packages/grpc-bridge/rpc/rpc.grpcweb.ts
  js/packages/web-dev-app/public/index.html
  js/packages/web-dev-app/src/App.tsx
  js/packages/web-dev-app/src/context.js
  js/packages/web-dev-app/src/hooks.js
Labels: chore, ✅ Approved

#2209 fix(messenger): universal link
  js/packages/berty-app/ios/Berty Debug.entitlements
  js/packages/berty-app/ios/Berty Staff.entitlements
  js/packages/berty-app/ios/Berty Yolo.entitlements
  js/packages/berty-app/ios/Berty.xcodeproj/project.pbxproj
  js/packages/berty-app/ios/Berty/Berty.entitlements
  js/packages/navigation/container.tsx
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
Labels: ✅ Approved

#2230 chore: simplify and update gomombile to support go1.15
  go.mod
  go.sum
  go/internal/tools/tools.go
  js/Makefile
  js/gen.sum
  js/packages/go-bridge/go.mod
  js/packages/go-bridge/go.sum
  js/packages/go-bridge/tools.go
Labels: chore, 🔍 Ready for Review

#2232 fix(messenger): system info and methods hooks
  js/packages/components/settings/DevTools.tsx
  js/packages/components/settings/SystemInfo.tsx
  js/packages/store/methods.js
Labels: bug, ✅ Approved

#2233 chore: fix typo
  js/packages/components/gates.tsx
  js/packages/store/provider.tsx
Labels: chore, ✅ Approved

#2213 feat: setup background fetch
  go/framework/bertybridge/bridge_protocol.go
  go/framework/bertybridge/driver_lifecycle.go
  go/internal/config/berty.go
  go/internal/tracer/tracer.go
  js/Makefile
  js/gen.sum
  js/packages/berty-app/ios/Berty DebugDebug.entitlements
  js/packages/berty-app/ios/Berty-Bridging-Header.h
  js/packages/berty-app/ios/Berty.xcodeproj/project.pbxproj
  js/packages/berty-app/ios/Berty/AppDelegate.m
  js/packages/berty-app/ios/Berty/Info.plist
  js/packages/berty-app/ios/Berty/LifeCycle.swift
  js/packages/berty-app/ios/Berty/main.m
  js/packages/berty-app/ios/File.swift
  js/packages/berty-app/ios/LocalNotificationManager.swift
  js/packages/berty-app/ios/Podfile.lock
  js/packages/go-bridge/go-bridge.podspec
  js/packages/go-bridge/ios/GoBridge.swift
  js/packages/go-bridge/ios/GoBridge.xcodeproj/project.pbxproj
  js/packages/go-bridge/ios/LifeCycleDriver.swift
  js/packages/go-bridge/ios/LoggerDriver.swift
  js/packages/store/provider.tsx
Labels: enhancement, 🔍 Ready for Review

#2235 fix(messenger): restore contact request
  go/pkg/bertymessenger/service.go
  js/Makefile
  js/gen.sum
  js/packages/components/main/Home.tsx
  js/packages/components/main/HomeModal.tsx
  js/packages/components/main/Scan.tsx
  js/packages/components/main/ScanRequest.tsx
  js/packages/components/main/index.ts
  js/packages/components/modals/AddThisContact.tsx
  js/packages/components/modals/InvalidScan.tsx
  js/packages/components/modals/ManageDeepLink.tsx
  js/packages/components/modals/SendContactRequest.tsx
  js/packages/components/modals/index.ts
  js/packages/components/settings/DevTools.tsx
  js/packages/components/storybook.tsx
  js/packages/navigation/hook.ts
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
  js/packages/store/hooks.js
  js/packages/store/methods.js
Labels: bug, messenger, 🔍 Ready for Review

#2236 fix(messenger): restore contact search
  js/packages/components/main/Search.tsx
Labels: bug, messenger, ✅ Approved

#2237 fix(messenger): restore multimember creation
  js/packages/components/main/CreateGroupAddMembers.tsx
  js/packages/components/main/CreateGroupFinalize.tsx
  js/packages/navigation/stacks.tsx
  js/packages/store/hooks.js
Labels: bug, messenger, 🔍 Ready for Review

#2238 messenger: improve go store
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/handlers.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertymessenger/service_test.go
  go/pkg/bertymessenger/util.go
Labels: messenger, ✅ Approved

#2240 chore(messenger): conversation list UI with new store
  js/packages/components/main/Home.tsx
  js/packages/components/shared-components/ProceduralCircleAvatar.tsx
  js/packages/store/hooks.js
  js/packages/web-dev-app/src/App.tsx
Labels: chore, messenger, 🔍 Ready for Review

#2234 chore(messenger): port data faker to new store
  js/gen.sum
  js/packages/components/faker.gen.tsx
  js/packages/components/faker.gen.tsx.hbs
  js/packages/components/faker.js
  js/packages/components/settings/DevTools.tsx
  js/packages/components/settings/FakeData.js
  js/packages/components/settings/index.ts
  js/packages/navigation/hook.ts
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
  js/packages/store/faker.js
  js/packages/store/hooks.js
  js/packages/store/provider.tsx
Labels: chore, messenger, 🔍 Ready for Review

#2241 chore: refactor bertymessenger tests
  api/bertymessenger.proto
  docs/gen.sum
  go/gen.sum
  go/internal/testutil/logging.go
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/handlers.go
  go/pkg/bertymessenger/service_test.go
  go/pkg/bertymessenger/testing.go
  go/pkg/bertymessenger/testing_test.go
  go/pkg/bertymessenger/types.go
  go/pkg/bertymessenger/util.go
  js/Makefile
  js/gen.sum
  js/packages/api/index.pb.js
Labels: chore, 🔍 Ready for Review

#2244 fix(webdev): conversation retrieval and creation bugs in webdev app
  js/packages/web-dev-app/src/App.tsx
Labels: bug, messenger, ✅ Approved

#2246 messenger: restore interaction list
  js/Makefile
  js/gen.sum
  js/packages/components/chat/ChatGroup.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/shared-components/Chat.tsx
  js/packages/components/chat/shared-components/Message.tsx
  js/packages/components/main/Home.tsx
  js/packages/components/settings/DevText.tsx
  js/packages/components/settings/DevTools.tsx
  js/packages/store/faker.js
  js/packages/store/hooks.js
  js/packages/store/provider.tsx
Labels: messenger, 🔍 Ready for Review

#2239 chore(bertymessenger): create Conversation when Contact is Established
  api/bertymessenger.proto
  docs/gen.sum
  docs/messenger/api.md
  docs/messenger/bertymessenger.swagger.json
  go.sum
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/handlers.go
  go/pkg/bertymessenger/service_test.go
  go/pkg/bertymessenger/types.go
  js/gen.sum
  js/packages/api/index.gen.js
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/codegen/index.gen.js
  js/packages/components/chat/ChatGroup.tsx
  js/packages/components/chat/ChatSettings.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/shared-components/Chat.tsx
  js/packages/components/chat/shared-components/Message.tsx
  js/packages/components/main/Home.tsx
  js/packages/store/faker.js
  js/packages/store/hooks.js
  js/packages/store/oldhooks/conversation.ts
  js/packages/store/provider.tsx
  js/packages/web-dev-app/src/App.tsx
Labels: chore, 🔍 Ready for Review

#2249 chore(messenger): restore multimember invitation messages
  go/pkg/bertymessenger/api.go
  js/packages/components/main/CreateGroupFinalize.tsx
  js/packages/store/hooks.js
  js/packages/web-dev-app/src/App.tsx
Labels: chore, 🔍 Ready for Review

#2250 chore: mark some tests as unstable, they work great locally but sometimes fail on the CI
  go/pkg/bertymessenger/service_test.go
Labels: chore, 🔍 Ready for Review

#2248 messenger: restore multimember share
  api/bertymessenger.proto
  docs/gen.sum
  docs/messenger/bertymessenger.swagger.json
  go/gen.sum
  go/pkg/bertymessenger/bertymessenger.pb.go
  js/gen.sum
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/MultiMemberQR.tsx
  js/packages/components/chat/MultiMemberSettings.tsx
  js/packages/components/chat/index.ts
  js/packages/components/modals/InvalidScan.tsx
  js/packages/components/modals/ManageDeepLink.tsx
  js/packages/components/modals/ManageGroupInvitation.tsx
  js/packages/components/storybook.tsx
  js/packages/navigation/hook.ts
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
  js/packages/store/methods.js
Labels: chore, messenger, 🔍 Ready for Review

#2251 fix: bump go-orbit-db and go-ipfs-log
  go.mod
  go.sum
Labels: bug, 🔍 Ready for Review

#2252 chore(messenger): update contact and 1to1 settings to new store
  js/packages/components/chat/ChatSettings.tsx
  js/packages/components/chat/ContactSettings.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/OneToOneSettings.tsx
  js/packages/components/chat/index.ts
  js/packages/navigation/hook.ts
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
  js/packages/store/hooks.js
Labels: chore, 🔍 Ready for Review

#2254 chore(messenger): restore send to all devtool
  js/packages/components/settings/DevTools.tsx
  js/packages/web-dev-app/src/App.tsx
Labels: chore, messenger, ✅ Approved

#2255 chore: display errors and above on unit tests by default
  go/internal/testutil/logging.go
Labels: chore, 🔍 Ready for Review

#2253 messenger: restore members
  api/bertymessenger.proto
  docs/gen.sum
  docs/messenger/api.md
  docs/messenger/bertymessenger.swagger.json
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/handlers.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertymessenger/service_test.go
  go/pkg/bertymessenger/testing.go
  go/pkg/bertymessenger/types.go
  js/gen.sum
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/MultiMemberSettings.tsx
  js/packages/components/chat/shared-components/Message.tsx
  js/packages/components/settings/DevTools.tsx
  js/packages/store/context.js
  js/packages/store/faker.js
  js/packages/store/hooks.js
  js/packages/store/provider.tsx
Labels: messenger, 🔍 Ready for Review

#2256 fix(messenger): hang at boot
  go/pkg/bertymessenger/service.go
Labels: bug, 🔍 Ready for Review

#2242 feat: add logs to db replay in messenger
  api/errcode.proto
  docs/gen.sum
  go.sum
  go/cmd/berty/mini.go
  go/cmd/berty/mini/main.go
  go/cmd/berty/opts.go
  go/gen.sum
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/handlers.go
  go/pkg/bertymessenger/replay.go
  go/pkg/bertymessenger/util.go
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/errcode/errcode.pb.go
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
Labels: enhancement, 🔍 Ready for Review

#2247 feat: conversation open/close (read status)
  api/bertymessenger.proto
  api/bertymessenger.yaml
  docs/gen.sum
  docs/messenger/api.md
  docs/messenger/bertymessenger.swagger.json
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/bertymessenger.pb.gw.go
  go/pkg/bertymessenger/handlers.go
  go/pkg/bertymessenger/service_test.go
  go/pkg/bertymessenger/types.go
  go/pkg/bertyprotocol/orbitdb_utils_test.go
  js/gen.sum
  js/packages/api/index.gen.js
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/codegen/index.gen.js
Labels: enhancement, 🔍 Ready for Review

#2257 fix(messenger): add sent_date on AppMessage directly and fix usage
  api/bertymessenger.proto
  docs/gen.sum
  docs/messenger/api.md
  go/cmd/berty/mini/view_group.go
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/handlers.go
  go/pkg/bertymessenger/service_test.go
  go/pkg/bertymessenger/types.go
  js/gen.sum
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/components/chat/shared-components/Message.tsx
  js/packages/store/faker.js
Labels: bug, 🔍 Ready for Review

#2258 chore: speedup gomobile
  js/Makefile
  js/gen.sum
Labels: chore, 🔍 Ready for Review
