Repository berty/berty, pull requests merged in 2020-09, with the labels that each got.

#2259 chore: various improvements on bertymessenger
  .gitignore
  go.mod
  go.sum
  go/Makefile
  go/gen.sum
  go/internal/testutil/logging.go
  go/internal/testutil/skip.go
  go/internal/testutil/util.go
  go/internal/tools/tools.go
  go/pkg/bertymessenger/handlers.go
  go/pkg/bertymessenger/service_test.go
Labels: chore, 🔍 Ready for Review

#2263 fix(messenger): activate groups on boot
  go/pkg/bertymessenger/service.go
Labels: bug, ✅ Approved

#2245 feat: better lifecycle
  go/cmd/berty/daemon.go
  go/cmd/berty/main.go
  go/framework/bertybridge/bridge_protocol.go
  go/framework/bertybridge/driver_lifecycle.go
  js/packages/berty-app/ios/Berty/LifeCycle.swift
  js/packages/go-bridge/ios/LifeCycleDriver.swift
Labels: enhancement, 🔍 Ready for Review

#2261 feat: improve scenario test
  .github/workflows/go.yml
  go/Makefile
  go/framework/bertybridge/bridge_test.go
  go/gen.sum
  go/internal/handshake/handshake_test.go
  go/internal/testutil/skip.go
  go/pkg/bertymessenger/service_test.go
  go/pkg/bertyprotocol/contact_request_manager_test.go
  go/pkg/bertyprotocol/keystore_message_utils_test.go
  go/pkg/bertyprotocol/orbitdb_many_adds_berty_test.go
  go/pkg/bertyprotocol/orbitdb_test.go
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/bertyprotocol/store_message_test.go
  go/pkg/bertyprotocol/store_metadata_test.go
  go/pkg/bertyprotocol/tinder_swiper_test.go
Labels: enhancement, ✅ Approved, 🔍 Ready for Review

#2262 fix: Panic in WaitGroup in the Multipeer Connectivity transport
  go/cmd/berty/mini/main.go
  go/framework/bertybridge/bridge_protocol.go
  go/internal/config/berty.go
  go/internal/ipfsutil/repo.go
  go/internal/multipeer-connectivity-transport/transport.go
Labels: bug, ✅ Approved

#2266 chore: test unstable tests on CI
  .github/workflows/go.yml
  go/Makefile
  go/gen.sum
  go/pkg/bertymessenger/README.md
  go/pkg/bertymessenger/service_test.go
  go/pkg/bertyprotocol/README.md
Labels: chore, 🔍 Ready for Review

#2260 messenger: add interactions backlog
  api/bertymessenger.proto
  docs/gen.sum
  docs/messenger/api.md
  docs/messenger/bertymessenger.swagger.json
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/handlers.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertymessenger/service_test.go
  go/pkg/bertymessenger/testing.go
  js/gen.sum
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/components/gates.tsx
  js/packages/store/provider.tsx
Labels: bug, messenger, ✅ Approved

#2267 feat: Added a quote.
  go/pkg/banner/quote.go
Labels: enhancement, ✅ Approved

#2271 messenger: restore conversations thumbnails
  js/.eslintignore
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/main/Home.tsx
  js/packages/components/settings/DevTools.tsx
  js/packages/store/hooks.js
  js/packages/store/provider.tsx
Labels: messenger, 🔍 Ready for Review

#2268 test: Adding test to avoid duplicate quote.
  go/pkg/banner/quote_test.go
Labels: test, ✅ Approved

#2273 fix(messenger): restore requests
  js/packages/components/main/ContactRequest.tsx
  js/packages/components/main/HomeModal.tsx
  js/packages/components/shared-components/Request.tsx
  js/packages/store/provider.tsx
Labels: bug, messenger, ✅ Approved

#2274 fix(messenger): close bridge on startup error
  go/framework/bertybridge/bridge_protocol.go
  js/packages/components/gates.tsx
  js/packages/components/main/HomeModal.tsx
  js/packages/components/main/RequestSent.tsx
  js/packages/components/shared-components/Request.tsx
Labels: bug, 🔍 Ready for Review

#2270 feat: refactor logger
  go.mod
  go.sum
  go/cmd/berty/daemon.go
  go/cmd/berty/main.go
  go/cmd/berty/mini.go
  go/cmd/berty/mini/main.go
  go/cmd/berty/opts.go
  go/cmd/rdvp/main.go
  go/framework/bertybridge/bridge.go
  go/framework/bertybridge/bridge_protocol.go
  go/framework/bertybridge/bridge_test.go
  go/framework/bertybridge/driver_logger.go
  go/internal/ipfsutil/testing.go
  go/internal/logutil/logutil.go
  go/internal/logutil/logutil_test.go
  go/internal/testutil/logging.go
  go/internal/testutil/skip.go
  go/internal/testutil/util.go
  go/internal/tinder/driver_multi_test.go
  go/pkg/bertymessenger/api_test.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertymessenger/service_test.go
  go/pkg/bertymessenger/testing.go
  go/pkg/bertymessenger/testing_test.go
  go/pkg/bertyprotocol/blackbox_test.go
  go/pkg/bertyprotocol/contact_request_manager_test.go
  go/pkg/bertyprotocol/orbitdb_test.go
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertyprotocol/store_metadata_test.go
  go/pkg/bertyprotocol/testing.go
  go/pkg/bertyprotocol/tinder_swiper_test.go
  js/.gitkeep
  js/packages/codegen/helpers/.gitkeep
  js/packages/go-bridge/android/src/main/java/tech/berty/gobridge/GoBridgeModule.java
  js/packages/go-bridge/ios/GoBridge.swift
  js/packages/go-bridge/types.ts
  js/packages/store/provider.tsx
  tool/berty-mini-local-helper/Makefile
  tool/berty-mini-web/berty-mini
  tool/deployments/.gitkeep
  tool/deployments/rdvp-dev/docker-compose.yml
  tool/test/experiment/dht/test/.gitkeep
  tool/test/testdata/.gitkeep
Labels: enhancement, 🔍 Ready for Review

#2276 messenger: restore state dates (created, sent)
  api/bertymessenger.proto
  docs/gen.sum
  docs/messenger/api.md
  docs/messenger/bertymessenger.swagger.json
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/handlers.go
  js/gen.sum
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/main/Home.tsx
  js/packages/components/main/HomeModal.tsx
  js/packages/components/shared-components/ProceduralCircleAvatar.tsx
Labels: bug, messenger, ✅ Approved

#2277 chore: refactor unstable tests workflow
  go.mod
  go.sum
  go/Makefile
  go/gen.sum
  go/internal/tools/tools.go
  go/pkg/bertymessenger/service_test.go
Labels: chore, 🔍 Ready for Review

#2278 fix(messenger): restore and improve search
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/main/Home.tsx
  js/packages/components/main/Search.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/shared-components/Footer.tsx
  js/packages/navigation/types.ts
  js/packages/store/hooks.js
Labels: bug, 🔍 Ready for Review

#2275 fix: improve subscribe + some small improvement for logging/testing
  go/pkg/bertymessenger/testing.go
  go/pkg/bertyprotocol/contact_request_manager.go
  go/pkg/bertyprotocol/service_group.go
  go/pkg/bertyprotocol/store_message.go
  go/pkg/bertyprotocol/store_message_test.go
  go/pkg/bertyprotocol/store_metadata.go
Labels: bug, ✅ Approved

#2279 chore: add a makefile helper to check if broken tests are still broken
  go.mod
  go.sum
  go/Makefile
  go/gen.sum
Labels: chore, 🔍 Ready for Review

#2284 fix: fine-tune the logger
  go.mod
  go.sum
  go/internal/logutil/logutil.go
  go/internal/logutil/logutil_test.go
  go/internal/testutil/logging.go
  go/pkg/bertyprotocol/testing.go
Labels: bug, 🔍 Ready for Review

#2280 feat: update react native 0.61.5 -> 0.63.2
  .gitattributes
  js/package.json
  js/packages/babel-preset/package.json
  js/packages/berty-app/.flowconfig
  js/packages/berty-app/android/app/build.gradle
  js/packages/berty-app/android/app/src/debug/java/tech/berty/app/ReactNativeFlipper.java
  js/packages/berty-app/android/app/src/main/AndroidManifest.xml
  js/packages/berty-app/android/app/src/main/java/tech/berty/app/MainApplication.java
  js/packages/berty-app/android/build.gradle
  js/packages/berty-app/android/gradle.properties
  js/packages/berty-app/android/gradle/wrapper/gradle-wrapper.jar
  js/packages/berty-app/android/gradle/wrapper/gradle-wrapper.properties
  js/packages/berty-app/android/gradlew
  js/packages/berty-app/android/gradlew.bat
  js/packages/berty-app/ios/Berty-tvOSTests/Info.plist
  js/packages/berty-app/ios/Berty.xcodeproj/project.pbxproj
  js/packages/berty-app/ios/Berty/AppDelegate.m
  js/packages/berty-app/ios/BertyTests/BertyTests.m
  js/packages/berty-app/ios/Podfile
  js/packages/berty-app/ios/Podfile.lock
  js/packages/berty-app/metro.config.js
  js/packages/berty-app/package.json
  js/packages/components/package.json
  js/packages/go-bridge/android/build.gradle
  js/packages/go-bridge/android/gradle.properties
  js/packages/go-bridge/package.json
  js/packages/navigation/package.json
  js/packages/react-native-example/android/.project
  js/packages/react-native-example/android/.settings/org.eclipse.buildship.core.prefs
  js/packages/react-native-example/android/build.gradle
  js/packages/react-native-example/package.json
  js/packages/store/package.json
  js/packages/storybook-mobile/.flowconfig
  js/packages/storybook-mobile/android/app/build.gradle
  js/packages/storybook-mobile/android/app/src/debug/java/com/storybook/ReactNativeFlipper.java
  js/packages/storybook-mobile/android/app/src/main/AndroidManifest.xml
  js/packages/storybook-mobile/android/app/src/main/java/com/storybook/MainApplication.java
  js/packages/storybook-mobile/android/build.gradle
  js/packages/storybook-mobile/android/gradle.properties
  js/packages/storybook-mobile/android/gradle/wrapper/gradle-wrapper.jar
  js/packages/storybook-mobile/android/gradle/wrapper/gradle-wrapper.properties
  js/packages/storybook-mobile/android/gradlew
  js/packages/storybook-mobile/android/gradlew.bat
  js/packages/storybook-mobile/ios/Podfile
  js/packages/storybook-mobile/ios/Podfile.lock
  js/packages/storybook-mobile/ios/storybook-tvOSTests/Info.plist
  js/packages/storybook-mobile/ios/storybook.xcodeproj/project.pbxproj
  js/packages/storybook-mobile/ios/storybook/AppDelegate.h
  js/packages/storybook-mobile/ios/storybook/AppDelegate.m
  js/packages/storybook-mobile/ios/storybook/main.m
  js/packages/storybook-mobile/ios/storybookTests/storybookTests.m
  js/packages/storybook-mobile/metro.config.js
  js/packages/storybook-mobile/package.json
  js/packages/storybook-web/package.json
  js/packages/styles/package.json
  js/packages/web-dev-app/package.json
  js/yarn.lock
Labels: enhancement, ✅ Approved

#2285 ci: Add niceness to the buildkite.
  .buildkite/pipeline.yml
Labels: ci, ✅ Approved

#2283 fix(messenger): hyperlinks
  js/packages/components/chat/shared-components/Message.tsx
  js/packages/components/package.json
  js/yarn.lock
Labels: bug, 🔍 Ready for Review

#2286 fix(messenger): avatar icon for multimember conversation
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/MultiMemberSettings.tsx
  js/packages/components/main/Avatar_Group_Copy_19.png
  js/packages/components/main/Home.tsx
Labels: bug, 🔍 Ready for Review

#2290 fix(messenger): Handle long contact name display
  js/packages/components/main/CreateGroupAddMembers.tsx
  js/packages/components/main/CreateGroupFinalize.tsx
  js/packages/components/main/Home.tsx
  js/packages/components/main/HomeModal.tsx
  js/packages/components/shared-components/Request.tsx
  js/packages/store/hooks.js
  js/packages/store/methods.js
Labels: bug, messenger, messenger-ui-cosmetic, 🔍 Ready for Review

#2289 fix: race condition in the MultipeerConnectivity transporter
  go/internal/multipeer-connectivity-transport/connmgr.go
  go/internal/multipeer-connectivity-transport/discovery.go
  go/internal/multipeer-connectivity-transport/listener.go
  go/internal/multipeer-connectivity-transport/transport.go
Labels: bug, ✅ Approved

#2287 feat: Add notification driver
  .buildkite/pipeline.yml
  go.mod
  go.sum
  go/cmd/berty/mini.go
  go/cmd/berty/mini/main.go
  go/cmd/berty/opts.go
  go/framework/bertybridge/bridge_protocol.go
  go/framework/bertybridge/driver_notification.go
  go/internal/notification/manager.go
  go/internal/notification/manager_desktop.go
  go/internal/notification/manager_logger.go
  go/internal/notification/manager_noop.go
  go/pkg/bertymessenger/service.go
  js/.bundle/config
  js/.gitignore
  js/Gemfile
  js/Gemfile.lock
  js/Makefile
  js/fastlane/Fastfile
  js/fastlane/README.md
  js/gen.sum
  js/packages/berty-app/ios/Berty.xcodeproj/project.pbxproj
  js/packages/berty-app/ios/Berty/LifeCycle.swift
  js/packages/berty-app/ios/LocalNotificationManager.swift
  js/packages/berty-app/ios/Podfile
  js/packages/berty-app/ios/Podfile.lock
  js/packages/go-bridge/go-bridge.podspec
  js/packages/go-bridge/ios/GoBridge.swift
  js/packages/go-bridge/ios/LifeCycleDriver.swift
  js/packages/go-bridge/ios/NotificationDriver.swift
  tool/build/shell/release-ios.sh
Labels: WIP, enhancement, 🔍 Ready for Review

#2291 fix(messenger): create group screen
  js/packages/components/main/CreateGroupAddMembers.tsx
Labels: bug, 🔍 Ready for Review

#2281 feat: added token issuer server for upcoming services
  api/bertymessenger.proto
  api/bertymessenger.yaml
  api/bertyprotocol.proto
  api/bertyprotocol.yaml
  api/bertytypes.proto
  api/errcode.proto
  docs/gen.sum
  docs/messenger/api.md
  docs/messenger/bertymessenger.swagger.json
  docs/protocol/api.md
  docs/protocol/bertyprotocol.swagger.json
  go.mod
  go.sum
  go/cmd/berty/main.go
  go/cmd/berty/mini.go
  go/cmd/berty/mini/view_group_incoming.go
  go/cmd/berty/mini/view_group_outgoing.go
  go/cmd/berty/opts.go
  go/cmd/berty/token.go
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/bertymessenger.pb.gw.go
  go/pkg/bertyprotocol/api_services_auth.go
  go/pkg/bertyprotocol/bertyprotocol.pb.go
  go/pkg/bertyprotocol/bertyprotocol.pb.gw.go
  go/pkg/bertyprotocol/events.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertyprotocol/service_test.go
  go/pkg/bertyprotocol/services_auth.go
  go/pkg/bertyprotocol/services_auth_server.go
  go/pkg/bertyprotocol/services_auth_server_test.go
  go/pkg/bertyprotocol/services_auth_test.go
  go/pkg/bertyprotocol/store_metadata.go
  go/pkg/bertyprotocol/store_metadata_index.go
  go/pkg/bertytypes/auth.go
  go/pkg/bertytypes/bertytypes.pb.go
  go/pkg/bertytypes/events_account.go
  go/pkg/errcode/errcode.pb.go
  js/gen.sum
  js/packages/api/index.gen.js
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/codegen/index.gen.js
Labels: enhancement, 🔍 Ready for Review

#2293 chore: automatically enable IPFS logger based on logging filters
  go.mod
  go.sum
  go/internal/logutil/logutil.go
Labels: chore, 🔍 Ready for Review

#2294 chore: auto-update readme's usage section with embedmd
  go/Makefile
  go/README.md
  go/cmd/berty/shareinvite.go
  go/gen.sum
Labels: chore, 🔍 Ready for Review

#2295 feat(messenger): lock portrait mode on mobile
  js/packages/berty-app/android/app/src/main/AndroidManifest.xml
  js/packages/berty-app/ios/Berty/Info.plist
Labels: enhancement, messenger, 🔍 Ready for Review

#2296 fix(messenger): margin and focus on conversation
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/shared-components/Chat.tsx
Labels: bug, 🔍 Ready for Review

#2301 feat(messenger): add Discord share confirmation dialog
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/shared-components/Message.tsx
  js/packages/components/settings/DevTools.tsx
  js/packages/store/faker.js
Labels: enhancement, feature-suggestion-ux, messenger, 🔍 Ready for Review

#2300 messenger: fix app brick when closed with a req in sent state
  .gitignore
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/handlers.go
  go/pkg/bertymessenger/replay.go
  js/Makefile
  js/gen.sum
Labels: messenger, 🔍 Ready for Review

#2298 fix: Remove QR Data from the discord share.
  go/internal/discordlog/discord.go
Labels: bug, ✅ Approved

#2304 chore: display wrapped errcode stack when printing with %+v
  go.mod
  go/cmd/berty/main.go
  go/pkg/errcode/error.go
Labels: chore, 🔍 Ready for Review

#2223 feat(messenger): crashlytics and shakebugs on dev release
  .buildkite/pipeline.yml
  .gitignore
  js/.gitignore
  js/package.json
  js/packages/berty-app/android/app/build.gradle
  js/packages/berty-app/android/app/google-services.json
  js/packages/berty-app/android/app/src/main/AndroidManifest.xml
  js/packages/berty-app/android/app/src/main/java/tech/berty/app/MainActivity.java
  js/packages/berty-app/android/app/src/main/java/tech/berty/app/MainApplication.java
  js/packages/berty-app/android/build.gradle
  js/packages/berty-app/index.js
  js/packages/berty-app/ios/Berty.xcodeproj/project.pbxproj
  js/packages/berty-app/ios/Berty/AppDelegate.m
  js/packages/berty-app/ios/Berty/GoogleService/Berty/GoogleService-Info.plist
  js/packages/berty-app/ios/Berty/GoogleService/BertyDebug/GoogleService-Info.plist
  js/packages/berty-app/ios/Berty/GoogleService/BertyStaff/GoogleService-Info.plist
  js/packages/berty-app/ios/Berty/GoogleService/BertyYolo/GoogleService-Info.plist
  js/packages/berty-app/ios/Berty/Info.plist
  js/packages/berty-app/ios/Debug.xcconfig
  js/packages/berty-app/ios/Podfile
  js/packages/berty-app/ios/Podfile.lock
  js/packages/berty-app/ios/Release.xcconfig
  js/packages/berty-app/package.json
  js/yarn.lock
Labels: enhancement, 🔍 Ready for Review

#2292 chore(messenger): restore group invitation functionality in 1-1 chat
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/shared-components/Chat.tsx
  js/packages/components/chat/shared-components/Message.tsx
  js/packages/components/modals/ManageDeepLink.tsx
  js/packages/store/hooks.js
  js/packages/store/methods.js
  js/packages/store/provider.tsx
  js/packages/web-dev-app/src/App.tsx
Labels: chore, messenger, 🔍 Ready for Review

#2299 feat: refactor CLI and initializations
  go/Makefile
  go/README.md
  go/cmd/berty/banner.go
  go/cmd/berty/daemon.go
  go/cmd/berty/groupinit.go
  go/cmd/berty/main.go
  go/cmd/berty/mini.go
  go/cmd/berty/mini/main.go
  go/cmd/berty/mini/utils.go
  go/cmd/berty/mini/view_group.go
  go/cmd/berty/mini/view_group_incoming.go
  go/cmd/berty/mini/view_group_outgoing.go
  go/cmd/berty/mini/view_tabbed_groups.go
  go/cmd/berty/opts.go
  go/cmd/berty/shareinvite.go
  go/cmd/berty/systeminfo.go
  go/cmd/berty/token.go
  go/cmd/rdvp/main.go
  go/framework/bertybridge/bridge.go
  go/framework/bertybridge/bridge_protocol.go
  go/gen.sum
  go/internal/grpcutil/server.go
  go/internal/initutil/datastore.go
  go/internal/initutil/logger.go
  go/internal/initutil/manager.go
  go/internal/initutil/node.go
  go/internal/ipfsutil/util.go
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertyprotocol/client.go
  go/pkg/bertyprotocol/testing.go
  js/Makefile
  js/gen.sum
  tool/berty-mini-local-helper/Makefile
  tool/berty-mini-web/berty-mini
Labels: enhancement, 🔍 Ready for Review

#2306 fix: multipeer transport race condition
  go/framework/bertybridge/bridge_test.go
  go/internal/multipeer-connectivity-transport/discovery.go
Labels: bug, ✅ Approved

#2307 feat(messenger): add and display sentDate in GroupInvitation messages
  go/pkg/bertymessenger/api.go
  js/Makefile
  js/gen.sum
  js/packages/components/chat/shared-components/Message.tsx
Labels: enhancement, messenger, 🔍 Ready for Review

#2305 fix: improve and test the init/close process
  .github/workflows/protobuf.yml
  go.mod
  go.sum
  go/cmd/berty/main.go
  go/cmd/berty/main_test.go
  go/internal/initutil/datastore.go
  go/internal/initutil/logger.go
  go/internal/initutil/manager.go
  go/internal/initutil/manager_test.go
  go/internal/initutil/node.go
Labels: bug, 🔍 Ready for Review

#2265 feat: refactor message / metadata list in protocol API
  api/bertyprotocol.proto
  api/bertyprotocol.yaml
  api/bertytypes.proto
  api/errcode.proto
  docs/gen.sum
  docs/protocol/api.md
  docs/protocol/bertyprotocol.swagger.json
  go/cmd/berty/mini/main.go
  go/cmd/berty/mini/view_group.go
  go/cmd/berty/mini/view_tabbed_groups.go
  go/gen.sum
  go/pkg/bertymessenger/replay.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertyprotocol/api_event.go
  go/pkg/bertyprotocol/api_group.go
  go/pkg/bertyprotocol/api_multimember.go
  go/pkg/bertyprotocol/bertyprotocol.pb.go
  go/pkg/bertyprotocol/bertyprotocol.pb.gw.go
  go/pkg/bertyprotocol/contact_request_manager_test.go
  go/pkg/bertyprotocol/group.go
  go/pkg/bertyprotocol/orbitdb_many_adds_berty_test.go
  go/pkg/bertyprotocol/orbitdb_test.go
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/bertyprotocol/service_group.go
  go/pkg/bertyprotocol/store_message.go
  go/pkg/bertyprotocol/store_message_test.go
  go/pkg/bertyprotocol/store_metadata.go
  go/pkg/bertyprotocol/store_utils.go
  go/pkg/bertytypes/bertytypes.pb.go
  go/pkg/errcode/errcode.pb.go
  js/gen.sum
  js/packages/api/index.gen.js
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/codegen/index.gen.js
Labels: enhancement, ✅ Approved

#2308 chore: added GetLocalIPFS and GetOrbitDB to initutil's Manager
  go/framework/bertybridge/bridge_protocol.go
  go/internal/initutil/ipfs.go
  go/internal/initutil/manager.go
  go/internal/initutil/node.go
  go/internal/initutil/orbitdb.go
  go/pkg/bertymessenger/api_test.go
  go/pkg/bertymessenger/testing.go
  go/pkg/bertymessenger/testing_test.go
  go/pkg/bertyprotocol/blackbox_test.go
  go/pkg/bertyprotocol/consts.go
  go/pkg/bertyprotocol/contact_request_manager_test.go
  go/pkg/bertyprotocol/orbitdb.go
  go/pkg/bertyprotocol/orbitdb_datastore_cache.go
  go/pkg/bertyprotocol/orbitdb_many_adds_berty_test.go
  go/pkg/bertyprotocol/orbitdb_test.go
  go/pkg/bertyprotocol/orbitdb_utils_test.go
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertyprotocol/service_group.go
  go/pkg/bertyprotocol/store_message.go
  go/pkg/bertyprotocol/store_metadata.go
  go/pkg/bertyprotocol/store_metadata_test.go
  go/pkg/bertyprotocol/testing.go
  go/pkg/bertyprotocol/testing_test.go
Labels: chore, ✅ Approved

#2309 chore: Added gitignore to exclude go binaries.
  .gitignore
Labels: chore, ✅ Approved, 🔍 Ready for Review

#2314 fix: various edge cases handling on initutil
  go.mod
  go.sum
  go/framework/bertybridge/bridge_protocol.go
  go/internal/config/berty.go
  go/internal/grpcutil/server.go
  go/internal/initutil/datastore.go
  go/internal/initutil/ipfs.go
  go/internal/initutil/manager.go
  go/internal/initutil/manager_test.go
  go/internal/initutil/node.go
  go/internal/ipfsutil/http_api.go
  go/internal/ipfsutil/localrecord.go
  go/internal/multipeer-connectivity-transport/conn.go
  go/internal/tinder/driver_localdiscovery.go
  go/pkg/bertymessenger/service.go
Labels: bug, 🔍 Ready for Review

#2315 feat(messenger): improve swipe screen navigation
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/main/Home.tsx
  js/packages/components/main/Search.tsx
  js/packages/components/package.json
  js/packages/components/settings/Home.tsx
  js/packages/components/shared-components/SwipeNavRecognizer.tsx
  js/yarn.lock
Labels: enhancement, 🔍 Ready for Review

#2311 chore: remove messenger context opts
  go/pkg/bertymessenger/service.go
Labels: chore, ✅ Approved, 🔍 Ready for Review

#2318 fix: change default gRPC listeners on berty daemon
  go/Makefile
  go/README.md
  go/cmd/berty/daemon.go
  go/cmd/berty/mini.go
  go/gen.sum
  go/internal/initutil/manager_test.go
  go/internal/initutil/node.go
Labels: bug, 🔍 Ready for Review

#2319 fix: reconfigure orbitdb logger consistently
  go/internal/initutil/orbitdb.go
  go/pkg/bertyprotocol/orbitdb.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertyprotocol/testing.go
Labels: bug, ✅ Approved

#2321 fix: remove gesture-blocking swipe listener
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/main/Home.tsx
  js/packages/components/main/Search.tsx
  js/packages/components/settings/Home.tsx
Labels: bug, messenger, 🔍 Ready for Review

#2317 fix: Fixed typo in berty mini.
  go/cmd/berty/mini/view_group.go
Labels: bug, ✅ Approved

#2313 feat: Allows the selection of key's params using rdvp.
  go/cmd/rdvp/main.go
Labels: enhancement, ✅ Approved

#2310 feat(messenger): notifications first pass
  api/bertymessenger.proto
  api/errcode.proto
  docs/gen.sum
  docs/messenger/api.md
  docs/messenger/bertymessenger.swagger.json
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/handlers.go
  go/pkg/bertymessenger/notifiee.go
  go/pkg/bertymessenger/notifiee_test.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertymessenger/types.go
  go/pkg/errcode/errcode.pb.go
  js/.eslintignore
  js/gen.sum
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/berty-app/App.tsx
  js/packages/berty-app/package.json
  js/packages/components/NodeGate.tsx
  js/packages/components/NotificationBody.tsx
  js/packages/components/NotificationProvider.tsx
  js/packages/components/index.ts
  js/packages/components/package.json
  js/packages/store/context.js
  js/packages/store/context.tsx
  js/packages/store/provider.tsx
  js/yarn.lock
Labels: enhancement, 🔍 Ready for Review

#2325 chore: configure :default: pattern replacement for testutil.Logger
  go/internal/testutil/logging.go
Labels: chore, ✅ Approved

#2322 chore: various Makefile improvements
  Dockerfile
  go/Makefile
  go/cmd/berty/version.go
  go/gen.sum
  js/Makefile
  js/gen.sum
Labels: chore, 🔍 Ready for Review

#2324 chore: configure depaware
  go.mod
  go.sum
  go/Makefile
  go/cmd/berty/depaware.txt
  go/cmd/rdvp/depaware.txt
  go/framework/bertybridge/depaware.txt
  go/gen.sum
  go/internal/tools/tools.go
Labels: chore, 🔍 Ready for Review

#2302 feat: beta-bot
  go/cmd/berty/betabot/main.go
  go/cmd/berty/betabot/utils.go
Labels: enhancement, ✅ Approved

#2326 fix: allow to specify IPFS webui addr
  go/README.md
  go/framework/bertybridge/bridge_protocol.go
  go/internal/initutil/manager.go
  go/internal/initutil/node.go
  go/internal/ipfsutil/http_api.go
  js/Makefile
  js/gen.sum
Labels: bug, ✅ Approved

#2332 fix(messenger): prevent from swiping back to onboarding from home
  js/packages/components/Onboarding.tsx
Labels: bug, 🔍 Ready for Review

#2334 fix: minor fixes around group activation and deactivation + SendMessage
  go/cmd/berty/mini/view_group.go
  go/pkg/bertymessenger/api.go
  go/pkg/bertyprotocol/service_group.go
Labels: bug, 🔍 Ready for Review

#2323 feat: Add lifecycle manager to bertymessenger
  go/.golangci.yml
  go/cmd/berty/mini.go
  go/cmd/berty/mini/main.go
  go/framework/bertybridge/bridge_protocol.go
  go/framework/bertybridge/driver_lifecycle.go
  go/internal/initutil/manager.go
  go/internal/initutil/node.go
  go/internal/lifecycle/manager.go
  go/pkg/bertymessenger/lifecycle.go
  go/pkg/bertymessenger/service.go
Labels: enhancement, ✅ Approved

#2303 feat: replication service + usage in mini
  api/bertymessenger.proto
  api/bertymessenger.yaml
  api/bertyprotocol.proto
  api/bertyprotocol.yaml
  api/bertyreplication.proto
  api/bertyreplication.yaml
  api/bertytypes.proto
  api/errcode.proto
  docs/gen.sum
  docs/messenger/api.md
  docs/messenger/bertymessenger.swagger.json
  docs/protocol/api.md
  docs/protocol/bertyprotocol.swagger.json
  go/Makefile
  go/cmd/berty/main.go
  go/cmd/berty/mini/view_group_outgoing.go
  go/cmd/berty/replication.go
  go/gen.sum
  go/internal/ipfsutil/testing.go
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/bertymessenger.pb.gw.go
  go/pkg/bertyprotocol/api_replication.go
  go/pkg/bertyprotocol/bertyprotocol.pb.go
  go/pkg/bertyprotocol/bertyprotocol.pb.gw.go
  go/pkg/bertyprotocol/bertyreplication.pb.go
  go/pkg/bertyprotocol/bertyreplication.pb.gw.go
  go/pkg/bertyprotocol/orbitdb.go
  go/pkg/bertyprotocol/orbitdb_many_adds_test.go
  go/pkg/bertyprotocol/orbitdb_test.go
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/bertyprotocol/service_group.go
  go/pkg/bertyprotocol/services_auth.go
  go/pkg/bertyprotocol/services_replication.go
  go/pkg/bertyprotocol/services_replication_test.go
  go/pkg/bertyprotocol/store_message.go
  go/pkg/bertyprotocol/store_metadata.go
  go/pkg/bertyprotocol/store_options.go
  go/pkg/bertyprotocol/testing.go
  go/pkg/bertytypes/bertytypes.pb.go
  go/pkg/bertytypes/group.go
  go/pkg/errcode/errcode.pb.go
  js/gen.sum
  js/packages/api/index.gen.js
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/codegen/index.gen.js
Labels: enhancement, 🔍 Ready for Review

#2338 feat: various betabot improvements
  .gitignore
  Dockerfile
  README.md
  go/Makefile
  go/README.md
  go/cmd/berty/betabot/main.go
  go/cmd/berty/betabot/utils.go
  go/cmd/betabot/depaware.txt
  go/cmd/betabot/main.go
  go/gen.sum
  go/internal/initutil/node.go
  tool/deployments/betabot/Makefile
  tool/deployments/betabot/docker-compose.yml
Labels: enhancement, 🔍 Ready for Review

#2341 fix(messenger): button ipfs webui in devtools
  js/packages/components/settings/DevTools.tsx
  js/packages/components/settings/Network.tsx
  js/packages/components/settings/index.ts
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
Labels: bug, ✅ Approved

#2340 fix: refactor versioning and systeminfo
  .goreleaser.yml
  api/bertymessenger.proto
  api/bertyprotocol.proto
  api/bertyprotocol.yaml
  api/bertytypes.proto
  docs/gen.sum
  docs/messenger/api.md
  docs/messenger/bertymessenger.swagger.json
  docs/protocol/api.md
  docs/protocol/bertyprotocol.swagger.json
  go/Makefile
  go/README.md
  go/cmd/berty/depaware.txt
  go/cmd/berty/mini/view_group_outgoing.go
  go/cmd/berty/systeminfo.go
  go/cmd/berty/version.go
  go/cmd/betabot/depaware.txt
  go/framework/bertybridge/depaware.txt
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/api_test.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertymessenger/version.go
  go/pkg/bertyprotocol/api_debug.go
  go/pkg/bertyprotocol/bertyprotocol.pb.go
  go/pkg/bertyprotocol/bertyprotocol.pb.gw.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertytypes/bertytypes.pb.go
  go/pkg/bertyversion/version.go
  js/Makefile
  js/gen.sum
  js/packages/api/index.gen.js
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/codegen/index.gen.js
  js/packages/components/settings/SystemInfo.tsx
Labels: bug, 🔍 Ready for Review

#2345 feat: Add (No)Announce IPFS config as flag
  go/internal/initutil/ipfs.go
  go/internal/initutil/manager.go
  go/internal/initutil/node.go
  go/internal/ipfsutil/api.go
  go/internal/ipfsutil/http_api.go
Labels: enhancement, 🔍 Ready for Review

#2316 feat: support multiple discovery drivers at the same time
  go/framework/bertybridge/bridge_protocol.go
  go/internal/config/berty.go
  go/internal/initutil/flag.go
  go/internal/initutil/ipfs.go
  go/internal/initutil/manager.go
  go/internal/ipfsutil/helper.go
  go/internal/tinder/asyncable_driver.go
  go/internal/tinder/driver_mocked.go
  go/internal/tinder/driver_multi.go
  go/internal/tinder/driver_multi_test.go
  go/internal/tinder/driver_rdv.go
  go/internal/tinder/testing_test.go
Labels: enhancement, 🔍 Ready for Review

#2346 chore: improve flag parsing and usage
  go/README.md
  go/cmd/berty/banner.go
  go/cmd/berty/daemon.go
  go/cmd/berty/groupinit.go
  go/cmd/berty/mini.go
  go/cmd/berty/replication.go
  go/cmd/berty/shareinvite.go
  go/cmd/berty/systeminfo.go
  go/cmd/berty/token.go
  go/cmd/berty/version.go
  go/cmd/rdvp/main.go
Labels: chore, 🔍 Ready for Review

#2343 fix: replication & orbitdb related issues
  go.mod
  go.sum
  go/cmd/berty/replication.go
  go/cmd/berty/token.go
  go/framework/bertybridge/internal/bridgepb/bertybridge.pb.go
  go/internal/initutil/orbitdb.go
  go/pkg/bertymessenger/api.go
  go/pkg/bertyprotocol/orbitdb.go
  go/pkg/bertyprotocol/orbitdb_test.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertyprotocol/services_replication.go
  go/pkg/bertyprotocol/testing.go
Labels: bug, ✅ Approved

#2348 fix(messenger): messages bubbles
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/shared-components/Message.tsx
Labels: bug, ✅ Approved

#2350 messenger: fix crash in home when contact is null
  js/packages/components/main/Home.tsx
Labels: messenger, 🔍 Ready for Review

#2352 fix: refactor rdvp logger with constant CLI and better defaults
  go/README.md
  go/cmd/berty/depaware.txt
  go/cmd/betabot/depaware.txt
  go/cmd/rdvp/depaware.txt
  go/cmd/rdvp/main.go
  go/framework/bertybridge/depaware.txt
Labels: bug, 🔍 Ready for Review

#2347 chore: updated linters configuration, setup gofumpt in Makefile, fixed various linter errors
  go.mod
  go.sum
  go/.golangci.yml
  go/Makefile
  go/cmd/berty/daemon.go
  go/cmd/berty/groupinit.go
  go/cmd/berty/main.go
  go/cmd/berty/mini/main.go
  go/cmd/berty/mini/view_group.go
  go/cmd/berty/mini/view_group_incoming.go
  go/cmd/berty/mini/view_group_outgoing.go
  go/cmd/berty/mini/view_tabbed_groups.go
  go/cmd/berty/replication.go
  go/framework/bertybridge/bridge_protocol.go
  go/framework/bertybridge/internal/bridgepb/bertybridge.pb.go
  go/gen.sum
  go/internal/cryptoutil/cryptoutil_test.go
  go/internal/handshake/request.go
  go/internal/initutil/datastore.go
  go/internal/initutil/ipfs.go
  go/internal/ipfsutil/http_api.go
  go/internal/ipfsutil/repo.go
  go/internal/logutil/logutil.go
  go/internal/multipeer-connectivity-transport/driver/mc-driver/cgo_bridge_darwin.go
  go/internal/multipeer-connectivity-transport/init.go
  go/internal/multipeer-connectivity-transport/multiaddr/init.go
  go/internal/tinder/driver_multi_test.go
  go/internal/tools/tools.go
  go/pkg/banner/quote.go
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/handlers.go
  go/pkg/bertymessenger/replay.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertymessenger/service_test.go
  go/pkg/bertymessenger/testing.go
  go/pkg/bertyprotocol/api_services_auth.go
  go/pkg/bertyprotocol/consts.go
  go/pkg/bertyprotocol/keystore_device_test.go
  go/pkg/bertyprotocol/keystore_message_utils_test.go
  go/pkg/bertyprotocol/orbitdb_many_adds_berty_test.go
  go/pkg/bertyprotocol/orbitdb_signed_entry_accesscontroller.go
  go/pkg/bertyprotocol/orbitdb_signed_entry_identity_provider.go
  go/pkg/bertyprotocol/orbitdb_utils_test.go
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/bertyprotocol/services_auth.go
  go/pkg/bertyprotocol/services_auth_server.go
  go/pkg/bertyprotocol/services_auth_test.go
  go/pkg/bertyprotocol/services_replication.go
  go/pkg/bertyprotocol/tinder_swiper_test.go
  go/pkg/errcode/error_test.go
  go/pkg/errcode/stdproto.go
Labels: chore, 🔍 Ready for Review

#2353 chore: update mpconnectivity build constraints
  go/internal/multipeer-connectivity-transport/driver/bridge_darwin.go
  go/internal/multipeer-connectivity-transport/driver/bridge_unsupported.go
  go/internal/multipeer-connectivity-transport/driver/mc-driver/cgo_bridge_darwin.go
  go/internal/multipeer-connectivity-transport/driver/mc-driver/cgo_bridge_unsupported.go
Labels: chore, 🔍 Ready for Review

#2355 fix: missing close empty channel
  go/internal/tinder/driver_localdiscovery.go
Labels: bug, ✅ Approved

#2354 fix: improve leakage cleanup in manager_test.go
  go/internal/initutil/manager.go
  go/internal/initutil/manager_test.go
  go/internal/initutil/node.go
  go/internal/ipfsutil/http_api.go
Labels: bug, 🔍 Ready for Review

#2356 fix: user message horizontal alignment
  js/packages/components/chat/shared-components/Message.tsx
Labels: bug, messenger, messenger-ui-cosmetic, 🔍 Ready for Review

#2357 feat: contact initiated styled message
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/shared-components/Message.tsx
Labels: enhancement, messenger, messenger-ui-cosmetic, 🔍 Ready for Review

#2333 feat: create navigation swipe wrapper
  js/packages/components/chat/ContactSettings.tsx
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/MultiMemberSettings.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/OneToOneSettings.tsx
  js/packages/components/main/Home.tsx
  js/packages/components/main/Scan.tsx
  js/packages/components/main/Search.tsx
  js/packages/components/package.json
  js/packages/components/settings/AboutBerty.tsx
  js/packages/components/settings/Bluetooth.tsx
  js/packages/components/settings/DevTools.tsx
  js/packages/components/settings/FakeData.js
  js/packages/components/settings/Help.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/Mode.tsx
  js/packages/components/settings/Notifications.tsx
  js/packages/components/settings/TermsOfUse.tsx
  js/packages/components/shared-components/Footer.tsx
  js/packages/components/shared-components/Header.tsx
  js/packages/components/shared-components/Request.tsx
  js/packages/components/shared-components/SwipeNavRecognizer.tsx
  js/packages/navigation/stacks.tsx
  js/yarn.lock
Labels: enhancement, messenger, 🔍 Ready for Review

#2359 chore: remove intermediary subdirectory in the mc driver
  go/internal/multipeer-connectivity-transport/driver/MCManager.h
  go/internal/multipeer-connectivity-transport/driver/MCManager.m
  go/internal/multipeer-connectivity-transport/driver/bridge_darwin.go
  go/internal/multipeer-connectivity-transport/driver/mc-driver.h
  go/internal/multipeer-connectivity-transport/driver/mc-driver.m
  go/internal/multipeer-connectivity-transport/driver/mc-driver/cgo_bridge_darwin.go
  go/internal/multipeer-connectivity-transport/driver/mc-driver/cgo_bridge_unsupported.go
Labels: chore, ✅ Approved, 🔍 Ready for Review

#2361 fix: support shared cli flags with different default values
  go.mod
  go.sum
  go/cmd/berty/banner.go
  go/cmd/berty/daemon.go
  go/cmd/berty/mini.go
  go/cmd/berty/replication.go
  go/cmd/berty/shareinvite.go
  go/cmd/berty/systeminfo.go
  go/cmd/berty/token.go
  go/internal/initutil/manager_test.go
Labels: bug, 🔍 Ready for Review

#2362 fix: nil lifecycle manager in bridge messenger
  go/framework/bertybridge/bridge_protocol.go
  go/framework/bertybridge/bridge_test.go
Labels: bug, 🔍 Ready for Review

#2364 chore: Updated IPFS to v0.7.0
  go.mod
  go.sum
  go/cmd/berty/depaware.txt
  go/cmd/betabot/depaware.txt
  go/cmd/rdvp/depaware.txt
  go/framework/bertybridge/depaware.txt
  go/internal/ipfsutil/api.go
Labels: chore, ✅ Approved

#2366 fix: update p2p rdvp configuration to match new server
  go/internal/config/berty.go
Labels: bug, ✅ Approved

#2349 feat: improve beta bot
  go/cmd/betabot/main.go
  js/packages/components/chat/shared-components/Message.tsx
  js/packages/components/main/Home.tsx
  js/packages/components/modals/AddBetabot.js
  js/packages/components/modals/Buck_Berty.svg
  js/packages/components/modals/Buck_Berty_Icon_Card.svg
  js/packages/components/modals/index.ts
  js/packages/navigation/hook.ts
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
Labels: enhancement, ✅ Approved

#2370 fix: multimember message alignment
  js/packages/components/chat/shared-components/Message.tsx
Labels: bug, 🔍 Ready for Review

#2371 fix: scroll background color in conversation list
  js/packages/components/main/Home.tsx
Labels: bug, messenger, messenger-ui-cosmetic, 🔍 Ready for Review

#2358 feat: replication UI in app
  api/bertymessenger.proto
  docs/gen.sum
  docs/messenger/api.md
  docs/messenger/bertymessenger.swagger.json
  go/cmd/berty/mini/view_group_outgoing.go
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/bertymessenger.pb.gw.go
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/handlers.go
  go/pkg/bertymessenger/replay.go
  js/gen.sum
  js/packages/api/index.gen.js
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/berty-app/android/app/src/main/java/tech/berty/app/MainApplication.java
  js/packages/berty-app/android/settings.gradle
  js/packages/berty-app/index.js
  js/packages/berty-app/ios/Podfile.lock
  js/packages/berty-app/package.json
  js/packages/codegen/index.gen.js
  js/packages/components/chat/MultiMemberSettings.tsx
  js/packages/components/chat/OneToOneSettings.tsx
  js/packages/components/chat/ReplicateGroupSettings.tsx
  js/packages/components/chat/index.ts
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/ServicesAuth.tsx
  js/packages/components/settings/index.ts
  js/packages/navigation/hook.ts
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
  js/yarn.lock
Labels: enhancement, 🔍 Ready for Review

#2369 chore: fix 'make generate' when vendor/ dir exists
  docs/Makefile
  docs/gen.sum
  go/Makefile
  go/gen.sum
  js/Makefile
  js/gen.sum
Labels: chore, 🔍 Ready for Review

#2365 fix: replication server token authentication
  go.mod
  go.sum
  go/cmd/berty/replication.go
  go/cmd/berty/token.go
  go/internal/grpcutil/simple_auth.go
  go/internal/grpcutil/simple_auth_test.go
  go/internal/initutil/manager.go
  go/internal/initutil/node.go
  go/pkg/bertyprotocol/api_replication.go
Labels: bug, ✅ Approved

#2336 Move the android mobile CI to actions.
  .github/workflows/android.yml
  .github/workflows/go.yml
  .github/workflows/js.yml
  .github/workflows/release.yml
  README.md
  js/Makefile
  js/gen.sum
Labels: WIP, ✅ Approved

#2368 fix: betabot behaviors
  go.sum
  go/cmd/betabot/main.go
  js/packages/components/main/Home.tsx
  js/packages/components/modals/AddBetabot.js
  js/packages/components/settings/DevTools.tsx
  js/packages/store/context.tsx
  js/packages/store/hooks.js
  js/packages/store/provider.tsx
Labels: bug, ✅ Approved

#2374 feat(js): improve notification UI/UX
  js/packages/berty-app/ios/Berty.xcodeproj/project.pbxproj
  js/packages/components/NotificationBody.tsx
  js/packages/navigation/index.tsx
Labels: enhancement, 🔍 Ready for Review

#2372 chore: add 'make doctor'
  Makefile
  go.mod
  go.sum
  tool/doctor/main.go
  tool/go.mod
  tool/go.sum
Labels: chore, 🔍 Ready for Review

#2376 Update README.md
  README.md
Labels: 🔍 Ready for Review

#2377 feat: added several quotes and alphabetized
  go/pkg/banner/quote.go
Labels: enhancement, ✅ Approved

#2373 perf: Add assets bundle and fake file.
  go.mod
  go.sum
  go/Makefile
  go/assets/pkged.go
  go/cmd/berty/main.go
  go/cmd/berty/mini/main.go
  go/cmd/betabot/main.go
  go/cmd/rdvp/main.go
  go/framework/bertybridge/bridge_protocol.go
  go/gen.sum
  go/internal/initutil/ipfs.go
  go/internal/initutil/node.go
  go/internal/multipeer-connectivity-transport/driver/mc-driver/cgo_bridge_unsupported.go
  go/internal/notification/manager_desktop.go
  go/internal/packingutil/packing.go
  go/internal/tools/tools_untool.go
Labels: performance, ✅ Approved

#2379 chore: Fixing metrics on quic.
  go.mod
  go.sum
Labels: chore, ✅ Approved

#2380 chore: Fixing typo in go/internal/packingutil/packing.go.
  go/internal/packingutil/packing.go
Labels: chore, 🔍 Ready for Review

#2375 chore: add betabot store + various go style improvements
  .gitignore
  go/cmd/betabot/main.go
  tool/deployments/betabot/docker-compose.yml
Labels: chore, ✅ Approved

#2384 feat: update berty deployment for traefik
  tool/deployments/betabot/docker-compose.yml
  tool/deployments/rdvp-dev/docker-compose.yml
Labels: enhancement, 🔍 Ready for Review

#2385 feat(js): branded loading dots
  js/packages/components/gates.tsx
  js/packages/components/shared-components/loader_dots.gif
Labels: enhancement, messenger, messenger-ui-cosmetic, 🔍 Ready for Review

#2383 fix: betabot scenario
  go/cmd/betabot/main.go
  js/packages/components/modals/AddBetabot.js
Labels: bug, ✅ Approved

#2363 fix: some UI/UX stuff
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/shared-components/Chat.tsx
  js/packages/components/main/Home.tsx
  js/packages/components/modals/AddBetabot.js
  js/packages/components/shared-components/Header.tsx
  js/packages/navigation/stacks.tsx
  js/packages/styles/map-declaration.ts
Labels: bug, 🔍 Ready for Review

#2382 ci: Added fake build log for testing YOLO
  .github/workflows/android.yml
Labels: ci, ✅ Approved

#2388 fix: english in betabot scenario and fix modal on small devices
  go/cmd/betabot/main.go
  js/packages/components/modals/AddBetabot.js
Labels: bug, 🔍 Ready for Review

#2389 chore(readme): update section about messenger dev status
  README.md
Labels: chore, ✅ Approved

#2392 fix: remove unused files in mc-driver
  go/internal/multipeer-connectivity-transport/driver/mc-driver/cgo_bridge_darwin.go
  go/internal/multipeer-connectivity-transport/driver/mc-driver/cgo_bridge_unsupported.go
Labels: bug, ✅ Approved

#2390 chore: configure docker-compose to always restart betabot instances
  tool/deployments/betabot/docker-compose.yml
Labels: chore, ✅ Approved

#2393 fix: deeplinks
  js/packages/berty-app/App.tsx
  js/packages/berty-app/ios/Berty/AppDelegate.m
  js/packages/components/main/Home.tsx
  js/packages/navigation/container.tsx
  js/packages/navigation/index.tsx
  js/packages/navigation/stacks.tsx
  js/packages/store/provider.tsx
Labels: bug, 🔍 Ready for Review

#2396 feat(messenger): Allow swiping back on the MyBertyId and Scan QR views
  js/packages/components/main/Home.tsx
  js/packages/components/main/Scan.tsx
  js/packages/components/settings/MyBertyId.tsx
Labels: enhancement, messenger, 🔍 Ready for Review

#2398 feat: add messenger.BannerQuote gRPC endpoint
  api/bertymessenger.proto
  api/bertymessenger.yaml
  docs/gen.sum
  docs/messenger/api.md
  docs/messenger/bertymessenger.swagger.json
  go/Makefile
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/api_test.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/bertymessenger.pb.gw.go
  js/gen.sum
  js/packages/api/index.gen.js
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/codegen/index.gen.js
Labels: enhancement, 🔍 Ready for Review

#2395 feat(messenger): notification navigate on press
  js/packages/berty-app/App.tsx
  js/packages/components/NotificationBody.tsx
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/navigation/index.tsx
  js/packages/navigation/rootRef.ts
  js/packages/store/hooks.js
Labels: enhancement, 🔍 Ready for Review
