Repository berty/berty, pull requests merged in 2020-04, with the labels that each got.

#1821 fix(chat): fix conversation header
  js/packages/berty-storybook/Onboarding.tsx
  js/packages/berty-storybook/chat/Chat.tsx
  js/packages/berty-storybook/chat/ChatGroup.tsx
  js/packages/berty-storybook/chat/ChatSettings.tsx
  js/packages/berty-storybook/chat/ContactChatSettings.tsx
  js/packages/berty-storybook/chat/GroupChatSettings.tsx
  js/packages/berty-storybook/chat/shared-components/Message.tsx
  js/packages/berty-storybook/main/CreateGroup.tsx
  js/packages/berty-storybook/main/GroupRequest.tsx
  js/packages/berty-storybook/main/InvalidScan.tsx
  js/packages/berty-storybook/main/List.tsx
  js/packages/berty-storybook/settings/AboutBerty.tsx
  js/packages/berty-storybook/settings/BlockedContacts.tsx
  js/packages/berty-storybook/settings/Bluetooth.tsx
  js/packages/berty-storybook/settings/DevTools.tsx
  js/packages/berty-storybook/settings/EditProfile.tsx
  js/packages/berty-storybook/settings/Help.tsx
  js/packages/berty-storybook/settings/Mode.tsx
  js/packages/berty-storybook/settings/Notifications.tsx
  js/packages/berty-storybook/settings/TermsOfUse.tsx
  js/packages/berty-storybook/shared-components/FingerprintContent.tsx
  js/packages/berty-storybook/shared-components/Header.tsx
  js/packages/berty-storybook/shared-components/ProceduralCircleAvatar.tsx
  js/packages/berty-storybook/shared-components/Request.tsx
  js/packages/berty-storybook/shared-components/SDTSModalComponent.tsx
  js/packages/berty-storybook/shared-components/SettingsButtons.tsx
  js/packages/berty-storybook/shared-components/TabBar.tsx
  js/packages/styles/index.tsx
Labels: chat, ✅ Approved

#1819 feat(chat): fill with samples when not enough conversations
  js/packages/berty-storybook/chat/Chat.tsx
  js/packages/berty-storybook/chat/shared-components/Chat.tsx
  js/packages/berty-storybook/main/List.tsx
  js/packages/berty-storybook/main/Scan.tsx
  js/packages/berty-storybook/shared-components/ProceduralCircleAvatar.tsx
  js/packages/store/chat/AppMessage.ts
  js/packages/store/chat/conversation.ts
  js/packages/store/chat/message.ts
Labels: chat, 🔍 Ready for Review

#1812 feat(protocol): replace service with grpc client
  go/.golangci.yml
  go/cmd/berty/main.go
  go/cmd/berty/mini/main.go
  go/cmd/berty/mini/view_group.go
  go/cmd/berty/mini/view_group_incoming.go
  go/cmd/berty/mini/view_group_outgoing.go
  go/cmd/berty/mini/view_tabbed_groups.go
  go/internal/testutil/logging.go
  go/pkg/bertydemo/client.go
  go/pkg/bertyprotocol/api_event.go
  go/pkg/bertyprotocol/api_group.go
  go/pkg/bertyprotocol/api_multimember.go
  go/pkg/bertyprotocol/client.go
  go/pkg/bertyprotocol/group.go
  go/pkg/bertyprotocol/group_context.go
  go/pkg/bertyprotocol/keystore_message_utils_test.go
  go/pkg/bertyprotocol/orbitdb.go
  go/pkg/bertyprotocol/orbitdb_many_adds_berty_test.go
  go/pkg/bertyprotocol/orbitdb_utils_test.go
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertyprotocol/service_group.go
  go/pkg/bertyprotocol/service_test.go
  go/pkg/bertyprotocol/store_message.go
  go/pkg/bertyprotocol/store_metadata.go
  go/pkg/bertyprotocol/store_metadata_index.go
  go/pkg/bertyprotocol/testing.go
  go/pkg/bertyprotocol/testing_test.go
  go/pkg/bertytypes/contact.go
Labels: ✅ Approved

#1767 feat: implement contact request handshake
  api/errcode.proto
  api/go-internal/handshake.proto
  docs/gen.sum
  go/gen.sum
  go/internal/handshake/.gitkeep
  go/internal/handshake/handshake.go
  go/internal/handshake/handshake.pb.go
  go/internal/handshake/handshake_test.go
  go/internal/handshake/handshake_util_test.go
  go/internal/handshake/request.go
  go/internal/handshake/response.go
  go/pkg/errcode/errcode.pb.go
Labels: 🔍 Ready for Review

#1817 feat: add logging to berty mini
  .buildkite/pipeline.yml
  go/cmd/berty/main.go
  go/cmd/berty/mini/main.go
  go/cmd/berty/mini/view_group.go
  go/cmd/berty/mini/view_group_incoming.go
  go/cmd/berty/mini/view_tabbed_groups.go
Labels: ✅ Approved

#1827 chore: reduce CI failures on go build
  .buildkite/pipeline.yml
Labels: 🔍 Ready for Review

#1825 chore: mark more file types as linguist-generated
  .gitattributes
Labels: 🔍 Ready for Review

#1826 fix: move berty banner package in the pkg/ directory
  go/cmd/berty/main.go
  go/cmd/berty/mini/view_group.go
  go/pkg/banner/banner.go
  go/pkg/banner/banner_test.go
  go/pkg/banner/quote.go
Labels: 🔍 Ready for Review

#1831 feat(testing): Add libp2p log enabler environment variable
  go/internal/ipfsutil/p2pzap.go
  go/internal/testutil/logging.go
Labels: 🔍 Ready for Review

#1818 docs(js): Create readme for js subfolder
  js/README.md
Labels: ✅ Approved

#1830 chore: create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: 🔍 Ready for Review

#1838 fix(chat): update react-navigation and clean integration
  js/packages/berty-app/index.js
  js/packages/berty-app/ios/Podfile.lock
  js/packages/berty-app/package.json
  js/packages/berty-navigation/index.tsx
  js/packages/berty-navigation/package.json
  js/packages/berty-storybook/package.json
  js/packages/storybook-mobile/package.json
  js/yarn.lock
Labels: chat, ✅ Approved

#1804 Some Makefile rules doesn't works inside the go folder
  go/Makefile
  go/gen.sum
Labels: bug, 🔍 Ready for Review

#1843 fix(chat): conditional hook in procedural avatar
  js/packages/berty-storybook/shared-components/ProceduralCircleAvatar.tsx
Labels: bug, chat, ✅ Approved

#1839 Clean QR code scanner
  js/global.d.ts
  js/package.json
  js/packages/berty-app/metro.config.js
  js/packages/berty-app/package.json
  js/packages/berty-storybook/main/Scan.tsx
  js/packages/berty-storybook/main/scan_target.svg
  js/packages/berty-storybook/package.json
  js/yarn.lock
Labels: chat, ✅ Approved

#1846 Scan error modal
  js/packages/berty-app/App.tsx
  js/packages/berty-app/LinkHandler.ts
  js/packages/berty-navigation/index.tsx
  js/packages/berty-storybook/index.ts
  js/packages/berty-storybook/main/Scan.tsx
  js/packages/berty-storybook/main/index.ts
  js/packages/berty-storybook/modals/AddThisContact.tsx
  js/packages/berty-storybook/modals/InvalidScan.tsx
  js/packages/berty-storybook/modals/SendContactRequest.tsx
  js/packages/berty-storybook/modals/index.ts
  js/packages/grpc-bridge/Makefile
  js/packages/hooks/Chat.tsx
Labels: chat, ✅ Approved

#1848 feat(ipfs): Bump ipfs & libp2p
  go.mod
  go.sum
  go/cmd/berty/mini/main.go
Labels: ✅ Approved

#1845 feat(chat): add contact screen
  js/packages/berty-storybook/chat/Chat.tsx
  js/packages/berty-storybook/chat/ChatSettings.tsx
  js/packages/berty-storybook/chat/ContactChatSettings.tsx
Labels: chat, ✅ Approved

#1842 fix(chat): contact last seen
  js/packages/berty-storybook/chat/Chat.tsx
  js/packages/berty-storybook/package.json
  js/packages/hooks/Chat.tsx
  js/packages/store/chat/message.ts
  js/yarn.lock
Labels: chat, 🔍 Ready for Review

#1822 fix(chat): fix contact request sent details page
  js/packages/berty-storybook/main/ListModal.tsx
  js/packages/berty-storybook/main/RequestSent.tsx
  js/packages/berty-storybook/main/Scan.tsx
  js/packages/berty-storybook/main/ScanRequest.tsx
  js/packages/berty-storybook/shared-components/Modal.tsx
  js/packages/berty-storybook/shared-components/Request.tsx
Labels: chat, 🔍 Ready for Review

#1856 fix(chat): hide footer in settings subscreens
  js/packages/berty-navigation/index.tsx
  js/packages/berty-storybook/settings/Footer.tsx
  js/packages/berty-storybook/shared-components/Footer.tsx
Labels: chat, 🔍 Ready for Review

#1847 refactor(proto): remove opaque reference and use ShareableContact
  api/bertytypes.proto
  docs/gen.sum
  docs/protocol/api.md
  go/cmd/berty/mini/view_group_incoming.go
  go/cmd/berty/mini/view_group_outgoing.go
  go/gen.sum
  go/pkg/bertyprotocol/api_contactrequest.go
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/bertyprotocol/store_metadata.go
  go/pkg/bertyprotocol/store_metadata_index.go
  go/pkg/bertytypes/bertytypes.pb.go
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/berty-storybook/modals/AddThisContact.tsx
  js/packages/berty-storybook/modals/SendContactRequest.tsx
  js/packages/codegen/Makefile
  js/packages/grpc-bridge/protocol/handler.ts
  js/packages/hooks/Chat.tsx
  js/packages/store/chat/account.ts
  js/packages/store/chat/contact.ts
  js/packages/store/chat/conversation.ts
  js/packages/store/protocol/client.gen.ts
  js/packages/store/protocol/client.gen.ts.hbs
  js/packages/store/protocol/client.ts
  js/packages/store/types/events.gen.ts
  js/packages/store/types/events.gen.ts.hbs
Labels: protocol, 🔍 Ready for Review

#1841 chore: update rdvp-dev deployment
  deployments/rdvp-dev/Makefile
  deployments/rdvp-dev/docker-compose.yml
Labels: 🔍 Ready for Review

#1858 fix(chat): make footer buttons match mockups + refactor footer and nav to simplify them
  js/packages/berty-navigation/index.tsx
  js/packages/berty-storybook/Onboarding.tsx
  js/packages/berty-storybook/main/Footer.tsx
  js/packages/berty-storybook/main/List.tsx
  js/packages/berty-storybook/settings/Footer.tsx
  js/packages/berty-storybook/settings/index.ts
  js/packages/berty-storybook/shared-components/Footer.tsx
Labels: chat, ✅ Approved

#1863 feat(chat): contact request incoming details page
  js/packages/berty-navigation/index.tsx
  js/packages/berty-storybook/main/ContactRequest.tsx
  js/packages/berty-storybook/main/List.tsx
  js/packages/berty-storybook/main/ScanRequest.tsx
  js/packages/berty-storybook/settings/Mode.tsx
Labels: chat, ✅ Approved

#1864 feat(chat): add this contact modal
  js/packages/berty-storybook/modals/AddThisContact.tsx
Labels: chat, ✅ Approved

#1862 fix(chat): remove bad usages of styles.text.family
  js/packages/berty-storybook/settings/AppUpdates.tsx
  js/packages/berty-storybook/settings/BlockedContacts.tsx
  js/packages/berty-storybook/settings/Home.tsx
  js/packages/berty-storybook/settings/TermsOfUse.tsx
  js/packages/berty-storybook/shared-components/Header.tsx
  js/packages/berty-storybook/shared-components/Request.tsx
  js/packages/berty-storybook/shared-components/SDTSModalComponent.tsx
  js/packages/berty-storybook/shared-components/SettingsButtons.tsx
  js/packages/berty-storybook/shared-components/TabBar.tsx
Labels: chat, ✅ Approved

#1859 Don't create conversation until contact has accepted request
  js/packages/hooks/Chat.tsx
  js/packages/store/chat/conversation.ts
Labels: chat, ✅ Approved

#1861 Conversation thumbnail icons
  js/packages/berty-storybook/chat/Chat.tsx
  js/packages/berty-storybook/main/List.tsx
  js/packages/berty-storybook/shared-components/Footer.tsx
  js/packages/hooks/Chat.tsx
  js/packages/store/chat/conversation.ts
  js/packages/store/chat/message.ts
Labels: chat, ✅ Approved

#1865 feat(chat): add link to the website and contact us
  js/packages/berty-storybook/settings/AboutBerty.tsx
Labels: chat, ✅ Approved

#1850 fix(chat): check font family
  js/packages/berty-app/android/app/src/main/assets/fonts/OpenSans-Bold.ttf
  js/packages/berty-app/android/app/src/main/assets/fonts/OpenSans-BoldItalic.ttf
  js/packages/berty-app/android/app/src/main/assets/fonts/OpenSans-ExtraBold.ttf
  js/packages/berty-app/android/app/src/main/assets/fonts/OpenSans-ExtraBoldItalic.ttf
  js/packages/berty-app/android/app/src/main/assets/fonts/OpenSans-Italic.ttf
  js/packages/berty-app/android/app/src/main/assets/fonts/OpenSans-Light.ttf
  js/packages/berty-app/android/app/src/main/assets/fonts/OpenSans-LightItalic.ttf
  js/packages/berty-app/android/app/src/main/assets/fonts/OpenSans-Regular.ttf
  js/packages/berty-app/android/app/src/main/assets/fonts/OpenSans-SemiBold.ttf
  js/packages/berty-app/android/app/src/main/assets/fonts/OpenSans-SemiBoldItalic.ttf
  js/packages/berty-app/assets/OpenSans-Bold.ttf
  js/packages/berty-app/assets/OpenSans-BoldItalic.ttf
  js/packages/berty-app/assets/OpenSans-ExtraBold.ttf
  js/packages/berty-app/assets/OpenSans-ExtraBoldItalic.ttf
  js/packages/berty-app/assets/OpenSans-Italic.ttf
  js/packages/berty-app/assets/OpenSans-Light.ttf
  js/packages/berty-app/assets/OpenSans-LightItalic.ttf
  js/packages/berty-app/assets/OpenSans-Regular.ttf
  js/packages/berty-app/assets/OpenSans-SemiBold.ttf
  js/packages/berty-app/assets/OpenSans-SemiBoldItalic.ttf
  js/packages/berty-app/ios/Berty.xcodeproj/project.pbxproj
  js/packages/berty-app/ios/Berty/Info.plist
  js/packages/berty-app/package.json
  js/packages/berty-app/react-native.config.js
  js/packages/berty-storybook/chat/Chat.tsx
  js/packages/berty-storybook/chat/ContactChatSettings.tsx
  js/packages/berty-storybook/chat/shared-components/Chat.tsx
  js/packages/berty-storybook/chat/shared-components/Message.tsx
  js/packages/berty-storybook/main/ContactRequest.tsx
  js/packages/berty-storybook/main/List.tsx
  js/packages/berty-storybook/main/RequestSent.tsx
  js/packages/berty-storybook/main/ScanRequest.tsx
  js/packages/berty-storybook/main/Search.tsx
  js/packages/berty-storybook/package.json
  js/packages/berty-storybook/settings/DevTools.tsx
  js/packages/berty-storybook/settings/EditProfile.tsx
  js/packages/berty-storybook/settings/TermsOfUse.tsx
  js/packages/berty-storybook/shared-components/FingerprintContent.tsx
  js/packages/berty-storybook/shared-components/Footer.tsx
  js/packages/berty-storybook/shared-components/SDTSModalComponent.tsx
  js/packages/berty-storybook/shared-components/SettingsButtons.tsx
  js/packages/berty-storybook/shared-components/TabBar.tsx
  js/packages/berty-storybook/theme.tsx
  js/packages/shared-storybook/package.json
  js/packages/storybook-mobile/package.json
  js/yarn.lock
Labels: chat, 🔍 Ready for Review

#1872 chore: allow retrying the bazel-go pipeline on CI
  .buildkite/pipeline.yml
Labels: 🔍 Ready for Review

#1873 chore: fix lint warns
  go/cmd/berty/mini/main.go
Labels: 🔍 Ready for Review

#1840 feat(discovery): Override ipfs routing with tinder package
  go.mod
  go.sum
  go/cmd/berty/main.go
  go/cmd/berty/mini/main.go
  go/cmd/berty/mini/view_group.go
  go/cmd/rdvp/main.go
  go/framework/bertybridge/bridge_demo.go
  go/framework/bertybridge/bridge_protocol.go
  go/framework/bertybridge/bridge_test.go
  go/framework/bertybridge/driver_logger.go
  go/internal/handshake/handshake_util_test.go
  go/internal/ipfsutil/api_inmemory.go
  go/internal/ipfsutil/cfg.go
  go/internal/ipfsutil/p2pzap.go
  go/internal/ipfsutil/routing.go
  go/internal/ipfsutil/testing.go
  go/internal/testutil/logging.go
  go/internal/tinder/driver.go
  go/internal/tinder/driver_dht.go
  go/internal/tinder/driver_mocked.go
  go/internal/tinder/driver_multi.go
  go/internal/tinder/driver_multi_test.go
  go/internal/tinder/driver_rdv.go
  go/internal/tinder/routing.go
  go/internal/tinder/service.go
  go/pkg/bertydemo/service.go
  go/pkg/bertydemo/service_test.go
  go/pkg/bertydemo/testing_test.go
  go/pkg/bertyprotocol/keystore_message_utils_test.go
  go/pkg/bertyprotocol/orbitdb_many_adds_berty_test.go
  go/pkg/bertyprotocol/orbitdb_many_adds_test.go
  go/pkg/bertyprotocol/orbitdb_utils_test.go
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertyprotocol/store_message_test.go
  go/pkg/bertyprotocol/store_metadata_test.go
  go/pkg/bertyprotocol/testing.go
Labels: dependent, ✅ Approved

#1879 fix(chat): text bold style
  js/packages/berty-storybook/chat/ChatSettings.tsx
  js/packages/berty-storybook/chat/ContactChatSettings.tsx
  js/packages/berty-storybook/modals/AddThisContact.tsx
  js/packages/berty-storybook/shared-components/Request.tsx
  js/packages/styles/index.tsx
Labels: chat, 🔍 Ready for Review

#1877 fix(chat): sort and boldify conversations
  js/packages/berty-storybook/main/List.tsx
  js/packages/berty-storybook/settings/Home.tsx
  js/packages/store/chat/conversation.ts
Labels: chat, 🔍 Ready for Review

#1874 Make icons closer to mockups
  js/packages/berty-app/App.tsx
  js/packages/berty-app/android/app/build.gradle
  js/packages/berty-app/android/app/src/main/assets/fonts/AntDesign.ttf
  js/packages/berty-app/android/app/src/main/assets/fonts/Entypo.ttf
  js/packages/berty-app/android/app/src/main/assets/fonts/EvilIcons.ttf
  js/packages/berty-app/android/app/src/main/assets/fonts/Feather.ttf
  js/packages/berty-app/android/app/src/main/assets/fonts/FontAwesome.ttf
  js/packages/berty-app/android/app/src/main/assets/fonts/FontAwesome5_Brands.ttf
  js/packages/berty-app/android/app/src/main/assets/fonts/FontAwesome5_Regular.ttf
  js/packages/berty-app/android/app/src/main/assets/fonts/FontAwesome5_Solid.ttf
  js/packages/berty-app/android/app/src/main/assets/fonts/Fontisto.ttf
  js/packages/berty-app/android/app/src/main/assets/fonts/Foundation.ttf
  js/packages/berty-app/android/app/src/main/assets/fonts/Ionicons.ttf
  js/packages/berty-app/android/app/src/main/assets/fonts/MaterialCommunityIcons.ttf
  js/packages/berty-app/android/app/src/main/assets/fonts/MaterialIcons.ttf
  js/packages/berty-app/android/app/src/main/assets/fonts/Octicons.ttf
  js/packages/berty-app/android/app/src/main/assets/fonts/SimpleLineIcons.ttf
  js/packages/berty-app/android/app/src/main/assets/fonts/Zocial.ttf
  js/packages/berty-app/android/app/src/main/java/tech/berty/app/MainApplication.java
  js/packages/berty-app/android/settings.gradle
  js/packages/berty-app/custom-icons-svgs/fingerprint.svg
  js/packages/berty-app/custom-icons-svgs/qr.svg
  js/packages/berty-app/custom-icons.tsx
  js/packages/berty-app/feather-icons.tsx
  js/packages/berty-app/ios/Berty.xcodeproj/project.pbxproj
  js/packages/berty-app/ios/Berty/Info.plist
  js/packages/berty-app/ios/Podfile.lock
  js/packages/berty-app/package.json
  js/packages/berty-storybook/chat/Chat.tsx
  js/packages/berty-storybook/chat/ChatGroup.tsx
  js/packages/berty-storybook/chat/ChatSettings.tsx
  js/packages/berty-storybook/chat/ContactChatSettings.tsx
  js/packages/berty-storybook/chat/GroupChatSettings.tsx
  js/packages/berty-storybook/main/Footer.tsx
  js/packages/berty-storybook/main/List.tsx
  js/packages/berty-storybook/main/ListModal.tsx
  js/packages/berty-storybook/main/Scan.tsx
  js/packages/berty-storybook/modals/AddThisContact.tsx
  js/packages/berty-storybook/settings/Mode.tsx
  js/packages/berty-storybook/settings/MyBertyId.tsx
  js/packages/berty-storybook/shared-components/Footer.tsx
  js/packages/berty-storybook/shared-components/Header.tsx
  js/packages/berty-storybook/shared-components/Request.tsx
  js/packages/berty-storybook/shared-components/SDTSModalComponent.tsx
  js/packages/berty-storybook/shared-components/TabBar.tsx
  js/packages/berty-storybook/theme.tsx
  js/yarn.lock
Labels: chat, 🔍 Ready for Review

#1875 chore: add package intro docs
  go/cmd/berty/doc.go
  go/cmd/berty/mini/doc.go
  go/cmd/rdvp/doc.go
  go/framework/bertybridge/doc.go
  go/internal/cryptoutil/doc.go
  go/internal/gomodhack/gomodhack.go
  go/internal/grpcutil/doc.go
  go/internal/handshake/doc.go
  go/internal/handshake/handshake.go
  go/internal/ipfsutil/doc.go
  go/internal/testutil/doc.go
  go/internal/tinder/doc.go
  go/pkg/banner/doc.go
  go/pkg/bertydemo/doc.go
  go/pkg/bertyprotocol/doc.go
  go/pkg/bertytypes/doc.go
  go/pkg/errcode/doc.go
Labels: 🔍 Ready for Review

#1881 Show an error modal if users tries to click deep link during onboarding
  js/packages/berty-storybook/Onboarding.tsx
  js/packages/berty-storybook/modals/SendContactRequest.tsx
  js/packages/store/chat/account.ts
Labels: chat, ✅ Approved

#1882 feat(rdvp): resolve dns maddr rendezvous point
  go.mod
  go/cmd/berty/main.go
  go/cmd/berty/mini/main.go
  go/internal/handshake/handshake_util_test.go
  go/internal/ipfsutil/routing.go
  go/internal/ipfsutil/testing.go
  go/pkg/bertyprotocol/orbitdb_utils_test.go
  go/pkg/bertyprotocol/testing.go
Labels: ✅ Approved

#1884 fix(chat): unset conversations reading state on app open
  js/packages/store/chat/conversation.ts
Labels: chat, ✅ Approved

#1886 fix(chat): show error modal when the user tries to add the same contact twice or to add itself
  js/packages/berty-storybook/modals/SendContactRequest.tsx
Labels: chat, ✅ Approved

#1887 Sha3 fingerprints
  js/packages/berty-storybook/chat/ContactChatSettings.tsx
  js/packages/berty-storybook/main/List.tsx
  js/packages/berty-storybook/modals/AddThisContact.tsx
  js/packages/berty-storybook/package.json
  js/packages/berty-storybook/settings/MyBertyId.tsx
  js/packages/berty-storybook/shared-components/FingerprintContent.tsx
  js/packages/berty-storybook/shared-components/Request.tsx
  js/packages/styles/index.tsx
  js/yarn.lock
Labels: chat, ✅ Approved

#1890 fix(chat): open all tabs in main modal
  js/packages/berty-navigation/index.tsx
  js/packages/berty-storybook/main/Footer.tsx
  js/packages/berty-storybook/main/ListModal.tsx
  js/packages/berty-storybook/shared-components/Footer.tsx
Labels: chat, 🔍 Ready for Review

#1894 Build yolo instead of staff on CI
  .buildkite/pipeline.yml
  js/packages/berty-app/Gemfile
  js/packages/berty-app/Gemfile.lock
  js/packages/berty-app/Makefile
  js/packages/berty-app/fastlane/Fastfile
  js/packages/berty-app/ios/Podfile.lock
Labels: build, chat, 🔍 Ready for Review

#1892 chore: improve godoc
  go/cmd/berty/doc.go
  go/cmd/berty/mini/doc.go
  go/cmd/rdvp/doc.go
  go/framework/bertybridge/doc.go
  go/internal/cryptoutil/doc.go
  go/internal/gomodhack/gomodhack.go
  go/internal/grpcutil/doc.go
  go/internal/handshake/doc.go
  go/internal/ipfsutil/doc.go
  go/internal/testutil/doc.go
  go/internal/tinder/doc.go
  go/pkg/banner/doc.go
  go/pkg/bertydemo/doc.go
  go/pkg/bertyprotocol/doc.go
  go/pkg/bertytypes/doc.go
  go/pkg/errcode/doc.go
Labels: ✅ Approved

#1896 Fix ListModal on iOS 12
  js/packages/berty-navigation/index.tsx
  js/packages/berty-storybook/main/ListModal.tsx
Labels: bug, chat, 🔍 Ready for Review

#1898 feat: add libp2p extra opts
  go/cmd/berty/main.go
  go/cmd/berty/mini/main.go
  go/framework/bertybridge/bridge_demo.go
  go/framework/bertybridge/bridge_protocol.go
  go/internal/config/berty.go
  go/internal/ipfsutil/api.go
  go/internal/ipfsutil/api_configurable.go
  go/internal/ipfsutil/api_inmemory.go
  go/internal/ipfsutil/cfg.go
  go/internal/ipfsutil/helper.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertyprotocol/service_test.go
Labels: 🔍 Ready for Review

#1899 fix(chat): grey out on send message button
  js/packages/berty-storybook/chat/shared-components/Chat.tsx
Labels: chat, ✅ Approved

#1895 fix(chat): infos and devices in tabs bar
  js/packages/berty-storybook/chat/ContactChatSettings.tsx
  js/packages/berty-storybook/modals/AddThisContact.tsx
  js/packages/berty-storybook/settings/MyBertyId.tsx
  js/packages/berty-storybook/shared-components/Request.tsx
  js/packages/berty-storybook/shared-components/TabBar.tsx
Labels: chat, 🔍 Ready for Review

#1891 fix(chat): padding for devices without unsafe zone
  js/packages/berty-storybook/main/List.tsx
  js/packages/berty-storybook/shared-components/Footer.tsx
Labels: chat, 🔍 Ready for Review

#1906 fix(chat): swipe down on main modal go back
  js/packages/berty-storybook/main/ListModal.tsx
Labels: chat, 🔍 Ready for Review

#1910 fix: identity provider issue/sync issue
  go/framework/bertybridge/bridge_demo.go
  go/framework/bertybridge/bridge_test.go
  go/pkg/bertydemo/service_test.go
  go/pkg/bertydemo/testing_test.go
  go/pkg/bertyprotocol/events.go
  go/pkg/bertyprotocol/orbitdb_signed_entry_accesscontroller.go
  go/pkg/bertyprotocol/orbitdb_signed_entry_identity_provider.go
  go/pkg/bertyprotocol/orbitdb_test.go
  go/pkg/bertyprotocol/store_message_test.go
  go/pkg/bertyprotocol/store_options.go
Labels: ✅ Approved

#1911 Fix MVP replication
  go/pkg/bertydemo/service.go
Labels: ✅ Approved

#1904 fix(chat): don't crash if bridge is already started
  js/packages/grpc-bridge/protocol/handler.ts
Labels: chat, 🔍 Ready for Review

#1912 fix(chat): fix icons on real devices and use more icons from mockups
  js/packages/berty-app/custom-icons-svgs/bubble.svg
  js/packages/berty-app/custom-icons-svgs/fingerprint.svg
  js/packages/berty-app/custom-icons-svgs/id.svg
  js/packages/berty-app/custom-icons-svgs/qr.svg
  js/packages/berty-app/custom-icons-svgs/share.svg
  js/packages/berty-app/custom-icons-svgs/user-plus.svg
  js/packages/berty-app/custom-icons-svgs/users.svg
  js/packages/berty-app/custom-icons.tsx
  js/packages/berty-storybook/chat/Chat.tsx
  js/packages/berty-storybook/chat/ChatGroup.tsx
  js/packages/berty-storybook/chat/ChatSettings.tsx
  js/packages/berty-storybook/chat/GroupChatSettings.tsx
  js/packages/berty-storybook/main/CreateGroup.tsx
  js/packages/berty-storybook/main/Footer.tsx
  js/packages/berty-storybook/main/List.tsx
  js/packages/berty-storybook/main/ListModal.tsx
  js/packages/berty-storybook/main/Scan.tsx
  js/packages/berty-storybook/modals/AddThisContact.tsx
  js/packages/berty-storybook/settings/Help.tsx
  js/packages/berty-storybook/settings/Home.tsx
  js/packages/berty-storybook/settings/MyBertyId.tsx
  js/packages/berty-storybook/settings/Notifications.tsx
  js/packages/berty-storybook/shared-components/Header.tsx
  js/packages/berty-storybook/shared-components/SettingsButtons.tsx
Labels: 🔍 Ready for Review

#1914 Improve onboarding and samples
  js/packages/berty-storybook/Onboarding.tsx
  js/packages/store/chat/conversation.ts
  js/packages/store/chat/message.ts
Labels: chat, 🔍 Ready for Review

#1897 fix(chat): fix app icon ios
  js/packages/berty-app/ios/Berty/Images.xcassets/AppIcon.appiconset/Contents.json
  js/packages/berty-app/ios/Berty/Images.xcassets/AppIcon.appiconset/icon_20pt@2x.png
  js/packages/berty-app/ios/Berty/Images.xcassets/AppIcon.appiconset/icon_20pt@3x.png
  js/packages/berty-app/ios/Berty/Images.xcassets/AppIcon.appiconset/icon_29pt@2x.png
  js/packages/berty-app/ios/Berty/Images.xcassets/AppIcon.appiconset/icon_29pt@3x.png
  js/packages/berty-app/ios/Berty/Images.xcassets/AppIcon.appiconset/icon_40pt@2x.png
  js/packages/berty-app/ios/Berty/Images.xcassets/AppIcon.appiconset/icon_40pt@3x.png
  js/packages/berty-app/ios/Berty/Images.xcassets/AppIcon.appiconset/icon_60pt@2x.png
  js/packages/berty-app/ios/Berty/Images.xcassets/AppIcon.appiconset/icon_60pt@3x.png
  js/packages/berty-app/ios/Berty/Images.xcassets/Contents.json
Labels: chat, ✅ Approved

#1919 Rework onboarding
  js/packages/berty-storybook/Onboarding.tsx
Labels: chat, 🔍 Ready for Review

#1920 Fix footer shaking
  js/packages/berty-app/App.tsx
  js/packages/berty-app/custom-icons-svgs/id.svg
  js/packages/berty-storybook/Onboarding.tsx
  js/packages/berty-storybook/chat/Chat.tsx
  js/packages/berty-storybook/chat/ChatGroup.tsx
  js/packages/berty-storybook/chat/shared-components/Chat.tsx
  js/packages/berty-storybook/main/CreateGroup.tsx
  js/packages/berty-storybook/main/List.tsx
  js/packages/berty-storybook/main/ListModal.tsx
  js/packages/berty-storybook/main/Scan.tsx
  js/packages/berty-storybook/main/ScanRequest.tsx
  js/packages/berty-storybook/main/Search.tsx
  js/packages/berty-storybook/modals/SendContactRequest.tsx
  js/packages/berty-storybook/settings/Home.tsx
  js/packages/berty-storybook/settings/MyBertyId.tsx
  js/packages/berty-storybook/shared-components/Footer.tsx
  js/packages/berty-storybook/shared-components/Header.tsx
  js/packages/berty-storybook/shared-components/Modal.tsx
  js/packages/berty-storybook/shared-components/SettingsButtons.tsx
Labels: chat, 🔍 Ready for Review

#1921 Add from-now in requests
  js/packages/berty-storybook/chat/Chat.tsx
  js/packages/berty-storybook/main/List.tsx
  js/packages/berty-storybook/main/ListModal.tsx
  js/packages/berty-storybook/shared-components/FromNow.tsx
  js/packages/store/chat/contact.ts
Labels: chat, 🔍 Ready for Review
