Repository berty/berty, pull requests merged in 2020-11, with the labels that each got.

#2622 fix: set docker to also listen on UDP ports + update list of RDVs servers
  config/config.gen.json
  config/config.yml
  go/internal/config/config.gen.go
  go/internal/initutil/ipfs.go
  js/packages/config/global.gen.js
  tool/deployments/rdvp-dev/docker-compose.yml
Labels: bug, ✅ Approved

#2618 feat(messenger): settings change i18n language
  js/package.json
  js/packages/components/onboarding/SetupFinished.js
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/Mode.tsx
  js/packages/store/provider.tsx
  js/yarn.lock
Labels: enhancement, ✅ Approved, 🔍 Ready for Review

#2621 chore: update download instructions
  .github/workflows/android.yml
  .github/workflows/go.yml
  .github/workflows/ios.yml
  README.md
  go/Makefile
  go/README.md
  go/gen.sum
  go/pkg/bertymessenger/README.md
  go/pkg/bertyprotocol/README.md
Labels: chore, ✅ Approved

#2605 feat: check for health of the RDVPs in `make doctor`
  Makefile
  go.mod
  go.sum
  go/Makefile
  go/cmd/bertydoctor/example_test.go
  go/cmd/bertydoctor/main.go
  go/cmd/bertydoctor/rdvp.go
  go/gen.sum
  go/internal/tinder/driver_rdv.go
  tool/go.mod
  tool/go.sum
Labels: WIP, enhancement, ✅ Approved

#2625 fix: Add bertydoctor to the gitignore
  .gitignore
Labels: bug, 🔍 Ready for Review

#2617 Fix: Fixed background alignment issue with profile screen
  js/packages/components/settings/Home.tsx
Labels: Fix, 🔍 Ready for Review

#2628 feat: Add temporary Hacked Relay
  config/config.gen.json
  config/config.yml
  go/framework/bertybridge/config.go
  go/internal/config/config.gen.go
  go/internal/initutil/ipfs.go
  go/internal/initutil/manager.go
  go/pkg/bertytypes/config.go
  js/packages/config/global.gen.js
Labels: enhancement, 🔍 Ready for Review

#2629 messenger: fix notifications and add sounds
  js/Makefile
  js/gen.sum
  js/ios/Berty/Sources/Berty_Notif_Message.mp3
  js/ios/Berty/Sources/Notif_Berty02.mp3
  js/ios/Berty/Sources/Notif_Berty04.mp3
  js/ios/Berty/Sources/Notif_Berty13.mp3
  js/ios/Berty/Sources/Notif_Berty14.mp3
  js/ios/Berty/Sources/Notif_Berty15message_envoye.mp3
  js/ios/Podfile.lock
  js/package.json
  js/packages/components/NotificationBody.tsx
  js/packages/components/NotificationProvider.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/shared-components/Chat.tsx
  js/packages/components/chat/shared-components/Message.tsx
  js/packages/components/hooks.ts
  js/packages/components/main/CreateGroupFinalize.tsx
  js/packages/components/main/Home.tsx
  js/packages/components/modals/DeleteAccount.tsx
  js/packages/components/settings/DevTools.tsx
  js/packages/components/settings/NetworkMap.js
  js/packages/components/sounds.ts
  js/packages/messenger-app/App.test.tsx
  js/yarn.lock
Labels: messenger, 🔍 Ready for Review

#2633 fix: Correctly setup RelayHack on mobile
  go/framework/bertybridge/config.go
  js/packages/go-bridge/defaults.ts
Labels: bug, 🚧 WIP

#2623 chore: js store code cleanup
  js/packages/berty-i18n/locale/debug/messages.json
  js/packages/berty-i18n/locale/en/messages.json
  js/packages/berty-i18n/locale/fr/messages.json
  js/packages/components/chat/ContactSettings.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/OneToOneSettings.tsx
  js/packages/components/gates.tsx
  js/packages/components/main/Home.tsx
  js/packages/components/modals/AddBetabot.js
  js/packages/components/modals/DeleteAccount.tsx
  js/packages/components/onboarding/AccountSelector.tsx
  js/packages/components/onboarding/Button.tsx
  js/packages/components/onboarding/CreateAccount.js
  js/packages/components/onboarding/GetStarted.js
  js/packages/components/onboarding/GetStarted.tsx
  js/packages/components/onboarding/SetupFinished.js
  js/packages/components/onboarding/index.ts
  js/packages/components/settings/DevTools.tsx
  js/packages/components/settings/Mode.tsx
  js/packages/components/settings/NetworkMap.js
  js/packages/components/settings/Notifications.tsx
  js/packages/grpc-bridge/service.d.ts
  js/packages/navigation/rootRef.ts
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
  js/packages/store/context.tsx
  js/packages/store/hooks.js
  js/packages/store/methods.ts
  js/packages/store/provider.tsx
  js/packages/store/providerEffects.ts
  js/packages/store/providerReducer.ts
  js/packages/store/services.tsx
Labels: chore, 🔍 Ready for Review

#2644 fix: android flavors config for network security and app name
  js/android/app/src/debug/AndroidManifest.xml
  js/android/app/src/debug/res/values/strings.xml
  js/android/app/src/releaseStaff/res/values/strings.xml
  js/android/app/src/releaseYolo/res/values/strings.xml
Labels: bug, ✅ Approved

#2630 fix(infra): forward compose udp ports
  tool/deployments/betabot/docker-compose.yml
  tool/deployments/testbot/docker-compose.yml
  tool/metrics-compose/docker-compose.yml
Labels: bug, ✅ Approved

#2642 importing/exporting messenger data
  api/bertymessenger.proto
  docs/gen.sum
  docs/messenger/api.md
  go/cmd/berty/export.go
  go/cmd/berty/main.go
  go/gen.sum
  go/internal/initutil/node.go
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/db_state_keeper.go
  go/pkg/bertymessenger/db_state_keeper_test.go
  go/pkg/bertymessenger/db_utils.go
  go/pkg/bertymessenger/export.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertymessenger/service_test.go
  go/pkg/bertyprotocol/account_export.go
  go/pkg/bertyprotocol/account_export_test.go
  js/gen.sum
  js/ios/Podfile.lock
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
Labels: 🔍 Ready for Review

#2647 chore: regen debug messages
  js/packages/berty-i18n/locale/debug/messages.json
Labels: chore, ✅ Approved

#2632 chore: move go/assets into go/pkg/assets
  go/Makefile
  go/cmd/berty/mini/main.go
  go/gen.sum
  go/pkg/assets/embed.go
  go/pkg/assets/example_test.go
  go/pkg/assets/pkged.go
Labels: chore, 🔍 Ready for Review

#2652 fix: Fixing hackrelay random selection logic
  go/internal/initutil/ipfs.go
Labels: bug, ✅ Approved

#2651 chore: update protobuf's github action filters
  .github/workflows/js.yml
  .github/workflows/protobuf.yml
Labels: chore, ✅ Approved

#2655 chore: update deployment scripts
  tool/deployments/betabot/docker-compose.yml
  tool/deployments/testbot/docker-compose.yml
Labels: chore, 🔍 Ready for Review

#2653 fix(betabot): Simpler locking for betabot's store
  go.mod
  go.sum
  go/cmd/betabot/main.go
Labels: bug, ✅ Approved, 🔍 Ready for Review

#2650 chore: removed debug locale
  js/Makefile
  js/gen.sum
  js/packages/berty-i18n/locale/debug/messages.json
  js/packages/berty-i18n/locale/en/messages.json
  js/packages/berty-i18n/locale/fr/messages.json
  js/packages/berty-i18n/locale/languages.js
  js/packages/components/settings/Mode.tsx
Labels: chore, ✅ Approved

#2656 fix(betabot): Fixing store lock again
  go/cmd/betabot/main.go
Labels: bug, ✅ Approved

#2641 feat(messenger): add more notifications
  .github/workflows/go.yml
  Makefile
  api/bertymessenger.proto
  docs/gen.sum
  docs/messenger/api.md
  go/gen.sum
  go/internal/initutil/manager_test.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/handlers.go
  js/gen.sum
  js/global.d.ts
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/components/NotificationBody.tsx
  js/packages/components/notifications/Basic.tsx
  js/packages/components/notifications/ContactRequestReceived.tsx
  js/packages/components/notifications/ContactRequestSent.tsx
  js/packages/components/notifications/MessageReceived.tsx
  js/packages/components/notifications/common.tsx
  js/packages/components/notifications/index.ts
  js/packages/store/context.tsx
Labels: enhancement, 🔍 Ready for Review

#2657 chore(js/deps): bump typescript and related
  js/.eslintignore
  js/Makefile
  js/gen.sum
  js/global.d.ts
  js/package.json
  js/packages/components/chat/MultiMemberSettings.tsx
  js/packages/components/helpers.ts
  js/packages/components/hooks.ts
  js/packages/components/shared-components/CircleAvatar.tsx
  js/packages/grpc-bridge/grpc-web-react-native-transport.ts
  js/packages/store/hooks.js
  js/yarn.lock
Labels: chore, 🔍 Ready for Review

#2659 chore(js/deps): bump all
  js/ios/Podfile.lock
  js/package.json
  js/yarn.lock
Labels: chore, 🔍 Ready for Review

#2624 feat: use bertybridge service as account manager
  api/bertyaccount.proto
  docs/gen.sum
  go/Makefile
  go/framework/bertybridge/blackbox_test.go
  go/framework/bertybridge/bridge.go
  go/framework/bertybridge/client.go
  go/framework/bertybridge/config.go
  go/framework/bertybridge/driver_lifecycle.go
  go/framework/bertybridge/driver_logger.go
  go/framework/bertybridge/internal/bridgepb/example_test.go
  go/framework/bertybridge/service.go
  go/gen.sum
  go/internal/grpcutil/lazy_client.go
  go/internal/grpcutil/lazy_message.go
  go/pkg/bertyaccount/bertyaccount.pb.go
  go/pkg/bertyaccount/serivce_lifecycle.go
  go/pkg/bertyaccount/service.go
  go/pkg/bertyaccount/service_account.go
  go/pkg/bertyaccount/service_grpc.go
  js/Makefile
  js/android/app/src/main/java/tech/berty/gobridge/GoBridgeModule.java
  js/gen.sum
  js/ios/Berty/Sources/Bridge/GoBridge.m
  js/ios/Berty/Sources/Bridge/GoBridge.swift
  js/ios/Berty/Sources/Bridge/LifeCycleDriver.swift
  js/packages/api/index.js
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/components/settings/DevTools.tsx
  js/packages/go-bridge/GoBridge.ts
  js/packages/go-bridge/types.ts
  js/packages/grpc-bridge/rpc/rpc.bridge.js
  js/packages/store/providerEffects.ts
Labels: enhancement, ✅ Approved

#2662 fix: Fixing MC setup on non darwin machine.
  .gitignore
  go/internal/initutil/ipfs.go
  go/internal/multipeer-connectivity-driver/bridge_darwin.go
  go/internal/multipeer-connectivity-driver/bridge_unsupported.go
Labels: bug, 🔍 Ready for Review

#2634 feat: add integration binary
  .github/workflows/integration.yml
  README.md
  config/config.gen.json
  config/config.yml
  go/Makefile
  go/cmd/berty-integration/README.md
  go/cmd/berty-integration/main.go
  go/gen.sum
  go/internal/config/config.gen.go
  go/internal/initutil/datastore.go
  js/packages/config/global.gen.js
  tool/deployments/testbot/docker-compose.yml
  tool/go.sum
Labels: enhancement, 🔍 Ready for Review

#2664 chore: git-friendly config generator
  config/Makefile
  go/internal/config/config.gen.go
  tool/config-generator/main.go
  tool/go.sum
Labels: chore, 🔍 Ready for Review

#2668 chore: notify failing scheduled tasks
  .github/workflows/integration.yml
  go/Makefile
  go/gen.sum
Labels: chore, 🔍 Ready for Review

#2669 feat: more consistant initutil CLI
  .gitignore
  go/Makefile
  go/README.md
  go/cmd/berty-doctor/example_test.go
  go/cmd/berty-doctor/main.go
  go/cmd/berty-doctor/rdvp.go
  go/cmd/berty-integration/README.md
  go/gen.sum
  go/internal/initutil/ipfs.go
  tool/deployments/betabot/docker-compose.yml
  tool/deployments/testbot/docker-compose.yml
Labels: enhancement, 🔍 Ready for Review

#2670 ci: Better url for integration test.
  .github/workflows/integration.yml
Labels: ci, ✅ Approved, 🔍 Ready for Review

#2663 fix: removed some dev warnings in rn client
  js/packages/components/hooks.ts
  js/packages/components/main/CreateGroupFinalize.tsx
  js/packages/components/main/Footer.tsx
  js/packages/components/main/Home.tsx
  js/packages/components/modals/AddBetabot.js
  js/packages/components/modals/AddThisContact.tsx
  js/packages/components/onboarding/GetStarted.tsx
  js/packages/components/settings/AboutBerty.tsx
  js/packages/components/settings/AddContactList.js
  js/packages/components/settings/DevTools.tsx
  js/packages/components/settings/Help.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/NetworkMap.js
  js/packages/components/settings/SystemInfo.tsx
  js/packages/store/context.tsx
  js/packages/store/providerReducer.ts
  js/packages/web-dev-app/src/App.tsx
Labels: bug, ✅ Approved

#2672 chore: setup integration benchmark
  .github/workflows/integration.yml
  go.mod
  go.sum
  go/cmd/berty-integration/main.go
  go/cmd/berty-integration/main_unsupported.go
  tool/go.sum
Labels: chore, 🔍 Ready for Review

#2673 update integration, run url gen at first
  .github/workflows/integration.yml
Labels: ✅ Approved, 🔍 Ready for Review

#2674 chore: fix integration github action
  .github/workflows/integration.yml
Labels: chore, 🔍 Ready for Review

#2675 fix: new i18n updates from crowdin
  js/packages/berty-i18n/locale/en/messages.json
  js/packages/berty-i18n/locale/fr/messages.json
Labels: bug, ✅ Approved

#2684 fix: go's `make install` on darwin
  .github/workflows/go.yml
  go/cmd/berty-integration/main.go
  go/cmd/berty-integration/main_unsupported.go
Labels: bug, 🔍 Ready for Review

#2687 Notification inhibitors
  go/pkg/bertymessenger/handlers.go
  js/ios/Podfile.lock
  js/packages/components/NotificationBody.tsx
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/main/CreateGroupAddMembers.tsx
  js/packages/components/main/Home.tsx
  js/packages/components/notifications/ContactRequestReceived.tsx
  js/packages/components/notifications/ContactRequestSent.tsx
  js/packages/components/notifications/MessageReceived.tsx
  js/packages/components/onboarding/AccountSelector.tsx
  js/packages/components/onboarding/CreateAccount.js
  js/packages/components/onboarding/GetStarted.js
  js/packages/components/onboarding/GetStarted.tsx
  js/packages/components/onboarding/ServicesAuth.tsx
  js/packages/components/onboarding/SetupFinished.js
  js/packages/grpc-bridge/service.d.ts
  js/packages/store/context.ts
  js/packages/store/hooks.ts
  js/packages/store/providerEffects.ts
  js/packages/store/providerReducer.ts
  js/packages/web-dev-app/src/App.tsx
Labels: 🔍 Ready for Review

#2695 fix(messenger): remove send on line return
  js/packages/components/chat/shared-components/Chat.tsx
Labels: bug, 🔍 Ready for Review

#2694 fix(messenger): add plurals and interpolation
  js/packages/berty-i18n/locale/en/messages.json
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/modals/DeleteAccount.tsx
  js/packages/components/settings/DevTools.tsx
  js/packages/components/settings/Notifications.tsx
Labels: bug, ✅ Approved

#2686 feat: multi account management
  api/bertyaccount.proto
  api/errcode.proto
  docs/gen.sum
  go/framework/bertybridge/blackbox_test.go
  go/gen.sum
  go/pkg/bertyaccount/bertyaccount.pb.go
  go/pkg/bertyaccount/service_account.go
  go/pkg/errcode/errcode.pb.go
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/berty-i18n/locale/en/messages.json
  js/packages/berty-i18n/locale/fr/messages.json
  js/packages/components/onboarding/AccountSelector.tsx
  js/packages/components/onboarding/SetupFinished.js
  js/packages/components/settings/Home.tsx
  js/packages/grpc-bridge/service.d.ts
  js/packages/store/context.ts
  js/packages/store/provider.tsx
  js/packages/store/providerEffects.ts
  js/packages/store/providerReducer.ts
Labels: enhancement, 🔍 Ready for Review

#2714 feat: add metrics endpoint to betabot/rdvp
  tool/deployments/betabot/docker-compose.yml
  tool/deployments/rdvp-dev/docker-compose.yml
Labels: enhancement

#2685 fix: android fault
  go/internal/grpcutil/lazy_client.go
Labels: WIP, bug, ✅ Approved

#2717 chore: bump deps
  go.mod
  go.sum
  tool/go.mod
  tool/go.sum
Labels: chore

#2719 chore: disable traefik on some deployment
  tool/deployments/betabot/docker-compose.yml
  tool/deployments/testbot/Makefile
  tool/deployments/testbot/docker-compose.yml
Labels: chore

#2676 New Crowdin updates
  js/packages/berty-i18n/locale/af/messages.json
  js/packages/berty-i18n/locale/ar/messages.json
  js/packages/berty-i18n/locale/ca/messages.json
  js/packages/berty-i18n/locale/cs/messages.json
  js/packages/berty-i18n/locale/da/messages.json
  js/packages/berty-i18n/locale/de/messages.json
  js/packages/berty-i18n/locale/el/messages.json
  js/packages/berty-i18n/locale/es/messages.json
  js/packages/berty-i18n/locale/fi/messages.json
  js/packages/berty-i18n/locale/fr/messages.json
  js/packages/berty-i18n/locale/he/messages.json
  js/packages/berty-i18n/locale/hu/messages.json
  js/packages/berty-i18n/locale/it/messages.json
  js/packages/berty-i18n/locale/ja/messages.json
  js/packages/berty-i18n/locale/ko/messages.json
  js/packages/berty-i18n/locale/nl/messages.json
  js/packages/berty-i18n/locale/no/messages.json
  js/packages/berty-i18n/locale/pl/messages.json
  js/packages/berty-i18n/locale/pt/messages.json
  js/packages/berty-i18n/locale/ro/messages.json
  js/packages/berty-i18n/locale/ru/messages.json
  js/packages/berty-i18n/locale/sr/messages.json
  js/packages/berty-i18n/locale/sv/messages.json
  js/packages/berty-i18n/locale/tr/messages.json
  js/packages/berty-i18n/locale/uk/messages.json
  js/packages/berty-i18n/locale/vi/messages.json
  js/packages/berty-i18n/locale/zh/messages.json
Labels: 🔍 Ready for Review

#2671 feat: Add Group Monitor
  api/bertymessenger.proto
  api/bertyprotocol.proto
  api/bertyprotocol.yaml
  api/bertytypes.proto
  docs/gen.sum
  docs/messenger/api.md
  docs/messenger/bertymessenger.swagger.json
  docs/protocol/api.md
  docs/protocol/bertyprotocol.swagger.json
  go/cmd/berty/mini/view_group.go
  go/cmd/berty/mini/view_group_incoming.go
  go/gen.sum
  go/internal/initutil/ipfs.go
  go/internal/initutil/manager.go
  go/internal/initutil/node.go
  go/internal/ipfsutil/pubsub_monitor.go
  go/internal/ipfsutil/testing.go
  go/internal/ipfsutil/util.go
  go/internal/tinder/asyncable_driver.go
  go/internal/tinder/driver_monitor.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertymessenger/types.go
  go/pkg/bertyprotocol/api_group.go
  go/pkg/bertyprotocol/bertyprotocol.pb.go
  go/pkg/bertyprotocol/bertyprotocol.pb.gw.go
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/bertytypes/bertytypes.pb.go
  js/gen.sum
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  tool/go.sum
Labels: enhancement, 🔍 Ready for Review

#2725 fix: new crowdin updates
  js/packages/berty-i18n/locale/af/messages.json
  js/packages/berty-i18n/locale/ar/messages.json
  js/packages/berty-i18n/locale/ca/messages.json
  js/packages/berty-i18n/locale/cs/messages.json
  js/packages/berty-i18n/locale/da/messages.json
  js/packages/berty-i18n/locale/de/messages.json
  js/packages/berty-i18n/locale/el/messages.json
  js/packages/berty-i18n/locale/es/messages.json
  js/packages/berty-i18n/locale/fi/messages.json
  js/packages/berty-i18n/locale/fr/messages.json
  js/packages/berty-i18n/locale/he/messages.json
  js/packages/berty-i18n/locale/hu/messages.json
  js/packages/berty-i18n/locale/it/messages.json
  js/packages/berty-i18n/locale/ja/messages.json
  js/packages/berty-i18n/locale/ko/messages.json
  js/packages/berty-i18n/locale/nl/messages.json
  js/packages/berty-i18n/locale/no/messages.json
  js/packages/berty-i18n/locale/pl/messages.json
  js/packages/berty-i18n/locale/pt/messages.json
  js/packages/berty-i18n/locale/ro/messages.json
  js/packages/berty-i18n/locale/ru/messages.json
  js/packages/berty-i18n/locale/sr/messages.json
  js/packages/berty-i18n/locale/sv/messages.json
  js/packages/berty-i18n/locale/tr/messages.json
  js/packages/berty-i18n/locale/uk/messages.json
  js/packages/berty-i18n/locale/vi/messages.json
  js/packages/berty-i18n/locale/zh/messages.json
Labels: bug, 🔍 Ready for Review

#2715 feat: export account data to tar file within mobile app
  js/android/app/build.gradle
  js/android/settings.gradle
  js/index.js
  js/ios/Podfile.lock
  js/package.json
  js/packages/berty-i18n/locale/en/messages.json
  js/packages/berty-i18n/locale/fr/messages.json
  js/packages/components/settings/Mode.tsx
  js/packages/messenger-app/App.test.tsx
  js/packages/store/services.tsx
  js/yarn.lock
Labels: enhancement, ✅ Approved

#2733 fix: whitescreen on start
  go/README.md
  go/cmd/berty-integration/README.md
  go/internal/initutil/datastore.go
  go/internal/initutil/logger.go
  go/internal/initutil/manager.go
  go/internal/initutil/node.go
  go/pkg/bertyaccount/service.go
  go/pkg/bertyaccount/service_account.go
  js/packages/go-bridge/defaults.ts
Labels: bug, ✅ Approved

#2738 fix(ci): downgrade go version in ios build
  .github/workflows/ios.yml
Labels: bug, ✅ Approved

#2730 feat(messenger): add UI message monitor metadata
  go/pkg/bertymessenger/service.go
  js/packages/berty-i18n/locale/en/messages.json
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/shared-components/Message.tsx
  js/packages/components/onboarding/SetupFinished.js
  js/packages/components/settings/DevTools.tsx
  js/packages/components/settings/Mode.tsx
  js/packages/store/context.ts
  js/packages/store/providerEffects.ts
  js/packages/store/providerReducer.ts
Labels: enhancement, ✅ Approved

#2720 fix(messenger): UI screen share qr group
  js/packages/berty-i18n/locale/en/messages.json
  js/packages/components/chat/MultiMemberQR.tsx
Labels: bug

#2741 fix: disable logging for the tor node
  go/internal/initutil/ipfs.go
Labels: bug, ✅ Approved

#2739 FIX: ipfs persistence
  go/internal/initutil/ipfs.go
  js/packages/components/chat/shared-components/Message.tsx
Labels: Fix, ✅ Approved

#2718 chore: bump ipfs/libp2p deps
  go.mod
  go.sum
  go/internal/handshake/handshake_test.go
  go/internal/initutil/manager_test.go
  go/internal/ipfsutil/helpers.go
  go/internal/ipfsutil/helpers_test.go
  go/internal/ipfsutil/pubsub_api.go
  go/pkg/bertyprotocol/contact_request_manager.go
  tool/go.sum
Labels: chore, ✅ Approved

#2745 fix: relay hack announce
  go/internal/initutil/ipfs.go
Labels: bug, ✅ Approved

#2737 chore: add grpc connectivity state information to betabot
  go/cmd/betabot/main.go
Labels: chore, 🔍 Ready for Review

#2752 chore: test doctor on CI
  .github/workflows/integration.yml
Labels: chore, 🔍 Ready for Review

#2753 chore: update gitattributes
  .gitattributes
Labels: chore, ✅ Approved

#2755 fix: update betabot addr
  config/Makefile
  config/config.gen.json
  config/config.yml
  go/cmd/betabot/README.md
  go/internal/config/config.gen.go
  js/packages/config/global.gen.js
Labels: bug, 🔍 Ready for Review

#2758 chore: bump deps
  .gitattributes
  go.mod
  go.sum
  tool/go.sum
Labels: chore, 🔍 Ready for Review

#2750 fix: mv contact list into dev conversations and improve it
  config/config.gen.json
  config/config.yml
  go/internal/config/config.gen.go
  go/pkg/bertytypes/config.go
  js/packages/berty-i18n/locale/en/messages.json
  js/packages/components/settings/AddConversationList.js
  js/packages/components/settings/AddDevConversations.js
  js/packages/components/settings/DevTools.tsx
  js/packages/components/settings/index.ts
  js/packages/config/global.gen.js
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
Labels: bug, ✅ Approved

#2772 fix(messenger): i18n key of no-results search
  js/packages/components/main/Home.tsx
Labels: bug, ✅ Approved

#2704 Improve search screen issue#2654
  js/packages/components/main/Home.tsx
  js/packages/components/shared-components/HintBody.js
  js/packages/components/shared-components/SwipeNavRecognizer.tsx
  js/packages/messenger-app/custom-icons-svgs/quote.svg
  js/packages/navigation/stacks.tsx
Labels: ✅ Approved

#2732 feat(messenger): import account data
  api/bertymessenger.proto
  docs/gen.sum
  docs/messenger/api.md
  go/gen.sum
  go/internal/initutil/manager.go
  go/internal/initutil/node.go
  go/pkg/bertyaccount/service_account.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/db_state_keeper.go
  go/pkg/bertymessenger/db_utils.go
  go/pkg/bertymessenger/db_utils_test.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertyprotocol/store_message.go
  go/pkg/bertyprotocol/store_metadata.go
  js/gen.sum
  js/ios/Podfile.lock
  js/package.json
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/components/onboarding/AccountSelector.tsx
  js/packages/components/settings/Home.tsx
  js/packages/store/providerEffects.ts
  js/yarn.lock
Labels: enhancement, ✅ Approved

#2773 chore: use go1.15 in bertytech/protoc:26
  .github/workflows/protobuf.yml
  docs/Makefile
  docs/gen.sum
  docs/messenger/bertymessenger.swagger.json
  docs/protocol/bertyprotocol.swagger.json
  go/Makefile
  go/gen.sum
  go/pkg/bertymessenger/bertymessenger.pb.gw.go
  go/pkg/bertyprotocol/bertyprotocol.pb.gw.go
  go/pkg/bertyprotocol/bertyreplication.pb.gw.go
  tool/docker-protoc/Dockerfile
  tool/docker-protoc/Makefile
Labels: chore, 🔍 Ready for Review

#2749 fix(messenger): UI message monitor metadata
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/message/MessageInvitation.tsx
  js/packages/components/chat/message/MessageMonitorMetadata.tsx
  js/packages/components/chat/message/MessageSystemWrapper.tsx
  js/packages/components/chat/message/QuickReplyOptions.tsx
  js/packages/components/chat/message/UserMessage.tsx
  js/packages/components/chat/message/UserMessageComponents.tsx
  js/packages/components/chat/message/index.tsx
  js/packages/components/chat/shared-components/Message.tsx
Labels: bug, ✅ Approved

#2747 fix: missing replicating logs
  go/pkg/bertyprotocol/api_event.go
Labels: bug, ✅ Approved

#2776 read more in conversation
  js/packages/components/chat/message/UserMessageComponents.tsx
Labels: ✅ Approved

#2774 fix(messenger): types for store providerEffect openingDaemon
  js/packages/go-bridge/defaults.ts
  js/packages/store/providerEffects.ts
Labels: bug, 🔍 Ready for Review

#2793 chore: add a check to skip CI jobs
  .github/workflows/android.yml
  .github/workflows/go.yml
  .github/workflows/integration.yml
  .github/workflows/ios.yml
  .github/workflows/js.yml
  .github/workflows/protobuf.yml
  .github/workflows/push.yml
  .github/workflows/release.yml
Labels: chore, 🔍 Ready for Review

#2795 Revert "Merge pull request #2793 from berty/dev/moul/skip-ci"
  .github/workflows/android.yml
  .github/workflows/go.yml
  .github/workflows/integration.yml
  .github/workflows/ios.yml
  .github/workflows/js.yml
  .github/workflows/protobuf.yml
  .github/workflows/push.yml
  .github/workflows/release.yml
Labels: 🔍 Ready for Review

#2643 Adding Omnisearch search engine.
  go/cmd/berty/main.go
  go/cmd/berty/omnisearch.go
  go/internal/initutil/node.go
  go/internal/ipfsutil/extended_core_api.go
  go/internal/omnisearch/berty-engine.go
  go/internal/omnisearch/berty-parser.go
  go/internal/omnisearch/config.go
  go/internal/omnisearch/coordinator.go
  go/internal/omnisearch/default.go
  go/internal/omnisearch/manager.go
  go/internal/omnisearch/mirror.go
  go/internal/omnisearch/rdvp.go
  go/internal/omnisearch/ressources.go
  go/pkg/bertymessenger/api.go
Labels: WIP, ✅ Approved

#2791 chore: fix testbot addr
  config/config.gen.json
  config/config.yml
  go/cmd/testbot/README.md
  go/internal/config/config.gen.go
  js/packages/config/global.gen.js
Labels: chore, ✅ Approved

#2777 feat: readability debug message
  js/packages/components/chat/message/MessageMonitorMetadata.tsx
Labels: enhancement, 🔍 Ready for Review

#2754 navigation transition
  js/ios/Podfile.lock
  js/package.json
  js/packages/components/main/RequestSent.tsx
  js/packages/components/main/Scan.tsx
  js/packages/components/main/Search.tsx
  js/packages/components/main/index.ts
  js/packages/components/settings/AddDevConversations.js
  js/packages/components/settings/Mode.tsx
  js/packages/navigation/hook.ts
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
  js/yarn.lock
Labels: WIP, 🔍 Ready for Review

#2723 Custom QR Design
  js/package.json
  js/packages/components/main/1_berty_picto.png
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/MyBertyId.tsx
  js/yarn.lock
Labels: WIP, 🔍 Ready for Review

#2807 fix: CI on master
  .github/workflows/android.yml
  .github/workflows/ios.yml
  .github/workflows/js.yml
  js/ios/Podfile.lock
  js/package.json
  js/packages/messenger-app/App.test.tsx
  js/yarn.lock
Labels: bug, ✅ Approved

#2804 New Crowdin updates
  js/packages/berty-i18n/locale/af/messages.json
  js/packages/berty-i18n/locale/ar/messages.json
  js/packages/berty-i18n/locale/bg/messages.json
  js/packages/berty-i18n/locale/ca/messages.json
  js/packages/berty-i18n/locale/cs/messages.json
  js/packages/berty-i18n/locale/da/messages.json
  js/packages/berty-i18n/locale/de/messages.json
  js/packages/berty-i18n/locale/el/messages.json
  js/packages/berty-i18n/locale/es/messages.json
  js/packages/berty-i18n/locale/fi/messages.json
  js/packages/berty-i18n/locale/fr/messages.json
  js/packages/berty-i18n/locale/he/messages.json
  js/packages/berty-i18n/locale/hu/messages.json
  js/packages/berty-i18n/locale/it/messages.json
  js/packages/berty-i18n/locale/ja/messages.json
  js/packages/berty-i18n/locale/ko/messages.json
  js/packages/berty-i18n/locale/nl/messages.json
  js/packages/berty-i18n/locale/no/messages.json
  js/packages/berty-i18n/locale/pl/messages.json
  js/packages/berty-i18n/locale/pt/messages.json
  js/packages/berty-i18n/locale/ro/messages.json
  js/packages/berty-i18n/locale/ru/messages.json
  js/packages/berty-i18n/locale/sr/messages.json
  js/packages/berty-i18n/locale/sv/messages.json
  js/packages/berty-i18n/locale/tr/messages.json
  js/packages/berty-i18n/locale/uk/messages.json
  js/packages/berty-i18n/locale/vi/messages.json
  js/packages/berty-i18n/locale/zh/messages.json
Labels: 🔍 Ready for Review

#2811 fix: set no concurrency when fetching node_modules with yarn
  js/Makefile
  js/package.json
Labels: bug, 🔍 Ready for Review

#2756 feat: refactor sharing links
  api/bertymessenger.proto
  docs/gen.sum
  docs/messenger/api.md
  docs/messenger/bertymessenger.swagger.json
  go.mod
  go.sum
  go/cmd/berty-integration/main.go
  go/cmd/berty/groupinit.go
  go/cmd/berty/mini/utils.go
  go/cmd/berty/mini/view_group_outgoing.go
  go/cmd/berty/shareinvite.go
  go/cmd/betabot/main.go
  go/gen.sum
  go/internal/omnisearch/berty-parser.go
  go/pkg/bertybot/bot.go
  go/pkg/bertybot/bot_test.go
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/api_test.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/links.go
  go/pkg/bertymessenger/links_test.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertymessenger/service_test.go
  go/pkg/bertymessenger/testing_test.go
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  js/packages/components/modals/ManageDeepLink.tsx
Labels: enhancement, 🔍 Ready for Review

#2813 fix: update testbot, betabot and test group keys
  config/config.gen.json
  config/config.yml
  go/cmd/betabot/README.md
  go/cmd/testbot/README.md
  go/internal/config/config.gen.go
  js/packages/config/global.gen.js
Labels: bug, 🔍 Ready for Review

#2792 fix: timeout while setuping
  .gitignore
  go/cmd/berty/daemon.go
  go/cmd/berty/mini.go
  go/internal/initutil/datastore.go
  go/internal/initutil/ipfs.go
  go/internal/initutil/logger.go
  go/internal/initutil/manager.go
  go/internal/initutil/metrics.go
  go/internal/initutil/node.go
  go/internal/initutil/notification.go
  go/internal/initutil/orbitdb.go
Labels: bug, ✅ Approved

#2798 fix: trying to use ble on an unsupported platform
  go/internal/initutil/ipfs.go
Labels: bug, ✅ Approved

#2809 fix(messenger): flow bridge
  js/packages/berty-i18n/locale/en/messages.json
  js/packages/components/onboarding/CreateAccount.js
  js/packages/components/settings/DevTools.tsx
  js/packages/store/context.ts
  js/packages/store/provider.tsx
  js/packages/store/providerEffects.ts
  js/packages/store/providerReducer.ts
Labels: bug, 🔍 Ready for Review

#2815 chore: update testbot-dev and betabot-dev
  config/config.gen.json
  config/config.yml
  go/internal/config/config.gen.go
  js/packages/config/global.gen.js
Labels: chore, 🔍 Ready for Review

#2814 chore: test the identity persistency with import/export
  go/cmd/berty/scenario_test.go
Labels: chore, 🔍 Ready for Review

#2820 chore: add {testbot,betabot} -log-format=json
  go.mod
  go.sum
  go/cmd/betabot/main.go
  go/cmd/testbot/main.go
Labels: chore, 🔍 Ready for Review

#2794 fix: set "App Uses Non-Exempt Encryption" to false
  js/ios/info.yaml
Labels: bug, ✅ Approved

#2824 fix: change JSON log formats to something more human-readable
  go/internal/logutil/logutil.go
Labels: bug, 🔍 Ready for Review

#2822 feat: file upload ui
  js/packages/berty-i18n/locale/en/messages.json
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/file-uploads/AddFileMenu.tsx
  js/packages/components/chat/shared-components/Chat.tsx
  js/packages/messenger-app/custom-icons-svgs/add-picture.svg
  js/packages/messenger-app/custom-icons-svgs/bertyzzz.svg
  js/packages/messenger-app/custom-icons-svgs/microphone.svg
  js/packages/messenger-app/custom-icons.tsx
Labels: enhancement, ✅ Approved

#2821 feat: bind go-libtor deps with iOS app
  go.mod
  go.sum
  js/Makefile
  js/gen.sum
  js/ios/.gitignore
  js/ios/OpenSSL-Universal-Override.podspec
  js/ios/Podfile
  js/ios/Podfile.lock
  js/ios/berty.yaml
Labels: enhancement, ✅ Approved

#2829 chore: update discord webhook for failing integrations
  .github/workflows/integration.yml
Labels: chore, 🔍 Ready for Review

#2828 feat: setup gomobile cache to reduce rebuild time
  go.mod
  go.sum
  js/Makefile
  js/android/.gitignore
  js/gen.sum
  js/ios/.gitignore
  js/metro.config.js
Labels: enhancement, ✅ Approved

#2825 fix: store state machine
  js/packages/components/settings/DevTools.tsx
  js/packages/store/providerEffects.ts
  js/packages/store/providerReducer.ts
Labels: bug, 🔍 Ready for Review

#2740 feat: change homepage button design#2713
  js/packages/berty-i18n/locale/en/messages.json
  js/packages/components/main/CreateGroupFinalize.tsx
  js/packages/components/main/Footer.tsx
  js/packages/components/main/Home.tsx
  js/packages/components/main/HomeModal.tsx
  js/packages/components/modals/ManageGroupInvitation.tsx
  js/packages/messenger-app/custom-icons-svgs/add-new-group.svg
  js/packages/messenger-app/custom-icons-svgs/qr.svg
  js/packages/messenger-app/custom-icons.tsx
  js/packages/navigation/hook.ts
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
Labels: enhancement, 🔍 Ready for Review

#2831 fix: Makefile rule for tor deps download
  js/Makefile
  js/gen.sum
Labels: bug, ✅ Approved, ✨ Merged

#2832 New Crowdin updates
  js/packages/berty-i18n/locale/af/messages.json
  js/packages/berty-i18n/locale/ar/messages.json
  js/packages/berty-i18n/locale/bg/messages.json
  js/packages/berty-i18n/locale/ca/messages.json
  js/packages/berty-i18n/locale/cs/messages.json
  js/packages/berty-i18n/locale/da/messages.json
  js/packages/berty-i18n/locale/de/messages.json
  js/packages/berty-i18n/locale/el/messages.json
  js/packages/berty-i18n/locale/en/messages.json
  js/packages/berty-i18n/locale/es/messages.json
  js/packages/berty-i18n/locale/fi/messages.json
  js/packages/berty-i18n/locale/fr/messages.json
  js/packages/berty-i18n/locale/he/messages.json
  js/packages/berty-i18n/locale/hu/messages.json
  js/packages/berty-i18n/locale/it/messages.json
  js/packages/berty-i18n/locale/ja/messages.json
  js/packages/berty-i18n/locale/ko/messages.json
  js/packages/berty-i18n/locale/nl/messages.json
  js/packages/berty-i18n/locale/no/messages.json
  js/packages/berty-i18n/locale/pl/messages.json
  js/packages/berty-i18n/locale/pt/messages.json
  js/packages/berty-i18n/locale/ro/messages.json
  js/packages/berty-i18n/locale/ru/messages.json
  js/packages/berty-i18n/locale/sr/messages.json
  js/packages/berty-i18n/locale/sv/messages.json
  js/packages/berty-i18n/locale/tr/messages.json
  js/packages/berty-i18n/locale/uk/messages.json
  js/packages/berty-i18n/locale/vi/messages.json
  js/packages/berty-i18n/locale/zh/messages.json
Labels: ✅ Approved

#2812 feat(doctor): mesure time for RDVP
  go/cmd/berty-doctor/rdvp.go
Labels: enhancement, 🔍 Ready for Review

#2834 chore: refactor docs/ folder
  docs/Makefile
  docs/apis/bertymessenger.md
  docs/apis/bertymessenger.swagger.json
  docs/apis/bertyprotocol.md
  docs/apis/bertyprotocol.swagger.json
  docs/architecture/2020-11-27-adr-berty-grpc-bridge.txt
  docs/architecture/2020-11-27-adr-gomobile-ipfs.md
  docs/architecture/README.md
  docs/architecture/messenger-mvp/README.md
  docs/architecture/messenger-mvp/contact-request.mermaid
  docs/architecture/messenger-mvp/contact-request.mermaid.svg
  docs/gen.sum
  docs/ideas/distributed-entropy.md
  docs/ideas/entropy-pool.md
Labels: chore, 🔍 Ready for Review

#2838 chore: restore caller in logs
  go/internal/logutil/logutil.go
  go/internal/logutil/logutil_test.go
Labels: chore, 🔍 Ready for Review

#2839 fix: append 'pb/' suffix to 'berty://' scheme to allow supporting encryption and dns in the future
  go/pkg/bertymessenger/api_test.go
  go/pkg/bertymessenger/links.go
  go/pkg/bertymessenger/links_test.go
Labels: bug, 🔍 Ready for Review

#2836 fix: appends announces
  go.mod
  go.sum
Labels: bug, ✅ Approved

#2842 chore: sync infra config
  tool/deployments/betabot/Makefile
  tool/deployments/betabot/docker-compose.yml
  tool/deployments/rdvp-dev/docker-compose.yml
  tool/deployments/testbot/Makefile
  tool/deployments/testbot/docker-compose.yml
Labels: chore, 🔍 Ready for Review

#2841 fix(messenger): call handle persistent options at onboarding
  js/packages/components/onboarding/SetupFinished.js
Labels: bug, 🔍 Ready for Review

#2823 feat(messenger): add tor toggle and change daemon option
  js/packages/berty-i18n/locale/en/messages.json
  js/packages/components/onboarding/SetupFinished.js
  js/packages/components/settings/DevTools.tsx
  js/packages/store/context.ts
  js/packages/store/providerEffects.ts
Labels: enhancement, 🔍 Ready for Review
