Repository berty/berty, pull requests merged in 2020-06, with the labels that each got.

#1986 chore: setup golangci-lint github action
  .buildkite/pipeline.yml
  .github/workflows/golangci-lint.yml
  go/cmd/berty/main.go
  go/cmd/berty/mini/main.go
  go/cmd/rdvp/main.go
  go/framework/bertybridge/bridge_protocol.go
  go/framework/bertybridge/bridge_test.go
  go/framework/bertybridge/driver_logger.go
  go/framework/bertybridge/testing_test.go
  go/internal/ipfsutil/api.go
  go/internal/ipfsutil/repo.go
  go/internal/ipfsutil/routing.go
  go/internal/multipeer-connectivity-transport/conn.go
  go/internal/multipeer-connectivity-transport/connmgr.go
  go/internal/multipeer-connectivity-transport/discovery.go
  go/internal/multipeer-connectivity-transport/init.go
  go/internal/multipeer-connectivity-transport/listener.go
  go/internal/multipeer-connectivity-transport/multiaddr/init.go
  go/internal/multipeer-connectivity-transport/multiaddr/multiaddr.go
  go/internal/multipeer-connectivity-transport/multiaddr/transcoder.go
  go/internal/multipeer-connectivity-transport/transport.go
  go/internal/tinder/driver_multi.go
  go/internal/tracer/tracer.go
  go/pkg/bertyprotocol/api_debug.go
  go/pkg/bertyprotocol/client.go
  go/pkg/bertyprotocol/contact_request_manager.go
  go/pkg/bertyprotocol/events_sig_checkers.go
  go/pkg/bertyprotocol/tinder_swiper.go
Labels: ✅ Approved

#1985 chore: reduce sleep time from 1m to 10s between tinder retries
  go/internal/tinder/driver_multi.go
  go/internal/tinder/driver_multi_test.go
Labels: ✅ Approved

#1990 chore: run the 'make generate' CI test to github actions
  .buildkite/pipeline.yml
  .github/workflows/protobuf.yml
Labels: ✅ Approved

#1987 fix(chat): responsive BertyId modal
  js/gen.sum
  js/package.json
  js/packages/components/settings/MyBertyId.tsx
  js/packages/components/shared-components/Request.tsx
  js/yarn.lock
Labels: messenger, 🔍 Ready for Review

#2004 feat: implement contact request from bertymessenger go package
  api/bertymessenger.proto
  api/errcode.proto
  docs/gen.sum
  docs/messenger/api.md
  go/cmd/berty/main.go
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/api_test.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/testing.go
  go/pkg/bertymessenger/testing_test.go
  go/pkg/errcode/errcode.pb.go
  js/packages/api/index.gen.js
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/codegen/index.gen.js
  js/packages/components/faker.gen.tsx
Labels: ✅ Approved

#1909 fix: scenario test, waiting all members to know other's secrets
  go.mod
  go.sum
  go/framework/bertybridge/bridge.go
  go/internal/tracer/runtime.go
  go/pkg/bertyprotocol/api_event.go
  go/pkg/bertyprotocol/group.go
  go/pkg/bertyprotocol/keystore_message.go
  go/pkg/bertyprotocol/keystore_message_utils.go
  go/pkg/bertyprotocol/keystore_message_utils_test.go
  go/pkg/bertyprotocol/orbitdb.go
  go/pkg/bertyprotocol/orbitdb_many_adds_berty_test.go
  go/pkg/bertyprotocol/orbitdb_test.go
  go/pkg/bertyprotocol/orbitdb_utils_test.go
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertyprotocol/service_group.go
  go/pkg/bertyprotocol/store_message.go
  go/pkg/bertyprotocol/store_message_test.go
  go/pkg/bertyprotocol/store_metadata.go
  go/pkg/bertyprotocol/store_metadata_index.go
  go/pkg/bertyprotocol/testing.go
Labels: ✅ Approved

#1978 feat(chat): add tracing config toggle
  go/framework/bertybridge/bridge_protocol.go
  go/internal/config/berty.go
  js/packages/components/Onboarding.tsx
  js/packages/components/settings/DevTools.tsx
  js/packages/go-bridge/ios/GoBridge.swift
  js/packages/go-bridge/types.ts
  js/packages/hooks/Settings.tsx
  js/packages/store/chat/index.ts
  js/packages/store/protocol/client.ts
  js/packages/store/settings/main.ts
Labels: messenger, ✅ Approved

#2005 docs: add protocol whitepaper
  docs/protocol/README.md
  docs/protocol/img/B1onw7wdI.png
  docs/protocol/img/B1qIgVw_8.png
  docs/protocol/img/BJAQwQP_I.png
  docs/protocol/img/BJWLZR6vU.png
  docs/protocol/img/BkFkKBDOU.png
  docs/protocol/img/BymgCaaDI.png
  docs/protocol/img/H1jJ6fvdI.png
  docs/protocol/img/HJ9wKg0PL.png
  docs/protocol/img/HkAFBapv8.png
  docs/protocol/img/Hkn4kg0v8.png
  docs/protocol/img/Hks1bEvu8.png
  docs/protocol/img/Hy-d6h6wL.png
  docs/protocol/img/HyEDRMvO8.png
  docs/protocol/img/SJ6dgzaiU.png
  docs/protocol/img/SkWZnyPOU.png
  docs/protocol/img/SkXjmJRvL.png
  docs/protocol/img/SklLFmD_I.png
  docs/protocol/img/rJP2m-vO8.png
  docs/protocol/img/rkI4GWD_8.png
  docs/protocol/img/rkYDSaaDI.png
  docs/protocol/img/ry6qXApPU.png
  docs/protocol/img/ryrmDTpw8.png
Labels: ✅ Approved

#2012 fix: request manager on mobile
  go/framework/bertybridge/bridge_protocol.go
Labels: ✅ Approved

#2006 chore: allow to customize the tracer prefix from the bridge
  go/framework/bertybridge/bridge_protocol.go
  js/packages/go-bridge/ios/GoBridge.swift
Labels: 🔍 Ready for Review

#2011 chore(messenger): set loglevel to debug
  js/packages/store/protocol/client.ts
Labels: ✅ Approved

#2014 chore: run go-build on a dedicated queue so it can only be run once per host in parallel
  .buildkite/pipeline.yml
  go/Makefile
  go/gen.sum
Labels: 🔍 Ready for Review

#2010 chore: refactor GitHub actions
  .github/workflows/ci.yml
  .github/workflows/golangci-lint.yml
Labels: 🔍 Ready for Review

#1993 Share QR code on dev channel (devtool)
  go/pkg/bertymessenger/api.go
  js/gen.make
  js/gen.sum
  js/packages/components/settings/DevTools.tsx
  js/packages/hooks/Chat.tsx
  js/packages/hooks/account.ts
  js/packages/store/chat/account.ts
  js/packages/store/messenger/MessengerServiceSagaClient.gen.ts
  js/packages/store/messenger/MessengerServiceSagaClient.gen.ts.hbs
  js/packages/store/messenger/client.gen.ts
  js/packages/store/messenger/client.gen.ts.hbs
  js/packages/store/protocol/client.ts
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb.d.ts
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb.js
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb_service.d.ts
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb_service.js
Labels: messenger, 🔍 Ready for Review

#2016 chore: share private and public invite link in the dev channel invite
  go/internal/discordlog/discord.go
Labels: 🔍 Ready for Review

#2017 chore: create CONTRIBUTING.MD
  CONTRIBUTING.MD
Labels: ✅ Approved

#2013 feat: tag found peers from group to keep them in the peerstore
  go/internal/ipfsutil/extended_core_api.go
  go/internal/ipfsutil/testing.go
  go/pkg/bertyprotocol/service_group.go
Labels: ✅ Approved

#1977 feat: add a connected peers list via the ipfs webui
  go.mod
  go.sum
  go/cmd/berty/main.go
  go/framework/bertybridge/bridge_protocol.go
  go/internal/config/berty.go
  go/internal/ipfsutil/api.go
  go/internal/ipfsutil/http_api.go
  js/gen.sum
  js/packages/berty-app/ios/Berty YoloRelease.entitlements
  js/packages/berty-app/ios/Podfile.lock
  js/packages/berty-app/package.json
  js/packages/berty-navigation/hook.tsx
  js/packages/berty-navigation/stacks.tsx
  js/packages/berty-navigation/types.ts
  js/packages/components/settings/DevTools.tsx
  js/packages/components/settings/IpfsWebUI.tsx
  js/packages/components/settings/Network.tsx
  js/packages/components/settings/index.ts
  js/yarn.lock
Labels: 🔍 Ready for Review

#2024 fix: text input text is black in dark iOS mode
  js/packages/components/Onboarding.tsx
  js/packages/components/modals/DeleteAccount.tsx
Labels: ✅ Approved

#2022 fix(front): stop bouncing on views with scroll if no bounce desired
  js/package.json
  js/packages/components/chat/ChatSettings.tsx
  js/packages/components/chat/ContactChatSettings.tsx
  js/packages/components/chat/GroupChatSettings.tsx
  js/packages/components/main/CreateGroup.tsx
  js/packages/components/main/GroupRequest.tsx
  js/packages/components/package.json
  js/packages/components/settings/AboutBerty.tsx
  js/packages/components/settings/AppUpdates.tsx
  js/packages/components/settings/BlockedContacts.tsx
  js/packages/components/settings/Bluetooth.tsx
  js/packages/components/settings/DevTools.tsx
  js/packages/components/settings/Help.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/IpfsWebUI.tsx
  js/packages/components/settings/Mode.tsx
  js/packages/components/settings/MyBertyId.tsx
  js/packages/components/settings/Network.tsx
  js/packages/components/settings/Notifications.tsx
  js/packages/components/settings/TermsOfUse.tsx
Labels: messenger, ✅ Approved

#1969 fix(chat): header messages list
  js/packages/components/main/1_berty_picto.svg
  js/packages/components/main/List.tsx
Labels: ✅ Approved

#1964 feat(chat): add vibrations
  js/packages/components/Onboarding.tsx
  js/packages/components/main/Scan.tsx
  js/packages/components/modals/DeleteAccount.tsx
  js/packages/components/settings/Mode.tsx
Labels: ✅ Approved

#2027 fix(front): disable autocomplete/capitalization for sensitive fields
  js/packages/components/Onboarding.tsx
  js/packages/components/modals/DeleteAccount.tsx
Labels: 🔍 Ready for Review

#1965 fix(chat): modal delete account
  js/packages/components/modals/DeleteAccount.tsx
Labels: 🔍 Ready for Review

#2029 fix(front): status bar text black regardless of iOS theme
  js/packages/components/modals/DeleteAccount.tsx
  js/packages/components/shared-components/StatusBarWrapper.tsx
  js/packages/components/shared-components/index.ts
  js/packages/components/theme.tsx
Labels: 🔍 Ready for Review

#2015 Support new id format
  js/.eslintrc.js
  js/gen.sum
  js/package.json
  js/packages/api/package.json
  js/packages/berty-app/App.tsx
  js/packages/berty-app/package.json
  js/packages/berty-navigation/container.tsx
  js/packages/codegen/helpers/protobuf.js
  js/packages/codegen/package.json
  js/packages/components/main/Scan.tsx
  js/packages/components/modals/AddThisContact.tsx
  js/packages/components/modals/InvalidScan.tsx
  js/packages/components/modals/SendContactRequest.tsx
  js/packages/components/settings/MyBertyId.tsx
  js/packages/eslint-config/index.js
  js/packages/hooks/contact.ts
  js/packages/store/chat/account.ts
  js/packages/store/chat/contact.ts
  js/packages/store/chat/conversation.ts
  js/packages/store/chat/index.ts
  js/packages/store/groups.ts
  js/packages/store/index.ts
  js/packages/store/messenger/MessengerServiceSagaClient.gen.ts
  js/packages/store/messenger/MessengerServiceSagaClient.gen.ts.hbs
  js/packages/store/messenger/client.gen.ts
  js/packages/store/messenger/client.gen.ts.hbs
  js/packages/store/package.json
  js/packages/store/protocol/ProtocolServiceSagaClient.gen.ts
  js/packages/store/protocol/client.gen.ts
  js/packages/store/protocol/client.gen.ts.hbs
  js/packages/store/protocol/client.ts
  js/packages/store/types/events.gen.ts
  js/packages/store/types/events.gen.ts.hbs
  js/packages/storybook-mobile/package.json
  js/packages/web-dev-app/package.json
  js/packages/web-dev-app/src/App.tsx
  js/yarn.lock
Labels: messenger, ✅ Approved

#2032 fix: allow own metadata to be shared during contact request
  api/bertymessenger.proto
  api/bertytypes.proto
  docs/gen.sum
  docs/messenger/api.md
  docs/protocol/api.md
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertyprotocol/api_contactrequest.go
  go/pkg/bertyprotocol/contact_request_manager.go
  go/pkg/bertyprotocol/contact_request_manager_test.go
  go/pkg/bertyprotocol/store_metadata.go
  go/pkg/bertyprotocol/store_metadata_index.go
  go/pkg/bertyprotocol/store_metadata_test.go
  go/pkg/bertytypes/bertytypes.pb.go
  js/gen.sum
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb.d.ts
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb.js
  js/packages/store/protocol/grpc-web-gen/bertytypes_pb.d.ts
  js/packages/store/protocol/grpc-web-gen/bertytypes_pb.js
Labels: ✅ Approved

#2030 fix(chat): replace powered by react native by logo
  js/packages/berty-app/ios/Berty/Base.lproj/LaunchScreen.xib
  js/packages/berty-app/ios/Berty/Images.xcassets/berty_picto.imageset/Contents.json
  js/packages/berty-app/ios/Berty/Images.xcassets/berty_picto.imageset/berty_picto.png
  js/packages/berty-app/ios/Podfile.lock
Labels: 🔍 Ready for Review

#2041 feat(messenger): use ownMetadata field to enable unidirectional contact request
  js/packages/store/chat/account.ts
  js/packages/store/chat/contact.ts
  js/packages/store/chat/conversation.ts
  js/packages/store/messenger/client.gen.ts
  js/packages/store/protocol/client.gen.ts
Labels: messenger, 🔍 Ready for Review

#1832 feat: Implement Multipeer Connectivity driver
  client/ios/Berty.xcodeproj/project.pbxproj
  client/ios/Berty.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  client/ios/Berty/Info.plist
  client/package-lock.json
  client/packages/bridge/service/api/node/kind.pb.json
  client/packages/bridge/service/api/node/service.pb.json
  client/packages/bridge/service/api/p2p/service.pb.json
  client/packages/bridge/service/chunk/chunk.pb.json
  client/packages/bridge/service/crypto/keypair/keypair.pb.json
  client/packages/bridge/service/crypto/sigchain/sigchain.pb.json
  client/packages/bridge/service/entity/config.pb.json
  client/packages/bridge/service/entity/contact.pb.json
  client/packages/bridge/service/entity/conversation.pb.json
  client/packages/bridge/service/entity/device.pb.json
  client/packages/bridge/service/entity/device_push_config.pb.json
  client/packages/bridge/service/entity/device_push_identifier.pb.json
  client/packages/bridge/service/entity/envelope.pb.json
  client/packages/bridge/service/entity/event.pb.json
  client/packages/bridge/service/entity/kind.pb.json
  client/packages/bridge/service/entity/message.pb.json
  client/packages/bridge/service/entity/sender_alias.pb.json
  client/packages/bridge/service/pkg/errorcodes/errors.pb.json
  client/packages/bridge/service/pkg/validate/validate.pb.json
  client/packages/common/locale/en/messages.json
  client/packages/common/locale/fr/messages.json
  client/packages/screen/Accounts/Auth.js
  client/packages/screen/Accounts/Onboarding/Bluetooth.js
  client/packages/screen/Settings/Devtools/Network/Config.js
  core/cmd/berty/daemon.go
  core/daemon/config.go
  core/go.mod
  core/go.sum
  core/platform/desktop/main.go
  core/platform/mobile/core/config.go
  network/go.mod
  network/go.sum
  network/host/conn.go
  network/host/defaults.go
  network/host/host_config.go
  network/localrecord.go
  network/transport/mc/addr.go
  network/transport/mc/conn.go
  network/transport/mc/connmgr.go
  network/transport/mc/discovery.go
  network/transport/mc/driver/bridge.go
  network/transport/mc/driver/mc-driver/MCManager.h
  network/transport/mc/driver/mc-driver/MCManager.m
  network/transport/mc/driver/mc-driver/cgo_bridge.go
  network/transport/mc/driver/mc-driver/mc-driver.h
  network/transport/mc/driver/mc-driver/mc-driver.m
  network/transport/mc/driver/other_bridge.go
  network/transport/mc/init.go
  network/transport/mc/listener.go
  network/transport/mc/logger.gen.go
  network/transport/mc/multiaddr/init.go
  network/transport/mc/multiaddr/logger.gen.go
  network/transport/mc/multiaddr/multiaddr.go
  network/transport/mc/multiaddr/pattern.go
  network/transport/mc/multiaddr/transcoder.go
  network/transport/mc/transport.go
Labels: 🔍 Ready for Review

#2039 feat: improve logger
  go/framework/bertybridge/bridge_protocol.go
  go/framework/bertybridge/driver_logger.go
  js/packages/berty-app/App.tsx
  js/packages/berty-app/index.js
  js/packages/go-bridge/GoBridge.ts
  js/packages/go-bridge/index.ts
  js/packages/go-bridge/ios/GoBridge.m
  js/packages/go-bridge/ios/GoBridge.swift
  js/packages/go-bridge/ios/LoggerDriver.swift
  js/packages/go-bridge/logger.ts
  js/packages/go-bridge/types.ts
Labels: ✅ Approved

#2038 chore: generate halfblock qrcodes on terminal to support smaller screens or splitted layouts
  go/cmd/berty/main.go
  go/cmd/berty/mini/view_group_outgoing.go
Labels: 🔍 Ready for Review

#2052 feat(messenger): add devtool for send messages to all contacts
  js/packages/components/settings/DevTools.tsx
  js/packages/hooks/message.ts
  js/packages/store/chat/conversation.ts
  js/packages/store/chat/message.ts
Labels: messenger, ✅ Approved

#2050 feat: Add orbitdb tracing & improve tracing
  go.mod
  go.sum
  go/pkg/bertyprotocol/orbitdb.go
  go/pkg/bertyprotocol/orbitdb_signed_entry_accesscontroller.go
  go/pkg/bertyprotocol/service.go
  js/packages/components/Onboarding.tsx
  js/packages/go-bridge/Makefile
  js/packages/go-bridge/ios/GoBridge.swift
  js/packages/go-bridge/types.ts
  js/packages/store/protocol/client.ts
Labels: ✅ Approved

#2057 fix(messenger): vibration and navigate after share QR on discord
  js/packages/components/settings/DevTools.tsx
Labels: messenger, 🔍 Ready for Review

#2059 chore(front): setup styles for search page
  js/packages/berty-navigation/stacks.tsx
  js/packages/components/main/Search.tsx
Labels: ✅ Approved

#2062 fix(messenger): whitelist messenger persistance
  js/packages/store/messenger/index.ts
Labels: bug, messenger, 🔍 Ready for Review

#2058 chore(quote): adding a quote from B.Schneier
  go/pkg/banner/quote.go
Labels: ✅ Approved

#2064 fix(messenger): chat -> messenger in useMessageSendToAll
  js/packages/hooks/message.ts
Labels: 🔍 Ready for Review

#2063 feat(front): add basic message body search to store
  js/packages/hooks/message.ts
  js/packages/store/messenger/message.ts
  js/packages/web-dev-app/src/App.tsx
Labels: 🔍 Ready for Review

#2068 feat: add ipad support
  js/packages/berty-app/ios/Berty.xcodeproj/project.pbxproj
Labels: ✅ Approved

#2066 feat: add a new bertymessenger.SystemInfo call
  Dockerfile
  api/bertymessenger.proto
  docs/gen.sum
  docs/messenger/api.md
  go.mod
  go.sum
  go/Makefile
  go/cmd/berty/main.go
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/api_test.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertymessenger/version.go
  js/gen.sum
  js/packages/api/index.gen.js
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/codegen/index.gen.js
  js/packages/components/faker.gen.tsx
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb.d.ts
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb.js
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb_service.d.ts
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb_service.js
Labels: 🔍 Ready for Review

#2069 fix(messenger): add date to messages for devtool send to all
  js/packages/store/messenger/message.ts
  js/packages/store/package.json
Labels: messenger

#2073 feat(messenger): add devtool and component systemInfo
  js/packages/components/settings/DevTools.tsx
  js/packages/components/settings/SystemInfo.tsx
  js/packages/components/settings/index.ts
  js/packages/hooks/Settings.tsx
  js/packages/navigation/hook.ts
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
  js/packages/store/messenger/MessengerServiceSagaClient.gen.ts
  js/packages/store/messenger/client.gen.ts
  js/packages/store/settings/main.ts
Labels: messenger

#2075 feat(messenger): use URLs for group invites
  api/bertymessenger.proto
  docs/gen.sum
  docs/messenger/api.md
  go/cmd/berty/main.go
  go/cmd/berty/mini/utils.go
  go/cmd/berty/mini/view_group_outgoing.go
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/api_test.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  js/gen.sum
  js/packages/api/index.gen.js
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/codegen/index.gen.js
  js/packages/components/faker.gen.tsx
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb.d.ts
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb.js
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb_service.d.ts
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb_service.js
Labels: 🔍 Ready for Review

#2077 feat(mini): ack support
  api/bertymessenger.proto
  docs/gen.sum
  docs/messenger/api.md
  go/cmd/berty/mini/view_group.go
  go/cmd/berty/mini/view_group_outgoing.go
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  js/gen.sum
  js/packages/api/index.gen.js
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/codegen/index.gen.js
  js/packages/components/faker.gen.tsx
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb.d.ts
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb.js
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb_service.d.ts
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb_service.js
Labels: ✅ Approved

#2078 feat(mini): /contact {accept,discard} all + pastable synopsis
  go/cmd/berty/mini/view_group.go
  go/cmd/berty/mini/view_group_incoming.go
  go/cmd/berty/mini/view_group_outgoing.go
Labels: ✅ Approved

#2079 feat(mini): unread badge
  go/cmd/berty/mini/view_group.go
  go/cmd/berty/mini/view_group_incoming.go
  go/cmd/berty/mini/view_tabbed_groups.go
Labels: ✅ Approved

#2081 feat(mini): added /debug {system,ipfs,group} commands
  go/cmd/berty/mini/view_group.go
  go/cmd/berty/mini/view_group_incoming.go
  go/cmd/berty/mini/view_group_outgoing.go
  go/cmd/berty/mini/view_tabbed_groups.go
Labels: 🔍 Ready for Review

#2086 fix(messenger): delete navigation, add vibration on send to all devtool
  js/packages/components/settings/DevTools.tsx
Labels: messenger, ✅ Approved

#2091 fix(go): update gRPC
  go.mod
  go.sum
Labels: ✅ Approved

#2090 chore: add tool/berty-mini-local-helper
  tool/berty-mini-local-helper/Makefile
  tool/berty-mini-local-helper/README.md
Labels: 🔍 Ready for Review

#2088 feat(mini): display names support
  go/cmd/berty/mini/main.go
  go/cmd/berty/mini/view_group.go
  go/cmd/berty/mini/view_group_incoming.go
  go/cmd/berty/mini/view_group_outgoing.go
  go/cmd/berty/mini/view_tabbed_groups.go
  go/pkg/bertyprotocol/store_metadata_index.go
Labels: ✅ Approved

#2096 fix: invalid bazel rules in makefile
  bazel.make
Labels: 🔍 Ready for Review

#2093 chore: configure ldflags on gomobile bind to inject build context
  js/packages/components/settings/SystemInfo.tsx
  js/packages/go-bridge/Makefile
Labels: 🔍 Ready for Review

#2097 migrate some jobs from buildkite to GitHub actions
  .buildkite/pipeline.yml
  .github/workflows/ci.yml
  .github/workflows/go.yml
  .github/workflows/js.yml
  .github/workflows/protobuf.yml
  .goreleaser.yml
  go/Makefile
  go/framework/bertybridge/bridge_test.go
  go/gen.sum
  go/internal/multipeer-connectivity-transport/driver/bridge_darwin.go
  go/internal/multipeer-connectivity-transport/driver/bridge_unsupported.go
  go/internal/multipeer-connectivity-transport/driver/mc-driver/cgo_bridge_darwin.go
  go/internal/multipeer-connectivity-transport/driver/mc-driver/cgo_bridge_unsupported.go
  go/internal/testutil/skip.go
Labels: 🔍 Ready for Review

#2092 feat(mini): defaulting to a persistent store + support for display name as a cli arg
  go.mod
  go.sum
  go/cmd/berty/main.go
  go/cmd/berty/mini/main.go
  go/cmd/berty/mini/view_tabbed_groups.go
Labels: 🔍 Ready for Review

#2018 feat: activate multipeer connectivity by default
  go/cmd/berty/main.go
  go/framework/bertybridge/bridge_protocol.go
  go/internal/config/berty.go
Labels: ✅ Approved

#2104 chore: test & stability improvements
  go/internal/grpcutil/pipe_listener.go
  go/internal/ipfsutil/testing.go
  go/pkg/bertyprotocol/blackbox_test.go
  go/pkg/bertyprotocol/contact_request_manager_test.go
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/bertyprotocol/service_test.go
  go/pkg/bertyprotocol/testing.go
  go/pkg/bertyprotocol/testing_test.go
Labels: 🔍 Ready for Review

#2103 feat(debug): list tagged peers for group
  api/bertyprotocol.proto
  api/bertytypes.proto
  docs/gen.sum
  docs/protocol/api.md
  go/cmd/berty/mini/view_group_outgoing.go
  go/gen.sum
  go/internal/ipfsutil/extended_core_api.go
  go/pkg/bertyprotocol/api_debug.go
  go/pkg/bertyprotocol/bertyprotocol.pb.go
  go/pkg/bertytypes/bertytypes.pb.go
  js/gen.sum
  js/packages/api/index.gen.js
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/codegen/index.gen.js
  js/packages/components/faker.gen.tsx
  js/packages/store/protocol/grpc-web-gen/bertyprotocol_pb_service.d.ts
  js/packages/store/protocol/grpc-web-gen/bertyprotocol_pb_service.js
  js/packages/store/protocol/grpc-web-gen/bertytypes_pb.d.ts
  js/packages/store/protocol/grpc-web-gen/bertytypes_pb.js
Labels: ✅ Approved

#2071 feat(front): connect search functionality to UI
  js/packages/berty-app/.watchmanconfig
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/main/Footer.tsx
  js/packages/components/main/Search.tsx
  js/packages/hooks/contact.ts
  js/packages/hooks/conversation.ts
  js/packages/hooks/message.ts
  js/packages/store/messenger/conversation.ts
  js/packages/store/messenger/message.ts
  js/packages/web-dev-app/src/App.tsx
Labels: 🔍 Ready for Review

#2048 feat: local discovery
  api/go-internal/records.proto
  go.mod
  go/gen.sum
  go/internal/ipfsutil/localrecord.go
  go/internal/ipfsutil/routing.go
  go/internal/tinder/driver_localdiscovery.go
  go/internal/tinder/records.pb.go
  go/pkg/bertyprotocol/store_message_test.go
Labels: 🔍 Ready for Review

#2087 chore: Improve CI logging
  .buildkite/pipeline.yml
  bazel.make
Labels: ✅ Approved

#2106 chore(tool/berty-mini-local-helper): improve develop rules
  .buildkite/pipeline.yml
  tool/berty-mini-local-helper/Makefile
Labels: 🔍 Ready for Review

#2094 feat: update ipfs/libp2p
  go.mod
  go.sum
  go/internal/gomodhack/gomodhack.go
  go/internal/ipfsutil/repo.go
  go/internal/ipfsutil/routing.go
  go/pkg/bertyprotocol/api_debug.go
  go/pkg/bertyprotocol/events.go
  go/pkg/bertyprotocol/keystore_message_utils.go
  go/pkg/bertyprotocol/store_metadata.go
  go/pkg/bertyprotocol/store_metadata_index.go
  js/packages/berty-app/ios/Berty.xcodeproj/project.pbxproj
Labels: ✅ Approved

#2107 fix(tinder): unadvertise on ttl < 1 on multidrive
  go/internal/tinder/driver_localdiscovery.go
  go/internal/tinder/driver_multi.go
Labels: ✅ Approved

#2105 feat: add peer-of-interest connections debug logging
  go/.golangci.yml
  go/cmd/berty/main.go
  go/cmd/berty/mini/main.go
  go/framework/bertybridge/bridge_protocol.go
  go/internal/ipfsutil/conn_logger.go
  go/internal/ipfsutil/testing.go
  go/pkg/bertyprotocol/service_group.go
  js/packages/berty-app/ios/Podfile.lock
  js/packages/go-bridge/ios/GoBridge.swift
  js/packages/store/protocol/client.ts
  tool/berty-mini-local-helper/Makefile
Labels: ✅ Approved

#2109 fix: invalid ttl
  go/internal/tinder/driver_localdiscovery.go
Labels: 🔍 Ready for Review

#2110 chore: improve berty-mini debugging
  go/cmd/berty/mini/view_group.go
  tool/berty-mini-local-helper/Makefile
Labels: 🔍 Ready for Review

#2108 feat: toggle localDiscovery
  go/cmd/berty/main.go
  go/cmd/berty/mini/main.go
  go/framework/bertybridge/bridge_protocol.go
  go/internal/ipfsutil/routing.go
  go/internal/ipfsutil/testing.go
  js/packages/go-bridge/ios/GoBridge.swift
  js/packages/store/protocol/client.ts
Labels: ✅ Approved

#2112 chore: udpate README.md
  README.md
Labels: 🔍 Ready for Review

#2113 refactor(js): move makefiles to the js root
  js/Makefile
  js/gen.sum
  js/makefiles/api.mk
  js/makefiles/berty-app.mk
  js/makefiles/codegen.mk
  js/makefiles/gen.mk
  js/makefiles/go-bridge.mk
  js/makefiles/storybook-mobile.mk
  js/makefiles/storybook-web.mk
  js/packages/codegen/Makefile
  js/packages/go-bridge/go.mod
  js/packages/go-bridge/go.sum
  js/packages/store/messenger/MessengerServiceSagaClient.gen.ts
  js/packages/store/messenger/client.gen.ts
  js/packages/store/protocol/ProtocolServiceClient.gen.ts
  js/packages/store/protocol/ProtocolServiceSagaClient.gen.ts
  js/packages/store/protocol/client.gen.ts
  js/packages/store/types/events.gen.ts
  js/packages/storybook-mobile/Makefile
Labels: build, 🔍 Ready for Review

#2115 chore: simplify JS' Makefile(s)
  .buildkite/pipeline.yml
  .github/workflows/protobuf.yml
  Makefile
  build/shell/release-android.sh
  build/shell/release-ios.sh
  docs/Makefile
  docs/gen.sum
  go/Makefile
  go/gen.sum
  js/Makefile
  js/README.md
  js/gen.sum
  js/makefiles/api.mk
  js/makefiles/berty-app.mk
  js/makefiles/codegen.mk
  js/makefiles/gen.mk
  js/makefiles/go-bridge.mk
  js/makefiles/storybook-mobile.mk
  js/makefiles/storybook-web.mk
Labels: 🔍 Ready for Review

#2119 feat: copy share commands output to clipboard in Berty mini
  go.mod
  go.sum
  go/cmd/berty/mini/view_group_outgoing.go
Labels: ✅ Approved

#2084 feat: Add grpc gateway
  .github/workflows/protobuf.yml
  Makefile
  api/bertymessenger.proto
  api/bertyprotocol.proto
  bazel.make
  docs/Makefile
  docs/gen.sum
  go.mod
  go.sum
  go/.golangci.yml
  go/Makefile
  go/cmd/berty/main.go
  go/gen.sum
  go/internal/grpcutil/server.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/bertymessenger.pb.gw.go
  go/pkg/bertyprotocol/bertyprotocol.pb.go
  go/pkg/bertyprotocol/bertyprotocol.pb.gw.go
  js/Makefile
  js/gen.sum
  tool/docker-protoc/Dockerfile
  tool/docker-protoc/Makefile
Labels: ✅ Approved

#2120 chore: ignore generated files on codecov
  .codecov.yml
Labels: 🔍 Ready for Review

#2122 chore: get rid of .aab artifact
  .buildkite/pipeline.yml
Labels: 🔍 Ready for Review

#2114 feat(js): add node watchdog and restart the client on failure
  js/packages/berty-app/App.tsx
  js/packages/components/settings/DevTools.tsx
  js/packages/go-bridge/ios/GoBridge.swift
  js/packages/store/groups.ts
  js/packages/store/messenger/index.ts
  js/packages/store/protocol/client.ts
Labels: messenger, 🔍 Ready for Review

#2121 chore: add 'make regenerate' and use 'gen.clean' in all subfolders
  Makefile
  docs/Makefile
  docs/gen.sum
  go/Makefile
  go/gen.sum
  js/Makefile
  js/gen.sum
Labels: 🔍 Ready for Review

#2127 remove bazel
  .buildkite/agent_setup/linux/debian/bazel_requirements.txt
  .buildkite/agent_setup/linux/user/.bazelrc
  .github/CODEOWNERS
  BUILD.bazel
  Makefile
  WORKSPACE
  bazel.make
  go/.bazel_fix_commands.json
  go/.gitignore
  go/BUILD.bazel
  go/Makefile
  go/config.bzl
  go/gen.sum
  go/repositories.bzl
  go/third_party/build_bazel_rules_apple/PR-554-rebase-master.patch
  go/third_party/io_bazel_rules_go/PR-2181-rebase-0.20.1.patch
  go/third_party/io_bazel_rules_go/PR-2181-rebase-0.23.1.patch
  go/third_party/io_bazel_rules_go/PR-2181-rebase-master.patch
  js/.bazelignore
  js/.bazelrc
  js/README.md
  js/packages/berty-app/.bazelrc
  js/packages/berty-app/BUILD.bazel
  js/packages/berty-app/WORKSPACE
  js/packages/berty-app/android/BUILD.bazel
  js/packages/berty-app/android/app/build_defs.bzl
  js/packages/berty-app/android/app/src/main/BUILD.bazel
  js/packages/berty-app/repositories.bzl
  js/packages/go-bridge/.bazelrc
  js/packages/go-bridge/BUILD.bazel
  js/packages/go-bridge/WORKSPACE
  js/packages/go-bridge/android/BUILD.bazel
  js/packages/go-bridge/config.bzl
  js/packages/go-bridge/ios/BUILD.bazel
  js/packages/go-bridge/ios/debug.bzl
  js/packages/go-bridge/ios/framework.bzl
  js/packages/go-bridge/repositories.bzl
  js/packages/storybook-mobile/android/app/build_defs.bzl
  tool/build/bazel/com_github_spacemonkeygo_openssl.BUILD.bazel
  tool/docker-bazel/Dockerfile
  tool/docker-bazel/Makefile
  tool/test/experiment/BUILD.bazel
  tool/test/experiment/dht/BUILD.bazel
  tool/test/experiment/dht/src/bittorrent/BUILD.bazel
  tool/test/experiment/dht/src/chord/BUILD.bazel
  tool/test/experiment/dht/src/gnunet/BUILD.bazel
  tool/test/experiment/dht/src/libp2p/BUILD.bazel
  tool/test/experiment/dht/src/matrix/BUILD.bazel
  tool/test/experiment/dht/src/opendht/BUILD.bazel
  tool/test/experiment/dht/test/BUILD.bazel
Labels: 🔍 Ready for Review

#2129 chore: generate openapi documentation
  .github/workflows/protobuf.yml
  .gitignore
  README.md
  docs/Makefile
  docs/gen.sum
  docs/messenger/bertymessenger.swagger.json
  docs/protocol/bertyprotocol.swagger.json
Labels: 🔍 Ready for Review

#2128 fix: allow incoming requests from contacts without rdv seed
  go/pkg/bertyprotocol/contact_request_manager_test.go
  go/pkg/bertyprotocol/store_metadata.go
  go/pkg/bertyprotocol/store_metadata_index.go
Labels: ✅ Approved
