Repository berty/berty, pull requests merged in 2020-07, with the labels that each got.

#2130 feat: set up report.ci
  .github/workflows/go.yml
Labels: 🔍 Ready for Review

#2132 chore: add berty-mini-web tool
  tool/berty-mini-web/Makefile
  tool/berty-mini-web/README.md
  tool/berty-mini-web/berty-mini
Labels: 🔍 Ready for Review

#2124 feat: add odb direct channel
  go.mod
  go.sum
  go/cmd/berty/main.go
  go/cmd/berty/mini/main.go
  go/framework/bertybridge/bridge_protocol.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertyprotocol/testing.go
Labels: ✅ Approved

#2133 fix: get initial scale size based on device orientation
  js/packages/styles/constant.ts
Labels: messenger, messenger-ui-cosmetic, 🔍 Ready for Review

#2137 chore: Revert "feat: set up report.ci"
  .github/workflows/go.yml
Labels: 🔍 Ready for Review

#2134 chore: JS makefile: add env args and no-dep make targets
  js/Makefile
  js/gen.sum
Labels: messenger, 🔍 Ready for Review

#2138 feat: display rlimit and rusage in systeminfo
  api/bertymessenger.proto
  docs/gen.sum
  docs/messenger/api.md
  docs/messenger/bertymessenger.swagger.json
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  js/gen.sum
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb.d.ts
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb.js
Labels: 🔍 Ready for Review

#2139 chore: set up release not preview on PR
  .github/workflows/pr.yml
Labels: 🔍 Ready for Review

#2135 feat: add .v1 package suffix in protobuf + refactor grpc-gateway generation
  api/bertymessenger.proto
  api/bertymessenger.yaml
  api/bertyprotocol.proto
  api/bertyprotocol.yaml
  api/bertytypes.proto
  docs/Makefile
  docs/gen.sum
  docs/messenger/api.md
  docs/messenger/bertymessenger.swagger.json
  docs/protocol/api.md
  docs/protocol/bertyprotocol.swagger.json
  go.mod
  go.sum
  go/Makefile
  go/framework/bertybridge/bridge_test.go
  go/gen.sum
  go/internal/gomodhack/gomodhack.go
  go/internal/tools/tools.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/bertymessenger.pb.gw.go
  go/pkg/bertyprotocol/bertyprotocol.pb.go
  go/pkg/bertyprotocol/bertyprotocol.pb.gw.go
  go/pkg/bertytypes/bertytypes.pb.go
  js/Makefile
  js/gen.sum
  js/packages/api/index.gen.js
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/codegen/index.gen.js
  js/packages/components/faker.gen.tsx
  js/packages/store/messenger/MessengerServiceSagaClient.gen.ts
  js/packages/store/messenger/MessengerServiceSagaClient.gen.ts.hbs
  js/packages/store/messenger/account.ts
  js/packages/store/messenger/client.gen.ts
  js/packages/store/messenger/client.gen.ts.hbs
  js/packages/store/messenger/contact.ts
  js/packages/store/messenger/conversation.ts
  js/packages/store/messenger/message.ts
  js/packages/store/protocol/ProtocolServiceClient.gen.ts
  js/packages/store/protocol/ProtocolServiceClient.gen.ts.hbs
  js/packages/store/protocol/ProtocolServiceSagaClient.gen.ts
  js/packages/store/protocol/ProtocolServiceSagaClient.gen.ts.hbs
  js/packages/store/protocol/client.gen.ts
  js/packages/store/protocol/client.gen.ts.hbs
  js/packages/store/protocol/client.ts
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb.d.ts
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb.js
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb_service.d.ts
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb_service.js
  js/packages/store/protocol/grpc-web-gen/bertyprotocol_pb.d.ts
  js/packages/store/protocol/grpc-web-gen/bertyprotocol_pb_service.d.ts
  js/packages/store/protocol/grpc-web-gen/bertyprotocol_pb_service.js
  js/packages/store/protocol/grpc-web-gen/bertytypes_pb.d.ts
  js/packages/store/protocol/grpc-web-gen/bertytypes_pb.js
  js/packages/store/protocol/grpc-web-gen/bertytypes_pb_service.d.ts
  js/packages/store/protocol/grpc-web-gen/bertytypes_pb_service.js
  js/packages/store/settings/main.ts
  js/packages/store/types/events.gen.ts
  js/packages/store/types/events.gen.ts.hbs
Labels: ✅ Approved

#2140 feat: returns connected_peers in bertymessenger.SystemInfo
  api/bertymessenger.proto
  docs/gen.sum
  docs/messenger/api.md
  docs/messenger/bertymessenger.swagger.json
  go/cmd/berty/main.go
  go/cmd/berty/mini/main.go
  go/framework/bertybridge/bridge_protocol.go
  go/gen.sum
  go/internal/ipfsutil/repo.go
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertyprotocol/service.go
  js/gen.sum
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb.d.ts
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb.js
Labels: 🔍 Ready for Review

#2142 feat: add count of open files in SystemInfo
  api/bertymessenger.proto
  docs/gen.sum
  docs/messenger/api.md
  docs/messenger/bertymessenger.swagger.json
  go.mod
  go.sum
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  js/gen.sum
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb.d.ts
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb.js
Labels: 🔍 Ready for Review

#2143 chore(js): add 'make bridge.start.docker' rule
  js/Makefile
  js/gen.sum
Labels: 🔍 Ready for Review

#2144 fix: add a too many files open indicator on SystemInfo
  api/bertymessenger.proto
  docs/gen.sum
  docs/messenger/api.md
  docs/messenger/bertymessenger.swagger.json
  go.mod
  go.sum
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  js/gen.sum
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb.d.ts
  js/packages/store/protocol/grpc-web-gen/bertymessenger_pb.js
Labels: 🔍 Ready for Review

#2145 feat(js): add flex utils to style API
  js/packages/components/main/Search.tsx
  js/packages/styles/map-declaration.ts
  js/packages/styles/types.ts
Labels: enhancement, ✅ Approved

#2118 feat(messenger): add contact connection indicator
  js/packages/berty-app/ios/Podfile.lock
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/settings/IpfsWebUI.tsx
  js/packages/hooks/Settings.tsx
  js/packages/store/settings/main.ts
Labels: messenger, 🔍 Ready for Review

#1970 fix(chat): warnings unique key
  js/packages/components/main/Home.tsx
  js/packages/components/shared-components/SettingsButtons.tsx
  js/packages/components/shared-components/TabBar.tsx
Labels: 🔍 Ready for Review

#2146 fix(messenger): search results margins
  js/packages/components/main/Search.tsx
Labels: bug, messenger, messenger-ui-cosmetic, ✅ Approved

#2153 fix: broken golangci github action
  .github/workflows/go.yml
Labels: bug, 🔍 Ready for Review

#2148 chore: add 'make mini.dev'
  go.mod
  go.sum
  go/Makefile
  go/cmd/berty/main.go
  go/gen.sum
  go/internal/tools/tools.go
Labels: chore, 🔍 Ready for Review

#2154 fix: increase golangci-lint timeout on CI
  .github/workflows/go.yml
Labels: bug, 🔍 Ready for Review

#2155 docs(js): update readme with packages guide
  js/README.md
Labels: documentation, 🔍 Ready for Review

#2156 chore: make mini's bird tell the quote of the day
  go/cmd/berty/mini/view_group.go
Labels: chore, 🔍 Ready for Review

#2157 fix: update go-bridge building method + bump some deps
  .buildkite/pipeline.yml
  Makefile
  docs/Makefile
  docs/gen.sum
  js/Makefile
  js/gen.sum
  js/go.mod
  js/go.sum
  js/packages/go-bridge/go.mod
  js/packages/go-bridge/go.sum
  js/packages/go-bridge/tools.go
  js/packages/store/protocol/client.ts
Labels: bug, 🔍 Ready for Review

#2151 fix(messenger): vibrations on delete account
  js/packages/components/modals/DeleteAccount.tsx
  js/packages/components/settings/Mode.tsx
Labels: ✅ Approved

#2085 fix(messenger): insta effect / scroll top
  js/packages/components/main/Home.tsx
  js/packages/store/messenger/conversation.ts
Labels: messenger, ✅ Approved

#2147 feat(messenger): onboarding animations
  js/packages/berty-app/ios/Podfile
  js/packages/berty-app/ios/Podfile.lock
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Berty BG.json
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Circle spin.json
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code Generated.json
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code generation row 1.json
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code generation row 2.json
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code generation row 3.json
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code generation row 4.json
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 1.json
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 10.json
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 11.json
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 12.json
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 13.json
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 14.json
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 15.json
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 2.json
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 3.json
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 4.json
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 5.json
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 6.json
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 7.json
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 8.json
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 9.json
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%201.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%2010.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%2011.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%2012.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%2013.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%2014.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%2015.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%202.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%203.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%204.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%205.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%206.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%207.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%208.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%209.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Finish appear.json
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Finish loop.json
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Shield appear.json
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Shield dissapear.json
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/demo/Berty%20BG.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/demo/Circle%20spin.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/demo/Code%20Generated.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/demo/Code%20generation%20row%201.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/demo/Code%20generation%20row%202.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/demo/Code%20generation%20row%203.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/demo/Code%20generation%20row%204.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/demo/Finish%20appear.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/demo/Finish%20loop.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/demo/Shield%20appear.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/demo/Shield%20dissapear.html
  js/packages/components/Onboarding.tsx
  js/packages/components/package.json
  js/yarn.lock
Labels: enhancement, ✅ Approved

#2159 fix(messenger): delete html files
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%201.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%2010.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%2011.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%2012.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%2013.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%2014.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%2015.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%202.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%203.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%204.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%205.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%206.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%207.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%208.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Single line phase demo/Code%20phase%209.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/demo/Berty%20BG.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/demo/Circle%20spin.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/demo/Code%20Generated.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/demo/Code%20generation%20row%201.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/demo/Code%20generation%20row%202.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/demo/Code%20generation%20row%203.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/demo/Code%20generation%20row%204.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/demo/Finish%20appear.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/demo/Finish%20loop.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/demo/Shield%20appear.html
  js/packages/components/Berty_onboard_animation_assets2/Startup animation assets/demo/Shield%20dissapear.html
Labels: 🔍 Ready for Review

#2116 feat: use custom odb pubsub
  go.mod
  go.sum
  go/cmd/berty/main.go
  go/cmd/berty/mini/main.go
  go/framework/bertybridge/bridge_protocol.go
  go/framework/bertybridge/bridge_test.go
  go/internal/ipfsutil/api.go
  go/internal/ipfsutil/pubsub_adaptater.go
  go/internal/ipfsutil/pubsub_api.go
  go/internal/ipfsutil/repo.go
  go/internal/ipfsutil/routing.go
  go/internal/ipfsutil/testing.go
  go/internal/tinder/driver_multi.go
  go/internal/tinder/driver_rdv.go
  go/internal/tinder/routing.go
  go/internal/tinder/service.go
  go/pkg/bertymessenger/api_test.go
  go/pkg/bertyprotocol/contact_request_manager.go
  go/pkg/bertyprotocol/contact_request_manager_test.go
  go/pkg/bertyprotocol/orbitdb_many_adds_berty_test.go
  go/pkg/bertyprotocol/orbitdb_many_adds_test.go
  go/pkg/bertyprotocol/orbitdb_test.go
  go/pkg/bertyprotocol/orbitdb_utils_test.go
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertyprotocol/testing.go
  go/pkg/bertyprotocol/tinder_swiper.go
  go/pkg/bertyprotocol/tinder_swiper_test.go
  tool/berty-mini-local-helper/Makefile
Labels: enhancement, ✅ Approved

#2161 feat: bump orbitdb to 1.10.1
  go.mod
  go.sum
  go/pkg/bertyprotocol/orbitdb_test.go
  go/pkg/bertyprotocol/service.go
Labels: enhancement, ✅ Approved

#2163 feat: Replace pipe listener with buf listener
  go/framework/bertybridge/bridge.go
  go/internal/grpcutil/buf_listener.go
  go/internal/grpcutil/doc.go
  go/internal/grpcutil/pipe_listener.go
  go/pkg/bertyprotocol/client.go
Labels: enhancement, ✅ Approved

#2160 test: improve scenario tests
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/bertyprotocol/testing.go
Labels: test, ✅ Approved

#2162 docs: simplify CONTRIBUTING.md
  CONTRIBUTING.MD
Labels: documentation, 🔍 Ready for Review

#2167 perf(messenger): fix onboarding anim lag
  js/packages/components/Onboarding.tsx
Labels: messenger, messenger-ui-cosmetic, performance, 🔍 Ready for Review

#2164 fix: bump deps
  .github/workflows/go.yml
  go.mod
  go.sum
  go/cmd/berty/main.go
  go/cmd/berty/mini/main.go
  go/framework/bertybridge/bridge_protocol.go
  go/internal/ipfsutil/http_api.go
  go/internal/tracer/runtime.go
  go/pkg/bertyprotocol/testing.go
Labels: bug, 🔍 Ready for Review

#2149 feat(messenger): conversation commands
  js/packages/components/chat/shared-components/Chat.tsx
  js/packages/components/chat/shared-components/Message.tsx
  js/packages/store/messenger/conversation.ts
  js/packages/store/messenger/message.ts
Labels: enhancement, ✅ Approved

#2169 fix(messenger): fix main modal and QR scanner sizing
  js/packages/components/main/HomeModal.tsx
  js/packages/components/main/Scan.tsx
  js/packages/components/settings/MyBertyId.tsx
  js/packages/styles/constant.ts
Labels: bug, messenger, 🔍 Ready for Review

#2173 fix(messenger): fix handling deep links opened from outside the app
  js/packages/berty-app/package.json
  js/packages/components/modals/ManageDeepLink.tsx
  js/packages/navigation/container.tsx
  js/packages/navigation/package.json
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
  js/packages/store/messenger/account.ts
  js/packages/store/messenger/index.ts
  js/packages/storybook-mobile/package.json
  js/yarn.lock
Labels: bug, 🔍 Ready for Review

#2172 feat(messenger): add timestamp to message search result
  js/packages/components/main/Search.tsx
Labels: enhancement, feature-suggestion-ux, messenger, ✅ Approved

#2176 feat: rich gRPC errors
  api/errcode.proto
  docs/gen.sum
  go/framework/bertybridge/bridge.go
  go/gen.sum
  go/internal/handshake/handshake_test.go
  go/internal/handshake/handshake_util_test.go
  go/pkg/bertymessenger/api_test.go
  go/pkg/bertymessenger/testing_test.go
  go/pkg/bertyprotocol/group.go
  go/pkg/bertyprotocol/keystore_message.go
  go/pkg/bertyprotocol/orbitdb.go
  go/pkg/bertyprotocol/testing_test.go
  go/pkg/errcode/errcode.pb.go
  go/pkg/errcode/error.go
  go/pkg/errcode/error_test.go
  go/pkg/errcode/stdproto.go
Labels: enhancement, 🔍 Ready for Review

#2177 chore: remove all t.Helper() from handshake_test.go
  go/internal/handshake/handshake_test.go
Labels: chore, 🔍 Ready for Review

#2171 feat(messenger): generate fake datas / add svg empty_chat
  js/packages/components/chat/shared-components/Chat.tsx
  js/packages/components/faker.js
  js/packages/components/faker.tsx
  js/packages/components/main/Home.tsx
  js/packages/components/main/empty_chat.svg
  js/packages/components/settings/DevTools.tsx
  js/packages/components/settings/FakeDatas.js
  js/packages/components/settings/index.ts
  js/packages/components/shared-components/ProceduralCircleAvatar.tsx
  js/packages/hooks/Settings.tsx
  js/packages/hooks/contact.ts
  js/packages/hooks/conversation.ts
  js/packages/hooks/message.ts
  js/packages/navigation/hook.ts
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
  js/packages/store/messenger/contact.js
  js/packages/store/messenger/conversation.js
  js/packages/store/messenger/message.js
  js/packages/store/settings/main.js
Labels: enhancement, 🔍 Ready for Review

#2181 fix(messenger): fix initial scaling calculation
  js/packages/styles/constant.ts
Labels: bug, messenger, messenger-ui-cosmetic, ✅ Approved

#2186 fix(messenger): svg bgcolor / gen fake datas
  js/packages/components/faker.js
  js/packages/components/main/Home.tsx
  js/packages/components/main/HomeModal.tsx
  js/packages/components/settings/SystemInfo.tsx
  js/packages/store/messenger/contact.js
  js/packages/store/messenger/conversation.js
  js/packages/store/messenger/message.js
Labels: bug, 🔍 Ready for Review

#2192 fix: refactor main
  go.mod
  go.sum
  go/cmd/berty/banner.go
  go/cmd/berty/daemon.go
  go/cmd/berty/groupinit.go
  go/cmd/berty/main.go
  go/cmd/berty/mini.go
  go/cmd/berty/opts.go
  go/cmd/berty/shareinvite.go
  go/cmd/berty/systeminfo.go
  go/cmd/berty/version.go
  go/cmd/rdvp/main.go
Labels: bug, ✅ Approved

#2188 feat(messenger): add avatar and name to multimember conversation
  js/packages/components/chat/ChatGroup.tsx
  js/packages/components/chat/shared-components/Message.tsx
Labels: enhancement, 🔍 Ready for Review

#2193 feat(messenger): dynamically update scale based on device + orientation
  js/packages/berty-app/App.tsx
  js/packages/berty-app/ios/Podfile.lock
  js/packages/components/chat/ChatGroup.tsx
  js/packages/components/chat/GroupSettings.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/shared-components/Chat.tsx
  js/packages/components/main/CreateGroupFinalize.tsx
  js/packages/components/main/Home.tsx
  js/packages/components/main/HomeModal.tsx
  js/packages/components/shared-components/FingerprintContent.tsx
  js/packages/styles/constant.ts
  js/packages/styles/hook.tsx
  js/packages/styles/map-border.ts
  js/packages/styles/map-declaration.ts
  js/packages/styles/map-sides.ts
  js/packages/styles/types.ts
Labels: enhancement, 🔍 Ready for Review

#2196 fix(messenger): fix animation lag on account create click
  js/packages/components/Onboarding.tsx
  js/packages/components/main/Search.tsx
  js/packages/eslint-config/index.js
Labels: bug, ✅ Approved

#2198 chore(front): Use dynamic UI scale values from styles API
  js/packages/components/Onboarding.tsx
  js/packages/components/chat/MultiMemberQR.tsx
  js/packages/components/main/CreateGroupAddMembers.tsx
  js/packages/components/main/CreateGroupFinalize.tsx
  js/packages/components/main/HomeModal.tsx
  js/packages/components/main/Scan.tsx
  js/packages/components/main/Search.tsx
  js/packages/components/settings/EditProfile.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/MyBertyId.tsx
  js/packages/components/shared-components/CircleAvatar.tsx
  js/packages/components/shared-components/ProceduralCircleAvatar.tsx
  js/packages/eslint-config/index.js
  js/packages/styles/constant.ts
  js/packages/styles/hook.tsx
Labels: chore, ✅ Approved

#2200 fix: bump deps
  go.mod
  go.sum
Labels: bug, 🔍 Ready for Review
