Repository berty/berty, pull requests merged in 2020-10, with the labels that each got.

#2399 chore: update yolo-friendly artifact suffix
  .github/workflows/ios.yml
Labels: chore, 🔍 Ready for Review

#2401 fix: ignore ipfs api errors
  go/framework/bertybridge/bridge_protocol.go
  go/internal/initutil/node.go
Labels: bug, ✅ Approved

#2403 chore: improve betabot logging + code styling
  go/cmd/betabot/main.go
Labels: chore, 🔍 Ready for Review

#2404 fix: update Betabot URL
  js/packages/components/modals/AddBetabot.js
Labels: bug, 🔍 Ready for Review

#2405 ci: codesign IPA using dummy identity
  .github/workflows/ios.yml
  tool/dummy-identity/berty-dummy.p12
Labels: ci, ✅ Approved

#2408 fix: use local time for qotd
  go/pkg/banner/quote.go
Labels: bug, ✅ Approved

#2409 fix: dummy sign shake.framework manually
  .github/workflows/ios.yml
Labels: bug, 🔍 Ready for Review

#2406 chore: refactor betabot for maintainability + improved logging
  go.mod
  go.sum
  go/cmd/betabot/main.go
  tool/deployments/betabot/docker-compose.yml
Labels: chore, 🔍 Ready for Review

#2400 chore(messenger): db and handlers refactor
  .goreleaser.yml
  api/bertymessenger.proto
  docs/gen.sum
  docs/messenger/api.md
  docs/messenger/bertymessenger.swagger.json
  go.mod
  go/assets/pkged.go
  go/cmd/betabot/main.go
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/api_test.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/db_test.go
  go/pkg/bertymessenger/handlers.go
  go/pkg/bertymessenger/handlers_test.go
  go/pkg/bertymessenger/replay.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertymessenger/service_test.go
  go/pkg/bertymessenger/testing.go
  go/pkg/bertymessenger/types.go
  go/pkg/bertymessenger/util.go
  js/gen.sum
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/navigation/stacks.tsx
  js/packages/store/faker.js
  js/packages/web-dev-app/src/App.tsx
Labels: chore, 🔍 Ready for Review

#2412 chore: update BetaBot URL
  js/packages/components/modals/AddBetabot.js
Labels: chore, 🔍 Ready for Review

#2410 fix(messenger): avoid handling already persisted interactions
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/db_test.go
  go/pkg/bertymessenger/handlers.go
Labels: bug, ✅ Approved

#2337 feat: start using xcodegen
  .buildkite/pipeline.yml
  .github/workflows/ios.yml
  js/.gitignore
  js/Gemfile.lock
  js/Makefile
  js/README.md
  js/fastlane/Pluginfile
  js/gen.sum
  js/packages/berty-app/android/app/build.gradle
  js/packages/berty-app/ios/.gitignore
  js/packages/berty-app/ios/Berty Debug.entitlements
  js/packages/berty-app/ios/Berty DebugDebug.entitlements
  js/packages/berty-app/ios/Berty Staff.entitlements
  js/packages/berty-app/ios/Berty Yolo.entitlements
  js/packages/berty-app/ios/Berty YoloRelease.entitlements
  js/packages/berty-app/ios/Berty-tvOS/Info.plist
  js/packages/berty-app/ios/Berty-tvOSTests/Info.plist
  js/packages/berty-app/ios/Berty.xcodeproj/project.pbxproj
  js/packages/berty-app/ios/Berty.xcodeproj/project.pbxproj.bkp
  js/packages/berty-app/ios/Berty.xcodeproj/xcshareddata/xcschemes/debug.xcscheme
  js/packages/berty-app/ios/Berty.xcodeproj/xcshareddata/xcschemes/staff.xcscheme
  js/packages/berty-app/ios/Berty.xcodeproj/xcshareddata/xcschemes/store.xcscheme
  js/packages/berty-app/ios/Berty.xcodeproj/xcshareddata/xcschemes/xcschememanagement.plist
  js/packages/berty-app/ios/Berty.xcodeproj/xcshareddata/xcschemes/yolo.xcscheme
  js/packages/berty-app/ios/Berty.xcworkspace/contents.xcworkspacedata
  js/packages/berty-app/ios/Berty.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  js/packages/berty-app/ios/Berty/AppDelegate.m
  js/packages/berty-app/ios/Berty/Base.lproj/LaunchScreen.xib
  js/packages/berty-app/ios/Berty/Berty-Bridging-Header.h
  js/packages/berty-app/ios/Berty/Info.plist
  js/packages/berty-app/ios/Berty/Sources/LifeCycle.swift
  js/packages/berty-app/ios/Berty/Sources/LocalNotificationManager.swift
  js/packages/berty-app/ios/BertyTests/BertyTests.m
  js/packages/berty-app/ios/BertyTests/Info.plist
  js/packages/berty-app/ios/Configs/AppStore.xcconfig
  js/packages/berty-app/ios/Configs/Debug.xcconfig
  js/packages/berty-app/ios/Configs/GoogleService/GoogleService-Info-tech.berty.ios.debug.plist
  js/packages/berty-app/ios/Configs/GoogleService/GoogleService-Info-tech.berty.ios.release.plist
  js/packages/berty-app/ios/Configs/GoogleService/GoogleService-Info-tech.berty.ios.staff.plist
  js/packages/berty-app/ios/Configs/GoogleService/GoogleService-Info-tech.berty.ios.yolo.plist
  js/packages/berty-app/ios/Configs/Staff.xcconfig
  js/packages/berty-app/ios/Configs/Yolo.xcconfig
  js/packages/berty-app/ios/Podfile
  js/packages/berty-app/ios/Podfile.lock
  js/packages/berty-app/ios/berty.yaml
  js/packages/berty-app/ios/entitlements.yaml
  js/packages/berty-app/ios/info.yaml
  js/packages/berty-app/package.json
  js/packages/components/package.json
  js/yarn.lock
  tool/build/shell/release-ios.sh
Labels: WIP, enhancement, ✅ Approved

#2413 fix: bump gorm and avoid syntax error
  go.mod
  go.sum
  go/framework/bertybridge/bridge_protocol.go
  go/internal/initutil/node.go
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/db_test.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertymessenger/testing.go
Labels: bug, 🔍 Ready for Review

#2417 chore: update BetaBot URL
  js/packages/components/modals/AddBetabot.js
Labels: chore, 🔍 Ready for Review

#2420 chore: setup shake on forks
  .github/workflows/android.yml
  .github/workflows/ios.yml
Labels: chore, ✅ Approved

#2415 feat: add a package that get username on iOS, Android and others
  api/bertymessenger.proto
  api/bertymessenger.yaml
  docs/gen.sum
  docs/messenger/api.md
  docs/messenger/bertymessenger.swagger.json
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/api_test.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/bertymessenger.pb.gw.go
  go/pkg/username/android.go
  go/pkg/username/ios.go
  go/pkg/username/others.go
  go/pkg/username/username.go
  js/Makefile
  js/gen.sum
  js/packages/api/index.gen.js
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/codegen/index.gen.js
  tool/build/shell/check-java.sh
Labels: enhancement, 🔍 Ready for Review

#2411 feat(app): open deep links in messages in app
  js/packages/components/chat/shared-components/Message.tsx
Labels: enhancement, ✅ Approved

#2418 fix(messenger): navigation
  js/packages/berty-app/ios/Podfile.lock
  js/packages/berty-app/package.json
  js/packages/components/main/Home.tsx
  js/packages/components/main/Scan.tsx
  js/packages/components/modals/AddBetabot.js
  js/packages/components/modals/DeleteAccount.tsx
  js/packages/components/package.json
  js/packages/components/settings/DevTools.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/MyBertyId.tsx
  js/packages/navigation/hook.ts
  js/packages/navigation/index.tsx
  js/packages/navigation/package.json
  js/packages/navigation/stacks.tsx
  js/packages/store/hooks.js
  js/packages/store/provider.tsx
  js/packages/storybook-mobile/package.json
  js/yarn.lock
Labels: bug, ✅ Approved

#2428 chore: use explicit artifact name on github action
  .github/workflows/android.yml
  .github/workflows/ios.yml
Labels: chore, 🔍 Ready for Review

#2427 fix: restore git version in system info on mobile
  js/Makefile
  js/gen.sum
Labels: bug, 🔍 Ready for Review

#2414 feat(messenger): quick replies buttons
  api/bertymessenger.proto
  api/bertymessenger.yaml
  docs/gen.sum
  docs/messenger/api.md
  docs/messenger/bertymessenger.swagger.json
  go/cmd/berty/mini/view_group.go
  go/cmd/berty/mini/view_group_outgoing.go
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/bertymessenger.pb.gw.go
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/db_test.go
  go/pkg/bertymessenger/handlers.go
  go/pkg/bertymessenger/types.go
  js/gen.sum
  js/packages/api/index.gen.js
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/codegen/index.gen.js
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/shared-components/Message.tsx
Labels: enhancement, ✅ Approved

#2429 chore(ci): use expected commit at checkout for versionning
  .github/workflows/android.yml
  .github/workflows/go.yml
  .github/workflows/ios.yml
  .github/workflows/release.yml
Labels: chore, 🔍 Ready for Review

#2425 feat: (re)add launchscreen xib
  js/Makefile
  js/gen.sum
  js/packages/berty-app/ios/Berty/Base.lproj/LaunchScreen.xib
Labels: enhancement, ✅ Approved

#2423 fix(messenger): avoid common errors from handlers
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/db_test.go
  go/pkg/bertymessenger/handlers.go
Labels: bug, ✅ Approved

#2431 chore: use semver on releases
  docs/Makefile
  docs/gen.sum
  go.mod
  go.sum
  go/Makefile
  go/gen.sum
  go/internal/tools/tools.go
  js/Makefile
  js/gen.sum
Labels: chore, 🔍 Ready for Review

#2435 chore: simplify rusage output in system info + add system username
  api/bertytypes.proto
  docs/gen.sum
  docs/messenger/bertymessenger.swagger.json
  docs/protocol/api.md
  docs/protocol/bertyprotocol.swagger.json
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertyprotocol/api_debug.go
  go/pkg/bertytypes/bertytypes.pb.go
  js/gen.sum
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
Labels: chore, 🔍 Ready for Review

#2434 feat: add auto semver on ios
  docs/Makefile
  docs/gen.sum
  go.mod
  go.sum
  go/Makefile
  go/gen.sum
  go/internal/tools/tools.go
  js/Makefile
  js/gen.sum
  js/packages/berty-app/ios/info.yaml
Labels: enhancement, 🔍 Ready for Review

#2416 perf: Cleaner replay check for beta bot and fix some race condition.
  go.mod
  go.sum
  go/cmd/betabot/main.go
Labels: performance, ✅ Approved

#2433 chore: bump golangci-lint-action
  .github/workflows/go.yml
Labels: chore, 🔍 Ready for Review

#2440 fix: Replace RDVP with ip instead of DNS for the CI.
  go/internal/config/berty.go
Labels: bug, 🔍 Ready for Review

#2436 feat(betabot): Added /demo version
  go/cmd/betabot/main.go
Labels: enhancement, 🔍 Ready for Review

#2419 feat: replication service UX improvements
  api/bertymessenger.proto
  api/bertymessenger.yaml
  api/bertytypes.proto
  docs/gen.sum
  docs/messenger/api.md
  docs/messenger/bertymessenger.swagger.json
  docs/protocol/api.md
  docs/protocol/bertyprotocol.swagger.json
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/bertymessenger.pb.gw.go
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/db_test.go
  go/pkg/bertymessenger/handlers.go
  go/pkg/bertyprotocol/api_replication.go
  go/pkg/bertyprotocol/events.go
  go/pkg/bertyprotocol/services_auth_server.go
  go/pkg/bertyprotocol/services_auth_templates.go
  go/pkg/bertyprotocol/store_metadata.go
  go/pkg/bertytypes/bertytypes.pb.go
  go/pkg/bertytypes/events_account.go
  js/gen.sum
  js/packages/api/index.gen.js
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/berty-app/android/app/src/main/AndroidManifest.xml
  js/packages/berty-app/android/app/src/main/java/com/facebook/react/PackageList.java
  js/packages/berty-app/android/app/src/main/java/tech/berty/app/BuildConfig.java
  js/packages/codegen/index.gen.js
  js/packages/components/Onboarding.tsx
  js/packages/components/chat/ReplicateGroupSettings.tsx
  js/packages/components/onboarding/Button.tsx
  js/packages/components/onboarding/ServicesAuth.tsx
  js/packages/components/onboarding/SwiperCard.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/ServicesAuth.tsx
  js/packages/navigation/stacks.tsx
  js/packages/store/context.tsx
  js/packages/store/services.tsx
Labels: WIP, enhancement, 🔍 Ready for Review

#2441 feat(messenger): add quotes of the day in search screen
  js/packages/berty-app/custom-icons-svgs/quote.svg
  js/packages/berty-app/custom-icons.tsx
  js/packages/components/main/Search.tsx
Labels: enhancement, messenger, 🔍 Ready for Review

#2439 fix: xcode12 build
  .github/workflows/ios.yml
  js/Gemfile
  js/Gemfile.lock
  js/Makefile
  js/gen.sum
  js/packages/berty-app/android/gradle.properties
  js/packages/berty-app/ios/Podfile
  js/packages/berty-app/ios/Podfile.lock
  js/packages/berty-app/ios/berty.yaml
  js/packages/berty-app/package.json
  js/packages/components/package.json
  js/packages/go-bridge/go-bridge.podspec
  js/packages/go-bridge/package.json
  js/packages/react-native-example/package.json
  js/packages/storybook-mobile/package.json
  js/packages/styles/package.json
  js/yarn.lock
Labels: WIP, bug, chore, 🔍 Ready for Review

#2444 ci: Make ShakeBugs works with GA on PR.
  .buildkite/pipeline.yml
  .github/workflows/android.yml
  .github/workflows/ios.yml
  tool/build/ci/.env
Labels: ci, ✅ Approved

#2438 feat: pkg/bertybot + cmd/testbot
  go/cmd/betabot/main.go
  go/cmd/testbot/main.go
  go/pkg/bertybot/bot.go
  go/pkg/bertybot/bot_test.go
  go/pkg/bertybot/commands.go
  go/pkg/bertybot/context.go
  go/pkg/bertybot/example_test.go
  go/pkg/bertybot/handlers.go
  go/pkg/bertybot/opts.go
  go/pkg/bertybot/recipes.go
  go/pkg/bertymessenger/service_test.go
  go/pkg/bertymessenger/testing.go
  go/pkg/bertymessenger/testing_test.go
  go/pkg/bertymessenger/types.go
Labels: enhancement, 🔍 Ready for Review

#2443 style: Better Berty icon for berty mini's notifications.
  assets/Buck_Berty_Icon_Card.svg
  go/assets/pkged.go
  go/internal/initutil/node.go
Labels: style, ✅ Approved

#2437 feat: add ams rdvp
  go/cmd/rdvp/main.go
  go/internal/config/berty.go
Labels: enhancement, ✅ Approved

#2450 feat: Patchable IPFS Config
  go/framework/bertybridge/bridge_protocol.go
  go/internal/initutil/ipfs.go
  go/internal/ipfsutil/api.go
  go/internal/ipfsutil/helper.go
  go/internal/ipfsutil/repo.go
Labels: enhancement, ✅ Approved

#2452 chore: deploy testbot
  .gitignore
  Dockerfile
  go/cmd/berty/banner.go
  go/cmd/berty/daemon.go
  go/cmd/berty/groupinit.go
  go/cmd/berty/mini.go
  go/cmd/berty/shareinvite.go
  go/cmd/berty/systeminfo.go
  go/cmd/berty/token.go
  go/cmd/berty/version.go
  go/internal/initutil/manager_test.go
  tool/deployments/testbot/Makefile
  tool/deployments/testbot/docker-compose.yml
Labels: chore, 🔍 Ready for Review

#2426 feat: new request-sent/betabot UI/UX
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/db_test.go
  go/pkg/bertymessenger/handlers.go
  go/pkg/bertymessenger/service_test.go
  js/packages/components/NotificationProvider.tsx
  js/packages/components/Onboarding.tsx
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/shared-components/Chat.tsx
  js/packages/components/chat/shared-components/Message.tsx
  js/packages/components/index.ts
  js/packages/components/main/CreateGroupFinalize.tsx
  js/packages/components/main/Home.tsx
  js/packages/components/onboarding/Berty_onboard_animation_assets2/Startup animation assets/Berty BG.json
  js/packages/components/onboarding/Berty_onboard_animation_assets2/Startup animation assets/Circle spin.json
  js/packages/components/onboarding/Berty_onboard_animation_assets2/Startup animation assets/Code Generated.json
  js/packages/components/onboarding/Berty_onboard_animation_assets2/Startup animation assets/Code generation row 1.json
  js/packages/components/onboarding/Berty_onboard_animation_assets2/Startup animation assets/Code generation row 2.json
  js/packages/components/onboarding/Berty_onboard_animation_assets2/Startup animation assets/Code generation row 3.json
  js/packages/components/onboarding/Berty_onboard_animation_assets2/Startup animation assets/Code generation row 4.json
  js/packages/components/onboarding/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 1.json
  js/packages/components/onboarding/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 10.json
  js/packages/components/onboarding/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 11.json
  js/packages/components/onboarding/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 12.json
  js/packages/components/onboarding/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 13.json
  js/packages/components/onboarding/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 14.json
  js/packages/components/onboarding/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 15.json
  js/packages/components/onboarding/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 2.json
  js/packages/components/onboarding/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 3.json
  js/packages/components/onboarding/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 4.json
  js/packages/components/onboarding/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 5.json
  js/packages/components/onboarding/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 6.json
  js/packages/components/onboarding/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 7.json
  js/packages/components/onboarding/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 8.json
  js/packages/components/onboarding/Berty_onboard_animation_assets2/Startup animation assets/Code single line phase/Code phase 9.json
  js/packages/components/onboarding/Berty_onboard_animation_assets2/Startup animation assets/Finish appear.json
  js/packages/components/onboarding/Berty_onboard_animation_assets2/Startup animation assets/Finish loop.json
  js/packages/components/onboarding/Berty_onboard_animation_assets2/Startup animation assets/Shield appear.json
  js/packages/components/onboarding/Berty_onboard_animation_assets2/Startup animation assets/Shield dissapear.json
  js/packages/components/onboarding/Button.tsx
  js/packages/components/onboarding/CreateAccount.js
  js/packages/components/onboarding/GetStarted.js
  js/packages/components/onboarding/OnboardingWrapper.js
  js/packages/components/onboarding/ServicesAuth.tsx
  js/packages/components/onboarding/SetupFinished.js
  js/packages/components/onboarding/SwiperCard.tsx
  js/packages/components/onboarding/berty_gradient_square.svg
  js/packages/components/onboarding/index.ts
  js/packages/components/settings/DevTools.tsx
  js/packages/components/settings/MyBertyId.tsx
  js/packages/components/shared-components/Card.tsx
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
  js/packages/store/hooks.js
Labels: enhancement, 🔍 Ready for Review

#2455 ci: Cancel previous Runs to avoid running out of runners.
  .github/workflows/push.yml
  tool/build/shell/resolve-workflows-for-cancel.py
Labels: ci, ✅ Approved

#2458 feat(bot): configure two daemons on testbot + add intro README + create /config/vars.yml file
  README.md
  config/Makefile
  config/vars.yml
  go.mod
  go.sum
  go/cmd/testbot/README.md
  go/cmd/testbot/main.go
  tool/deployments/testbot/Makefile
  tool/deployments/testbot/docker-compose.yml
Labels: enhancement, 🔍 Ready for Review

#2445 refactor(messenger): timestamp parse and display using Moment
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/helpers.ts
  js/packages/components/main/Home.tsx
  js/packages/components/main/Search.tsx
  js/packages/store/faker.js
  js/packages/store/hooks.js
  js/packages/store/oldhooks/message.ts
  js/packages/web-dev-app/src/App.tsx
Labels: refactor, 🔍 Ready for Review

#2449 chore: multidevices tests
  go/pkg/bertyprotocol/store_metadata.go
  go/pkg/bertyprotocol/store_metadata_index.go
  go/pkg/bertyprotocol/store_metadata_test.go
Labels: chore, ✅ Approved

#2459 fix(messenger): better handle new models
  api/bertymessenger.proto
  docs/gen.sum
  docs/messenger/api.md
  docs/messenger/bertymessenger.swagger.json
  go/cmd/betabot/main.go
  go/gen.sum
  go/pkg/bertybot/bot.go
  go/pkg/bertybot/handlers.go
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/db_test.go
  go/pkg/bertymessenger/handlers.go
  go/pkg/bertymessenger/handlers_test.go
  go/pkg/bertymessenger/notifiee.go
  go/pkg/bertymessenger/notifiee_test.go
  go/pkg/bertymessenger/replay.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertymessenger/service_test.go
  go/pkg/bertymessenger/testing.go
  go/pkg/bertymessenger/types.go
  js/gen.sum
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/store/hooks.js
  js/packages/store/provider.tsx
  js/packages/web-dev-app/src/App.tsx
Labels: bug, messenger, ✅ Approved

#2448 fix: enable auto replicate on sent contact requests
  go/pkg/bertymessenger/api.go
Labels: bug, ✅ Approved

#2460 fix(messenger): remove requests from modal / some fixes
  js/packages/components/chat/ContactSettings.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/OneToOneSettings.tsx
  js/packages/components/main/HomeModal.tsx
  js/packages/components/main/Scan.tsx
  js/packages/components/modals/AddThisContact.tsx
Labels: bug, ✅ Approved

#2461 fix(messenger): restore readEffect in multimember
  js/packages/components/chat/MultiMember.tsx
Labels: bug, 🔍 Ready for Review

#2463 feat(messenger): sticky date dividers in 1-1 chatrooms
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/shared-components/Chat.tsx
  js/packages/components/helpers.ts
  js/packages/components/main/Home.tsx
Labels: enhancement, messenger, 🔍 Ready for Review

#2462 fix(messenger): ui-ux beta stuff
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/MultiMemberSettings.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/OneToOneSettings.tsx
  js/packages/components/chat/shared-components/Chat.tsx
  js/packages/components/main/CreateGroupAddMembers.tsx
  js/packages/components/main/CreateGroupFooter.tsx
  js/packages/components/main/HomeModal.tsx
  js/packages/components/shared-components/SettingsButtons.tsx
Labels: bug, ✅ Approved

#2466 fix(messenger): hotfix remove stickydate + add multimember date dividers
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
Labels: bug, messenger, 🔍 Ready for Review

#2465 WIP: chore(messenger): add date dividers to multimember conversations
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
Labels: WIP, messenger, 🚧 WIP

#2469 chore: update betabot deploy and URL
  config/vars.yml
  js/packages/components/modals/AddBetabot.js
  tool/deployments/betabot/Makefile
  tool/deployments/betabot/docker-compose.yml
Labels: chore, ✅ Approved

#2471 chore: update betabot script + default URL
  config/vars.yml
  js/packages/components/modals/AddBetabot.js
  tool/deployments/betabot/Makefile
  tool/deployments/rdvp-dev/Makefile
Labels: chore, 🔍 Ready for Review

#2467 chore: unexport messageKeystore
  go/internal/initutil/orbitdb.go
  go/pkg/bertyprotocol/group_context.go
  go/pkg/bertyprotocol/keystore_message.go
  go/pkg/bertyprotocol/keystore_message_utils_test.go
  go/pkg/bertyprotocol/orbitdb.go
  go/pkg/bertyprotocol/orbitdb_utils_test.go
  go/pkg/bertyprotocol/store_message.go
  go/pkg/bertyprotocol/store_metadata.go
Labels: chore, ✅ Approved

#2312 feat: add a message cache for messages that can't be opened
  api/errcode.proto
  docs/gen.sum
  go/gen.sum
  go/pkg/bertyprotocol/api_debug.go
  go/pkg/bertyprotocol/group.go
  go/pkg/bertyprotocol/keystore_message.go
  go/pkg/bertyprotocol/store_message.go
  go/pkg/bertyprotocol/store_message_test.go
  go/pkg/bertyprotocol/store_metadata.go
  go/pkg/bertyprotocol/store_metadata_index.go
  go/pkg/errcode/errcode.pb.go
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
Labels: enhancement, 🔍 Ready for Review

#2473 chore: Fixing typo in packing.go
  go/internal/packingutil/packing.go
Labels: chore, 🔍 Ready for Review

#2470 feat(messenger): use GetUsername to prefill CreateAccount page
  js/packages/components/onboarding/CreateAccount.js
Labels: enhancement, ✅ Approved

#2468 fix: add user friendly error message on invitation error
  js/packages/components/chat/shared-components/Message.tsx
Labels: bug, messenger, messenger-ui-cosmetic, 🔍 Ready for Review

#2474 fix(messenger): hardcode betabot URL
  js/packages/components/onboarding/CreateAccount.js
Labels: bug, ✅ Approved

#2475 fix: contact requests in Home readability
  js/packages/components/main/Home.tsx
Labels: bug, messenger, messenger-ui-cosmetic, 🔍 Ready for Review

#2472 chore: add new config generator
  .gitattributes
  .github/workflows/protobuf.yml
  Makefile
  config/Makefile
  config/config.gen.json
  config/config.yml
  config/vars.yml
  go/internal/config/config.gen.go
  go/internal/config/config_test.go
  go/pkg/bertytypes/config.go
  js/Makefile
  js/gen.sum
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/onboarding/CreateAccount.js
  js/packages/config/global.gen.js
  js/packages/config/index.js
  js/packages/config/package.json
  tool/config-generator/main.go
  tool/go.mod
  tool/go.sum
Labels: chore, 🔍 Ready for Review

#2478 feat(messenger): add devtool to list config contacts
  js/packages/components/settings/AddContactList.js
  js/packages/components/settings/DevTools.tsx
  js/packages/components/settings/index.ts
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
Labels: enhancement, ✅ Approved

#2479 chore: update config/ structure, add the Conversation type, add more contacts, and more metadata
  config/Makefile
  config/config.gen.json
  config/config.yml
  go.mod
  go.sum
  go/Makefile
  go/README.md
  go/cmd/betabot/README.md
  go/cmd/testbot/README.md
  go/gen.sum
  go/internal/config/config.gen.go
  go/internal/tools/tools.go
  go/pkg/bertytypes/config.go
  js/packages/config/global.gen.js
  tool/config-generator/main.go
  tool/go.mod
  tool/go.sum
Labels: chore, 🔍 Ready for Review

#2480 chore: Adding my server TCP's address.
  go/internal/config/berty.go
Labels: chore, 🔍 Ready for Review

#2456 chore: cleanup buildkite and project
  .buildkite/agent_setup/linux/README.md
  .buildkite/agent_setup/linux/berty-build-agent@.service
  .buildkite/agent_setup/linux/create-agent.sh
  .buildkite/agent_setup/linux/debian/install_docker.sh
  .buildkite/agent_setup/linux/debian/install_yarn.sh
  .buildkite/agent_setup/linux/debian/sysdeps.sh
  .buildkite/agent_setup/linux/user/Makefile
  .buildkite/agent_setup/linux/user/entrypoint.sh
  .buildkite/agent_setup/linux/user/environment.hook.template.sh
  .buildkite/agent_setup/macos/README.md
  .buildkite/agent_setup/macos/create_agent.sh
  .buildkite/agent_setup/macos/user/Makefile
  .buildkite/pipeline.yml
  .dockerignore
  .github/workflows/android.yml
  .github/workflows/ios.yml
  .github/workflows/js.yml
  .github/workflows/protobuf.yml
  .gitignore
  README.md
  js/.env.development
  js/.eslintignore
  js/.gitignore
  js/Gemfile
  js/Gemfile.lock
  js/Makefile
  js/README.md
  js/XCodeGen.version
  js/fastlane/Fastfile
  js/fastlane/Pluginfile
  js/fastlane/README.md
  js/gen.sum
  js/packages/berty-app/.gitignore
  js/packages/berty-app/android/app/build.gradle
  js/packages/berty-app/ios/Podfile
  js/packages/berty-app/ios/Podfile.lock
  js/packages/berty-app/ios/berty.yaml
  js/packages/go-bridge/.gitignore
  js/packages/storybook-mobile/.gitignore
  tool/build/bazel/com_github_libp2p_go_openssl.BUILD.bzl
  tool/build/ci/paths_changed
  tool/build/dummy-identity/berty-dummy.p12
  tool/build/shakebugs-infos/env
  tool/build/shell/release-android.sh
  tool/build/shell/release-ios.sh
  tool/build/shell/shortcut_build.sh
  tool/test/experiment/.gitignore
  tool/test/experiment/WORKSPACE
Labels: chore, 🔍 Ready for Review

#2481 chore: add new functions to ignore list of goleak
  go/internal/initutil/manager_test.go
Labels: chore, 🔍 Ready for Review

#2486 chore: fix shakebug on master
  .github/workflows/android.yml
  .github/workflows/ios.yml
Labels: chore, ✅ Approved

#2487 fix: bump orbit-db with last fixes from @phanhuynhquy
  go.mod
  go.sum
Labels: bug, 🔍 Ready for Review

#2488 fix: reduce globing scope in ci workflow for yarn.lock listing
  .github/workflows/android.yml
  .github/workflows/ios.yml
  .github/workflows/js.yml
  .github/workflows/protobuf.yml
Labels: bug, ✅ Approved

#2476 feat: add replies buttons for betabot
  go/cmd/betabot/main.go
Labels: enhancement, ✅ Approved

#2483 feat: add libp2p metrics
  go.mod
  go.sum
  go/cmd/berty/daemon.go
  go/cmd/berty/mini.go
  go/cmd/rdvp/main.go
  go/internal/initutil/ipfs.go
  go/internal/initutil/manager.go
  go/internal/initutil/metrics.go
  go/internal/ipfsutil/collector_bandwidth.go
  go/internal/ipfsutil/collector_host.go
  go/internal/ipfsutil/metrics.go
  tool/metrics-compose/.gitignore
  tool/metrics-compose/config/grafana/grafana.ini
  tool/metrics-compose/config/grafana/provisioning/dashboards/dashboard.yml
  tool/metrics-compose/config/prometheus/prometheus.yml
  tool/metrics-compose/docker-compose.yml
Labels: enhancement, ✅ Approved

#2454 feat(messenger): automatically drop db on schema conflict
  go/internal/testutil/logging.go
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/db_state_keeper.go
  go/pkg/bertymessenger/db_state_keeper_test.go
  go/pkg/bertymessenger/db_test.go
  go/pkg/bertymessenger/db_utils.go
  go/pkg/bertymessenger/db_utils_test.go
  go/pkg/bertymessenger/replay.go
  go/pkg/bertymessenger/service.go
Labels: enhancement, ✅ Approved

#2447 feat: refactor account and contact group init
  go/pkg/bertyprotocol/group.go
  go/pkg/bertyprotocol/orbitdb.go
  go/pkg/bertyprotocol/orbitdb_many_adds_berty_test.go
  go/pkg/bertyprotocol/orbitdb_test.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertyprotocol/service_group.go
  go/pkg/bertyprotocol/services_replication_test.go
  go/pkg/bertyprotocol/store_metadata.go
  go/pkg/bertyprotocol/store_metadata_index.go
  go/pkg/bertyprotocol/store_metadata_test.go
Labels: enhancement, ✅ Approved

#2493 chore: Bump deps and remove useless go.mod replace.
  go.mod
  go.sum
  go/pkg/bertymessenger/db_state_keeper_test.go
  go/pkg/bertymessenger/db_utils_test.go
  tool/go.sum
Labels: chore, 🔍 Ready for Review

#2490 chore(messenger): Search screen autofocus and keyboard
  js/packages/components/main/Search.tsx
Labels: chore, messenger, 🔍 Ready for Review

#2497 fix(messenger): contact request alignment
  js/packages/components/main/Home.tsx
Labels: bug, messenger, 🔍 Ready for Review

#2489 fix: test windows on CI
  .github/workflows/go.yml
  go/assets/example_test.go
  go/cmd/berty/mini/example_test.go
  go/cmd/betabot/example_test.go
  go/cmd/rdvp/example_test.go
  go/cmd/testbot/example_test.go
  go/framework/bertybridge/internal/bridgepb/example_test.go
  go/internal/lifecycle/example_test.go
  go/internal/multipeer-connectivity-transport/driver/example_test.go
  go/internal/multipeer-connectivity-transport/example_test.go
  go/internal/multipeer-connectivity-transport/multiaddr/example_test.go
  go/internal/notification/example_test.go
  go/internal/packingutil/example_test.go
  go/internal/sysutil/sysutil.go
  go/internal/sysutil/sysutil_unix.go
  go/internal/sysutil/sysutil_unsupported.go
  go/internal/testutil/example_test.go
  go/internal/tools/example_test.go
  go/pkg/bertymessenger/api.go
  go/pkg/bertyprotocol/api_debug.go
  go/pkg/bertytypes/example_test.go
  go/pkg/bertyversion/example_test.go
  go/pkg/username/example_test.go
Labels: bug, 🔍 Ready for Review

#2504 chore: fix typo and styling
  go/internal/sysutil/sysutil_unix.go
  go/internal/sysutil/sysutil_unsupported.go
Labels: chore, ✅ Approved

#2503 feat: implement native tempdir getter for Android and iOS
  go/pkg/tempdir/tempdir.go
  go/pkg/tempdir/tempdir_android.go
  go/pkg/tempdir/tempdir_darwin.go
  go/pkg/tempdir/tempdir_others.go
Labels: enhancement, ✅ Approved

#2502 feat: set Android and iOS minimum versions for gomobile bind
  js/Makefile
  js/gen.sum
Labels: enhancement, 🔍 Ready for Review

#2498 fix(messenger): increase text size and align text in Home and Message
  js/packages/components/chat/shared-components/Message.tsx
  js/packages/components/main/Home.tsx
Labels: bug, messenger, 🔍 Ready for Review

#2505 chore(messenger): unify date formatting
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/shared-components/Chat.tsx
  js/packages/components/chat/shared-components/Message.tsx
  js/packages/components/helpers.ts
  js/packages/components/main/Home.tsx
  js/packages/components/main/Search.tsx
Labels: chore, messenger, 🔍 Ready for Review

#2494 fix(messenger): in conv keep sent state only on last message
  js/packages/components/chat/MultiMemberSettings.tsx
  js/packages/components/chat/shared-components/Message.tsx
  js/packages/components/main/Home.tsx
Labels: bug, 🔍 Ready for Review

#2492 fix(messenger): activate devtool notifications
  js/packages/components/NotificationProvider.tsx
  js/packages/components/main/Home.tsx
  js/packages/components/onboarding/SetupFinished.js
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/Notifications.tsx
  js/packages/components/shared-components/SettingsButtons.tsx
Labels: bug, 🔍 Ready for Review

#2430 feat: Adding parameters for go-libp2p-tor-transport
  go.mod
  go.sum
  go/internal/initutil/flag.go
  go/internal/initutil/ipfs.go
  go/internal/initutil/manager.go
  go/internal/initutil/tor_embedded.go
  go/internal/initutil/tor_unembedded.go
Labels: enhancement, ✅ Approved

#2496 fix: Improve MC stability
  go/framework/bertybridge/bridge_protocol.go
  go/internal/initutil/ipfs.go
  go/internal/multipeer-connectivity-transport/conn.go
  go/internal/multipeer-connectivity-transport/connmgr.go
  go/internal/multipeer-connectivity-transport/discovery.go
  go/internal/multipeer-connectivity-transport/driver/MCManager.m
  go/internal/multipeer-connectivity-transport/driver/bridge_darwin.go
  go/internal/multipeer-connectivity-transport/driver/bridge_unsupported.go
  go/internal/multipeer-connectivity-transport/driver/mc-driver.h
  go/internal/multipeer-connectivity-transport/driver/mc-driver.m
  go/internal/multipeer-connectivity-transport/init.go
  go/internal/multipeer-connectivity-transport/listener.go
  go/internal/multipeer-connectivity-transport/transport.go
  js/packages/berty-app/ios/Podfile.lock
  js/packages/berty-app/ios/info.yaml
Labels: bug, 🔍 Ready for Review

#2512 chore: bump ipfs webui version
  go.mod
  go.sum
Labels: chore, ✅ Approved, 🔍 Ready for Review

#2514 chore: update crowdin configuration
  .crowdin.yml
Labels: chore, 🔍 Ready for Review

#2516 fix: new translations from Crowdin
  js/packages/berty-i18n/locale/en/messages.json
  js/packages/berty-i18n/locale/fr/messages.json
Labels: bug, 🔍 Ready for Review

#2477 feat: initial version of the PeerList call + new 'berty peers' CLI command
  api/bertyprotocol.proto
  api/bertyprotocol.yaml
  api/bertytypes.proto
  docs/gen.sum
  docs/protocol/api.md
  docs/protocol/bertyprotocol.swagger.json
  go/cmd/berty/main.go
  go/cmd/berty/peers.go
  go/cmd/berty/systeminfo.go
  go/gen.sum
  go/pkg/bertyprotocol/api_debug.go
  go/pkg/bertyprotocol/bertyprotocol.pb.go
  go/pkg/bertyprotocol/bertyprotocol.pb.gw.go
  go/pkg/bertytypes/bertytypes.pb.go
  js/gen.sum
  js/packages/api/index.gen.js
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/codegen/index.gen.js
Labels: enhancement, ✅ Approved

#2521 chore: Bump `go-libp2p-tor-transport`
  go.mod
  go.sum
Labels: chore, 🔍 Ready for Review

#2525 New Crowdin updates
  js/packages/berty-i18n/locale/de/messages.json
  js/packages/berty-i18n/locale/fr/messages.json
Labels: 🔍 Ready for Review

#2526 New Crowdin updates
  js/packages/berty-i18n/locale/es/messages.json
Labels: 🔍 Ready for Review

#2506 feat: account export and import in mini
  api/bertymessenger.proto
  api/bertymessenger.yaml
  api/bertyprotocol.proto
  api/bertytypes.proto
  docs/gen.sum
  docs/messenger/api.md
  docs/messenger/bertymessenger.swagger.json
  docs/protocol/api.md
  docs/protocol/bertyprotocol.swagger.json
  go.mod
  go.sum
  go/cmd/berty/mini/view_group_outgoing.go
  go/gen.sum
  go/internal/initutil/manager.go
  go/internal/initutil/node.go
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/bertymessenger.pb.gw.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertyprotocol/account_export.go
  go/pkg/bertyprotocol/account_export_test.go
  go/pkg/bertyprotocol/api_client.go
  go/pkg/bertyprotocol/bertyprotocol.pb.go
  go/pkg/bertyprotocol/bertyprotocol.pb.gw.go
  go/pkg/bertyprotocol/keystore_device.go
  go/pkg/bertyprotocol/orbitdb.go
  go/pkg/bertyprotocol/testing.go
  go/pkg/bertytypes/bertytypes.pb.go
  js/gen.sum
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
Labels: WIP, enhancement, ✅ Approved

#2528 chore: update crowdin configuration
  .crowdin.yml
  .github/workflows/android.yml
  .github/workflows/ios.yml
Labels: chore, 🔍 Ready for Review

#2530 chore(i18n): update crowdin configuration
  .crowdin.yml
Labels: chore, 🔍 Ready for Review

#2532 New Crowdin updates
  js/packages/berty-i18n/locale/co/messages.json
  js/packages/berty-i18n/locale/ja/messages.json
Labels: 🔍 Ready for Review

#2523 build: Fix Makefiles to be compatible with jobserver.
  Makefile
  js/Makefile
  js/gen.sum
Labels: build, 🔍 Ready for Review

#2533 chore: small makefile fix
  config/Makefile
Labels: chore, 🔍 Ready for Review

#2536 chore: fix typo
  js/packages/berty-i18n/locale/en/messages.json
Labels: chore, 🔍 Ready for Review

#2540 fix(messenger): home conv list text size and alignment
  js/packages/components/main/Home.tsx
Labels: bug, messenger, messenger-ui-cosmetic, 🔍 Ready for Review

#2541 fix(messenger): user message text timestamp size
  js/packages/components/chat/shared-components/Message.tsx
Labels: bug, messenger, messenger-ui-cosmetic, 🔍 Ready for Review

#2537 chore(js): update list of languages + generate a "debug" fake lang
  .github/workflows/android.yml
  .github/workflows/ios.yml
  Makefile
  js/Makefile
  js/gen.sum
  js/go.sum
  js/packages/berty-i18n/locale/co/messages.json
  js/packages/berty-i18n/locale/debug/messages.json
  js/packages/berty-i18n/locale/en/messages.json
  js/packages/berty-i18n/locale/languages.js
  tool/generate-i18n-testlang/main.go
  tool/go.sum
Labels: chore, 🔍 Ready for Review

#2534 chore: add crowdin badge
  README.md
Labels: chore, ✅ Approved

#2542 fix(messenger): date text style harmonization continued
  js/packages/components/chat/OneToOne.tsx
Labels: bug, messenger, messenger-ui-cosmetic, 🔍 Ready for Review

#2543 fix(messenger): increase size of all super-tiny text
  js/packages/components/settings/Mode.tsx
  js/packages/components/shared-components/SettingsButtons.tsx
Labels: bug, messenger, messenger-ui-cosmetic, 🔍 Ready for Review

#2544 chore(messenger): system message harmonization
  js/Makefile
  js/gen.sum
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/shared-components/Message.tsx
Labels: build, chore, messenger, messenger-ui-cosmetic, 🔍 Ready for Review

#2545 fix: temp, marking TestRestoreAccount as unstable
  go/pkg/bertyprotocol/account_export_test.go
Labels: bug, ✅ Approved

#2499 feat(bridge): use initutil to initialize the mobile bridge
  go/framework/bertybridge/blackbox_test.go
  go/framework/bertybridge/bridge.go
  go/framework/bertybridge/bridge_protocol.go
  go/framework/bertybridge/bridge_test.go
  go/framework/bertybridge/client.go
  go/framework/bertybridge/config.go
  go/framework/bertybridge/driver_lifecycle.go
  go/framework/bertybridge/driver_logger.go
  go/framework/bertybridge/driver_notification.go
  go/framework/bertybridge/service.go
  go/framework/bertybridge/testing_test.go
  go/internal/initutil/datastore.go
  go/internal/initutil/flag.go
  go/internal/initutil/ipfs.go
  go/internal/initutil/logger.go
  go/internal/initutil/manager.go
  go/internal/initutil/manager_test.go
  go/internal/initutil/metrics.go
  go/internal/initutil/node.go
  go/internal/initutil/notification.go
  go/internal/initutil/orbitdb.go
  go/internal/ipfsutil/helper.go
  go/pkg/bertyprotocol/account_export_test.go
  js/android/app/.gitignore
  js/android/app/src/main/java/tech/berty/gobridge/GoBridgeModule.java
  js/ios/Berty/Sources/Bridge/GoBridge.swift
  js/ios/Berty/Sources/Bridge/LifeCycleDriver.swift
  js/ios/Podfile.lock
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/Notifications.tsx
  js/packages/go-bridge/defaults.ts
  js/packages/go-bridge/index.ts
  js/packages/go-bridge/types.ts
  js/packages/store/provider.tsx
  js/tsconfig.json
Labels: enhancement, 🔍 Ready for Review

#2539 New Crowdin updates
  js/packages/berty-i18n/locale/en/messages.json
  js/packages/berty-i18n/locale/es/messages.json
Labels: ✅ Approved

#2524 fix: launch screen center icon
  js/ios/Berty/LaunchScreen.storyboard
Labels: bug, ✅ Approved

#2550 chore: 5 new quotes
  go/pkg/banner/quote.go
Labels: chore, 🔍 Ready for Review

#2556 feat(ci): add dependabot for js
  .github/dependabot.yml
Labels: enhancement, ✅ Approved

#2522 chore: refactor the proximity transport and the MC driver
  go/internal/config/berty.go
  go/internal/initutil/ipfs.go
  go/internal/initutil/manager.go
  go/internal/ipfsutil/localrecord.go
  go/internal/multipeer-connectivity-driver/MCManager.h
  go/internal/multipeer-connectivity-driver/MCManager.m
  go/internal/multipeer-connectivity-driver/bridge_darwin.go
  go/internal/multipeer-connectivity-driver/bridge_unsupported.go
  go/internal/multipeer-connectivity-driver/const.go
  go/internal/multipeer-connectivity-driver/example_test.go
  go/internal/multipeer-connectivity-driver/init.go
  go/internal/multipeer-connectivity-driver/mc-driver.h
  go/internal/multipeer-connectivity-driver/mc-driver.m
  go/internal/multipeer-connectivity-driver/multiaddr.go
  go/internal/multipeer-connectivity-transport/driver/bridge_darwin.go
  go/internal/multipeer-connectivity-transport/driver/bridge_unsupported.go
  go/internal/multipeer-connectivity-transport/driver/example_test.go
  go/internal/multipeer-connectivity-transport/init.go
  go/internal/multipeer-connectivity-transport/multiaddr/example_test.go
  go/internal/multipeer-connectivity-transport/multiaddr/multiaddr.go
  go/internal/multipeer-connectivity-transport/multiaddr/pattern.go
  go/internal/proximity-transport/addr.go
  go/internal/proximity-transport/conn.go
  go/internal/proximity-transport/connmgr.go
  go/internal/proximity-transport/discovery.go
  go/internal/proximity-transport/example_test.go
  go/internal/proximity-transport/listener.go
  go/internal/proximity-transport/nativedriver.go
  go/internal/proximity-transport/transport.go
  go/internal/tinder/driver_localdiscovery.go
Labels: chore, ✅ Approved

#2563 chore: update dependabot config
  .github/dependabot.yml
Labels: chore, 🔍 Ready for Review

#2574 chore: fix dependabot config for go (go.mod is at root)
  .github/dependabot.yml
Labels: chore, 🔍 Ready for Review

#2580 chore: bump go deps
  go.mod
  go.sum
  go/cmd/betabot/main.go
  go/cmd/testbot/main.go
  tool/go.sum
Labels: chore, 🔍 Ready for Review

#2555 feat: cleanup / refactor app projects
  .github/workflows/android.yml
  .github/workflows/ios.yml
  .github/workflows/js.yml
  .github/workflows/protobuf.yml
  js/.eslintignore
  js/.gitignore
  js/Makefile
  js/android/app/_BUCK
  js/android/app/build.gradle
  js/android/app/google-services.json
  js/android/app/proguard-rules.pro
  js/android/app/src/debug/java/tech/berty/android/ReactNativeFlipper.java
  js/android/app/src/main/AndroidManifest.xml
  js/android/app/src/main/java/tech/berty/android/MainActivity.java
  js/android/app/src/main/java/tech/berty/android/MainApplication.java
  js/android/app/src/main/res/xml/network_security_config.xml
  js/android/build.gradle
  js/gen.sum
  js/ios/.bundle/config
  js/ios/Configs/AppStore.xcconfig
  js/ios/Configs/Debug.xcconfig
  js/ios/Configs/Staff.xcconfig
  js/ios/Configs/Yolo.xcconfig
  js/ios/Gemfile
  js/ios/Gemfile.lock
  js/ios/Podfile
  js/ios/Podfile.lock
  js/ios/XcodeGen.version
  js/ios/berty.yaml
  js/packages/messenger-app/App.test.tsx
  js/packages/messenger-app/App.tsx
Labels: enhancement, 🔍 Ready for Review

#2595 chore: add coverage for /js
  .github/workflows/js.yml
  js/.gitignore
  js/Makefile
  js/gen.sum
Labels: chore, ✅ Approved

#2597 chore: use multiple codecov flags
  .codecov.yml
  .github/workflows/go.yml
  .github/workflows/js.yml
  README.md
Labels: chore, ✅ Approved

#2585 feat: update bertyprotocol.PeerList + add new fields
  api/bertytypes.proto
  docs/gen.sum
  docs/protocol/api.md
  docs/protocol/bertyprotocol.swagger.json
  go/gen.sum
  go/pkg/bertyprotocol/api_debug.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertytypes/bertytypes.pb.go
  js/gen.sum
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
Labels: enhancement, 🔍 Ready for Review

#2598 fix: iOS crashlytics config filename for release build
  js/ios/Configs/GoogleService/GoogleService-Info-tech.berty.ios.plist
  js/ios/Podfile.lock
Labels: bug, 🔍 Ready for Review

#2599 fix: bump IPFS/LibP2P
  go.mod
  go.sum
  tool/go.sum
Labels: bug, 🔍 Ready for Review

#2596 feat: set Android tempdir in go from Java getCacheDir method
  go/framework/bertybridge/config_android.go
  js/android/app/src/main/java/tech/berty/gobridge/GoBridgeModule.java
Labels: enhancement, ✅ Approved

#2553 chore: small makefile refactor to handle relative go.mod
  docs/Makefile
  docs/gen.sum
  js/Makefile
  js/gen.sum
  tool/go.sum
Labels: chore, 🔍 Ready for Review

#2606 fix: rendezvous streams leaks
  go.mod
  go.sum
Labels: bug, ✅ Approved

#2607 chore: update deployment config (by @gfanton)
  tool/deployments/betabot/docker-compose.yml
  tool/deployments/rdvp-dev/docker-compose.yml
  tool/deployments/testbot/docker-compose.yml
Labels: chore, 🔍 Ready for Review

#2608 fix: Bump `moul.io/srand`.
  go.mod
  go.sum
Labels: bug, 🔍 Ready for Review

#2551 New Crowdin updates
  js/packages/berty-i18n/locale/cs/messages.json
  js/packages/berty-i18n/locale/da/messages.json
  js/packages/berty-i18n/locale/fi/messages.json
  js/packages/berty-i18n/locale/it/messages.json
  js/packages/berty-i18n/locale/nl/messages.json
  js/packages/berty-i18n/locale/pl/messages.json
  js/packages/berty-i18n/locale/pt/messages.json
  js/packages/berty-i18n/locale/ro/messages.json
  js/packages/berty-i18n/locale/ru/messages.json
  js/packages/berty-i18n/locale/sv/messages.json
  js/packages/berty-i18n/locale/uk/messages.json
Labels: 🔍 Ready for Review

#2611 chore: cleanup old config
  go/internal/config/berty.go
  go/internal/initutil/ipfs.go
  go/internal/ipfsutil/repo.go
Labels: chore, 🔍 Ready for Review

#2586 feat(messenger): new UI/UX
  js/packages/components/helpers.ts
  js/packages/components/main/CreateGroupAddMembers.tsx
  js/packages/components/main/CreateGroupFinalize.tsx
  js/packages/components/main/Footer.tsx
  js/packages/components/main/Home.tsx
  js/packages/components/main/HomeModal.tsx
  js/packages/components/main/Scan.tsx
  js/packages/components/main/Search.tsx
  js/packages/components/main/index.ts
  js/packages/components/settings/Help.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/Mode.tsx
  js/packages/components/settings/MyBertyId.tsx
  js/packages/components/shared-components/Footer.tsx
  js/packages/components/shared-components/HintBody.js
  js/packages/components/shared-components/SwipeNavRecognizer.tsx
  js/packages/components/shared-components/index.ts
  js/packages/messenger-app/custom-icons-svgs/account-berty.svg
  js/packages/messenger-app/custom-icons-svgs/plus.svg
  js/packages/messenger-app/custom-icons.tsx
  js/packages/navigation/hook.ts
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
Labels: enhancement, 🔍 Ready for Review

#2613 fix: js gen mod
  js/Makefile
  js/gen.sum
Labels: bug, ✅ Approved

#2616 fix(messenger): anim home logo
  js/packages/components/main/Home.tsx
  js/packages/components/main/berty_logo_animated.json
Labels: bug, ✅ Approved
