Repository berty/berty, pull requests merged in 2020-03, with the labels that each got.

#1761 chore(ci): add [skip-ci] commit hint
  .buildkite/pipeline.yml
Labels: 🔍 Ready for Review

#1764 chore: update badges in README
  README.md
Labels: 🔍 Ready for Review

#1765 chore: add more per-folder README.md files
  README.md
  go/README.md
  go/pkg/bertyprotocol/README.md
Labels: 🔍 Ready for Review

#1768 feat(chat): use jdenticon as user profile picture
  js/packages/berty-storybook/main/Footer.tsx
  js/packages/berty-storybook/main/List.tsx
  js/packages/berty-storybook/main/ListModal.tsx
  js/packages/berty-storybook/package.json
  js/packages/berty-storybook/settings/Footer.tsx
  js/packages/berty-storybook/settings/Home.tsx
  js/packages/berty-storybook/settings/MyBertyId.tsx
  js/packages/berty-storybook/shared-components/Footer.tsx
  js/packages/berty-storybook/shared-components/ProceduralCircleAvatar.tsx
  js/packages/berty-storybook/shared-components/Request.tsx
  js/packages/berty-storybook/shared-components/TabBar.tsx
  js/packages/berty-storybook/shared-components/index.ts
  js/packages/hooks/Chat.tsx
  js/packages/store/chat/contact.ts
  js/packages/store/chat/conversation.ts
  js/yarn.lock
Labels: chat, 🔍 Ready for Review

#1769 feat(chat): add message acknowledgment
  js/packages/berty-storybook/chat/Chat.tsx
  js/packages/berty-storybook/chat/shared-components/Message.tsx
  js/packages/hooks/Chat.tsx
  js/packages/store/chat/AppMessage.ts
  js/packages/store/chat/message.ts
Labels: chat, 🔍 Ready for Review

#1770 chore(chat): add contact request documentation graph
  docs/chat-mvp/README.md
  docs/chat-mvp/contact-request.mermaid
  docs/chat-mvp/contact-request.mermaid.svg
Labels: chat, 🔍 Ready for Review

#1772 Warn user for using the v1 version.
  core/cmd/berty/main.go
Labels: 🔍 Ready for Review

#1776 fix: add top-level go package with deprecation warning
  deprecated.go
Labels: 🔍 Ready for Review

#1782 fix: Moving depreacation in node for go mod user.
  core/cmd/berty/main.go
  core/node/node.go
Labels: 🌟 Needs more Approvals, 🔍 Ready for Review

#1781 fix: {ios,android}-build on the CI
  js/packages/go-bridge/Makefile
Labels: 🔍 Ready for Review

#1784 fix: launch error because of bluetooth privilege required
  client/ios/Berty/Info.plist
Labels: 🌟 Needs more Approvals, 🔍 Ready for Review

#1789 fix(test): fix test timeout
  go/internal/ipfsutil/testing.go
Labels: 🔍 Ready for Review

#1792 feat(tool): berty mini cluster with tmux
  go/cmd/berty/mini/main.go
  tool/berty-mini-cluster/commander
  tool/berty-mini-cluster/docker-compose.yml
Labels: 🔍 Ready for Review

#1796 refactor: cleanup dead errcodes and rename some of them for consistency
  api/errcode.proto
  docs/gen.sum
  go/gen.sum
  go/internal/orbitutil/orbitdb.go
  go/internal/orbitutil/store_message.go
  go/internal/orbitutil/store_metadata.go
  go/pkg/bertyprotocol/api_app.go
  go/pkg/bertyprotocol/api_contact.go
  go/pkg/bertyprotocol/api_multimember.go
  go/pkg/bertyprotocol/client_group.go
  go/pkg/bertyprotocol/events.go
  go/pkg/bertyprotocol/events_sig_checkers.go
  go/pkg/bertyprotocol/group.go
  go/pkg/bertyprotocol/iface_account.go
  go/pkg/bertyprotocol/message_keys.go
  go/pkg/bertyprotocol/message_keys_datastore.go
  go/pkg/bertytypes/group.go
  go/pkg/errcode/errcode.pb.go
  go/pkg/errcode/error_test.go
Labels: 🔍 Ready for Review

#1794 chore: moved orbitutil and account packages contents inside bertyprotocol
  go/cmd/berty/main.go
  go/cmd/berty/mini/main.go
  go/framework/bertybridge/bridge_protocol.go
  go/internal/orbitutil/context_group.go
  go/internal/orbitutil/doc.go
  go/pkg/bertydemo/client.go
  go/pkg/bertyprotocol/api_client.go
  go/pkg/bertyprotocol/api_contact.go
  go/pkg/bertyprotocol/api_contactrequest.go
  go/pkg/bertyprotocol/api_group.go
  go/pkg/bertyprotocol/api_multimember.go
  go/pkg/bertyprotocol/client.go
  go/pkg/bertyprotocol/client_group.go
  go/pkg/bertyprotocol/client_test.go
  go/pkg/bertyprotocol/doc.go
  go/pkg/bertyprotocol/events.go
  go/pkg/bertyprotocol/events_sig_checkers.go
  go/pkg/bertyprotocol/group.go
  go/pkg/bertyprotocol/group_context.go
  go/pkg/bertyprotocol/group_test.go
  go/pkg/bertyprotocol/iface_orbitutils.go
  go/pkg/bertyprotocol/keystore_device.go
  go/pkg/bertyprotocol/keystore_device_test.go
  go/pkg/bertyprotocol/keystore_message.go
  go/pkg/bertyprotocol/keystore_message_utils.go
  go/pkg/bertyprotocol/keystore_message_utils_test.go
  go/pkg/bertyprotocol/orbitdb.go
  go/pkg/bertyprotocol/orbitdb_datastore_cache.go
  go/pkg/bertyprotocol/orbitdb_many_adds_berty_test.go
  go/pkg/bertyprotocol/orbitdb_many_adds_test.go
  go/pkg/bertyprotocol/orbitdb_signed_entry_accesscontroller.go
  go/pkg/bertyprotocol/orbitdb_signed_entry_identity_provider.go
  go/pkg/bertyprotocol/orbitdb_signed_entry_keystore.go
  go/pkg/bertyprotocol/orbitdb_utils_test.go
  go/pkg/bertyprotocol/store_message.go
  go/pkg/bertyprotocol/store_message_test.go
  go/pkg/bertyprotocol/store_metadata.go
  go/pkg/bertyprotocol/store_metadata_index.go
  go/pkg/bertyprotocol/store_metadata_test.go
  go/pkg/bertyprotocol/store_options.go
  go/pkg/bertyprotocol/testing_test.go
Labels: ✅ Approved

#1800 chore: add godoc example
  go/pkg/bertyprotocol/client_test.go
Labels: ✅ Approved

#1802 fix(chat): change types paths from .protocol. to .types.
  js/packages/grpc-bridge/protocol/handler.ts
  js/packages/store/chat/conversation.ts
  js/packages/store/protocol/client.ts
Labels: chat, 🔍 Ready for Review

#1799 refactor: disambiguate rand packages and reorganize cryptoutil
  go/cmd/berty/main.go
  go/cmd/rdvp/main.go
  go/internal/banner/quote.go
  go/internal/cryptoutil/cryptoutil.go
  go/internal/ipfsutil/api_inmemory.go
  go/internal/ipfsutil/cfg.go
  go/internal/ipfsutil/testing.go
  go/internal/tinder/driver_rdv.go
  go/pkg/bertydemo/client.go
  go/pkg/bertyprotocol/events.go
  go/pkg/bertyprotocol/group.go
  go/pkg/bertyprotocol/group_test.go
  go/pkg/bertyprotocol/keystore_message.go
  go/pkg/bertyprotocol/keystore_message_utils.go
  go/pkg/bertyprotocol/orbitdb_many_adds_test.go
  go/pkg/bertyprotocol/store_metadata.go
  go/pkg/bertyprotocol/store_metadata_test.go
Labels: ✅ Approved

#1779 feat(chat): add navigation in implemented screens
  js/packages/berty-storybook/main/List.tsx
  js/packages/berty-storybook/settings/AboutBerty.tsx
  js/packages/berty-storybook/settings/AppUpdates.tsx
  js/packages/berty-storybook/settings/Bluetooth.tsx
  js/packages/berty-storybook/settings/DevTools.tsx
  js/packages/berty-storybook/settings/Mode.tsx
  js/packages/berty-storybook/settings/Notifications.tsx
  js/packages/berty-storybook/settings/TermsOfUse.tsx
  js/packages/berty-storybook/shared-components/Header.tsx
  js/packages/berty-storybook/shared-components/Request.tsx
  js/packages/berty-storybook/shared-components/SettingsButtons.tsx
Labels: chat, ✅ Approved

#1762 feat(chat): turn fullscreens modals into pages
  js/packages/berty-storybook/main/Scan.tsx
  js/packages/berty-storybook/settings/MyBertyId.tsx
Labels: chat, ✅ Approved

#1788 feat: allow configuring rdvp from CLI
  go/cmd/rdvp/main.go
Labels: ✅ Approved

#1795 chore: configure more go linters
  githooks/pre-commit
  go.mod
  go/.golangci.yml
  go/cmd/berty/mini/main.go
  go/cmd/berty/mini/view_group.go
  go/cmd/berty/mini/view_group_incoming.go
  go/cmd/berty/mini/view_group_outgoing.go
  go/cmd/berty/mini/view_tabbed_groups.go
  go/framework/bertybridge/bridge.go
  go/framework/bertybridge/bridge_protocol.go
  go/internal/banner/banner.go
  go/internal/banner/banner_test.go
  go/internal/banner/quote.go
  go/internal/grpcutil/lazy_message.go
  go/internal/grpcutil/server.go
  go/internal/ipfsutil/datastore_namespaced.go
  go/internal/tinder/driver.go
  go/internal/tinder/driver_dht.go
  go/internal/tinder/driver_mocked.go
  go/internal/tinder/driver_multi.go
  go/pkg/bertyprotocol/api_group.go
  go/pkg/bertyprotocol/api_multimember.go
  go/pkg/bertyprotocol/client_group.go
  go/pkg/bertyprotocol/events.go
  go/pkg/bertyprotocol/group.go
  go/pkg/bertyprotocol/keystore_message_utils.go
  go/pkg/bertyprotocol/store_message.go
  go/pkg/bertyprotocol/store_metadata.go
  go/pkg/bertytypes/group.go
Labels: ✅ Approved

#1803 fix(mini): watcher loops should wait for goroutines init before returning
  go/cmd/berty/mini/main.go
  go/cmd/berty/mini/view_group.go
  go/cmd/berty/mini/view_group_incoming.go
  go/cmd/berty/mini/view_group_outgoing.go
  go/cmd/rdvp/main.go
  go/internal/testutil/skip.go
Labels: 🔍 Ready for Review

#1780 fix(chat): align bullet point
  js/packages/berty-storybook/main/Scan.tsx
  js/packages/berty-storybook/settings/Home.tsx
  js/packages/berty-storybook/shared-components/Header.tsx
  js/packages/berty-storybook/shared-components/SettingsButtons.tsx
Labels: chat, 🔍 Ready for Review

#1806 chore: add rdvp deployment helpers + configure docker to use host network
  deployments/rdvp-dev/Makefile
  deployments/rdvp-dev/docker-compose.yml
Labels: ✅ Approved

#1805 feat(protocol): Expose bridge protocol
  go.mod
  go.sum
  go/cmd/berty/main.go
  go/cmd/berty/mini/main.go
  go/cmd/berty/mini/view_group.go
  go/cmd/berty/mini/view_group_incoming.go
  go/cmd/berty/mini/view_group_outgoing.go
  go/cmd/berty/mini/view_tabbed_groups.go
  go/framework/bertybridge/bridge_demo.go
  go/framework/bertybridge/bridge_protocol.go
  go/pkg/bertydemo/service.go
  go/pkg/bertydemo/service_test.go
  go/pkg/bertydemo/testing_test.go
  go/pkg/bertyprotocol/api_app.go
  go/pkg/bertyprotocol/api_client.go
  go/pkg/bertyprotocol/api_contact.go
  go/pkg/bertyprotocol/api_contactrequest.go
  go/pkg/bertyprotocol/api_event.go
  go/pkg/bertyprotocol/api_group.go
  go/pkg/bertyprotocol/api_multimember.go
  go/pkg/bertyprotocol/group_context.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertyprotocol/service_group.go
  go/pkg/bertyprotocol/service_test.go
  go/pkg/bertyprotocol/store_metadata.go
  go/pkg/bertyprotocol/testing.go
  js/packages/go-bridge/ios/GoBridge.m
  js/packages/go-bridge/ios/GoBridge.swift
Labels: 🔍 Ready for Review

#1808 feat: allow logging to a file
  go/cmd/berty/main.go
Labels: 🔍 Ready for Review

#1810 feat(chat): disable unimplemented buttons
  js/packages/berty-storybook/settings/AboutBerty.tsx
  js/packages/berty-storybook/settings/AppUpdates.tsx
  js/packages/berty-storybook/settings/Bluetooth.tsx
  js/packages/berty-storybook/settings/DevTools.tsx
  js/packages/berty-storybook/settings/Help.tsx
  js/packages/berty-storybook/settings/Home.tsx
  js/packages/berty-storybook/settings/Mode.tsx
  js/packages/berty-storybook/settings/Notifications.tsx
  js/packages/berty-storybook/shared-components/Header.tsx
  js/packages/berty-storybook/shared-components/SettingsButtons.tsx
Labels: chat, ✅ Approved

#1815 fix(chat): fix message border styles
  js/packages/berty-storybook/chat/shared-components/Message.tsx
Labels: chat, ✅ Approved

#1807 feat(chat): implement share button and deep link handling
  js/packages/berty-app/App.tsx
  js/packages/berty-app/LinkHandler.ts
  js/packages/berty-app/ios/Berty/AppDelegate.m
  js/packages/berty-app/ios/Berty/Info.plist
  js/packages/berty-storybook/settings/MyBertyId.tsx
Labels: chat, ✅ Approved
