Repository berty/berty, pull requests merged in 2020-12, with the labels that each got.

#2853 feat: add configurable poll interval
  go/internal/initutil/ipfs.go
  go/internal/initutil/manager.go
Labels: enhancement, ✅ Approved

#2837 feat(messenger): multimedia
  api/bertymessenger.proto
  api/bertymessenger.yaml
  api/errcode.proto
  docs/apis/bertymessenger.md
  docs/apis/bertymessenger.swagger.json
  docs/gen.sum
  go/gen.sum
  go/internal/streamutil/func_io.go
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/bertymessenger.pb.go
  go/pkg/bertymessenger/bertymessenger.pb.gw.go
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/db_test.go
  go/pkg/bertymessenger/handlers.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertymessenger/service_test.go
  go/pkg/bertymessenger/testing.go
  go/pkg/bertymessenger/types.go
  go/pkg/bertyprotocol/api_attachment.go
  go/pkg/bertyprotocol/attachment_crypto.go
  go/pkg/bertyprotocol/attachment_utils.go
  go/pkg/errcode/errcode.pb.go
  js/Makefile
  js/gen.sum
  js/package.json
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  js/packages/components/AttachmentImage.tsx
  js/packages/components/avatars.tsx
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/OneToOneSettings.tsx
  js/packages/components/chat/ReplicateGroupSettings.tsx
  js/packages/components/chat/common.tsx
  js/packages/components/chat/file-uploads/AddFileMenu.tsx
  js/packages/components/chat/message/MessageInvitation.tsx
  js/packages/components/chat/message/MessageMonitorMetadata.tsx
  js/packages/components/chat/message/QuickReplyOptions.tsx
  js/packages/components/chat/message/UserMessage.tsx
  js/packages/components/chat/message/UserMessageComponents.tsx
  js/packages/components/chat/message/index.tsx
  js/packages/components/modals/Image.tsx
  js/packages/components/modals/ManageDeepLink.tsx
  js/packages/components/modals/index.ts
  js/packages/components/settings/EditProfile.tsx
  js/packages/components/settings/NetworkMap.tsx
  js/packages/components/utils.ts
  js/packages/grpc-bridge/rpc/rpc.bridge.ts
  js/packages/grpc-bridge/welsh-clients.gen.ts
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
  js/packages/store/context.ts
  js/packages/store/gen-type-utils.js
  js/packages/store/hooks.ts
  js/packages/store/methods.ts
  js/packages/store/providerEffects.ts
  js/packages/store/providerReducer.ts
  js/packages/store/types.gen.ts
Labels: enhancement, ✅ Approved

#2848 fix: temporary disable embedTor for iOS
  js/Makefile
Labels: bug, 🔍 Ready for Review

#2858 chore(js): bump deps
  js/.eslintrc.js
  js/gen.sum
  js/ios/Podfile.lock
  js/package.json
  js/yarn.lock
Labels: chore, 🔍 Ready for Review

#2859 chore(js): use global mocks
  js/__mocks__/@react-native-community/async-storage.js
  js/__mocks__/@react-native-community/audio-toolkit.js
  js/__mocks__/@shakebugs/react-native-shake.js
  js/__mocks__/react-native-fs.js
  js/__mocks__/react-native-gesture-handler.js
  js/__mocks__/react-native-permissions.js
  js/__mocks__/react-native-reanimated.js
  js/__mocks__/react-native-screens.js
  js/__mocks__/react-native-share.js
  js/__mocks__/rn-fetch-blob.js
  js/assetsTransformer.js
  js/package.json
  js/packages/grpc-bridge/service.test.ts
  js/packages/messenger-app/App.test.tsx
Labels: chore, 🔍 Ready for Review

#2810 chore: add a local integration environment (within docker)
  .dockerignore
  .github/workflows/integration.yml
  Dockerfile
  go/cmd/rdvp/main.go
  tool/compose-integration/Makefile
  tool/compose-integration/docker-compose.yml
  tool/go.mod
  tool/go.sum
Labels: chore, 🔍 Ready for Review

#2861 chore: fix integration test
  .github/workflows/integration.yml
Labels: chore, 🔍 Ready for Review

#2866 chore(github): use Dependent Issues action
  .github/workflows/dependent-issues.yml
Labels: chore, ✅ Approved

#2856 fix(messenger): size add members item in create group
  js/packages/components/avatars.tsx
  js/packages/components/main/CreateGroupAddMembers.tsx
Labels: bug, ✅ Approved

#2855 fix(messenger): auto correct text input
  js/packages/components/chat/common.tsx
Labels: bug, ✅ Approved

#2883 fix(i18n): use full locale in path
  .crowdin.yml
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/berty-i18n/locale/languages.js
Labels: bug, 🔍 Ready for Review

#2881 feat: encrypted berty links
  .gitattributes
  api/errcode.proto
  api/messengertypes.proto
  docs/apis/messengertypes.md
  docs/apis/messengertypes.swagger.json
  docs/gen.sum
  go/cmd/berty/groupinit.go
  go/cmd/berty/mini/utils.go
  go/cmd/berty/mini/view_group_outgoing.go
  go/cmd/berty/shareinvite.go
  go/cmd/betabot/main.go
  go/gen.sum
  go/internal/bertylinks/links.go
  go/internal/bertylinks/links_test.go
  go/internal/cryptoutil/cryptoutil.go
  go/internal/cryptoutil/cryptoutil_test.go
  go/internal/omnisearch/berty-parser.go
  go/pkg/bertymessenger/api.go
  go/pkg/errcode/errcode.pb.go
  go/pkg/messengertypes/links.go
  go/pkg/messengertypes/messengertypes.pb.go
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
Labels: enhancement, ✅ Approved

#2889 fix: pass log filters through gobridge
  js/packages/go-bridge/defaults.ts
  js/packages/go-bridge/types.ts
  js/packages/store/providerEffects.ts
Labels: bug, ✅ Approved

#2891 chore: New Crowdin updates
  js/packages/berty-i18n/locale/af-ZA/messages.json
  js/packages/berty-i18n/locale/ar-SA/messages.json
  js/packages/berty-i18n/locale/bg-BG/messages.json
  js/packages/berty-i18n/locale/ca-ES/messages.json
  js/packages/berty-i18n/locale/cs-CZ/messages.json
  js/packages/berty-i18n/locale/da-DK/messages.json
  js/packages/berty-i18n/locale/de-DE/messages.json
  js/packages/berty-i18n/locale/el-GR/messages.json
  js/packages/berty-i18n/locale/es-ES/messages.json
  js/packages/berty-i18n/locale/fi-FI/messages.json
  js/packages/berty-i18n/locale/fr-FR/messages.json
  js/packages/berty-i18n/locale/he-IL/messages.json
  js/packages/berty-i18n/locale/hu-HU/messages.json
  js/packages/berty-i18n/locale/id-ID/messages.json
  js/packages/berty-i18n/locale/it-IT/messages.json
  js/packages/berty-i18n/locale/ja-JP/messages.json
  js/packages/berty-i18n/locale/ko-KR/messages.json
  js/packages/berty-i18n/locale/nl-NL/messages.json
  js/packages/berty-i18n/locale/no-NO/messages.json
  js/packages/berty-i18n/locale/pl-PL/messages.json
  js/packages/berty-i18n/locale/pt-BR/messages.json
  js/packages/berty-i18n/locale/pt-PT/messages.json
  js/packages/berty-i18n/locale/ro-RO/messages.json
  js/packages/berty-i18n/locale/ru-RU/messages.json
  js/packages/berty-i18n/locale/sr-Cyrl/messages.json
  js/packages/berty-i18n/locale/sv-SE/messages.json
  js/packages/berty-i18n/locale/tr-TR/messages.json
  js/packages/berty-i18n/locale/uk-UA/messages.json
  js/packages/berty-i18n/locale/vi-VN/messages.json
  js/packages/berty-i18n/locale/zh-CN/messages.json
  js/packages/berty-i18n/locale/zh-TW/messages.json
Labels: chore, ✅ Approved

#2830 feat: record and play functionality
  .github/workflows/android.yml
  js/android/app/src/main/AndroidManifest.xml
  js/android/build.gradle
  js/global.d.ts
  js/ios/Podfile
  js/ios/Podfile.lock
  js/ios/info.yaml
  js/package.json
  js/packages/api/root.pb.d.ts
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/components/AttachmentImage.tsx
  js/packages/components/chat/ImageCounter.tsx
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/common.tsx
  js/packages/components/chat/file-uploads/AddFileMenu.tsx
  js/packages/components/chat/file-uploads/GallerySection.tsx
  js/packages/components/chat/file-uploads/GifSection.tsx
  js/packages/components/chat/file-uploads/MenuListItem.tsx
  js/packages/components/chat/file-uploads/SecurityAccess.tsx
  js/packages/components/chat/file-uploads/types.tsx
  js/packages/components/chat/message/AudioMessage.tsx
  js/packages/components/chat/message/FileMessage.tsx
  js/packages/components/chat/message/PictureMessage.tsx
  js/packages/components/chat/message/UserMessage.tsx
  js/packages/components/chat/message/UserMessageComponents.tsx
  js/packages/components/main/Home.tsx
  js/packages/components/modals/ForwardToBertyContactModal.tsx
  js/packages/components/modals/Image.tsx
  js/packages/components/modals/ImageView.tsx
  js/packages/components/modals/index.ts
  js/packages/components/shared-components/StickyMusicPlayer.tsx
  js/packages/components/utils.ts
  js/packages/messenger-app/App.tsx
  js/packages/messenger-app/custom-icons-svgs/add-picture.svg
  js/packages/messenger-app/custom-icons-svgs/bertyzzz.svg
  js/packages/messenger-app/custom-icons-svgs/camera.svg
  js/packages/messenger-app/custom-icons-svgs/files.svg
  js/packages/messenger-app/custom-icons-svgs/gallery.svg
  js/packages/messenger-app/custom-icons-svgs/gif.svg
  js/packages/messenger-app/custom-icons-svgs/pause-player.svg
  js/packages/messenger-app/custom-icons-svgs/play-player.svg
  js/packages/messenger-app/custom-icons.tsx
  js/packages/music-player/index.tsx
  js/packages/navigation/hook.ts
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
  js/tsconfig.json
  js/yarn.lock
Labels: WIP, enhancement, 🔍 Ready for Review

#2897 fix: bump go-orbit-db
  go.mod
  go.sum
  tool/go.sum
Labels: bug, 🔍 Ready for Review

#2898 fix: refactor bertylinks error handling
  go/internal/bertylinks/links.go
  go/internal/bertylinks/links_test.go
  go/pkg/bertymessenger/api.go
Labels: bug, 🔍 Ready for Review

#2906 chore: fix indent style on i18n
  .editorconfig
  js/packages/berty-i18n/locale/en-US/messages.json
Labels: chore, ✅ Approved

#2900 fix: add optional checksum for bertylinks + keep display name in clear
  api/errcode.proto
  api/messengertypes.proto
  docs/apis/messengertypes.md
  docs/apis/messengertypes.swagger.json
  docs/gen.sum
  go/gen.sum
  go/internal/bertylinks/links.go
  go/internal/bertylinks/links_test.go
  go/pkg/errcode/errcode.pb.go
  go/pkg/messengertypes/messengertypes.pb.go
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
Labels: bug, 🔍 Ready for Review

#2899 feat: ui encrypted links
  js/packages/components/modals/AddThisContact.tsx
  js/packages/components/modals/ManageDeepLink.tsx
  js/packages/components/modals/ManageGroupInvitation.tsx
  js/packages/components/shared-components/FingerprintContent.tsx
Labels: enhancement, ✅ Approved

#2908 fix: fallback when empty string
  js/packages/berty-i18n/index.ts
Labels: bug, ✅ Approved

#2909 chore: add demo conversation with passphrase
  config/config.gen.json
  config/config.yml
  go/internal/config/config.gen.go
  js/packages/config/global.gen.js
Labels: chore, 🔍 Ready for Review

#2862 fix: implem bots
  config/config.gen.json
  config/config.yml
  go/internal/config/config.gen.go
  go/pkg/protocoltypes/config.go
  js/packages/components/avatars.tsx
  js/packages/components/chat/ContactSettings.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/OneToOneSettings.tsx
  js/packages/components/main/Home.tsx
  js/packages/components/modals/AddBot.js
  js/packages/components/modals/index.ts
  js/packages/components/onboarding/CreateAccount.js
  js/packages/components/onboarding/SetupFinished.js
  js/packages/config/global.gen.js
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
  js/packages/store/context.ts
  js/packages/store/providerEffects.ts
Labels: bug, 🔍 Ready for Review

#2918 chore: New Crowdin updates
  js/packages/berty-i18n/locale/cs-CZ/messages.json
  js/packages/berty-i18n/locale/sl-SI/messages.json
Labels: chore

#2921 fix: keyboard issue fix, support music player
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/settings/EditProfile.tsx
  js/packages/components/shared-components/KeyboardAvoidingView.tsx
  js/packages/components/shared-components/StickyMusicPlayer.tsx
  js/packages/messenger-app/App.tsx
Labels: bug

#2923 chore(js): bump deps
  js/ios/Gemfile
  js/ios/Gemfile.lock
  js/ios/Podfile.lock
  js/package.json
  js/yarn.lock
Labels: chore, messenger

#2916 fix(messenger): navigate after create group
  js/packages/components/main/CreateGroupAddMembers.tsx
  js/packages/components/main/CreateGroupFinalize.tsx
Labels: bug

#2917 fix(messenger): ux edit profile
  js/packages/components/avatars.tsx
  js/packages/components/main/Home.tsx
  js/packages/components/settings/EditProfile.tsx
  js/packages/messenger-app/custom-icons-svgs/camera-outline.svg
  js/packages/messenger-app/custom-icons.tsx
Labels: bug

#2926 feat: ui improvements
  js/packages/components/chat/common.tsx
  js/packages/components/chat/file-uploads/AddFileMenu.tsx
  js/packages/components/chat/message/PictureMessage.tsx
  js/packages/components/chat/message/UserMessage.tsx
  js/packages/components/main/CreateGroupAddMembers.tsx
  js/packages/components/main/CreateGroupFinalize.tsx
  js/packages/components/main/Home.tsx
  js/packages/components/main/HomeModal.tsx
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
Labels: enhancement

#2922 chore: New Crowdin updates
  js/packages/berty-i18n/locale/es-ES/messages.json
  js/packages/berty-i18n/locale/ru-RU/messages.json
Labels: chore

#2928 chore: rename shakebugs env -> env.prod and add env.dev
  .github/workflows/android.yml
  .github/workflows/ios.yml
  tool/build/shakebugs-infos/env.dev
  tool/build/shakebugs-infos/env.prod
Labels: chore

#2927 messenger: better app startup ux
  js/android/app/build.gradle
  js/android/app/src/main/AndroidManifest.xml
  js/android/app/src/main/java/tech/berty/android/MainActivity.java
  js/android/app/src/main/res/drawable/bootsplash.xml
  js/android/app/src/main/res/mipmap-hdpi/bootsplash_logo.png
  js/android/app/src/main/res/mipmap-mdpi/bootsplash_logo.png
  js/android/app/src/main/res/mipmap-xhdpi/bootsplash_logo.png
  js/android/app/src/main/res/mipmap-xxhdpi/bootsplash_logo.png
  js/android/app/src/main/res/mipmap-xxxhdpi/bootsplash_logo.png
  js/android/app/src/main/res/values/colors.xml
  js/android/app/src/main/res/values/styles.xml
  js/assets/bootsplash_logo.png
  js/assets/bootsplash_logo@1,5x.png
  js/assets/bootsplash_logo@2x.png
  js/assets/bootsplash_logo@3x.png
  js/assets/bootsplash_logo@4x.png
  js/global.d.ts
  js/ios/Berty/AppDelegate.m
  js/ios/Berty/BootSplash.storyboard
  js/ios/info.yaml
  js/package.json
  js/packages/components/gates.tsx
  js/packages/components/onboarding/AccountSelector.tsx
  js/packages/components/shared-components/LoaderDots.tsx
  js/packages/components/shared-components/loader_dots.gif
  js/packages/messenger-app/App.tsx
  js/yarn.lock
Labels: messenger

#2937 fix(messenger): widen group password input
  js/packages/components/modals/ManageGroupInvitation.tsx
Labels: bug

#2946 feat(ci): check Podfile.lock sync
  .github/workflows/ios.yml
  js/Makefile
  js/ios/Podfile.lock
Labels: enhancement

#2929 fix: clean i18n time handler
  js/packages/berty-i18n/dateFns.js
  js/packages/berty-i18n/locale/en-US/messages.json
Labels: bug

#2943 fix: navigate after add this contact
  js/packages/components/modals/AddThisContact.tsx
Labels: bug

#2938 fix(messenger): preserve anchor in shared links
  js/packages/components/settings/MyBertyId.tsx
Labels: bug

#2920 feat(grpc): improve grpc bridge errors
  api/bertyaccount.proto
  docs/gen.sum
  go/gen.sum
  go/internal/grpcutil/lazy_client.go
  go/pkg/bertyaccount/bertyaccount.pb.go
  go/pkg/bertyaccount/service_grpc.go
  go/pkg/bertyaccount/service_test.go
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
Labels: enhancement

#2949 fix(messenger): revert error details bug
  api/bertyaccount.proto
  docs/gen.sum
  go/gen.sum
  go/internal/grpcutil/lazy_client.go
  go/pkg/bertyaccount/bertyaccount.pb.go
  go/pkg/bertyaccount/service_grpc.go
  go/pkg/bertyaccount/service_test.go
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
Labels: bug

#2947 betabot: add avatar and fix duplicate messages
  config/config.gen.json
  config/config.yml
  go/cmd/betabot/main.go
  go/internal/config/config.gen.go
  go/pkg/protocoltypes/config.go
  js/package.json
  js/packages/assets/berty_bot_pink_bg.png
  js/packages/assets/berty_dev_green_bg.png
  js/packages/components/avatars.tsx
  js/packages/components/chat/ContactSettings.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/OneToOneSettings.tsx
  js/packages/components/main/Home.tsx
  js/packages/components/settings/AddDevConversations.js
  js/packages/components/settings/AddDevConversations.tsx
  js/packages/config/global.gen.js
  js/packages/store/context.ts
  js/tsconfig.json
  tool/go.sum
Labels: betabot

#2948 fix: bump deps
  go.mod
  go.sum
  go/internal/ipfsutil/localrecord.go
  go/internal/tinder/driver_localdiscovery.go
Labels: bug

#2956 feat: ui improvements
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/components/chat/MultiMemberSettings.tsx
  js/packages/components/main/Home.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/shared-components/SettingsButtons.tsx
Labels: enhancement

#2957 feat: custom dropdown picker
  .github/workflows/ios.yml
  js/Makefile
  js/ios/Podfile.lock
  js/package.json
  js/packages/components/settings/DevTools.tsx
  js/packages/components/settings/Mode.tsx
  js/packages/components/shared-components/DropDownPicker.tsx
  js/yarn.lock
Labels: enhancement

#2963 chore: avoid false-positive test failures
  go/internal/bertylinks/links_test.go
Labels: chore

#2967 chore: new Crowdin updates
  js/packages/berty-i18n/locale/af-ZA/messages.json
  js/packages/berty-i18n/locale/ar-SA/messages.json
  js/packages/berty-i18n/locale/bg-BG/messages.json
  js/packages/berty-i18n/locale/ca-ES/messages.json
  js/packages/berty-i18n/locale/cs-CZ/messages.json
  js/packages/berty-i18n/locale/da-DK/messages.json
  js/packages/berty-i18n/locale/de-DE/messages.json
  js/packages/berty-i18n/locale/el-GR/messages.json
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/berty-i18n/locale/es-ES/messages.json
  js/packages/berty-i18n/locale/fi-FI/messages.json
  js/packages/berty-i18n/locale/fr-FR/messages.json
  js/packages/berty-i18n/locale/he-IL/messages.json
  js/packages/berty-i18n/locale/hu-HU/messages.json
  js/packages/berty-i18n/locale/id-ID/messages.json
  js/packages/berty-i18n/locale/it-IT/messages.json
  js/packages/berty-i18n/locale/ja-JP/messages.json
  js/packages/berty-i18n/locale/ko-KR/messages.json
  js/packages/berty-i18n/locale/nl-NL/messages.json
  js/packages/berty-i18n/locale/no-NO/messages.json
  js/packages/berty-i18n/locale/pl-PL/messages.json
  js/packages/berty-i18n/locale/pt-BR/messages.json
  js/packages/berty-i18n/locale/pt-PT/messages.json
  js/packages/berty-i18n/locale/ro-RO/messages.json
  js/packages/berty-i18n/locale/ru-RU/messages.json
  js/packages/berty-i18n/locale/sl-SI/messages.json
  js/packages/berty-i18n/locale/sr-Cyrl/messages.json
  js/packages/berty-i18n/locale/sv-SE/messages.json
  js/packages/berty-i18n/locale/tr-TR/messages.json
  js/packages/berty-i18n/locale/uk-UA/messages.json
  js/packages/berty-i18n/locale/vi-VN/messages.json
  js/packages/berty-i18n/locale/zh-CN/messages.json
  js/packages/berty-i18n/locale/zh-TW/messages.json
Labels: chore

#2968 feat: minor ui updates
  js/packages/components/chat/MultiMemberSettings.tsx
  js/packages/components/chat/file-uploads/AddFileMenu.tsx
  js/packages/components/chat/file-uploads/GallerySection.tsx
  js/packages/components/chat/message/AudioMessage.tsx
  js/packages/components/chat/message/PictureMessage.tsx
  js/packages/components/chat/message/UserMessage.tsx
  js/packages/components/main/Home.tsx
Labels: enhancement

#2950 fix: improve grpc bridge errors
  api/bertyaccount.proto
  api/errcode.proto
  api/messengertypes.proto
  api/messengertypes.yaml
  docs/apis/messengertypes.md
  docs/apis/messengertypes.swagger.json
  docs/gen.sum
  go/gen.sum
  go/internal/grpcutil/lazy_client.go
  go/pkg/bertyaccount/bertyaccount.pb.go
  go/pkg/bertyaccount/service_grpc.go
  go/pkg/bertyaccount/service_test.go
  go/pkg/bertymessenger/api.go
  go/pkg/errcode/errcode.pb.go
  go/pkg/messengertypes/messengertypes.pb.go
  go/pkg/messengertypes/messengertypes.pb.gw.go
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  js/packages/go-bridge/defaults.ts
  js/packages/grpc-bridge/error.ts
  js/packages/grpc-bridge/index.ts
  js/packages/grpc-bridge/rpc/rpc.bridge.ts
  js/packages/grpc-bridge/rpc/rpc.grpcweb.ts
  js/packages/grpc-bridge/rpc/utils.ts
  js/packages/grpc-bridge/types.ts
  js/packages/grpc-bridge/welsh-clients.gen.ts
Labels: bug

#2940 feat: image view swipe out
  js/package.json
  js/packages/components/modals/ImageView.tsx
  js/packages/navigation/stacks.tsx
  js/yarn.lock
Labels: enhancement

#2972 feat: ui fixes
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/components/chat/ContactSettings.tsx
  js/packages/components/chat/ReplicateGroupSettings.tsx
  js/packages/components/main/CreateGroupFinalize.tsx
  js/packages/components/modals/AddThisContact.tsx
  js/packages/components/modals/ManageGroupInvitation.tsx
  js/packages/components/settings/MyBertyId.tsx
  js/packages/components/shared-components/DropDownPicker.tsx
  js/packages/components/shared-components/Request.tsx
  js/packages/components/shared-components/TabBar.tsx
Labels: enhancement

#2945 feat: convert long-running unary endpoints to stream ones, with progress updates
  api/bertyaccount.proto
  api/protocoltypes.proto
  docs/apis/protocoltypes.md
  docs/gen.sum
  go.mod
  go.sum
  go/cmd/berty-integration/main.go
  go/cmd/berty/main.go
  go/framework/bertybridge/.gitignore
  go/gen.sum
  go/internal/initutil/manager.go
  go/internal/initutil/manager_test.go
  go/pkg/bertyaccount/bertyaccount.pb.go
  go/pkg/bertyaccount/blackbox_test.go
  go/pkg/bertyaccount/service.go
  go/pkg/bertyaccount/service_account.go
  go/pkg/errcode/error.go
  go/pkg/protocoltypes/protocoltypes.pb.go
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  js/packages/grpc-bridge/welsh-clients.gen.ts
  tool/go.sum
Labels: enhancement
