Repository berty/berty, pull requests merged in 2020-05, with the labels that each got.

#1915 chore: Update rdvp boostrap peer addr
  go/internal/config/berty.go
Labels: ✅ Approved

#1908 feat: add the multipeer connectivity transport
  go.mod
  go/cmd/berty/main.go
  go/framework/bertybridge/bridge_demo.go
  go/internal/config/berty.go
  go/internal/multipeer-connectivity-transport/addr.go
  go/internal/multipeer-connectivity-transport/conn.go
  go/internal/multipeer-connectivity-transport/connmgr.go
  go/internal/multipeer-connectivity-transport/discovery.go
  go/internal/multipeer-connectivity-transport/driver/bridge.go
  go/internal/multipeer-connectivity-transport/driver/mc-driver/MCManager.h
  go/internal/multipeer-connectivity-transport/driver/mc-driver/MCManager.m
  go/internal/multipeer-connectivity-transport/driver/mc-driver/cgo_bridge.go
  go/internal/multipeer-connectivity-transport/driver/mc-driver/mc-driver.h
  go/internal/multipeer-connectivity-transport/driver/mc-driver/mc-driver.m
  go/internal/multipeer-connectivity-transport/driver/other_bridge.go
  go/internal/multipeer-connectivity-transport/init.go
  go/internal/multipeer-connectivity-transport/listener.go
  go/internal/multipeer-connectivity-transport/multiaddr/init.go
  go/internal/multipeer-connectivity-transport/multiaddr/multiaddr.go
  go/internal/multipeer-connectivity-transport/multiaddr/pattern.go
  go/internal/multipeer-connectivity-transport/multiaddr/transcoder.go
  go/internal/multipeer-connectivity-transport/transport.go
  js/packages/berty-app/ios/Berty.xcodeproj/project.pbxproj
Labels: 🔍 Ready for Review

#1924 fix: typo in README s/concensus/consensus/
  README.md
Labels: ✅ Approved

#1929 fix: wrapping in memory datastore with a lock
  go/cmd/berty/main.go
Labels: ✅ Approved

#1925 fix(chat): add berty logo onboarding
  js/packages/berty-app/ios/Podfile.lock
  js/packages/berty-storybook/Onboarding.tsx
  js/packages/berty-storybook/berty_gradient_square.svg
Labels: ✅ Approved

#1927 fix(chat): fix swipe down keyboard on messageList
  js/packages/berty-storybook/chat/Chat.tsx
Labels: ✅ Approved

#1926 fix(chat): load spinner style when load app
  js/packages/hooks/Chat.tsx
Labels: ✅ Approved

#1931 fix(chat): delete shared props
  js/packages/berty-storybook/settings/MyBertyId.tsx
  js/packages/berty-storybook/shared-props/User.tsx
Labels: ✅ Approved

#1932 fix(chat): fix unused variables
  js/packages/berty-storybook/chat/Chat.tsx
  js/packages/berty-storybook/chat/shared-components/Chat.tsx
  js/packages/berty-storybook/chat/shared-components/Message.tsx
  js/packages/berty-storybook/main/ListModal.tsx
  js/packages/berty-storybook/main/Scan.tsx
  js/packages/berty-storybook/settings/AboutBerty.tsx
  js/packages/berty-storybook/settings/AppUpdates.tsx
  js/packages/berty-storybook/settings/BlockedContacts.tsx
  js/packages/berty-storybook/settings/EditProfile.tsx
  js/packages/berty-storybook/settings/Home.tsx
  js/packages/berty-storybook/shared-components/CircleAvatar.tsx
  js/packages/berty-storybook/shared-components/Footer.tsx
  js/packages/berty-storybook/shared-components/ProceduralCircleAvatar.tsx
  js/packages/berty-storybook/shared-components/Request.tsx
  js/packages/berty-storybook/shared-components/SDTSModalComponent.tsx
Labels: ✅ Approved

#1937 fix(chat): icon empty contact request
  js/packages/berty-storybook/main/ListModal.tsx
  js/packages/berty-storybook/main/empty_contact.svg
Labels: ✅ Approved

#1945 clean: remove bertydemo
  README.md
  api/bertydemo.proto
  bazel.make
  docs/gen.sum
  go/cmd/berty/main.go
  go/framework/bertybridge/bridge_demo.go
  go/framework/bertybridge/bridge_test.go
  go/gen.sum
  go/pkg/bertydemo/bertydemo.pb.go
  go/pkg/bertydemo/client.go
  go/pkg/bertydemo/doc.go
  go/pkg/bertydemo/service.go
  go/pkg/bertydemo/service_test.go
  go/pkg/bertydemo/testing_test.go
  js/packages/api/Makefile
  js/packages/api/index.gen.js
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/berty-app/Makefile
  js/packages/berty-app/ios/Podfile.lock
  js/packages/codegen/Makefile
  js/packages/codegen/index.gen.js
  js/packages/go-bridge/android/src/main/java/tech/berty/gobridge/GoBridgeModule.java
  js/packages/go-bridge/ios/GoBridge.m
  js/packages/go-bridge/ios/GoBridge.swift
  js/packages/grpc-bridge/Makefile
  js/packages/grpc-bridge/cli.ts
  js/packages/grpc-bridge/index.ts
  js/packages/grpc-bridge/mock.ts
  js/packages/grpc-bridge/protocol/cli.ts
  js/packages/grpc-bridge/protocol/handler.gen.ts
  js/packages/grpc-bridge/protocol/handler.gen.ts.hbs
  js/packages/grpc-bridge/protocol/handler.ts
  js/packages/grpc-bridge/protocol/index.ts
Labels: ✅ Approved

#1938 feat(chat): add modal on delete account
  js/packages/berty-navigation/index.tsx
  js/packages/berty-storybook/modals/DeleteAccount.tsx
  js/packages/berty-storybook/modals/SendContactRequest.tsx
  js/packages/berty-storybook/modals/index.ts
  js/packages/berty-storybook/settings/Mode.tsx
  js/packages/store/chat/account.ts
Labels: ✅ Approved

#1949 fix(chat): refactor hooks package
  js/packages/hooks/Chat.tsx
  js/packages/hooks/account.ts
  js/packages/hooks/contact.ts
  js/packages/hooks/conversation.ts
  js/packages/hooks/message.ts
  js/packages/hooks/provider.tsx
Labels: ✅ Approved

#1948 fix(chat): refactor styles package
  js/package.json
  js/packages/berty-storybook/main/GroupRequest.tsx
  js/packages/berty-storybook/main/Search.tsx
  js/packages/berty-storybook/shared-components/Header.tsx
  js/packages/codegen/helpers/case.js
  js/packages/codegen/helpers/hack.js
  js/packages/codegen/helpers/json-prettify.js
  js/packages/codegen/helpers/protobuf.js
  js/packages/codegen/helpers/template.js
  js/packages/grpc-bridge/grpc-web-websocket-transport.ts
  js/packages/store/chat/account.ts
  js/packages/store/chat/contact.ts
  js/packages/store/chat/conversation.ts
  js/packages/store/chat/member.ts
  js/packages/store/chat/message.ts
  js/packages/store/protocol/client.ts
  js/packages/store/settings/main.ts
  js/packages/store/utils.ts
  js/packages/styles/constant.ts
  js/packages/styles/hook.tsx
  js/packages/styles/index.tsx
  js/packages/styles/map-border.ts
  js/packages/styles/map-colors.ts
  js/packages/styles/map-declaration.ts
  js/packages/styles/map-sides.ts
  js/packages/styles/types.ts
  js/yarn.lock
Labels: 🔍 Ready for Review

#1944 clean(chat): remove old store
  api/js-internal/bertychat.proto
  api/js-internal/chatmodel.proto
  js/Makefile
  js/packages/api/Makefile
  js/packages/api/index.gen.js
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/berty-app/App.tsx
  js/packages/berty-navigation/hook.tsx
  js/packages/berty-navigation/stacks.tsx
  js/packages/berty-navigation/types.ts
  js/packages/berty-store/Makefile
  js/packages/berty-store/README.md
  js/packages/berty-store/faker.tsx
  js/packages/berty-store/helpers.ts
  js/packages/berty-store/index.ts
  js/packages/berty-store/package.json
  js/packages/berty-store/swr.gen.tsx
  js/packages/berty-store/swr.gen.tsx.hbs
  js/packages/berty-storybook/chat/index.ts
  js/packages/berty-storybook/faker.gen.tsx
  js/packages/berty-storybook/main/List.tsx
  js/packages/berty-storybook/main/index.ts
  js/packages/berty-storybook/settings/Home.tsx
  js/packages/berty-storybook/shared-components/CircleAvatar.tsx
  js/packages/berty-storybook/shared-components/ProceduralCircleAvatar.tsx
  js/packages/codegen/Makefile
  js/packages/codegen/index.gen.js
  js/packages/hooks/conversation.ts
  js/packages/store/chat/account.ts
  js/packages/store/chat/conversation.ts
  js/yarn.lock
Labels: chat, 🔍 Ready for Review

#1941 feat: bootstrap open-telemetry
  go.mod
  go.sum
  go/cmd/berty/main.go
  go/cmd/berty/mini/main.go
  go/internal/tracer/tracer.go
  go/pkg/bertyprotocol/testing.go
Labels: help wanted, ✅ Approved, 🔍 Ready for Review

#1961 chore: bump protoc
  .buildkite/pipeline.yml
  bazel.make
  docs/Makefile
  docs/gen.sum
  docs/protocol/api.md
  go/Makefile
  go/gen.sum
  tool/docker-protoc/Dockerfile
  tool/docker-protoc/Makefile
Labels: 🔍 Ready for Review

#1952 fix(chat): i18n warnings
  js/packages/berty-i18n/index.ts
Labels: 🔍 Ready for Review

#1950 Rework app grpc
  .buildkite/pipeline.yml
  .gitattributes
  js/.eslintignore
  js/Makefile
  js/gen.make
  js/gen.sum
  js/package.json
  js/packages/berty-app/App.tsx
  js/packages/go-bridge/GoBridge.native.ts
  js/packages/go-bridge/GoBridge.ts
  js/packages/go-bridge/index.js
  js/packages/go-bridge/index.ts
  js/packages/go-bridge/package.json
  js/packages/go-bridge/types.ts
  js/packages/grpc-bridge/Makefile
  js/packages/grpc-bridge/bridge.ts
  js/packages/grpc-bridge/index.ts
  js/packages/grpc-bridge/orbitdb/client.gen.ts
  js/packages/grpc-bridge/orbitdb/index.ts
  js/packages/grpc-bridge/orbitdb/native.android.ts
  js/packages/grpc-bridge/orbitdb/native.ios.ts
  js/packages/grpc-bridge/orbitdb/native.ts
  js/packages/grpc-bridge/package.json
  js/packages/grpc-bridge/protocol/client.gen.ts.hbs
  js/packages/grpc-bridge/protocol/index.ts
  js/packages/store/chat/account.ts
  js/packages/store/chat/index.ts
  js/packages/store/chat/message.ts
  js/packages/store/package.json
  js/packages/store/protocol/ProtocolServiceClient.gen.ts
  js/packages/store/protocol/ProtocolServiceClient.gen.ts.hbs
  js/packages/store/protocol/ProtocolServiceSagaClient.gen.ts
  js/packages/store/protocol/ProtocolServiceSagaClient.gen.ts.hbs
  js/packages/store/protocol/client.ts
  js/packages/store/protocol/grpc-web-gen/bertyprotocol_pb.d.ts
  js/packages/store/protocol/grpc-web-gen/bertyprotocol_pb.js
  js/packages/store/protocol/grpc-web-gen/bertyprotocol_pb_service.d.ts
  js/packages/store/protocol/grpc-web-gen/bertyprotocol_pb_service.js
  js/packages/store/protocol/grpc-web-gen/bertytypes_pb.d.ts
  js/packages/store/protocol/grpc-web-gen/bertytypes_pb.js
  js/packages/store/protocol/grpc-web-gen/bertytypes_pb_service.d.ts
  js/packages/store/protocol/grpc-web-gen/bertytypes_pb_service.js
  js/packages/store/protocol/grpc-web-gen/github.com/gogo/protobuf/gogoproto/gogo_pb.d.ts
  js/packages/store/protocol/grpc-web-gen/github.com/gogo/protobuf/gogoproto/gogo_pb.js
  js/packages/store/protocol/grpc-web-gen/github.com/gogo/protobuf/gogoproto/gogo_pb_service.d.ts
  js/packages/store/protocol/grpc-web-gen/github.com/gogo/protobuf/gogoproto/gogo_pb_service.js
  js/packages/store/protocol/useExternalBridge.native.ts
  js/packages/store/protocol/useExternalBridge.ts
  js/packages/store/sagaUtils.ts
  js/packages/web-dev-app/src/App.tsx
  js/yarn.lock
Labels: build, chat, ✅ Approved

#1966 fix(build/js): run gen with protoc:23 locally
  js/gen.make
  js/gen.sum
Labels: 🔍 Ready for Review

#1967 fix(chat): error invalid scan
  js/packages/components/modals/InvalidScan.tsx
Labels: ✅ Approved

#1962 fix(chat): police onboarding darkmode
  js/packages/components/Onboarding.tsx
Labels: ✅ Approved

#1939 initial contact request manager
  go.mod
  go.sum
  go/cmd/berty/main.go
  go/cmd/berty/mini/main.go
  go/framework/bertybridge/bridge_protocol.go
  go/framework/bertybridge/testing_test.go
  go/internal/handshake/handshake_test.go
  go/internal/handshake/request.go
  go/internal/handshake/response.go
  go/internal/ipfsutil/api.go
  go/internal/ipfsutil/extended_core_api.go
  go/internal/ipfsutil/testing.go
  go/internal/tinder/driver_multi.go
  go/pkg/bertyprotocol/api_contactrequest.go
  go/pkg/bertyprotocol/api_event.go
  go/pkg/bertyprotocol/contact_request_manager.go
  go/pkg/bertyprotocol/contact_request_manager_test.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertyprotocol/store_metadata.go
  go/pkg/bertyprotocol/store_metadata_test.go
  go/pkg/bertyprotocol/testing.go
  go/pkg/bertyprotocol/tinder_swiper.go
  go/pkg/bertyprotocol/tinder_swiper_test.go
  go/pkg/bertytypes/contact.go
Labels: 🔍 Ready for Review

#1963 feat(debug): inspect stores in mini + corresponding grpc calls
  api/bertyprotocol.proto
  api/bertytypes.proto
  docs/gen.sum
  docs/protocol/api.md
  go/cmd/berty/mini/view_group_outgoing.go
  go/gen.sum
  go/pkg/bertyprotocol/api_debug.go
  go/pkg/bertyprotocol/bertyprotocol.pb.go
  go/pkg/bertytypes/bertytypes.pb.go
  js/gen.sum
  js/packages/api/index.gen.js
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/codegen/index.gen.js
  js/packages/components/faker.gen.tsx
  js/packages/store/protocol/ProtocolServiceClient.gen.ts
  js/packages/store/protocol/client.gen.ts
  js/packages/store/protocol/grpc-web-gen/bertyprotocol_pb_service.d.ts
  js/packages/store/protocol/grpc-web-gen/bertyprotocol_pb_service.js
  js/packages/store/protocol/grpc-web-gen/bertytypes_pb.d.ts
  js/packages/store/protocol/grpc-web-gen/bertytypes_pb.js
Labels: ✅ Approved

#1971 feat: add an helper to share invite links on a dedicated dev discord channel
  go.mod
  go.sum
  go/cmd/berty/main.go
  go/internal/discordlog/discord.go
  go/internal/discordlog/discord_test.go
  go/internal/discordlog/doc.go
  go/pkg/bertyprotocol/orbitdb.go
Labels: 🔍 Ready for Review

#1973 chore: hardcode dep version protobuf@v1.3.2
  go.mod
  go.sum
Labels: 🔍 Ready for Review

#1975 chore: bump bazel to 3.1.0
  .buildkite/pipeline.yml
  go/config.bzl
  go/repositories.bzl
  go/third_party/io_bazel_rules_go/PR-2181-rebase-0.23.1.patch
  js/packages/go-bridge/go.mod
  tool/docker-bazel/Dockerfile
  tool/docker-bazel/Makefile
  tool/docker-build-go/Dockerfile
  tool/docker-build-go/Makefile
Labels: ✅ Approved

#1974 docs: update readme with commands to use real protocol bridge
  js/README.md
Labels: 🔍 Ready for Review

#1976 fix(ios): fix lock problem with badger
  go/framework/bertybridge/bridge_protocol.go
Labels: ✅ Approved

#1979 chore(quote): Freedom and Liberty is like air...
  go/pkg/banner/quote.go
Labels: 🔍 Ready for Review

#1981 chore: add 'berty banner --random' option
  go/cmd/berty/main.go
Labels: 🔍 Ready for Review

#1980 chore(chat): improve user-facing language (spelling, grammar...)
  js/packages/components/main/CreateGroup.tsx
  js/packages/components/modals/AddThisContact.tsx
  js/packages/components/modals/DeleteAccount.tsx
  js/packages/components/modals/SendContactRequest.tsx
Labels: ✅ Approved

#1982 feat: new bertychat service
  api/bertychat.proto
  docs/Makefile
  docs/chat/api.md
  docs/gen.sum
  go/cmd/berty/main.go
  go/framework/bertybridge/bridge_protocol.go
  go/gen.sum
  go/internal/grpcutil/pipe_listener.go
  go/pkg/bertychat/api.go
  go/pkg/bertychat/api_test.go
  go/pkg/bertychat/bertychat.pb.go
  go/pkg/bertychat/doc.go
  go/pkg/bertychat/service.go
  go/pkg/bertychat/testing.go
  go/pkg/bertyprotocol/client.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertyprotocol/store_metadata_index.go
  go/pkg/bertyprotocol/store_metadata_test.go
  go/pkg/bertyprotocol/testing.go
  go/pkg/bertyprotocol/testing_test.go
  js/packages/api/Makefile
  js/packages/api/index.gen.js
  js/packages/api/index.pb.d.ts
  js/packages/api/index.pb.js
  js/packages/codegen/Makefile
  js/packages/codegen/index.gen.js
  js/packages/components/faker.gen.tsx
Labels: ✅ Approved
