Repository berty/berty, pull requests merged in 2021-11, with the labels that each got.

#3597 feat: flag indicating if a push message was already received
  api/messengertypes.proto
  api/protocoltypes.proto
  api/pushtypes.proto
  docs/apis/messengertypes.md
  docs/apis/messengertypes.swagger.json
  docs/apis/protocoltypes.md
  docs/apis/protocoltypes.swagger.json
  docs/gen.sum
  go/gen.sum
  go/internal/cryptoutil/keystore_message.go
  go/internal/messengerpayloads/handlers.go
  go/pkg/bertypush/push.go
  go/pkg/bertypush/push_handler.go
  go/pkg/bertypush/push_opener.go
  go/pkg/bertypush/push_test.go
  go/pkg/bertyreplication/services_replication_test.go
  go/pkg/messengertypes/messengertypes.pb.go
  go/pkg/protocoltypes/protocoltypes.pb.go
  go/pkg/pushtypes/pushtypes.pb.go
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
Labels: 🔍 Ready for Review, enhancement

#3619 fix: update testbot addresses
  config/config.gen.json
  config/config.yml
  go/cmd/testbot/README.md
  go/internal/config/config.gen.go
  go/pkg/bertyaccount/blackbox_test.go
  js/packages/config/global.gen.js
Labels: bug, 🔍 Ready for Review

#3625 fix: sigabrt on macos monterey
  go/Makefile
  go/gen.sum
Labels: bug, ✅ Approved

#3626 feat: secure grpc connections
  go/internal/initutil/manager.go
  go/internal/initutil/node.go
  go/pkg/bertyprotocol/api_push.go
  go/pkg/bertyprotocol/api_replication.go
  go/pkg/bertyprotocol/service.go
Labels: ✅ Approved, enhancement

#3627 fix: app crash in grpc streams
  js/packages/grpc-bridge/service.ts
Labels: bug, 🔍 Ready for Review

#3600 RNFS security
  js/android/build.gradle
  js/global.d.ts
  js/package.json
  js/packages/components/chat/SharedMedias.tsx
  js/packages/components/chat/file-uploads/GallerySection.tsx
  js/packages/components/chat/message/FileMessage.tsx
  js/packages/components/modals/ForwardToBertyContactModal.tsx
  js/packages/store/utils.ts
  js/yarn.lock
Labels: 🔍 Ready for Review

#3630 fix: ignore fake cids while finding lazy-loading ref
  js/packages/components/chat/MessageList.tsx
Labels: bug, 🔍 Ready for Review

#3269 feat: encrypted orbitdb links
  .github/workflows/go.yml
  api/accounttypes.proto
  api/bertyreplication.proto
  api/messengertypes.proto
  api/protocoltypes.proto
  docs/apis/messengertypes.md
  docs/apis/messengertypes.swagger.json
  docs/apis/protocoltypes.md
  docs/apis/protocoltypes.swagger.json
  docs/gen.sum
  go.mod
  go.sum
  go/Makefile
  go/gen.sum
  go/internal/bertylinks/links.go
  go/internal/bertylinks/links_test.go
  go/internal/cryptoutil/attachment_crypto.go
  go/internal/cryptoutil/group.go
  go/internal/cryptoutil/keystore_message_utils.go
  go/internal/tinder/service_test.go
  go/pkg/accounttypes/accounttypes.pb.go
  go/pkg/bertyprotocol/account_export.go
  go/pkg/bertyprotocol/api_replication.go
  go/pkg/bertyprotocol/events.go
  go/pkg/bertyprotocol/group.go
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/bertyprotocol/store_options.go
  go/pkg/bertypush/push_handler.go
  go/pkg/bertyreplication/services_replication.go
  go/pkg/bertyreplication/services_replication_test.go
  go/pkg/messengertypes/messengertypes.pb.go
  go/pkg/protocoltypes/group.go
  go/pkg/protocoltypes/protocoltypes.pb.go
  go/pkg/replicationtypes/bertyreplication.pb.go
  go/pkg/replicationtypes/models.go
  js/Makefile
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  tool/go.sum
Labels: ✅ Approved, enhancement

#3646 fix: remove InsecureSkipVerify
  go/internal/tinder/service_test.go
  go/pkg/bertyprotocol/api_push.go
  go/pkg/bertyprotocol/api_replication.go
Labels: bug, 🔍 Ready for Review

#3652 Enable type-checking for js/packages/store
  js/Makefile
  js/fix-types.sh
  js/gen.sum
  js/global.d.ts
  js/package.json
  js/packages/go-bridge/logger.ts
  js/packages/grpc-bridge/gen-clients.js
  js/packages/grpc-bridge/welsh-clients.gen.ts
  js/packages/navigation/hook.ts
  js/packages/store/effectableCallbacks.ts
  js/packages/store/hooks.ts
  js/packages/store/providerCallbacks.ts
  js/packages/styles/map-declaration.ts
  js/tsconfig.json
  js/yarn.lock
Labels: 🔍 Ready for Review

#3656 fix: replace fix-types bash script with js
  js/fix-types.js
  js/fix-types.sh
  js/package.json
Labels: bug, 🔍 Ready for Review

#3660 fix(js): undefined navigation on group creation
  js/packages/components/chat/MultiMember.tsx
Labels: bug, 🔍 Ready for Review

#3651 fix: microphone button on Android
  js/android/app/src/main/java/tech/berty/android/MainActivity.java
Labels: bug

#3662 fix: bump document picker and fix usage
  js/ios/Podfile.lock
  js/package.json
  js/packages/components/chat/file-uploads/AddFileMenu.tsx
  js/packages/components/main/home/MultiAccount.tsx
  js/packages/components/onboarding/CreateAccount.tsx
  js/packages/components/pickerUtils.ts
  js/packages/components/settings/ThemeEditor.tsx
  js/yarn.lock
Labels: bug, 🔍 Ready for Review

#3663 fix(js): group creation navigation misuse
  js/packages/components/main/CreateGroupAddMembers.tsx
  js/packages/components/main/CreateGroupFooter.tsx
Labels: bug, 🔍 Ready for Review

#3666 fix(js): StreamInProgress usage
  js/packages/components/gates.tsx
  js/packages/store/effectableCallbacks.ts
  js/packages/store/providerCallbacks.ts
  js/packages/store/providerEffects.ts
  js/packages/store/reducer/uiReducer.ts
  js/packages/store/types.ts
  js/packages/store/utils.ts
Labels: bug, 🔍 Ready for Review

#3668 chore: remove spam warnings at boot
  js/packages/store/context.ts
  js/packages/store/provider.tsx
  js/packages/store/reducer/index.ts
Labels: 🔍 Ready for Review, chore

#3669 chore: bump babel and jest deps
  js/package.json
  js/yarn.lock
Labels: 🔍 Ready for Review, chore

#3670 chore: bump several js deps
  js/__mocks__/react-native-image-crop-picker.js
  js/ios/Podfile.lock
  js/package.json
  js/yarn.lock
Labels: 🔍 Ready for Review, chore

#3676 chore(js): bump some react-native deps
  js/global.d.ts
  js/ios/Gemfile
  js/ios/Gemfile.lock
  js/ios/Podfile.lock
  js/package.json
  js/packages/grpc-bridge/middleware/logs/logs.js
  js/yarn.lock
Labels: 🔍 Ready for Review, chore

#3675 chore: bump docker-protoc deps
  .github/workflows/protobuf.yml
  docs/Makefile
  docs/gen.sum
  go/Makefile
  go/cmd/berty-integration/main.go
  go/cmd/berty-integration/main_unsupported.go
  go/cmd/berty/gui.go
  go/cmd/berty/noopgui.go
  go/framework/bertybridge/config_android.go
  go/gen.sum
  go/internal/androidnearby/bridge_android.go
  go/internal/androidnearby/bridge_unsupported.go
  go/internal/ble-driver/bridge_android.go
  go/internal/ble-driver/bridge_darwin.go
  go/internal/ble-driver/bridge_unsupported.go
  go/internal/initutil/tor_embedded.go
  go/internal/initutil/tor_unembedded.go
  go/internal/multipeer-connectivity-driver/bridge_darwin.go
  go/internal/multipeer-connectivity-driver/bridge_unsupported.go
  go/internal/multipeer-connectivity-driver/driver/cgo_bridge.go
  go/internal/sysutil/sysutil_unix.go
  go/internal/sysutil/sysutil_unsupported.go
  go/internal/testutil/skip_norace.go
  go/internal/testutil/skip_race.go
  go/internal/tools/tools.go
  go/internal/tools/tools_untool.go
  go/pkg/assets/pkged.go
  go/pkg/tempdir/tempdir_android.go
  go/pkg/tempdir/tempdir_darwin.go
  go/pkg/tempdir/tempdir_others.go
  go/pkg/username/android.go
  go/pkg/username/ios.go
  go/pkg/username/others.go
  tool/docker-protoc/Dockerfile
  tool/docker-protoc/Makefile
Labels: 🔍 Ready for Review, chore

#3664 chore: bump typescript to 4.4.4
  js/package.json
  js/yarn.lock
Labels: 🔍 Ready for Review, chore

#3680 chore: bump react-native deps
  js/ios/Podfile.lock
  js/package.json
  js/yarn.lock
Labels: 🔍 Ready for Review, chore

#3677 Audio message
  js/packages/components/chat/message/AudioMessage.tsx
  js/packages/components/chat/message/UserMessage.tsx
Labels: ✅ Approved

#3687 chore: rename Unstable to Flappy for testing utilities
  .github/workflows/go.yml
  go/Makefile
  go/gen.sum
  go/internal/testutil/skip.go
  go/pkg/bertybot/bot_test.go
  go/pkg/bertymessenger/service_test.go
  go/pkg/bertyprotocol/account_export_test.go
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/bertyprotocol/store_message_test.go
  go/pkg/bertyprotocol/store_metadata_test.go
Labels: 🔍 Ready for Review, chore

#3690 chore: update crowdin config
  .crowdin.yml
Labels: 🔍 Ready for Review, chore

#3691 New Crowdin updates
  .github/workflows/codeql-analysis.yml
  js/packages/berty-i18n/locale/de-DE/messages.json
  js/packages/berty-i18n/locale/es-ES/messages.json
  js/packages/berty-i18n/locale/fr-FR/messages.json
  js/packages/berty-i18n/locale/hu-HU/messages.json
  js/packages/berty-i18n/locale/it-IT/messages.json
  js/packages/berty-i18n/locale/nl-NL/messages.json
  js/packages/berty-i18n/locale/pl-PL/messages.json
  js/packages/berty-i18n/locale/ru-RU/messages.json
  js/packages/berty-i18n/locale/sv-SE/messages.json
  js/packages/berty-i18n/locale/tr-TR/messages.json
  js/packages/berty-i18n/locale/zh-CN/messages.json
  js/packages/berty-i18n/locale/zh-TW/messages.json
Labels: 🔍 Ready for Review

#3686 fix: notification badge below the avatar
  js/packages/components/avatars.tsx
  js/packages/components/main/home/Header.tsx
Labels: bug, ✅ Approved

#3692 fix: berty services
  go/pkg/bertyprotocol/api_push.go
  go/pkg/bertyprotocol/api_replication.go
  go/pkg/bertyprotocol/api_services_auth.go
Labels: bug, ✅ Approved

#3608 chore(ci): test on mac
  .github/workflows/go.yml
Labels: 🔍 Ready for Review, chore

#3695 chore: use secrets to bump cache version suffix
  .github/workflows/android.yml
  .github/workflows/go.yml
  .github/workflows/integration.yml
  .github/workflows/ios.yml
  .github/workflows/js.yml
  .github/workflows/protobuf.yml
  .github/workflows/release.yml
Labels: 🔍 Ready for Review, chore

#3698 fix: disalbe `embed_swift` for Notification Service
  js/ios/berty.yaml
Labels: bug, ✅ Approved

#3697 chore: new Crowdin updates
  js/packages/berty-i18n/locale/fr-FR/messages.json
  js/packages/berty-i18n/locale/zh-CN/messages.json
Labels: ✅ Approved, chore

#3693 chore: update betabot and testbot addresses
  .github/workflows/ios.yml
  config/config.gen.json
  config/config.yml
  go/cmd/betabot/README.md
  go/cmd/testbot/README.md
  go/internal/config/config.gen.go
  js/packages/config/global.gen.js
Labels: 🔍 Ready for Review, chore

#3699 fix: play/pause player + hide player in chat views
  js/packages/components/chat/message/AudioMessage.tsx
  js/packages/components/shared-components/StickyMusicPlayer.tsx
Labels: bug, ✅ Approved

#3701 fix: some silent log in debug, staff, yolo scheme
  go/framework/bertybridge/driver_logger.go
  go/pkg/bertymessenger/service.go
  js/ios/Berty/Sources/Bridge/GoBridge.swift
  js/ios/Berty/Sources/Bridge/LoggerDriver.swift
  js/ios/berty.yaml
Labels: bug, ✅ Approved

#3702 fix: remove avatar opacity
  js/packages/components/avatars.tsx
  js/packages/components/settings/EditProfile.tsx
Labels: bug, 🔍 Ready for Review

#3703 feat: removed group pk from push relay accessible information
  api/protocoltypes.proto
  api/pushtypes.proto
  docs/apis/protocoltypes.md
  docs/gen.sum
  go/gen.sum
  go/internal/cryptoutil/group.go
  go/internal/cryptoutil/keystore_message.go
  go/pkg/bertyprotocol/store_message.go
  go/pkg/bertypush/push_handler.go
  go/pkg/protocoltypes/protocoltypes.pb.go
  go/pkg/pushtypes/pushtypes.pb.go
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
Labels: 🔍 Ready for Review, enhancement

#3708 fix: revert: "feat: removed group pk from push relay accessible information"
  api/protocoltypes.proto
  api/pushtypes.proto
  docs/apis/protocoltypes.md
  docs/gen.sum
  go/gen.sum
  go/internal/cryptoutil/group.go
  go/internal/cryptoutil/keystore_message.go
  go/pkg/bertyprotocol/store_message.go
  go/pkg/bertypush/push_handler.go
  go/pkg/protocoltypes/protocoltypes.pb.go
  go/pkg/pushtypes/pushtypes.pb.go
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
Labels: bug, 🔍 Ready for Review

#3647 feat: rotate identities over time
  go/internal/initutil/ipfs.go
  go/internal/initutil/manager.go
  go/internal/initutil/node.go
  go/internal/initutil/orbitdb.go
  go/internal/ipfsutil/repo.go
  go/internal/rendezvous/rendezvous.go
  go/internal/rendezvous/rendezvous_test.go
  go/pkg/bertyprotocol/orbitdb.go
  go/pkg/bertyprotocol/orbitdb_topic.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertyprotocol/store_metadata_test.go
  go/pkg/bertyprotocol/testing.go
  go/pkg/bertyprotocol/tinder_swiper.go
  go/pkg/bertyprotocol/tinder_swiper_test.go
Labels: ✅ Approved, enhancement

#3706 fix: create redux store + move adding member from components to redux
  js/package.json
  js/packages/components/chat/MultiMembersSettingsAddMembers.tsx
  js/packages/components/main/CreateGroupAddMembers.tsx
  js/packages/components/main/CreateGroupFinalize.tsx
  js/packages/components/shared-components/ContactPicker.tsx
  js/packages/messenger-app/App.tsx
  js/packages/navigation/stacks.tsx
  js/packages/redux/reducers/newGroup.reducer.ts
  js/packages/redux/store.ts
  js/yarn.lock
Labels: bug, 🔍 Ready for Review

#3700 fix(ci): re-enable checking Podfile.lock sync
  .github/workflows/ios.yml
  js/ios/.gitignore
  js/packages/scripts/extract-pods-hashes.js
  js/packages/scripts/restore-pods-hashes.js
Labels: bug, ✅ Approved

#3709 feat: removed group pk from push relay accessible information
  .github/workflows/go.yml
  api/protocoltypes.proto
  api/pushtypes.proto
  docs/apis/protocoltypes.md
  docs/gen.sum
  go/gen.sum
  go/internal/cryptoutil/group.go
  go/internal/cryptoutil/keystore_message.go
  go/internal/rendezvous/rendezvous_test.go
  go/pkg/bertyprotocol/store_message.go
  go/pkg/bertypush/push_handler.go
  go/pkg/protocoltypes/protocoltypes.pb.go
  go/pkg/pushtypes/pushtypes.pb.go
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
Labels: 🔍 Ready for Review, enhancement

#3635 feat: front logic push notif
  go/internal/bertylinks/links.go
  go/internal/messengerpayloads/handlers.go
  go/pkg/bertymessenger/service_post_actions.go
  go/pkg/messengertypes/links.go
  js/android/app/src/main/java/tech/berty/notification/NotificationService.java
  js/ios/Berty/AppDelegate.m
  js/ios/NotificationService/NotificationService.swift
  js/ios/Podfile.lock
  js/packages/components/NotificationProvider.tsx
  js/packages/components/chat/common.tsx
  js/packages/components/modals/ManageDeepLink.tsx
  js/packages/components/settings/Home.tsx
  js/packages/messenger-app/App.tsx
  js/packages/navigation/stacks.tsx
  js/packages/store/context.ts
  js/packages/store/provider.tsx
  js/packages/store/providerEffects.ts
  js/packages/store/types.ts
Labels: 🔍 Ready for Review, enhancement

#3719 feat: add crowdin localization for golang
  .crowdin.yml
  go/localization/locales/en-US/localization.json
Labels: ✅ Approved, enhancement

#3717 New Crowdin updates
  js/packages/berty-i18n/locale/el-GR/messages.json
Labels: 🔍 Ready for Review

#3720 New Crowdin updates
  go/localization/locales/af-ZA/localization.json
  go/localization/locales/ar-SA/localization.json
  go/localization/locales/bg-BG/localization.json
  go/localization/locales/ca-ES/localization.json
  go/localization/locales/cs-CZ/localization.json
  go/localization/locales/da-DK/localization.json
  go/localization/locales/de-DE/localization.json
  go/localization/locales/el-GR/localization.json
  go/localization/locales/es-ES/localization.json
  go/localization/locales/et-EE/localization.json
  go/localization/locales/fi-FI/localization.json
  go/localization/locales/fr-FR/localization.json
  go/localization/locales/he-IL/localization.json
  go/localization/locales/hi-IN/localization.json
  go/localization/locales/hu-HU/localization.json
  go/localization/locales/id-ID/localization.json
  go/localization/locales/it-IT/localization.json
  go/localization/locales/ja-JP/localization.json
  go/localization/locales/ka-GE/localization.json
  go/localization/locales/ko-KR/localization.json
  go/localization/locales/my-MM/localization.json
  go/localization/locales/nl-NL/localization.json
  go/localization/locales/no-NO/localization.json
  go/localization/locales/pl-PL/localization.json
  go/localization/locales/pt-BR/localization.json
  go/localization/locales/pt-PT/localization.json
  go/localization/locales/ro-RO/localization.json
  go/localization/locales/ru-RU/localization.json
  go/localization/locales/sl-SI/localization.json
  go/localization/locales/sr-Cyrl/localization.json
  go/localization/locales/sv-SE/localization.json
  go/localization/locales/te-IN/localization.json
  go/localization/locales/tr-TR/localization.json
  go/localization/locales/uk-UA/localization.json
  go/localization/locales/vi-VN/localization.json
  go/localization/locales/zh-CN/localization.json
  go/localization/locales/zh-TW/localization.json
Labels: ✅ Approved

#3724 test: disable periodic prod integration test on the CI
  .github/workflows/integration.yml
Labels: 🔍 Ready for Review, test

#3710 feat: hide keys, payload in logs by default
  go/cmd/berty/daemon.go
  go/cmd/berty/gui/account.go
  go/cmd/berty/mini/view_group.go
  go/framework/bertybridge/driver_notification.go
  go/internal/accountutils/utils.go
  go/internal/bertylinks/links.go
  go/internal/cryptoutil/attachment_crypto.go
  go/internal/cryptoutil/keystore_device.go
  go/internal/cryptoutil/keystore_device_test.go
  go/internal/cryptoutil/keystore_message_utils_test.go
  go/internal/initutil/ipfs.go
  go/internal/initutil/metrics.go
  go/internal/initutil/node.go
  go/internal/initutil/orbitdb.go
  go/internal/ipfsutil/conn_logger.go
  go/internal/ipfsutil/helpers.go
  go/internal/ipfsutil/pubsub_api.go
  go/internal/ipfsutil/pubsub_monitor.go
  go/internal/logutil/private_field.go
  go/internal/messengerdb/db.go
  go/internal/messengerpayloads/handlers.go
  go/internal/notification/manager_desktop.go
  go/internal/notification/manager_logger.go
  go/internal/proximitytransport/conn.go
  go/internal/proximitytransport/mplex.go
  go/internal/proximitytransport/ringBuffer_map.go
  go/internal/proximitytransport/transport.go
  go/internal/tinder/driver_localdiscovery.go
  go/internal/tinder/driver_rdv.go
  go/internal/tinder/notify_network.go
  go/internal/tinder/watchdogs_advertiser.go
  go/internal/tinder/watchdogs_discoverer.go
  go/pkg/bertyaccount/service_account.go
  go/pkg/bertybot/recipes.go
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertymessenger/service_post_actions.go
  go/pkg/bertyprotocol/account_export_test.go
  go/pkg/bertyprotocol/api_group.go
  go/pkg/bertyprotocol/api_push.go
  go/pkg/bertyprotocol/api_replication.go
  go/pkg/bertyprotocol/api_services_auth.go
  go/pkg/bertyprotocol/blackbox_test.go
  go/pkg/bertyprotocol/contact_request_manager.go
  go/pkg/bertyprotocol/group.go
  go/pkg/bertyprotocol/group_context.go
  go/pkg/bertyprotocol/orbitdb.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertyprotocol/store_message.go
  go/pkg/bertyprotocol/store_metadata.go
  go/pkg/bertyprotocol/testing.go
  go/pkg/bertyprotocol/tinder_swiper.go
  go/pkg/bertypush/push_opener.go
  go/pkg/bertypush/push_test.go
  go/pkg/bertypushrelay/services_push.go
  go/pkg/bertypushrelay/services_push_apns.go
Labels: ✅ Approved, enhancement

#3715 feat: add golang i18next support
  .crowdin.yml
  api/accounttypes.proto
  api/pushtypes.proto
  docs/gen.sum
  go.mod
  go/Makefile
  go/framework/bertybridge/bridge.go
  go/framework/bertybridge/config.go
  go/framework/bertybridge/logger.go
  go/framework/bertybridge/push.go
  go/framework/bertypush/logger.go
  go/framework/bertypush/service.go
  go/gen.sum
  go/internal/i18n/catalog.go
  go/internal/i18n/catalog_test.go
  go/internal/i18n/locales_test/en-US/localization.json
  go/internal/i18n/locales_test/fr-FR/localization.json
  go/internal/i18n/translations_i18next.go
  go/localization/localization.go
  go/localization/localization_test.go
  go/pkg/accounttypes/accounttypes.pb.go
  go/pkg/bertyaccount/service.go
  go/pkg/bertyaccount/service_account.go
  go/pkg/bertypush/push_format.go
  go/pkg/pushtypes/pushtypes.pb.go
  js/android/app/src/main/java/tech/berty/gobridge/GoBridgeModule.java
  js/android/app/src/main/java/tech/berty/gobridge/LoggerDriver.java
  js/android/app/src/main/java/tech/berty/notification/NotificationLogger.java
  js/android/app/src/main/java/tech/berty/notification/NotificationService.java
  js/gen.sum
  js/ios/Berty/Sources/Bridge/GoBridge.swift
  js/ios/NotificationService/NotificationService.swift
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
Labels: 🔍 Ready for Review, enhancement, WIP
