Repository berty/berty, pull requests merged in 2021-04, with the labels that each got.

#3220 fix(messenger): pastille ack notification
  go/pkg/bertymessenger/handlers.go
Labels: bug

#3230 feat(messenger): log filters button
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/components/settings/DevTools.tsx
  js/packages/go-bridge/defaults.ts
  js/packages/store/context.ts
  js/packages/store/providerEffects.ts
Labels: enhancement

#3231 chore(bergy): clearer usage description
  go/cmd/berty/gui.go
Labels: chore

#3197 feat: reply in chat
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/service.go
  js/global.d.ts
  js/package.json
  js/packages/components/chat/MessageList.tsx
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/ReplyReactionContext.tsx
  js/packages/components/chat/common.tsx
  js/packages/components/chat/message/Popover.tsx
  js/packages/components/chat/message/UserMessage.tsx
  js/packages/components/chat/message/UserMessageComponents.tsx
  js/packages/components/chat/message/index.tsx
  js/packages/store/providerReducer.ts
  js/yarn.lock
Labels: enhancement

#3224 fix(messenger): bluetooth grey buttons
  js/packages/components/settings/Bluetooth.tsx
  js/packages/components/shared-components/SettingsButtons.tsx
Labels: bug

#3240 chore: new Crowdin updates
  js/packages/berty-i18n/locale/af-ZA/messages.json
  js/packages/berty-i18n/locale/ar-SA/messages.json
  js/packages/berty-i18n/locale/bg-BG/messages.json
  js/packages/berty-i18n/locale/ca-ES/messages.json
  js/packages/berty-i18n/locale/cs-CZ/messages.json
  js/packages/berty-i18n/locale/da-DK/messages.json
  js/packages/berty-i18n/locale/de-DE/messages.json
  js/packages/berty-i18n/locale/el-GR/messages.json
  js/packages/berty-i18n/locale/es-ES/messages.json
  js/packages/berty-i18n/locale/fi-FI/messages.json
  js/packages/berty-i18n/locale/fr-FR/messages.json
  js/packages/berty-i18n/locale/he-IL/messages.json
  js/packages/berty-i18n/locale/hi-IN/messages.json
  js/packages/berty-i18n/locale/hu-HU/messages.json
  js/packages/berty-i18n/locale/id-ID/messages.json
  js/packages/berty-i18n/locale/it-IT/messages.json
  js/packages/berty-i18n/locale/ja-JP/messages.json
  js/packages/berty-i18n/locale/ko-KR/messages.json
  js/packages/berty-i18n/locale/nl-NL/messages.json
  js/packages/berty-i18n/locale/no-NO/messages.json
  js/packages/berty-i18n/locale/pl-PL/messages.json
  js/packages/berty-i18n/locale/pt-BR/messages.json
  js/packages/berty-i18n/locale/pt-PT/messages.json
  js/packages/berty-i18n/locale/ro-RO/messages.json
  js/packages/berty-i18n/locale/ru-RU/messages.json
  js/packages/berty-i18n/locale/sl-SI/messages.json
  js/packages/berty-i18n/locale/sr-Cyrl/messages.json
  js/packages/berty-i18n/locale/sv-SE/messages.json
  js/packages/berty-i18n/locale/te-IN/messages.json
  js/packages/berty-i18n/locale/tr-TR/messages.json
  js/packages/berty-i18n/locale/uk-UA/messages.json
  js/packages/berty-i18n/locale/vi-VN/messages.json
  js/packages/berty-i18n/locale/zh-CN/messages.json
  js/packages/berty-i18n/locale/zh-TW/messages.json
Labels: chore

#3244 feat: qr code update
  js/package.json
  js/packages/components/chat/MultiMemberQR.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/MyBertyId.tsx
  js/yarn.lock
Labels: enhancement

#3246 fix(messenger): audio message take full screen
  js/packages/components/chat/message/AudioMessage.tsx
Labels: bug

#3225 fix(messenger): android crash multiple blur view
  js/package.json
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/common.tsx
  js/packages/components/main/home/Home.tsx
  js/packages/components/modals/AddBot.js
  js/packages/components/modals/ManageDeepLink.tsx
  js/packages/components/modals/WelcomeConfiguration.tsx
  js/packages/components/settings/EditProfile.tsx
  js/packages/components/shared-components/BlurView.android.tsx
  js/packages/components/shared-components/BlurView.tsx
  js/packages/components/shared-components/Modal.tsx
  js/patches/@react-native-community+blur+3.6.0.patch
  js/yarn.lock
Labels: bug

#3167 fix: support android notch for KeyboardAvoidingView
  js/android/app/src/main/AndroidManifest.xml
  js/global.d.ts
  js/package.json
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/shared-components/KeyboardAvoidingView.tsx
  js/packages/components/shared-components/StickyMusicPlayer.tsx
  js/yarn.lock
Labels: bug

#3252 chore: fix libgl CI install
  .github/workflows/release.yml
Labels: chore

#3253 chore: fix typo in docs/protocol/README.md
  docs/protocol/README.md
Labels: chore

#3263 chore: add more steps on OpenAccountWithProgress
  .github/workflows/go.yml
  .github/workflows/release.yml
  go.mod
  go.sum
  go/pkg/bertyaccount/blackbox_test.go
  go/pkg/bertyaccount/service_account.go
Labels: chore

#3264 chore: setup codeql analysis (experiment)
  .github/workflows/codeql-analysis.yml
Labels: chore

#3262 fix(messenger): create new account does not work
  js/packages/store/provider.tsx
Labels: bug

#3258 fix(messenger): android edit profile
  js/packages/components/main/home/Header.tsx
  js/packages/components/main/home/Home.tsx
  js/packages/components/settings/EditProfile.tsx
Labels: bug

#3256 fix(messenger): button restart the app in duplicate in crash screen
  js/packages/components/error.tsx
Labels: bug

#3270 feat: token service generation flag + no click mode flags
  go/cmd/berty/token.go
  go/pkg/bertyprotocol/services_auth_server.go
  go/pkg/bertyprotocol/services_auth_server_test.go
Labels: enhancement

#3282 fix: design multimember qr
  js/packages/components/chat/MultiMemberQR.tsx
Labels: bug

#3271 feat: added reply and reactions to medias
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/components/chat/ReplyReactionContext.tsx
  js/packages/components/chat/common.tsx
  js/packages/components/chat/message/AudioMessage.tsx
  js/packages/components/chat/message/FileMessage.tsx
  js/packages/components/chat/message/PictureMessage.tsx
  js/packages/components/chat/message/UserMessage.tsx
  js/packages/components/chat/message/UserMessageComponents.tsx
  js/packages/components/utils.ts
Labels: enhancement

#3266 feat: pressable avatar images
  js/packages/components/AttachmentImage.tsx
  js/packages/components/avatars.tsx
  js/packages/components/chat/MultiMemberSettings.tsx
  js/packages/components/chat/OneToOneSettings.tsx
  js/packages/components/chat/message/UserMessage.tsx
  js/packages/components/modals/ImageView.tsx
  js/packages/navigation/types.ts
Labels: enhancement

#3286 fix: include token_id in AuthServiceCompleteFlow reply
  api/protocoltypes.proto
  docs/apis/protocoltypes.md
  docs/apis/protocoltypes.swagger.json
  docs/gen.sum
  go/gen.sum
  go/pkg/bertyprotocol/api_services_auth.go
  go/pkg/protocoltypes/protocoltypes.pb.go
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
Labels: bug

#3139 feat: rework tinder
  config/config.gen.json
  config/config.yml
  go/cmd/berty/mini/view_group_incoming.go
  go/internal/config/config.gen.go
  go/internal/initutil/ipfs.go
  go/internal/initutil/manager.go
  go/internal/ipfsutil/pubsub_monitor.go
  go/internal/ipfsutil/testing.go
  go/internal/lifecycle/manager.go
  go/internal/notify/notify.go
  go/internal/notify/notify_test.go
  go/internal/omnisearch/rdvp.go
  go/internal/tinder/asyncable_driver.go
  go/internal/tinder/discovery_monitor.go
  go/internal/tinder/driver.go
  go/internal/tinder/driver_dht.go
  go/internal/tinder/driver_localdiscovery.go
  go/internal/tinder/driver_mocked.go
  go/internal/tinder/driver_monitor.go
  go/internal/tinder/driver_multi.go
  go/internal/tinder/driver_multi_test.go
  go/internal/tinder/driver_rdv.go
  go/internal/tinder/filter.go
  go/internal/tinder/notify_network.go
  go/internal/tinder/option.go
  go/internal/tinder/routing.go
  go/internal/tinder/service.go
  go/internal/tinder/service_test.go
  go/internal/tinder/testing_test.go
  go/internal/tinder/watchdogs_advertiser.go
  go/internal/tinder/watchdogs_discoverer.go
  go/pkg/bertyaccount/blackbox_test.go
  go/pkg/bertyprotocol/api_group.go
  go/pkg/bertyprotocol/service.go
  go/pkg/protocoltypes/config.go
  js/packages/components/chat/message/MessageMonitorMetadata.tsx
  js/packages/config/global.gen.js
  tool/berty-mini-local-helper/Makefile
Labels: WIP, enhancement

#3280 feat: add static relays as cmd argument
  go/internal/initutil/ipfs.go
  go/internal/initutil/manager.go
  go/internal/ipfsutil/helpers.go
  go/internal/omnisearch/rdvp.go
Labels: enhancement

#3290 fix: minor ui fixes
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/MultiMemberSettings.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/SharedMedias.tsx
  js/packages/components/chat/message/UserMessageComponents.tsx
Labels: bug

#3291 feat: rework some flags
  go/README.md
  go/cmd/berty-integration/README.md
  go/framework/bertybridge/blackbox_test.go
  go/internal/initutil/ipfs.go
  go/internal/initutil/logger.go
  go/internal/initutil/manager.go
  go/internal/initutil/node.go
  js/packages/go-bridge/defaults.ts
  tool/compose-integration/docker-compose.yml
  tool/tyber/go/parser/header.go
Labels: enhancement

#3261 feat(messenger): handler SetGroupInfo
  api/messengertypes.proto
  docs/apis/messengertypes.md
  docs/apis/messengertypes.swagger.json
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/handlers.go
  go/pkg/messengertypes/messengertypes.pb.go
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/MultiMemberSettings.tsx
Labels: enhancement

#2979 feat: display startup info on berty daemon
  go/cmd/berty/daemon.go
  go/cmd/berty/shareinvite.go
Labels: echoes/throughput, enhancement

#3293 fix: add crypto tld
  js/packages/components/chat/message/UserMessageComponents.tsx
Labels: bug

#3294 fix: android dropdown picker not scrollable
  js/packages/components/settings/Home.tsx
  js/packages/components/shared-components/DropDownPicker.tsx
Labels: bug

#3297 fix: support all emoji shown in emoji board
  js/global.d.ts
  js/package.json
  js/packages/components/chat/message/Popover.tsx
  js/packages/components/chat/message/UserMessage.tsx
  js/packages/components/utils.ts
  js/tsconfig.json
  js/yarn.lock
Labels: bug
