Repository berty/berty, pull requests merged in 2021-08, with the labels that each got.

#3471 fix: permission ui on ipad
  js/packages/components/main/Permissions.tsx
Labels: bug, 🔍 Ready for Review

#3434 fix: call ImportAccountWithProgress
  js/packages/store/effectableCallbacks.ts
  js/packages/store/providerCallbacks.ts
Labels: bug, 🔍 Ready for Review

#3474 fix: sanitize check multi addr for network config
  go/pkg/bertyaccount/service_account.go
  go/pkg/bertyaccount/service_account_test.go
Labels: bug, ✅ Approved

#3478 chore: fix typo in berty mini
  go/cmd/berty/mini/view_group_incoming.go
Labels: chore, ✅ Approved

#3473 fix: front network config
  go/pkg/bertyaccount/service_account_test.go
  js/package.json
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/components/NotificationProvider.tsx
  js/packages/components/helpers.ts
  js/packages/components/notifications/Basic.tsx
  js/packages/components/onboarding/CreateAccount.js
  js/packages/components/settings/Bluetooth.tsx
  js/packages/components/settings/DevTools.tsx
  js/packages/components/settings/Mode.tsx
  js/packages/components/settings/ServicesAuth.tsx
  js/packages/components/shared-components/SettingsButtons.tsx
  js/packages/store/providerReducer.ts
  js/yarn.lock
Labels: bug, ✅ Approved

#3491 fix: kanban fixes
  js/package.json
  js/packages/components/chat/common.tsx
  js/packages/components/main/NetworkOptions.tsx
  js/packages/components/shared-components/DropDownPicker.tsx
  js/packages/components/shared-components/Header.tsx
  js/yarn.lock
Labels: bug, 🔍 Ready for Review

#3495 feat: custom toggle component
  js/packages/components/shared-components/Request.tsx
  js/packages/components/shared-components/SettingsButtons.tsx
  js/packages/components/shared-components/Toggle.tsx
Labels: 🔍 Ready for Review, enhancement

#3493 feat: native navigation
  js/packages/assets/loader_dots.gif
  js/packages/components/chat/ContactSettings.tsx
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/MultiMemberQR.tsx
  js/packages/components/chat/MultiMemberSettings.tsx
  js/packages/components/chat/MultiMembersSettingsAddMembers.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/OneToOneSettings.tsx
  js/packages/components/chat/ReplicateGroupSettings.tsx
  js/packages/components/chat/SharedMedias.tsx
  js/packages/components/chat/common.tsx
  js/packages/components/gates.tsx
  js/packages/components/main/CreateGroupAddMembers.tsx
  js/packages/components/main/CreateGroupFinalize.tsx
  js/packages/components/main/NetworkOptions.tsx
  js/packages/components/main/Permissions.tsx
  js/packages/components/main/Scan.tsx
  js/packages/components/main/home/Header.tsx
  js/packages/components/modals/ManageDeepLink.tsx
  js/packages/components/modals/index.ts
  js/packages/components/onboarding/ChoosePreset.tsx
  js/packages/components/onboarding/CreateAccount.js
  js/packages/components/settings/AboutBerty.tsx
  js/packages/components/settings/AddDevConversations.tsx
  js/packages/components/settings/AppUpdates.tsx
  js/packages/components/settings/BlockedContacts.tsx
  js/packages/components/settings/Bluetooth.tsx
  js/packages/components/settings/DeleteAccount.tsx
  js/packages/components/settings/DevText.tsx
  js/packages/components/settings/DevTools.tsx
  js/packages/components/settings/EditProfile.tsx
  js/packages/components/settings/FakeData.js
  js/packages/components/settings/Help.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/IpfsWebUI.tsx
  js/packages/components/settings/Mode.tsx
  js/packages/components/settings/MyBertyId.tsx
  js/packages/components/settings/NetworkMap.tsx
  js/packages/components/settings/Notifications.tsx
  js/packages/components/settings/ServicesAuth.tsx
  js/packages/components/settings/SystemInfo.tsx
  js/packages/components/settings/TermsOfUse.tsx
  js/packages/components/settings/ThemeEditor.tsx
  js/packages/components/settings/index.ts
  js/packages/components/shared-components/Fallback.tsx
  js/packages/components/shared-components/Header.tsx
  js/packages/components/shared-components/LoaderDots.tsx
  js/packages/components/shared-components/StatusBarWrapper.tsx
  js/packages/components/shared-components/SwipeNavRecognizer.tsx
  js/packages/components/shared-components/index.ts
  js/packages/components/theme.tsx
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
Labels: 🔍 Ready for Review, enhancement

#3502 chore(ci): use mkache for gomobile artifacts
  .github/workflows/android.yml
  .github/workflows/ios.yml
Labels: 🔍 Ready for Review, chore
