Repository berty/berty, pull requests merged in 2021-06, with the labels that each got.

#3361 feat: add bertyaccount.LogfileList gRPC endpoint
  api/bertyaccount.proto
  docs/gen.sum
  go/gen.sum
  go/internal/ipfsutil/helpers_test.go
  go/internal/logutil/logutil.go
  go/internal/logutil/logutil_test.go
  go/internal/logutil/stream.go
  go/pkg/bertyaccount/bertyaccount.pb.go
  go/pkg/bertyaccount/blackbox_test.go
  go/pkg/bertyaccount/service_account.go
  go/pkg/bertyaccount/service_log.go
  js/Makefile
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  js/packages/grpc-bridge/welsh-clients.gen.ts
Labels: enhancement

#3363 feat(js): add log files to shake reports
  js/packages/store/effectableCallbacks.ts
  js/packages/store/utils.ts
Labels: enhancement

#3370 feat(messenger): pass logs to crashlytics
  js/android/app/build.gradle
  js/android/app/src/main/java/tech/berty/gobridge/LoggerDriver.java
  js/ios/Berty/Sources/Bridge/LoggerDriver.swift
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/components/settings/DevTools.tsx
Labels: enhancement

#3373 fix(android): crashlytics installation
  js/android/app/build.gradle
  js/android/build.gradle
  js/ios/Podfile.lock
  js/package.json
  js/yarn.lock
Labels: bug

#3376 fix: background fetch
  go/framework/bertybridge/bridge.go
Labels: bug

#3377 fix: bump rn-permission and fix iOS 14.5 breaking change on openAuth
  js/ios/Podfile.lock
  js/package.json
  js/packages/store/services.tsx
  js/yarn.lock
Labels: bug

#3369 feat: make android project releasable
  js/android/app/build.gradle
  js/android/app/proguard-rules.pro
  js/android/app/src/main/java/tech/berty/gobridge/BertyNearbyDriver.java
  js/android/app/src/main/java/tech/berty/gobridge/GoBridgeModule.java
  js/android/app/src/main/java/tech/berty/gobridge/GoBridgePackage.java
  js/android/app/src/main/java/tech/berty/gobridge/JavaPromiseBlock.java
  js/android/app/src/main/java/tech/berty/gobridge/LoggerDriver.java
  js/android/app/src/main/java/tech/berty/gobridge/LoggerLevel.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/Advertiser.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/BleDriver.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/BleInterface.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/BleQueue.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/DeviceManager.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/GattServer.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/GattServerCallback.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/Peer.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/PeerDevice.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/PeerManager.java
  js/android/build.gradle
Labels: enhancement

#3354 fix: ios build for apple m1
  .github/workflows/android.yml
  .github/workflows/ios.yml
  .github/workflows/js.yml
  .github/workflows/protobuf.yml
  js/Makefile
  js/gen.sum
  js/ios/Gemfile
  js/ios/Gemfile.lock
  js/ios/OpenSSL-Universal-Override.podspec
  js/ios/Podfile
  js/ios/Podfile.lock
  js/ios/berty.yaml
  js/ios/glog/glog.podspec
  js/ios/glog/ios-configure-glog.sh
  js/package.json
  js/patches/react-native+0.63.4.patch
  js/yarn.lock
  tool/build/shell/dl-go-libtor-ios.sh
Labels: WIP, bug

#3356 fix: betabot send date and quick reply options
  js/packages/components/chat/MessageList.tsx
Labels: bug

#3357 fix: show confetti when 'Start using Berty' button pressed
  js/packages/components/onboarding/SetupFinished.js
Labels: bug

#3379 fix: android recording error
  js/android/app/src/main/AndroidManifest.xml
  js/package.json
  js/packages/components/chat/record/RecordComponent.tsx
  js/yarn.lock
Labels: bug

#3386 fix(mini): deadlock fix when unhandled meta events received
  go/cmd/berty/mini/view_tabbed_groups.go
Labels: bug, ✅ Approved

#3391 fix: wording and lock preset screen onboarding
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/berty-i18n/locale/languages.js
  js/packages/components/onboarding/ChoosePreset.tsx
  js/packages/components/settings/Home.tsx
  js/packages/navigation/stacks.tsx
  js/packages/store/providerReducer.ts
Labels: bug, ✅ Approved

#3392 fix: betabot waiting time before interact
  go/cmd/betabot/main.go
Labels: bug, ✅ Approved

#3319 Slow message reception fix
  go.mod
  go.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/handlers.go
  go/pkg/bertymessenger/service_non_mocked_test.go
  go/pkg/bertymessenger/service_test.go
  go/pkg/bertymessenger/testing.go
  go/pkg/bertyprotocol/client.go
  go/pkg/bertyprotocol/keystore_message.go
  go/pkg/bertyprotocol/orbitdb.go
  go/pkg/bertyprotocol/orbitdb_many_adds_berty_test.go
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/bertyprotocol/testing.go
Labels: WIP, ✅ Approved

#3381 feat: add Bluetooth permission request explanation in settings
  go/pkg/bertymessenger/service_test.go
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/berty-i18n/locale/fr-FR/messages.json
  js/packages/components/onboarding/SetupFinished.js
  js/packages/components/settings/Bluetooth.tsx
Labels: enhancement, 🔍 Ready for Review

#3390 fix: android build on yolo
  js/android/app/build.gradle
  js/android/build.gradle
  js/patches/react-native+0.63.4.patch
Labels: bug, 🔍 Ready for Review

#3397 fix: prevent proguard to strip inAppBrowser required symbols
  js/android/app/proguard-rules.pro
Labels: bug, ✅ Approved

#3399 feat: add generated version code and name in gradle
  .github/workflows/android.yml
  js/android/app/build.gradle
  js/android/build.gradle
Labels: enhancement, 🔍 Ready for Review

#3401 chore: bump moul.io/u dep (fix #3400)
  go.mod
  go.sum
  tool/go.mod
  tool/go.sum
Labels: chore, 🔍 Ready for Review

#3404 chore: removed github action workflow cancel
  .github/workflows/push.yml
  tool/build/shell/resolve-workflows-for-cancel.py
Labels: chore, ✅ Approved

#3408 fix(android): align atomic int64s
  go.mod
  go.sum
Labels: bug, chore, ✅ Approved

#3409 fix: add current version in updates screen
  js/packages/components/settings/AppUpdates.tsx
Labels: bug, 🔍 Ready for Review

#3412 fix: unset Android env var to prevent gomobile error on init
  js/Makefile
Labels: bug, ✅ Approved

#3413 fix: unset Android env var to prevent gomobile error on bind
  js/Makefile
Labels: bug, ✅ Approved
