Repository berty/berty, pull requests merged in 2021-12, with the labels that each got.

#3636 feat: onboarding-v5
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/components/NotificationProvider.tsx
  js/packages/components/onboarding/Button.tsx
  js/packages/components/onboarding/CreateAccount.tsx
  js/packages/components/onboarding/CreateAccountBox.tsx
  js/packages/components/onboarding/ExpertSetup.tsx
  js/packages/components/onboarding/GetStarted.tsx
  js/packages/components/onboarding/OnboardingWrapper.js
  js/packages/components/onboarding/SetupFinished.tsx
  js/packages/components/onboarding/SwiperCard.tsx
  js/packages/components/onboarding/index.ts
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/NetworkConfig.tsx
  js/packages/components/settings/ReplicationServices.tsx
  js/packages/components/settings/ServicesAuth.tsx
  js/packages/components/settings/index.ts
  js/packages/components/shared-components/DropDownPicker.tsx
  js/packages/components/shared-components/SettingsButtons.tsx
  js/packages/components/shared-components/Toggle.tsx
  js/packages/messenger-app/custom-icons-svgs/config.svg
  js/packages/messenger-app/custom-icons-svgs/earth.svg
  js/packages/messenger-app/custom-icons-svgs/expert-bluetooth.svg
  js/packages/messenger-app/custom-icons-svgs/expert-mdns.svg
  js/packages/messenger-app/custom-icons-svgs/expert-node.svg
  js/packages/messenger-app/custom-icons-svgs/expert-push-notif.svg
  js/packages/messenger-app/custom-icons-svgs/peer.svg
  js/packages/messenger-app/custom-icons-svgs/proximity.svg
  js/packages/messenger-app/custom-icons-svgs/services.svg
  js/packages/messenger-app/custom-icons-svgs/settings.svg
  js/packages/messenger-app/custom-icons.tsx
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
  js/packages/store/effectableCallbacks.ts
  js/packages/store/provider.tsx
  js/packages/store/providerEffects.ts
  js/packages/store/services.tsx
  js/packages/store/types.ts
Labels: 🔍 Ready for Review, enhancement

#3721 fix: fix dark theme mode + add redux persist
  js/package.json
  js/packages/components/modals/ThemeColorName.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/ThemeEditor.tsx
  js/packages/redux/persistStorage.ts
  js/packages/redux/store.ts
  js/packages/store/context.ts
  js/packages/store/hooks.ts
  js/packages/store/providerEffects.ts
  js/packages/store/types.ts
  js/yarn.lock
Labels: bug, 🔍 Ready for Review

#3730 fix: permissions onComplete freeze
  js/packages/components/main/Permissions.tsx
  js/packages/navigation/types.ts
Labels: bug, 🔍 Ready for Review

#3733 fix: deeplink interaction on background push notif
  js/ios/Berty/AppDelegate.m
Labels: bug, 🔍 Ready for Review

#3734 chore(attachment_crypto): use helper to get sk seed and remove overhead magic number
  go/internal/cryptoutil/attachment_crypto.go
Labels: 🔍 Ready for Review, chore

#3728 fix: import theme
  js/packages/components/settings/ThemeEditor.tsx
Labels: bug, 🔍 Ready for Review

#3740 fix: use i18n variables for front push notif
  go/pkg/bertyaccount/service_account.go
  js/Makefile
  js/packages/components/NotificationProvider.tsx
Labels: bug, ✅ Approved

#3743 fix: onboarding create account name screen
  js/ios/Podfile.lock
  js/packages/components/onboarding/CreateAccount.tsx
Labels: bug, ✅ Approved

#3741 fix: apply OS language
  js/packages/components/onboarding/CreateAccount.tsx
  js/packages/store/context.ts
Labels: bug, 🔍 Ready for Review

#3736 feat: navigation bump at the GetStarted screen
  js/packages/components/settings/ThemeEditor.tsx
  js/packages/navigation/stacks.tsx
Labels: 🔍 Ready for Review, enhancement

#3742 fix: enable direct channel
  go.mod
  go.sum
  go/internal/initutil/orbitdb.go
  go/pkg/bertyprotocol/orbitdb.go
  go/pkg/bertyprotocol/service.go
Labels: bug, ✅ Approved

#3714 fix: rewrite chat footer and optimize some components
  js/package.json
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/berty-i18n/locale/fr-FR/messages.json
  js/packages/components/AttachmentImage.tsx
  js/packages/components/NotificationProvider.tsx
  js/packages/components/avatars.tsx
  js/packages/components/chat/MessageList.tsx
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/ReplyReactionContext.tsx
  js/packages/components/chat/SharedMedias.tsx
  js/packages/components/chat/audioMessageCommon.tsx
  js/packages/components/chat/common.tsx
  js/packages/components/chat/footer/ChatFooter.tsx
  js/packages/components/chat/footer/ChatFooterButtons.tsx
  js/packages/components/chat/footer/ChatTextInput.tsx
  js/packages/components/chat/footer/file-uploads/AddFileMenu.tsx
  js/packages/components/chat/footer/file-uploads/GallerySection.tsx
  js/packages/components/chat/footer/file-uploads/MenuListItem.tsx
  js/packages/components/chat/footer/file-uploads/SecurityAccess.tsx
  js/packages/components/chat/footer/file-uploads/types.tsx
  js/packages/components/chat/footer/record/PreviewComponent.tsx
  js/packages/components/chat/footer/record/RecordComponent.tsx
  js/packages/components/chat/footer/record/RecordingComponent.tsx
  js/packages/components/chat/message/AudioMessage.tsx
  js/packages/components/chat/message/PictureMessage.tsx
  js/packages/components/chat/message/index.tsx
  js/packages/components/chat/record/common.ts
  js/packages/components/error.tsx
  js/packages/components/main/home/Conversations.tsx
  js/packages/components/onboarding/CreateAccount.tsx
  js/packages/components/onboarding/CreateAccountBox.tsx
  js/packages/components/onboarding/OnboardingWrapper.js
  js/packages/components/onboarding/OnboardingWrapper.tsx
  js/packages/components/onboarding/SwiperCard.tsx
  js/packages/components/settings/DevTools.tsx
  js/packages/components/settings/EditProfile.tsx
  js/packages/components/shared-components/KeyboardAvoidingView.tsx
  js/packages/grpc-bridge/middleware/logs/logs.js
  js/packages/messenger-app/App.tsx
  js/packages/navigation/stacks.tsx
  js/packages/redux/persistStorage.ts
  js/packages/redux/react-redux/index.ts
  js/packages/redux/reducers/chatInputs.reducer.ts
  js/packages/redux/reducers/newGroup.reducer.ts
  js/packages/redux/store.ts
  js/packages/rnutil/checkPermissions.ts
  js/packages/rnutil/keyboardAvoiding.tsx
  js/packages/store/context.ts
  js/packages/store/hooks.ts
  js/packages/store/providerEffects.ts
  js/packages/store/reducer/eventStreamReducer.ts
  js/packages/store/reducer/uiReducer.ts
  js/packages/store/types.ts
  js/yarn.lock
Labels: bug, 🔍 Ready for Review

#3748 fix(js): replication services swiper card flex
  js/packages/components/settings/ReplicationServices.tsx
Labels: bug, 🔍 Ready for Review

#3749 feat: per account storage key, per account redux persistance, fix checklist
  api/accounttypes.proto
  docs/gen.sum
  go/framework/bertybridge/push.go
  go/framework/bertypush/service.go
  go/gen.sum
  go/internal/accountutils/utils.go
  go/internal/initutil/datastore.go
  go/internal/initutil/ipfs.go
  go/internal/initutil/manager.go
  go/internal/initutil/node.go
  go/pkg/accounttypes/accounttypes.pb.go
  go/pkg/bertyaccount/service.go
  go/pkg/bertyaccount/service_account.go
  go/pkg/bertyaccount/service_storage.go
  go/pkg/bertypush/push_opener.go
  go/pkg/bertypush/push_test.go
  js/android/app/src/main/java/tech/berty/notification/NotificationService.java
  js/gen.sum
  js/ios/Berty/Sources/Bridge/KeystoreDriver.swift
  js/ios/NotificationService/NotificationService.swift
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/components/chat/footer/ChatFooter.tsx
  js/packages/components/helpers.ts
  js/packages/components/main/CreateGroupFinalize.tsx
  js/packages/components/main/home/MultiAccount.tsx
  js/packages/components/modals/AddThisContact.tsx
  js/packages/components/modals/ManageGroupInvitation.tsx
  js/packages/components/modals/ThemeColorName.tsx
  js/packages/components/settings/EditProfile.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/ReplicationServices.tsx
  js/packages/components/settings/ThemeEditor.tsx
  js/packages/components/settings/WelcomeChecklist.tsx
  js/packages/grpc-bridge/middleware/logs/logs.js
  js/packages/redux/reducers/checklist.reducer.ts
  js/packages/redux/store.ts
  js/packages/store/accountService.ts
  js/packages/store/context.ts
  js/packages/store/effectableCallbacks.ts
  js/packages/store/hooks.ts
  js/packages/store/provider.tsx
  js/packages/store/providerCallbacks.ts
  js/packages/store/providerEffects.ts
  js/packages/store/types.ts
Labels: 🔍 Ready for Review, enhancement

#3751 fix: bump go-ipfs-repo-encrypted to v1.0.11
  go.mod
  go.sum
Labels: bug, 🔍 Ready for Review

#3753 fix: don't keep storage keys in memory
  go/internal/initutil/datastore.go
  go/internal/initutil/ipfs.go
  go/internal/initutil/manager.go
  go/internal/initutil/node.go
  go/pkg/bertyaccount/service.go
Labels: bug, 🔍 Ready for Review

#3754 fix: rename audio messages and allow sharing them
  js/packages/components/chat/SharedMedias.tsx
  js/packages/components/chat/footer/ChatFooter.tsx
  js/packages/components/chat/footer/file-uploads/AddFileMenu.tsx
  js/packages/components/chat/footer/record/RecordComponent.tsx
  js/packages/components/chat/message/AudioMessage.tsx
  js/packages/components/settings/EditProfile.tsx
  js/packages/store/utils.ts
Labels: bug, 🔍 Ready for Review

#3755 fix: allow per-account language setting that can be empty
  js/packages/berty-i18n/index.ts
  js/packages/components/settings/Home.tsx
  js/packages/redux/reducers/accountSettings.reducer.ts
  js/packages/redux/store.ts
  js/packages/store/context.ts
  js/packages/store/provider.tsx
  js/packages/store/providerEffects.ts
  js/packages/store/types.ts
Labels: bug, 🔍 Ready for Review

#3756 fix chat footer colors
  js/packages/components/chat/footer/ChatFooter.tsx
  js/packages/components/chat/footer/ChatTextInput.tsx
  js/packages/redux/reducers/chatInputs.reducer.ts
Labels: bug, 🔍 Ready for Review

#3758 fix: account switch
  js/packages/components/main/home/MultiAccount.tsx
  js/packages/grpc-bridge/middleware/logs/logs.js
  js/packages/store/context.ts
  js/packages/store/effectableCallbacks.ts
  js/packages/store/providerEffects.ts
Labels: bug, 🔍 Ready for Review

#3759 fix: reorg conversation settings and reset navigation after onPress in-app notification
  js/ios/Podfile.lock
  js/packages/components/NotificationProvider.tsx
  js/packages/components/chat/ContactSettings.tsx
  js/packages/components/chat/MultiMemberSettings.tsx
  js/packages/components/chat/OneToOneSettings.tsx
  js/packages/components/notifications/ContactRequestReceived.tsx
  js/packages/components/notifications/ContactRequestSent.tsx
  js/packages/components/notifications/MessageReceived.tsx
Labels: bug, 🔍 Ready for Review

#3760 fix: cancel reply cross is outside box with long large text
  js/packages/components/chat/footer/ChatTextInput.tsx
Labels: bug, 🔍 Ready for Review

#3744 fix: refracto settings screens
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/components/main/NetworkOptions.tsx
  js/packages/components/main/index.ts
  js/packages/components/onboarding/AdvancedSettings.tsx
  js/packages/components/onboarding/CreateAccount.tsx
  js/packages/components/onboarding/index.ts
  js/packages/components/settings/Bluetooth.tsx
  js/packages/components/settings/DevTools.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/Mode.tsx
  js/packages/components/settings/Notifications.tsx
  js/packages/components/settings/WelcomeChecklist.tsx
  js/packages/components/settings/index.ts
  js/packages/components/shared-components/SettingsButtons.tsx
  js/packages/messenger-app/custom-icons-svgs/peer.svg
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
Labels: bug, 🔍 Ready for Review

#3747 fix: add LF dark theme in default collection theme
  js/packages/components/main/home/MultiAccount.tsx
  js/packages/store/context.ts
  js/packages/styles/DarkLF-theme.json
Labels: bug, 🔍 Ready for Review

#3766 fix: add version badge to Berty icon
  js/packages/components/main/home/Header.tsx
Labels: bug, 🔍 Ready for Review

#3745 feat: update deprecated golangci linters: golint/scopelint
  .github/workflows/go.yml
  go/.golangci.yml
  go/cmd/berty/peers.go
  go/cmd/rdvp/main.go
  go/internal/grpcutil/lazy_client.go
  go/internal/grpcutil/server.go
  go/internal/initutil/ipfs.go
  go/internal/omnisearch/config.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertyprotocol/api_event.go
  go/pkg/tyber/format.go
Labels: 🔍 Ready for Review, enhancement

#3763 fix: add display name in qr profile
  js/packages/components/settings/Home.tsx
Labels: bug, 🔍 Ready for Review

#3765 fix: fix upload picture on Android
  js/packages/components/modals/EditProfile.tsx
  js/packages/components/modals/index.ts
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/WelcomeChecklist.tsx
  js/packages/components/settings/index.ts
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
Labels: bug, 🔍 Ready for Review

#3769 fix: can collapse long message after click on read more
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/components/chat/message/UserMessageComponents.tsx
Labels: bug, 🔍 Ready for Review

#3773 fix: add dropdown to members list in multimember conv
  js/packages/components/chat/MultiMemberSettings.tsx
  js/packages/components/shared-components/SettingsButtons.tsx
Labels: bug, 🔍 Ready for Review

#3768 fix: ask permissions for push and proximity transport
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/components/chat/footer/ChatFooter.tsx
  js/packages/components/main/Permissions.tsx
  js/packages/components/main/home/Home.tsx
  js/packages/components/onboarding/AdvancedSettings.tsx
  js/packages/components/onboarding/CreateAccountBox.tsx
  js/packages/navigation/types.ts
  js/packages/rnutil/checkPermissions.ts
Labels: bug, 🔍 Ready for Review

#3775 feat: optimistic interactions
  js/packages/components/chat/MultiMembersSettingsAddMembers.tsx
  js/packages/components/chat/footer/ChatFooter.tsx
  js/packages/components/chat/footer/file-uploads/AddFileMenu.tsx
  js/packages/components/chat/footer/record/RecordComponent.tsx
  js/packages/components/chat/message/QuickReplyOptions.tsx
  js/packages/store/provider.tsx
  js/packages/store/providerCallbacks.ts
Labels: 🔍 Ready for Review, enhancement

#3777 fix: apply button in advanced settings as float button
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/components/onboarding/AdvancedSettings.tsx
Labels: bug, 🔍 Ready for Review

#3778 fix: pass media metadata to network
  go/pkg/messengertypes/types.go
Labels: bug, 🔍 Ready for Review

#3713 fix: pause QR code scanner
  js/packages/components/main/Scan.tsx
Labels: bug, ✅ Approved

#3780 fix: match avatar color to message color
  js/packages/components/avatars.tsx
Labels: bug, 🔍 Ready for Review

#3781 fix: media alignment in conversation
  js/packages/components/chat/message/UserMessage.tsx
Labels: bug, 🔍 Ready for Review

#3784 fix: remove shakebugs
  .github/workflows/android.yml
  .github/workflows/ios.yml
  js/__mocks__/@shakebugs/react-native-shake.js
  js/android/app/proguard-rules.pro
  js/android/app/src/main/AndroidManifest.xml
  js/android/app/src/main/java/tech/berty/android/MainActivity.java
  js/android/app/src/main/java/tech/berty/android/MainApplication.java
  js/ios/Podfile.lock
  js/package.json
  js/packages/messenger-app/App.tsx
  js/packages/store/effectableCallbacks.ts
  js/packages/store/utils.ts
  js/yarn.lock
Labels: bug, 🔍 Ready for Review

#3779 fix: roadmap link
  js/packages/components/settings/Roadmap.tsx
Labels: bug, ✅ Approved

#3770 fix: display qr code in right size on ipads
  js/packages/components/chat/MultiMemberQR.tsx
  js/packages/components/settings/MyBertyId.tsx
  js/packages/store/hooks.ts
Labels: bug, ⚠️ Changes requested

#3786 fix: don't cut device music
  js/packages/store/sounds.ts
Labels: bug, 🔍 Ready for Review

#3789 fix: description error screens
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/berty-i18n/locale/fr-FR/messages.json
Labels: bug, 🔍 Ready for Review

#3645 feat: enable l2cap in BLE drivers
  go/framework/bertybridge/proximity_driver.go
  go/internal/ble-driver/BertyDevice_darwin.h
  go/internal/ble-driver/BertyDevice_darwin.m
  go/internal/ble-driver/BleInterface_darwin.h
  go/internal/ble-driver/BleInterface_darwin.m
  go/internal/ble-driver/BleManager_darwin.h
  go/internal/ble-driver/BleManager_darwin.m
  go/internal/ble-driver/BleQueue.h
  go/internal/ble-driver/BleQueue.m
  go/internal/ble-driver/ConnectedPeer.h
  go/internal/ble-driver/ConnectedPeer.m
  go/internal/ble-driver/Logger.h
  go/internal/ble-driver/Logger.m
  go/internal/ble-driver/PeerManager.h
  go/internal/ble-driver/PeerManager.m
  go/internal/ble-driver/bridge_darwin.go
  go/internal/ble-driver/init.go
  go/internal/initutil/ipfs.go
  go/internal/multipeer-connectivity-driver/driver/cgo_bridge.go
  go/internal/proximitytransport/conn.go
  go/internal/proximitytransport/listener.go
  go/internal/proximitytransport/ringBuffer_map.go
  go/internal/proximitytransport/transport.go
  js/android/app/src/main/java/tech/berty/gobridge/GoBridgeModule.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/Advertiser.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/BleDriver.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/BleInterface.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/BleQueue.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/DeviceManager.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/GattServer.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/GattServerCallback.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/Logger.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/Peer.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/PeerDevice.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/PeerManager.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/Scanner.java
Labels: ✅ Approved, enhancement

#3790 fix(tmp): mock internal network helper not compatible with Android SDK30
  go.mod
  go.sum
  go/pkg/bertyaccount/service_account.go
  js/android/build.gradle
Labels: bug, 🔍 Ready for Review

#3795 chore: enable ios github runners
  .github/workflows/ios.yml
Labels: ✅ Approved, chore

#3793 fix: add loader placeholder during settings home QR load
  js/packages/components/gates.tsx
  js/packages/components/settings/Home.tsx
Labels: bug, 🔍 Ready for Review

#3776 fix: rename betabot into welcome bot and remove betabot dev
  .gitignore
  Dockerfile
  README.md
  config/Makefile
  config/config.gen.json
  config/config.yml
  go/Makefile
  go/README.md
  go/cmd/berty-doctor/depaware.txt
  go/cmd/berty-integration/README.md
  go/cmd/berty-integration/depaware.txt
  go/cmd/berty-integration/main.go
  go/cmd/berty/depaware.txt
  go/cmd/betabot/depaware.txt
  go/cmd/rdvp/depaware.txt
  go/cmd/welcomebot/README.md
  go/cmd/welcomebot/depaware.txt
  go/cmd/welcomebot/example_test.go
  go/cmd/welcomebot/main.go
  go/framework/bertybridge/depaware.txt
  go/gen.sum
  go/internal/config/config.gen.go
  go/internal/config/config_test.go
  js/packages/config/global.gen.js
  tool/compose-integration/docker-compose.yml
  tool/deployments/welcomebot/Makefile
  tool/deployments/welcomebot/docker-compose.yml
Labels: bug, 🔍 Ready for Review

#3794 fix: add qr in multimember settings
  js/packages/components/chat/MultiMemberSettings.tsx
Labels: bug, 🔍 Ready for Review

#3787 fix: remove crashlytics
  js/__mocks__/@react-native-firebase/crashlytics.js
  js/android/app/build.gradle
  js/android/app/src/main/java/tech/berty/gobridge/LoggerDriver.java
  js/android/build.gradle
  js/ios/Berty/AppDelegate.m
  js/ios/Berty/Sources/Bridge/LoggerDriver.swift
  js/ios/Podfile
  js/ios/Podfile.lock
  js/ios/berty.yaml
  js/package.json
  js/packages/components/settings/DevTools.tsx
  js/yarn.lock
Labels: bug, ✅ Approved

#3792 fix: protect against nil payloads
  go/internal/messengerpayloads/handlers.go
Labels: bug, 🔍 Ready for Review

#3804 fix: disable Android Nearby driver
  js/android/app/src/main/java/tech/berty/gobridge/GoBridgeModule.java
Labels: bug, 🔍 Ready for Review

#3800 fix: disable logging on store release
  go/framework/bertybridge/bridge.go
  go/internal/initutil/logger.go
  go/internal/initutil/manager.go
  go/pkg/bertyaccount/service.go
  go/pkg/bertyaccount/service_account.go
  js/android/app/src/main/java/tech/berty/gobridge/GoBridgeModule.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/Logger.java
  js/ios/Berty/Sources/Bridge/GoBridge.swift
  js/ios/Berty/Sources/Bridge/LoggerDriver.swift
  js/ios/NotificationService/NotificationService.swift
  js/ios/berty.yaml
Labels: bug, ✅ Approved

#3802 fix: ignore all empty payloads except for ack
  go/internal/messengerpayloads/handlers.go
  go/pkg/bertymessenger/service_test.go
  go/pkg/messengertypes/types.go
Labels: bug, 🔍 Ready for Review

#3803 fix: properly handle record permissions and sending state
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/berty-i18n/locale/fr-FR/messages.json
  js/packages/components/InfosChat.tsx
  js/packages/components/chat/footer/ChatFooter.tsx
  js/packages/components/chat/footer/ChatFooterButtons.tsx
  js/packages/components/chat/footer/file-uploads/AddFileMenu.tsx
  js/packages/components/chat/footer/file-uploads/GallerySection.tsx
  js/packages/components/chat/footer/record/RecordComponent.tsx
  js/packages/components/chat/message/MessageInvitation.tsx
  js/packages/components/chat/message/UserMessageComponents.tsx
  js/packages/components/main/Permissions.tsx
  js/packages/components/main/home/Conversations.tsx
  js/packages/components/main/home/Home.tsx
  js/packages/components/onboarding/AdvancedSettings.tsx
  js/packages/components/onboarding/CreateAccount.tsx
  js/packages/components/onboarding/CreateAccountBox.tsx
  js/packages/grpc-bridge/rpc/rpc.bridge.ts
  js/packages/redux/reducers/chatInputsVolatile.reducer.ts
  js/packages/redux/store.ts
  js/packages/rnutil/checkPermissions.ts
  js/packages/store/effectableCallbacks.ts
Labels: bug, 🔍 Ready for Review

#3810 fix: allow empty user message body and strengthen front
  go/internal/messengerpayloads/handlers.go
  go/internal/multipeer-connectivity-driver/driver/cgo_bridge.go
  js/packages/components/chat/ReplyReactionContext.tsx
  js/packages/components/chat/SharedMedias.tsx
  js/packages/components/chat/footer/file-uploads/AddFileMenu.tsx
  js/packages/components/chat/footer/file-uploads/SecurityAccess.tsx
  js/packages/components/chat/message/MessageMonitorMetadata.tsx
  js/packages/components/chat/message/UserMessage.tsx
  js/packages/components/chat/message/UserMessageComponents.tsx
  js/packages/components/chat/message/index.tsx
  js/packages/components/main/home/Conversations.tsx
  js/packages/components/main/home/Search.tsx
  js/packages/store/convert.ts
  js/packages/store/gen-type-utils.js
  js/packages/store/providerEffects.ts
  js/packages/store/reducer/eventStreamReducer.ts
  js/packages/store/types.gen.ts
Labels: bug, 🔍 Ready for Review

#3799 fix: my berty id ui
  js/packages/components/settings/MyBertyId.tsx
Labels: bug, 🔍 Ready for Review

#3811 fix: crash on android webviews screens cause blurview
  js/packages/components/shared-components/WebViews.tsx
Labels: bug, 🔍 Ready for Review

#3809 fix: change wording relay/replication server by Berty services
  js/ios/Podfile.lock
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/components/chat/ReplicateGroupSettings.tsx
  js/packages/components/settings/BertyServices.tsx
  js/packages/components/settings/WelcomeChecklist.tsx
  js/packages/components/settings/index.ts
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
  js/packages/redux/reducers/checklist.reducer.ts
Labels: bug, 🔍 Ready for Review

#3798 feat: implement native interface getter
  go.mod
  go.sum
  go/framework/bertybridge/bridge.go
  go/framework/bertybridge/config.go
  go/framework/bertybridge/driver_mdnslocker.go
  go/framework/bertybridge/driver_net.go
  go/internal/initutil/ipfs.go
  go/internal/initutil/manager.go
  go/internal/initutil/node.go
  go/pkg/bertyaccount/service.go
  go/pkg/bertyaccount/service_account.go
  go/pkg/osversion/android.go
  go/pkg/osversion/ios.go
  go/pkg/osversion/osversion.go
  go/pkg/osversion/others.go
  js/android/app/src/main/AndroidManifest.xml
  js/android/app/src/main/java/tech/berty/gobridge/GoBridgeModule.java
  js/android/app/src/main/java/tech/berty/gobridge/MDNSLockerDriver.java
  js/android/app/src/main/java/tech/berty/gobridge/NetDriver.java
Labels: 🔍 Ready for Review, enhancement

#3791 fix: add animation in launch screen
  js/packages/assets/berty_startup.json
  js/packages/components/gates.tsx
Labels: bug, 🔍 Ready for Review

#3813 fix: Android deeplink
  js/android/app/src/main/AndroidManifest.xml
  js/android/app/src/main/java/tech/berty/notification/NotificationService.java
  js/packages/components/modals/ManageDeepLink.tsx
  js/packages/navigation/stacks.tsx
Labels: bug, 🔍 Ready for Review

#3816 chore: update welcomebot addr
  config/config.yml
Labels: 🔍 Ready for Review, chore

#3817 fix: Typo in README
  README.md
Labels: bug, ✅ Approved

#3823 chore: randomly choose a mac builder
  .github/workflows/ios.yml
  .github/workflows/mac-runner-matrix-builder.js
Labels: ✅ Approved, chore

#3828 fix: android release app icon
  js/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  js/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  js/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  js/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  js/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
Labels: bug, 🔍 Ready for Review

#3814 fix: kanban fixes
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/components/onboarding/AdvancedSettings.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/MyBertyId.tsx
  js/packages/components/settings/Roadmap.tsx
  js/packages/components/settings/ThemeEditor.tsx
  js/packages/navigation/stacks.tsx
Labels: bug, 🔍 Ready for Review

#3827 fix: delete fingerprint animation at launch
  js/packages/assets/berty_startup.json
  js/packages/components/gates.tsx
Labels: bug, 🔍 Ready for Review

#3826 fix: unify title screen
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/components/settings/AppUpdates.tsx
  js/packages/components/settings/Help.tsx
  js/packages/components/settings/index.ts
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
Labels: bug, 🔍 Ready for Review

#3832 feat: improve audio message playback ux
  js/packages/components/chat/audioMessageCommon.tsx
  js/packages/components/chat/message/AudioMessage.tsx
  js/packages/components/music-player.tsx
  js/packages/components/shared-components/StickyMusicPlayer.tsx
  js/packages/messenger-app/App.tsx
  js/packages/music-player/index.tsx
Labels: 🔍 Ready for Review, enhancement

#3806 fix: move create group button bellow info text
  js/packages/components/main/CreateGroupFinalize.tsx
  js/packages/components/main/CreateGroupFooter.tsx
Labels: bug, 🔍 Ready for Review

#3834 fix(messenger): set group info on metadata log
  api/messengertypes.proto
  docs/apis/messengertypes.md
  docs/apis/messengertypes.swagger.json
  docs/gen.sum
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/messengertypes/messengertypes.pb.go
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/MultiMemberSettings.tsx
Labels: bug, ✅ Approved

#3838 fix(redux): properly update falsy values
  js/packages/redux/reducers/messenger.reducer.ts
Labels: bug, 🔍 Ready for Review

#3839 chore: refactor conversations list
  js/packages/components/main/home/Conversations.tsx
Labels: 🔍 Ready for Review, chore
