Repository berty/berty, pull requests merged in 2021-01, with the labels that each got.

#2973 chore(js): update README.md
  js/README.md
Labels: chore

#2978 chore: happy new year
  COPYRIGHT
  LICENSE-APACHE
  LICENSE-MIT
  README.md
Labels: chore

#2974 feat: allow stream on bertyaccount
  api/bertyaccount.proto
  api/bertybridge.proto
  api/go-internal/testutil.proto
  docs/architecture/2020-11-27-adr-gomobile-ipfs.md
  docs/gen.sum
  go/Makefile
  go/framework/bertybridge/blackbox_test.go
  go/framework/bertybridge/bridge.go
  go/gen.sum
  go/internal/testutil/service.go
  go/internal/testutil/testutil.pb.go
  go/pkg/bertyaccount/bertyaccount.pb.go
  go/pkg/bertyaccount/service.go
  go/pkg/bertyaccount/service_account.go
  go/pkg/bertyaccount/service_grpc.go
  go/pkg/bertybridge/bertybridge.pb.go
  go/pkg/bertybridge/service.go
  go/pkg/bertybridge/service_clients.go
  go/pkg/bertybridge/service_grpc.go
  go/pkg/bertybridge/service_test.go
  js/Makefile
  js/gen.sum
  js/packages/api/index.d.ts
  js/packages/api/index.js
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  js/packages/grpc-bridge/error.ts
  js/packages/grpc-bridge/rpc/rpc.bridge.ts
  js/packages/grpc-bridge/welsh-clients.gen.ts
  js/packages/store/providerEffects.ts
Labels: WIP, enhancement

#2984 feat: reenable tor on iOS
  js/Makefile
  tool/go.mod
  tool/go.sum
Labels: enhancement

#2983 chore: New Crowdin updates
  js/packages/berty-i18n/locale/af-ZA/messages.json
  js/packages/berty-i18n/locale/ar-SA/messages.json
  js/packages/berty-i18n/locale/bg-BG/messages.json
  js/packages/berty-i18n/locale/ca-ES/messages.json
  js/packages/berty-i18n/locale/cs-CZ/messages.json
  js/packages/berty-i18n/locale/da-DK/messages.json
  js/packages/berty-i18n/locale/de-DE/messages.json
  js/packages/berty-i18n/locale/el-GR/messages.json
  js/packages/berty-i18n/locale/es-ES/messages.json
  js/packages/berty-i18n/locale/fi-FI/messages.json
  js/packages/berty-i18n/locale/he-IL/messages.json
  js/packages/berty-i18n/locale/hu-HU/messages.json
  js/packages/berty-i18n/locale/id-ID/messages.json
  js/packages/berty-i18n/locale/it-IT/messages.json
  js/packages/berty-i18n/locale/ja-JP/messages.json
  js/packages/berty-i18n/locale/ko-KR/messages.json
  js/packages/berty-i18n/locale/nl-NL/messages.json
  js/packages/berty-i18n/locale/no-NO/messages.json
  js/packages/berty-i18n/locale/pl-PL/messages.json
  js/packages/berty-i18n/locale/pt-BR/messages.json
  js/packages/berty-i18n/locale/pt-PT/messages.json
  js/packages/berty-i18n/locale/ro-RO/messages.json
  js/packages/berty-i18n/locale/ru-RU/messages.json
  js/packages/berty-i18n/locale/sl-SI/messages.json
  js/packages/berty-i18n/locale/sr-Cyrl/messages.json
  js/packages/berty-i18n/locale/sv-SE/messages.json
  js/packages/berty-i18n/locale/tr-TR/messages.json
  js/packages/berty-i18n/locale/uk-UA/messages.json
  js/packages/berty-i18n/locale/vi-VN/messages.json
  js/packages/berty-i18n/locale/zh-CN/messages.json
  js/packages/berty-i18n/locale/zh-TW/messages.json
Labels: chore

#2989 fix: in memory database
  go/internal/initutil/datastore.go
Labels: bug

#3012 fix: android build on CI with ndk22
  .github/workflows/android.yml
Labels: bug, echoes/throughput

#2936 fix: state machine to support new multi-account UI/UX
  js/packages/components/avatars.tsx
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/gates.tsx
  js/packages/components/main/Home.tsx
  js/packages/components/main/home/Conversations.tsx
  js/packages/components/main/home/Footer.tsx
  js/packages/components/main/home/Header.tsx
  js/packages/components/main/home/Home.tsx
  js/packages/components/main/home/HomeModal.tsx
  js/packages/components/main/home/MultiAccount.tsx
  js/packages/components/main/home/Requests.tsx
  js/packages/components/main/home/Search.tsx
  js/packages/components/main/home/UnreadCount.tsx
  js/packages/components/main/index.ts
  js/packages/components/modals/DeleteAccount.tsx
  js/packages/components/onboarding/AccountSelector.tsx
  js/packages/components/onboarding/GetStarted.tsx
  js/packages/components/onboarding/index.ts
  js/packages/components/settings/Home.tsx
  js/packages/components/shared-components/DropDownPicker.tsx
  js/packages/messenger-app/App.tsx
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
  js/packages/store/context.ts
  js/packages/store/hooks.ts
  js/packages/store/provider.tsx
  js/packages/store/providerCallbacks.ts
  js/packages/store/providerEffects.ts
  js/packages/store/providerReducer.ts
Labels: bug, echoes/risks

#2991 chore: new Crowdin updates
  js/packages/berty-i18n/locale/cs-CZ/messages.json
  js/packages/berty-i18n/locale/es-ES/messages.json
  js/packages/berty-i18n/locale/nl-NL/messages.json
  js/packages/berty-i18n/locale/pt-BR/messages.json
  js/packages/berty-i18n/locale/sl-SI/messages.json
  js/packages/berty-i18n/locale/sv-SE/messages.json
Labels: chore

#3020 fix(messenger): replace EOF checks
  js/packages/components/settings/DevTools.tsx
  js/packages/components/utils.ts
  js/packages/store/providerEffects.ts
  js/packages/store/services.tsx
Labels: bug

#3021 chore: cleanup assets and iOS project
  js/Makefile
  js/assets/bootsplash_logo.png
  js/assets/bootsplash_logo@1,5x.png
  js/assets/bootsplash_logo@2x.png
  js/assets/bootsplash_logo@3x.png
  js/assets/bootsplash_logo@4x.png
  js/assets/font/OpenSans-Bold.ttf
  js/assets/font/OpenSans-BoldItalic.ttf
  js/assets/font/OpenSans-ExtraBold.ttf
  js/assets/font/OpenSans-ExtraBoldItalic.ttf
  js/assets/font/OpenSans-Italic.ttf
  js/assets/font/OpenSans-Light.ttf
  js/assets/font/OpenSans-LightItalic.ttf
  js/assets/font/OpenSans-Regular.ttf
  js/assets/font/OpenSans-SemiBold.ttf
  js/assets/font/OpenSans-SemiBoldItalic.ttf
  js/assets/sound/contact_request_accepted.mp3
  js/assets/sound/contact_request_received.mp3
  js/assets/sound/contact_request_sent.mp3
  js/assets/sound/group_created.mp3
  js/assets/sound/message_received.mp3
  js/assets/sound/message_sent.mp3
  js/ios/berty.yaml
  js/packages/components/sounds.ts
Labels: chore, echoes/chores, t/js

#2992 feat: bergy
  .github/workflows/go.yml
  .github/workflows/release.yml
  .gitignore
  .goreleaser.yml
  go.mod
  go.sum
  go/cmd/berty/gui.go
  go/cmd/berty/gui/account.go
  go/cmd/berty/gui/app.go
  go/cmd/berty/gui/contacts.go
  go/cmd/berty/gui/conversations.go
  go/cmd/berty/gui/interactions.go
  go/cmd/berty/gui/main.go
  go/cmd/berty/gui/mchelper.go
  go/cmd/berty/gui/multimember.go
  go/cmd/berty/gui/store.go
  go/cmd/berty/gui/utils.go
  go/cmd/berty/main.go
  go/cmd/berty/noopgui.go
Labels: echoes/throughput, echoes/users, enhancement

#3026 chore: New Crowdin updates
  js/packages/berty-i18n/locale/el-GR/messages.json
Labels: chore

#3019 feat: swipe improvement and contact already added error message
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/components/main/home/HomeModal.tsx
  js/packages/components/modals/AddThisContact.tsx
  js/packages/components/modals/InvalidScan.tsx
  js/packages/components/modals/ManageDeepLink.tsx
  js/packages/components/modals/ManageGroupInvitation.tsx
Labels: enhancement

#3031 fix: fix module resolver
  js/alias.js
  js/babel.config.js
  js/tsconfig.json
Labels: bug

#3037 fix: typo in betabot
  go/cmd/betabot/main.go
Labels: bug

#3040 chore: update gomobile ipfs doc
  docs/architecture/2020-11-27-adr-gomobile-ipfs.md
  go/Makefile
Labels: chore

#3030 chore: new Crowdin updates
  js/packages/berty-i18n/locale/af-ZA/messages.json
  js/packages/berty-i18n/locale/ar-SA/messages.json
  js/packages/berty-i18n/locale/bg-BG/messages.json
  js/packages/berty-i18n/locale/ca-ES/messages.json
  js/packages/berty-i18n/locale/cs-CZ/messages.json
  js/packages/berty-i18n/locale/da-DK/messages.json
  js/packages/berty-i18n/locale/de-DE/messages.json
  js/packages/berty-i18n/locale/el-GR/messages.json
  js/packages/berty-i18n/locale/es-ES/messages.json
  js/packages/berty-i18n/locale/fi-FI/messages.json
  js/packages/berty-i18n/locale/fr-FR/messages.json
  js/packages/berty-i18n/locale/he-IL/messages.json
  js/packages/berty-i18n/locale/hu-HU/messages.json
  js/packages/berty-i18n/locale/id-ID/messages.json
  js/packages/berty-i18n/locale/it-IT/messages.json
  js/packages/berty-i18n/locale/ja-JP/messages.json
  js/packages/berty-i18n/locale/ko-KR/messages.json
  js/packages/berty-i18n/locale/nl-NL/messages.json
  js/packages/berty-i18n/locale/no-NO/messages.json
  js/packages/berty-i18n/locale/pl-PL/messages.json
  js/packages/berty-i18n/locale/pt-BR/messages.json
  js/packages/berty-i18n/locale/pt-PT/messages.json
  js/packages/berty-i18n/locale/ro-RO/messages.json
  js/packages/berty-i18n/locale/ru-RU/messages.json
  js/packages/berty-i18n/locale/sl-SI/messages.json
  js/packages/berty-i18n/locale/sr-Cyrl/messages.json
  js/packages/berty-i18n/locale/sv-SE/messages.json
  js/packages/berty-i18n/locale/tr-TR/messages.json
  js/packages/berty-i18n/locale/uk-UA/messages.json
  js/packages/berty-i18n/locale/vi-VN/messages.json
  js/packages/berty-i18n/locale/zh-CN/messages.json
  js/packages/berty-i18n/locale/zh-TW/messages.json
Labels: chore

#3032 chore(messenger): remove react-native-elements
  js/gen.sum
  js/package.json
  js/packages/components/chat/ReplicateGroupSettings.tsx
  js/yarn.lock
Labels: chore

#3000 feat(messenger): add IsCreator and IsMe fields to Member type
  api/errcode.proto
  api/messengertypes.proto
  docs/apis/messengertypes.md
  docs/apis/messengertypes.swagger.json
  docs/gen.sum
  go.sum
  go/cmd/berty/gui/conversations.go
  go/cmd/berty/gui/mchelper.go
  go/cmd/berty/gui/multimember.go
  go/cmd/berty/gui/store.go
  go/gen.sum
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/db_test.go
  go/pkg/bertymessenger/handlers.go
  go/pkg/bertymessenger/service_test.go
  go/pkg/bertymessenger/testing.go
  go/pkg/bertymessenger/util.go
  go/pkg/errcode/errcode.pb.go
  go/pkg/messengertypes/messengertypes.pb.go
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  js/packages/components/chat/MultiMemberSettings.tsx
Labels: echoes/throughput, enhancement

#3004 feat: add cellular / relay benchmark tool
  tool/bench-cellular/.gitignore
  tool/bench-cellular/Makefile
  tool/bench-cellular/bench.go
  tool/bench-cellular/client.go
  tool/bench-cellular/go.mod
  tool/bench-cellular/go.sum
  tool/bench-cellular/server.go
  tool/go.sum
Labels: echoes/risks, enhancement, experiment, optimization

#3044 chore: New Crowdin updates
  js/packages/berty-i18n/locale/ar-SA/messages.json
  js/packages/berty-i18n/locale/bg-BG/messages.json
  js/packages/berty-i18n/locale/de-DE/messages.json
  js/packages/berty-i18n/locale/it-IT/messages.json
  js/packages/berty-i18n/locale/ko-KR/messages.json
  js/packages/berty-i18n/locale/tr-TR/messages.json
Labels: chore

#3045 chore: display Podfile.lock diff in CI
  .github/workflows/ios.yml
Labels: chore

#3039 fix: some dev warnings
  js/packages/berty-i18n/index.ts
  js/packages/berty-i18n/locale/languages.js
  js/packages/components/chat/message/MessageMonitorMetadata.tsx
  js/packages/components/settings/AboutBerty.tsx
  js/packages/components/settings/AddDevConversations.tsx
  js/packages/components/settings/DevTools.tsx
  js/packages/components/settings/Help.tsx
  js/packages/components/settings/NetworkMap.tsx
  js/packages/store/context.ts
Labels: bug

#3054 fix(cli): check argv len before access
  go/cmd/berty/main.go
Labels: bug

#3059 fix(messenger): prevent overriding contact info with own info
  go/pkg/bertymessenger/handlers.go
Labels: bug

#3058 chore: fix various typos
  docs/Makefile
  docs/apis/protocoltypes.md
  docs/apis/protocoltypes.swagger.json
  docs/architecture/2020-11-27-adr-gomobile-ipfs.md
  docs/architecture/messenger-mvp/contact-request.mermaid
  docs/architecture/messenger-mvp/contact-request.mermaid.svg
  go/cmd/berty-doctor/rdvp.go
  go/cmd/betabot/main.go
  go/cmd/rdvp/main.go
  go/framework/bertybridge/bridge.go
  go/internal/ble-driver/CircularQueue.m
  go/internal/initutil/ipfs.go
  go/internal/initutil/manager.go
  go/internal/initutil/manager_test.go
  go/internal/ipfsutil/helpers_test.go
  go/internal/omnisearch/coordinator.go
  go/internal/omnisearch/ressources.go
  go/internal/tinder/driver_multi.go
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/service_test.go
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/protocoltypes/protocoltypes.pb.go
  js/Makefile
  js/ios/Berty/AppDelegate.m
Labels: chore

#3057 ci: update semantic release action to pull from ghcr
  .github/workflows/release.yml
Labels: ci
