Repository berty/berty, pull requests merged in 2021-09, with the labels that each got.

#3512 fix: push server register
  go/cmd/berty/push.go
  go/cmd/berty/replication.go
  go/internal/initutil/manager.go
  go/internal/initutil/node.go
  go/pkg/bertyprotocol/api_push.go
  go/pkg/bertyprotocol/api_services_auth.go
  go/pkg/bertyprotocol/service.go
Labels: bug, ✅ Approved

#3501 fix: kanban fixes
  js/package.json
  js/packages/berty-i18n/index.ts
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/berty-i18n/locale/fr-FR/messages.json
  js/packages/components/InfosChat.tsx
  js/packages/components/chat/MessageList.tsx
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/MultiMemberQR.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/common.tsx
  js/packages/components/chat/record/RecordComponent.tsx
  js/packages/components/gates.tsx
  js/packages/components/main/CreateGroupFooter.tsx
  js/packages/components/main/NetworkOptions.tsx
  js/packages/components/main/Permissions.tsx
  js/packages/components/main/Scan.tsx
  js/packages/components/main/home/Conversations.tsx
  js/packages/components/main/home/Home.tsx
  js/packages/components/main/home/Requests.tsx
  js/packages/components/modals/InvalidScan.tsx
  js/packages/components/modals/WelcomeConfiguration.tsx
  js/packages/components/modals/index.ts
  js/packages/components/onboarding/ChoosePreset.tsx
  js/packages/components/onboarding/CreateAccount.tsx
  js/packages/components/onboarding/GetStarted.tsx
  js/packages/components/onboarding/ServicesAuth.tsx
  js/packages/components/onboarding/SetupFinished.js
  js/packages/components/onboarding/SetupFinished.tsx
  js/packages/components/settings/Bluetooth.tsx
  js/packages/components/settings/DevTools.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/Mode.tsx
  js/packages/components/settings/MyBertyId.tsx
  js/packages/components/shared-components/ContactPicker.tsx
  js/packages/components/shared-components/KeyboardAvoidingView.tsx
  js/packages/components/utils.ts
  js/packages/messenger-app/App.test.tsx
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
  js/packages/store/context.ts
  js/packages/store/effectableCallbacks.ts
  js/packages/store/hooks.ts
  js/packages/store/provider.tsx
  js/packages/store/providerCallbacks.ts
  js/packages/store/providerEffects.ts
  js/packages/store/providerReducer.ts
  js/yarn.lock
Labels: bug, 🔍 Ready for Review

#3515 fix: keyboard avoiding and persistent input values
  js/packages/components/chat/MessageList.tsx
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/common.tsx
  js/packages/components/settings/ServicesAuth.tsx
Labels: bug, 🔍 Ready for Review

#3504 fix: add shadow color to themes
  js/packages/berty-i18n/index.ts
  js/packages/berty-i18n/locale/fr-FR/messages.json
  js/packages/components/NotificationBody.tsx
  js/packages/components/avatars.tsx
  js/packages/components/chat/MultiMemberQR.tsx
  js/packages/components/chat/file-uploads/AddFileMenu.tsx
  js/packages/components/chat/message/AudioMessage.tsx
  js/packages/components/chat/message/FileMessage.tsx
  js/packages/components/chat/message/MessageSystemWrapper.tsx
  js/packages/components/chat/message/PictureMessage.tsx
  js/packages/components/chat/message/UserMessageComponents.tsx
  js/packages/components/helpers.ts
  js/packages/components/main/CreateGroupAddMembers.tsx
  js/packages/components/main/CreateGroupFinalize.tsx
  js/packages/components/main/home/Home.tsx
  js/packages/components/main/home/MultiAccount.tsx
  js/packages/components/main/home/Requests.tsx
  js/packages/components/main/home/Search.tsx
  js/packages/components/modals/AddBot.js
  js/packages/components/modals/AddBot.tsx
  js/packages/components/modals/AddThisContact.tsx
  js/packages/components/modals/InvalidScan.tsx
  js/packages/components/modals/ManageDeepLink.tsx
  js/packages/components/modals/ManageGroupInvitation.tsx
  js/packages/components/modals/ThemeColorName.tsx
  js/packages/components/onboarding/SwiperCard.tsx
  js/packages/components/settings/DeleteAccount.tsx
  js/packages/components/settings/EditProfile.tsx
  js/packages/components/settings/MyBertyId.tsx
  js/packages/components/shared-components/DropDownPicker.tsx
  js/packages/components/shared-components/Modal.tsx
  js/packages/components/shared-components/Request.tsx
  js/packages/components/shared-components/SettingsButtons.tsx
  js/packages/store/provider.tsx
  js/packages/store/providerEffects.ts
  js/packages/styles/colors.json
  js/packages/styles/darktheme-default.json
  js/packages/styles/pinktheme-default.json
  js/patches/rn-fetch-blob+0.12.0.patch
Labels: bug, 🔍 Ready for Review

#3525 feat: bump libp2p
  .github/workflows/go.yml
  go.mod
  go.sum
  go/cmd/berty/push.go
  go/cmd/rdvp/main.go
  go/internal/initutil/manager_test.go
  go/internal/initutil/metrics.go
  go/internal/ipfsutil/keystore_datastore.go
  go/internal/ipfsutil/mdns_discovery.go
  go/internal/ipfsutil/repo.go
  go/internal/ipfsutil/testing.go
  go/internal/logutil/logutil.go
  go/pkg/bertyprotocol/account_export.go
  go/pkg/bertyprotocol/api_services_auth.go
  go/pkg/bertyprotocol/keystore_device.go
  go/pkg/bertyprotocol/orbitdb.go
  go/pkg/bertyprotocol/orbitdb_signed_entry_identity_provider.go
  go/pkg/bertyprotocol/orbitdb_utils_test.go
  js/android/build.gradle
  js/gen.sum
  js/package.json
  js/packages/components/settings/ThemeEditor.tsx
  js/packages/store/services.tsx
  js/packages/store/types.gen.ts
  js/patches/rn-fetch-blob+0.12.0.patch
  js/yarn.lock
Labels: 🔍 Ready for Review, enhancement, WIP

#3516 fix: UI when we have requests and no requests
  js/packages/components/main/home/Conversations.tsx
  js/packages/components/main/home/Header.tsx
  js/packages/components/main/home/Home.tsx
  js/packages/components/main/home/Requests.tsx
  js/packages/components/main/home/UnreadCount.tsx
Labels: bug, 🔍 Ready for Review

#3535 fix: booleanize variable
  js/packages/components/main/home/Home.tsx
Labels: bug, 🔍 Ready for Review

#3540 chore: use the same tee logger for ipfs/go-log
  go.mod
  go.sum
  go/internal/logutil/logutil.go
  tool/go.sum
Labels: ✅ Approved, chore

#3543 fix: bump js libs
  js/ios/Podfile.lock
  js/package.json
  js/packages/messenger-app/App.test.tsx
  js/yarn.lock
Labels: bug, 🔍 Ready for Review

#3533 fix: qr size was cut on large screen
  js/packages/components/main/home/Home.tsx
  js/packages/components/settings/MyBertyId.tsx
  js/packages/components/shared-components/TabBar.tsx
Labels: bug, 🔍 Ready for Review

#3544 New Crowdin updates
  js/packages/berty-i18n/locale/af-ZA/messages.json
  js/packages/berty-i18n/locale/ar-SA/messages.json
  js/packages/berty-i18n/locale/bg-BG/messages.json
  js/packages/berty-i18n/locale/ca-ES/messages.json
  js/packages/berty-i18n/locale/cs-CZ/messages.json
  js/packages/berty-i18n/locale/da-DK/messages.json
  js/packages/berty-i18n/locale/de-DE/messages.json
  js/packages/berty-i18n/locale/el-GR/messages.json
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/berty-i18n/locale/es-ES/messages.json
  js/packages/berty-i18n/locale/et-EE/messages.json
  js/packages/berty-i18n/locale/fi-FI/messages.json
  js/packages/berty-i18n/locale/fr-FR/messages.json
  js/packages/berty-i18n/locale/he-IL/messages.json
  js/packages/berty-i18n/locale/hi-IN/messages.json
  js/packages/berty-i18n/locale/hu-HU/messages.json
  js/packages/berty-i18n/locale/id-ID/messages.json
  js/packages/berty-i18n/locale/it-IT/messages.json
  js/packages/berty-i18n/locale/ja-JP/messages.json
  js/packages/berty-i18n/locale/ka-GE/messages.json
  js/packages/berty-i18n/locale/ko-KR/messages.json
  js/packages/berty-i18n/locale/my-MM/messages.json
  js/packages/berty-i18n/locale/nl-NL/messages.json
  js/packages/berty-i18n/locale/no-NO/messages.json
  js/packages/berty-i18n/locale/pl-PL/messages.json
  js/packages/berty-i18n/locale/pt-BR/messages.json
  js/packages/berty-i18n/locale/pt-PT/messages.json
  js/packages/berty-i18n/locale/ro-RO/messages.json
  js/packages/berty-i18n/locale/ru-RU/messages.json
  js/packages/berty-i18n/locale/sl-SI/messages.json
  js/packages/berty-i18n/locale/sr-Cyrl/messages.json
  js/packages/berty-i18n/locale/sv-SE/messages.json
  js/packages/berty-i18n/locale/te-IN/messages.json
  js/packages/berty-i18n/locale/tr-TR/messages.json
  js/packages/berty-i18n/locale/uk-UA/messages.json
  js/packages/berty-i18n/locale/vi-VN/messages.json
  js/packages/berty-i18n/locale/zh-CN/messages.json
  js/packages/berty-i18n/locale/zh-TW/messages.json
Labels: 🔍 Ready for Review, ✅ Approved

#3500 feat: refactor tyber streaming to be asynchronous
  Makefile
  go.mod
  go.sum
  go/framework/bertybridge/config.go
  go/internal/initutil/logger.go
  go/internal/initutil/manager.go
  go/internal/logutil/logutil.go
  go/internal/logutil/stream.go
  go/internal/logutil/tyber.go
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/api_test.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertymessenger/testing.go
  js/android/app/src/main/java/tech/berty/gobridge/GoBridgeModule.java
  js/gen.sum
  js/ios/Berty/Sources/Bridge/GoBridge.m
  js/ios/Berty/Sources/Bridge/GoBridge.swift
  js/packages/go-bridge/types.ts
  js/packages/store/providerEffects.ts
  tool/go.sum
  tool/tyber/go/go.sum
Labels: 🔍 Ready for Review, enhancement
