Repository berty/berty, pull requests merged in 2021-07, with the labels that each got.

#3406 New Crowdin updates
  js/packages/berty-i18n/locale/de-DE/messages.json
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/berty-i18n/locale/ko-KR/messages.json
Labels: 🔍 Ready for Review

#3405 fix: android export account
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/db_test.go
  go/pkg/bertymessenger/service.go
  js/android/app/src/main/AndroidManifest.xml
  js/global.d.ts
  js/ios/Podfile.lock
  js/package.json
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/components/helpers.ts
  js/packages/components/main/home/MultiAccount.tsx
  js/packages/components/onboarding/CreateAccount.js
  js/packages/components/settings/Mode.tsx
  js/packages/store/providerEffects.ts
  js/packages/store/services.tsx
  js/yarn.lock
Labels: bug, 🔍 Ready for Review

#3422 feat: make iOS build compatible with arm64 simulator and catalyst
  .github/workflows/ios.yml
  go.mod
  go.sum
  go/internal/multipeer-connectivity-driver/bridge_darwin.go
  go/internal/multipeer-connectivity-driver/bridge_unsupported.go
  go/internal/multipeer-connectivity-driver/driver/MCManager.h
  go/internal/multipeer-connectivity-driver/driver/MCManager.m
  go/internal/multipeer-connectivity-driver/driver/cgo_bridge.go
  go/internal/multipeer-connectivity-driver/driver/mc-driver.h
  go/internal/multipeer-connectivity-driver/driver/mc-driver.m
  go/pkg/username/ios.go
  go/pkg/username/others.go
  js/Makefile
  js/gen.sum
  js/ios/berty.yaml
  js/ios/info.yaml
Labels: enhancement, 🔍 Ready for Review

#3416 chore: update android prominent disclosure to comply with Play Store rules
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/berty-i18n/locale/fr-FR/messages.json
Labels: chore, 🔍 Ready for Review

#3410 fix: onboarding without node
  api/bertyaccount.proto
  api/messengertypes.proto
  api/messengertypes.yaml
  go/gen.sum
  go/pkg/bertyaccount/bertyaccount.pb.go
  go/pkg/bertyaccount/service_account.go
  go/pkg/bertymessenger/api.go
  go/pkg/messengertypes/messengertypes.pb.go
  go/pkg/messengertypes/messengertypes.pb.gw.go
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  js/packages/components/main/home/MultiAccount.tsx
  js/packages/components/onboarding/ChoosePreset.tsx
  js/packages/components/onboarding/CreateAccount.js
  js/packages/components/onboarding/GetStarted.tsx
  js/packages/components/onboarding/SetupFinished.js
  js/packages/components/settings/Bluetooth.tsx
  js/packages/grpc-bridge/welsh-clients.gen.ts
  js/packages/navigation/stacks.tsx
  js/packages/store/context.ts
  js/packages/store/effectableCallbacks.ts
  js/packages/store/provider.tsx
  js/packages/store/providerEffects.ts
  js/packages/store/providerReducer.ts
  js/packages/store/types.gen.ts
Labels: bug, 🔍 Ready for Review

#3425 feat: add BertyAccount.ImportWithProgress alternative endpoint
  api/bertyaccount.proto
  docs/apis/messengertypes.md
  docs/apis/messengertypes.swagger.json
  docs/gen.sum
  go/gen.sum
  go/pkg/bertyaccount/bertyaccount.pb.go
  go/pkg/bertyaccount/blackbox_test.go
  go/pkg/bertyaccount/service.go
  go/pkg/bertyaccount/service_account.go
  go/pkg/bertyaccount/service_grpc.go
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  js/packages/grpc-bridge/welsh-clients.gen.ts
Labels: enhancement, 🔍 Ready for Review

#3389 feat: Import ios/android BLE drivers from dev repo
  go/framework/bertybridge/bridge.go
  go/framework/bertybridge/config.go
  go/framework/bertybridge/proximity_driver.go
  go/internal/androidnearby/bridge_android.go
  go/internal/androidnearby/bridge_unsupported.go
  go/internal/ble-driver/BertyDevice_darwin.h
  go/internal/ble-driver/BertyDevice_darwin.m
  go/internal/ble-driver/BleInterface_darwin.m
  go/internal/ble-driver/BleManager_darwin.h
  go/internal/ble-driver/BleManager_darwin.m
  go/internal/ble-driver/BleQueue.h
  go/internal/ble-driver/BleQueue.m
  go/internal/ble-driver/ConnectedPeer.h
  go/internal/ble-driver/ConnectedPeer.m
  go/internal/ble-driver/CountDownLatch_darwin.m
  go/internal/ble-driver/PeerManager.h
  go/internal/ble-driver/PeerManager.m
  go/internal/ble-driver/TaskDelay.h
  go/internal/ble-driver/TaskDelay.m
  go/internal/ble-driver/bridge_android.go
  go/internal/ble-driver/bridge_darwin.go
  go/internal/ble-driver/bridge_unsupported.go
  go/internal/initutil/ipfs.go
  go/internal/initutil/manager.go
  go/internal/multipeer-connectivity-driver/bridge_darwin.go
  go/internal/multipeer-connectivity-driver/bridge_unsupported.go
  go/internal/proximitytransport/proximitydriver.go
  go/internal/proximitytransport/transport.go
  go/pkg/bertyaccount/service.go
  js/android/app/src/main/java/tech/berty/gobridge/BertyNearbyDriver.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/Advertiser.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/BleDriver.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/BleInterface.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/BleQueue.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/DeviceManager.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/GattServer.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/GattServerCallback.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/Peer.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/PeerDevice.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/PeerManager.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/Scanner.java
  js/android/app/src/main/java/tech/berty/gobridge/nearbydriver/base/NearbyDriver.java
  js/android/app/src/main/java/tech/berty/gobridge/nearbydriver/lifecycle/UserAcceptCallback.java
  js/android/app/src/main/java/tech/berty/gobridge/nearbydriver/lifecycle/UserConnectionCallback.java
  js/android/app/src/main/java/tech/berty/gobridge/nearbydriver/lifecycle/UserMessageCallback.java
  js/android/app/src/main/java/tech/berty/gobridge/nearbydriver/lifecycle/UserRequestCallback.java
  js/android/app/src/main/java/tech/berty/gobridge/nearbydriver/lifecycle/UserSearchCallback.java
  js/android/app/src/main/java/tech/berty/gobridge/nearbydriver/model/Endpoint.java
  js/android/app/src/main/java/tech/berty/gobridge/nearbydriver/util/BertyLogger.java
  js/packages/store/providerEffects.ts
Labels: enhancement, 🔍 Ready for Review

#3431 fix: remove inappbrowser hack
  js/ios/Podfile.lock
  js/packages/store/services.tsx
  js/yarn.lock
Labels: bug, ✅ Approved

#3407 feat: tyber discovery + removed tracer package
  api/messengertypes.proto
  api/messengertypes.yaml
  docs/apis/messengertypes.md
  docs/apis/messengertypes.swagger.json
  docs/gen.sum
  go.mod
  go.sum
  go/cmd/berty/main.go
  go/cmd/berty/mini/view_group.go
  go/cmd/berty/scenario_test.go
  go/gen.sum
  go/internal/initutil/logger.go
  go/internal/initutil/manager.go
  go/internal/initutil/manager_test.go
  go/internal/initutil/node.go
  go/internal/initutil/orbitdb.go
  go/internal/omnisearch/manager.go
  go/internal/tracer/bertytypes_header.go
  go/internal/tracer/runtime.go
  go/internal/tracer/testing.go
  go/internal/tracer/tracer.go
  go/pkg/bertyaccount/service_account.go
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/service_non_mocked_test.go
  go/pkg/bertyprotocol/api_event.go
  go/pkg/bertyprotocol/keystore_message.go
  go/pkg/bertyprotocol/keystore_message_utils.go
  go/pkg/bertyprotocol/keystore_message_utils_test.go
  go/pkg/bertyprotocol/orbitdb.go
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/bertyprotocol/store_message.go
  go/pkg/bertyprotocol/testing.go
  go/pkg/messengertypes/messengertypes.pb.go
  go/pkg/messengertypes/messengertypes.pb.gw.go
  js/gen.sum
  js/ios/Podfile.lock
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/components/settings/DevTools.tsx
  js/packages/go-bridge/defaults.ts
  js/packages/grpc-bridge/welsh-clients.gen.ts
  js/packages/store/providerEffects.ts
  js/packages/store/types.gen.ts
  tool/go.sum
  tool/tyber/go/bridge/bridge.go
  tool/tyber/go/bridge/jstogo.go
  tool/tyber/go/cmd/websocket/main.go
  tool/tyber/go/config/config.go
  tool/tyber/go/config/settings.go
  tool/tyber/go/go.mod
  tool/tyber/go/go.sum
  tool/tyber/go/main.go
  tool/tyber/js/app/components/MainPanel.tsx
Labels: enhancement, 🔍 Ready for Review

#3437 fix(android): remove native exception catcher to get crashlytics report
  js/packages/components/error.tsx
Labels: bug, ✅ Approved

#3432 fix: remove giphy integration
  js/packages/components/chat/file-uploads/AddFileMenu.tsx
  js/packages/components/chat/file-uploads/GifSection.tsx
Labels: bug, 🔍 Ready for Review

#3439 fix: tyber hang
  go/internal/logutil/logutil.go
Labels: bug, ✅ Approved

#3446 docs: update bertyaccount.proto
  api/bertyaccount.proto
Labels: documentation, 🔍 Ready for Review

#3455 chore: small .proto fix + regenerate
  api/bertyaccount.proto
  docs/gen.sum
  go/gen.sum
  go/pkg/bertyaccount/bertyaccount.pb.go
  js/gen.sum
Labels: chore, 🔍 Ready for Review

#3444 chore(ci): merge ios jobs
  .github/workflows/ios.yml
Labels: chore, ✅ Approved

#3438 New Crowdin updates
  js/packages/berty-i18n/locale/af-ZA/messages.json
  js/packages/berty-i18n/locale/ar-SA/messages.json
  js/packages/berty-i18n/locale/bg-BG/messages.json
  js/packages/berty-i18n/locale/ca-ES/messages.json
  js/packages/berty-i18n/locale/cs-CZ/messages.json
  js/packages/berty-i18n/locale/da-DK/messages.json
  js/packages/berty-i18n/locale/de-DE/messages.json
  js/packages/berty-i18n/locale/el-GR/messages.json
  js/packages/berty-i18n/locale/es-ES/messages.json
  js/packages/berty-i18n/locale/et-EE/messages.json
  js/packages/berty-i18n/locale/fi-FI/messages.json
  js/packages/berty-i18n/locale/fr-FR/messages.json
  js/packages/berty-i18n/locale/he-IL/messages.json
  js/packages/berty-i18n/locale/hi-IN/messages.json
  js/packages/berty-i18n/locale/hu-HU/messages.json
  js/packages/berty-i18n/locale/id-ID/messages.json
  js/packages/berty-i18n/locale/it-IT/messages.json
  js/packages/berty-i18n/locale/ja-JP/messages.json
  js/packages/berty-i18n/locale/ka-GE/messages.json
  js/packages/berty-i18n/locale/ko-KR/messages.json
  js/packages/berty-i18n/locale/nl-NL/messages.json
  js/packages/berty-i18n/locale/no-NO/messages.json
  js/packages/berty-i18n/locale/pl-PL/messages.json
  js/packages/berty-i18n/locale/pt-BR/messages.json
  js/packages/berty-i18n/locale/pt-PT/messages.json
  js/packages/berty-i18n/locale/ro-RO/messages.json
  js/packages/berty-i18n/locale/ru-RU/messages.json
  js/packages/berty-i18n/locale/sl-SI/messages.json
  js/packages/berty-i18n/locale/sr-Cyrl/messages.json
  js/packages/berty-i18n/locale/sv-SE/messages.json
  js/packages/berty-i18n/locale/te-IN/messages.json
  js/packages/berty-i18n/locale/tr-TR/messages.json
  js/packages/berty-i18n/locale/uk-UA/messages.json
  js/packages/berty-i18n/locale/vi-VN/messages.json
  js/packages/berty-i18n/locale/zh-CN/messages.json
  js/packages/berty-i18n/locale/zh-TW/messages.json
Labels: ✅ Approved

#3429 permission view
  js/global.d.ts
  js/packages/assets/audio-lottie.json
  js/packages/assets/camera-lottie.json
  js/packages/assets/notification-lottie.json
  js/packages/assets/p2p-lottie.json
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/components/chat/common.tsx
  js/packages/components/chat/record/RecordComponent.tsx
  js/packages/components/main/NetworkOptions.tsx
  js/packages/components/main/Permissions.tsx
  js/packages/components/main/Scan.tsx
  js/packages/components/main/bluetooth.ts
  js/packages/components/main/home/Conversations.tsx
  js/packages/components/main/index.ts
  js/packages/components/modals/WelcomeConfiguration.tsx
  js/packages/components/onboarding/CreateAccount.js
  js/packages/components/onboarding/ServicesAuth.tsx
  js/packages/components/utils.ts
  js/packages/navigation/hook.ts
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
Labels: WIP, ✅ Approved

#3385 feat: add none routing opt
  go/internal/initutil/ipfs.go
  js/packages/go-bridge/defaults.ts
Labels: WIP, enhancement, ✅ Approved

#3462 feat: update permissions animation files
  js/packages/assets/audio-lottie.json
  js/packages/assets/camera-lottie.json
  js/packages/assets/notification-lottie.json
Labels: enhancement, 🔍 Ready for Review

#3443 feat: in app network config management
  api/bertyaccount.proto
  docs/gen.sum
  go/framework/bertybridge/bridge.go
  go/framework/bertybridge/driver_notification.go
  go/gen.sum
  go/internal/config/config.go
  go/internal/initutil/ipfs.go
  go/internal/ipfsutil/pubsub_adaptater.go
  go/internal/ipfsutil/testing.go
  go/pkg/bertyaccount/bertyaccount.pb.go
  go/pkg/bertyaccount/service.go
  go/pkg/bertyaccount/service_account.go
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/components/main/NetworkOptions.tsx
  js/packages/components/main/Permissions.tsx
  js/packages/components/main/home/Conversations.tsx
  js/packages/components/main/home/MultiAccount.tsx
  js/packages/components/modals/WelcomeConfiguration.tsx
  js/packages/components/onboarding/ChoosePreset.tsx
  js/packages/components/onboarding/CreateAccount.js
  js/packages/components/settings/Bluetooth.tsx
  js/packages/components/settings/DevTools.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/Mode.tsx
  js/packages/components/settings/SystemInfo.tsx
  js/packages/go-bridge/defaults.ts
  js/packages/grpc-bridge/welsh-clients.gen.ts
  js/packages/store/context.ts
  js/packages/store/effectableCallbacks.ts
  js/packages/store/hooks.ts
  js/packages/store/provider.tsx
  js/packages/store/providerEffects.ts
Labels: enhancement, 🔍 Ready for Review

#3470 fix: BLE crashes
  go/internal/ble-driver/BleInterface_darwin.m
  go/internal/ble-driver/BleManager_darwin.h
  go/internal/ble-driver/BleManager_darwin.m
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/BleDriver.java
Labels: bug, ✅ Approved

#3468 fix: quick fixes
  js/packages/components/avatars.tsx
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/MultiMemberSettings.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/message/MessageSystemWrapper.tsx
  js/packages/components/chat/message/QuickReplyOptions.tsx
  js/packages/components/chat/message/UserMessageComponents.tsx
  js/packages/components/main/home/Conversations.tsx
  js/packages/components/main/home/Header.tsx
  js/packages/components/main/home/Home.tsx
  js/packages/components/main/home/Search.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/shared-components/DropDownPicker.tsx
  js/packages/components/shared-components/HintBody.js
  js/packages/store/context.ts
  js/packages/store/hooks.ts
Labels: bug, 🔍 Ready for Review
