Repository berty/berty, pull requests merged in 2021-02, with the labels that each got.

#3060 chore: update connect HTML template
  go/pkg/bertyprotocol/services_auth_templates.go
Labels: chore

#3061 chore(messenger): bump js
  js/ios/Podfile.lock
  js/package.json
  js/yarn.lock
Labels: chore

#3013 feat: UI/UX multi account
  api/bertyaccount.proto
  api/errcode.proto
  go/gen.sum
  go/pkg/bertyaccount/bertyaccount.pb.go
  go/pkg/bertyaccount/service_account.go
  go/pkg/errcode/errcode.pb.go
  go/pkg/protocoltypes/protocoltypes.pb.go
  js/Makefile
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/components/avatars.tsx
  js/packages/components/gates.tsx
  js/packages/components/main/home/Header.tsx
  js/packages/components/main/home/Home.tsx
  js/packages/components/main/home/MultiAccount.tsx
  js/packages/components/onboarding/CreateAccount.js
  js/packages/components/settings/EditProfile.tsx
  js/packages/components/shared-components/SwipeNavRecognizer.tsx
  js/packages/grpc-bridge/welsh-clients.gen.ts
  js/packages/store/context.ts
  js/packages/store/provider.tsx
  js/packages/store/providerCallbacks.ts
  js/packages/store/providerEffects.ts
  js/packages/store/providerReducer.ts
Labels: echoes/users, enhancement

#3063 fix(replication): "Connect" button click logic
  go/pkg/bertyprotocol/services_auth_templates.go
Labels: bug

#3073 fix(messenger): remove crashlytics devtool
  js/packages/components/settings/DevTools.tsx
Labels: bug

#3065 refactor(messenger): rename Interaction.IsMe into Interaction.IsMine
  api/messengertypes.proto
  docs/apis/messengertypes.md
  docs/apis/messengertypes.swagger.json
  docs/apis/protocoltypes.md
  docs/apis/protocoltypes.swagger.json
  docs/gen.sum
  go/cmd/berty/gui/interactions.go
  go/cmd/betabot/main.go
  go/gen.sum
  go/pkg/bertybot/context.go
  go/pkg/bertybot/handlers.go
  go/pkg/bertybot/recipes.go
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/db_test.go
  go/pkg/bertymessenger/handlers.go
  go/pkg/bertymessenger/service_test.go
  go/pkg/messengertypes/messengertypes.pb.go
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
Labels: refactor

#3068 chore: new Crowdin updates
  js/packages/berty-i18n/locale/af-ZA/messages.json
  js/packages/berty-i18n/locale/ar-SA/messages.json
  js/packages/berty-i18n/locale/bg-BG/messages.json
  js/packages/berty-i18n/locale/ca-ES/messages.json
  js/packages/berty-i18n/locale/cs-CZ/messages.json
  js/packages/berty-i18n/locale/da-DK/messages.json
  js/packages/berty-i18n/locale/de-DE/messages.json
  js/packages/berty-i18n/locale/el-GR/messages.json
  js/packages/berty-i18n/locale/es-ES/messages.json
  js/packages/berty-i18n/locale/fi-FI/messages.json
  js/packages/berty-i18n/locale/fr-FR/messages.json
  js/packages/berty-i18n/locale/he-IL/messages.json
  js/packages/berty-i18n/locale/hu-HU/messages.json
  js/packages/berty-i18n/locale/id-ID/messages.json
  js/packages/berty-i18n/locale/it-IT/messages.json
  js/packages/berty-i18n/locale/ja-JP/messages.json
  js/packages/berty-i18n/locale/ko-KR/messages.json
  js/packages/berty-i18n/locale/nl-NL/messages.json
  js/packages/berty-i18n/locale/no-NO/messages.json
  js/packages/berty-i18n/locale/pl-PL/messages.json
  js/packages/berty-i18n/locale/pt-BR/messages.json
  js/packages/berty-i18n/locale/pt-PT/messages.json
  js/packages/berty-i18n/locale/ro-RO/messages.json
  js/packages/berty-i18n/locale/ru-RU/messages.json
  js/packages/berty-i18n/locale/sl-SI/messages.json
  js/packages/berty-i18n/locale/sr-Cyrl/messages.json
  js/packages/berty-i18n/locale/sv-SE/messages.json
  js/packages/berty-i18n/locale/tr-TR/messages.json
  js/packages/berty-i18n/locale/uk-UA/messages.json
  js/packages/berty-i18n/locale/vi-VN/messages.json
  js/packages/berty-i18n/locale/zh-CN/messages.json
  js/packages/berty-i18n/locale/zh-TW/messages.json
Labels: chore

#3080 Revert "fix: android build on CI with ndk22"
  .github/workflows/android.yml
Labels: bug, echoes/throughput

#3083 fix: prog panic
  go/pkg/bertyaccount/service_account.go
  js/index.js
  js/packages/go-bridge/defaults.ts
  js/packages/go-bridge/logger.ts
Labels: bug

#3082 fix: invalid usage of progress channel lifecycle
  go/internal/initutil/manager.go
  go/pkg/bertyaccount/service_account.go
Labels: bug

#3087 fix(messenger): IsMine rebase fail
  js/packages/components/chat/message/MessageInvitation.tsx
  js/packages/components/chat/message/UserMessage.tsx
  js/packages/components/chat/message/UserMessageComponents.tsx
  js/packages/components/chat/message/index.tsx
  js/packages/components/main/home/Conversations.tsx
  js/packages/store/faker.js
Labels: bug

#3090 feat: improve logger
  js/packages/api/index.d.ts
  js/packages/go-bridge/logger.ts
  js/packages/grpc-bridge/error.ts
Labels: enhancement

#3092 fix: force protobuf (un)marshal methods generation in go to avoid using reflect
  api/bertyaccount.proto
  api/bertybridge.proto
  api/bertyreplication.proto
  api/errcode.proto
  docs/gen.sum
  go/gen.sum
  go/pkg/bertyaccount/bertyaccount.pb.go
  go/pkg/bertyaccount/blackbox_test.go
  go/pkg/bertyaccount/service_account_test.go
  go/pkg/bertybridge/bertybridge.pb.go
  go/pkg/bertyprotocol/bertyreplication.pb.go
  go/pkg/errcode/errcode.pb.go
Labels: bug

#3088 fix: hyperlink dot app domains
  js/global.d.ts
  js/package.json
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/components/chat/message/UserMessageComponents.tsx
  js/packages/components/settings/DevTools.tsx
  js/packages/go-bridge/defaults.ts
  js/packages/store/context.ts
  js/packages/store/providerEffects.ts
  js/yarn.lock
Labels: bug

#3097 chore(tool/tyber): fix go.mod
  tool/tyber/go/bridge/bridge.go
  tool/tyber/go/bridge/gotojs.go
  tool/tyber/go/config/config.go
  tool/tyber/go/go.mod
  tool/tyber/go/go.sum
  tool/tyber/go/main.go
  tool/tyber/go/parser/log.go
  tool/tyber/go/parser/parser.go
  tool/tyber/go/parser/session.go
  tool/tyber/go/parser/status.go
  tool/tyber/go/parser/trace.go
Labels: chore

#3111 fix(messenger): race and bad test
  go/pkg/bertymessenger/service_test.go
Labels: bug

#3024 feat: add gomobile ipfs
  api/errcode.proto
  docs/gen.sum
  go.mod
  go.sum
  go/framework/bertybridge/blackbox_test.go
  go/gen.sum
  go/internal/handshake/handshake_util_test.go
  go/internal/initutil/ipfs.go
  go/internal/initutil/manager.go
  go/internal/initutil/metrics.go
  go/internal/initutil/node.go
  go/internal/ipfsutil/api.go
  go/internal/ipfsutil/extended_core_api.go
  go/internal/ipfsutil/http_api.go
  go/internal/ipfsutil/mobile.go
  go/internal/ipfsutil/repo.go
  go/internal/ipfsutil/testing.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertyprotocol/testing.go
  go/pkg/errcode/errcode.pb.go
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
Labels: WIP, enhancement

#3125 chore: allow skipping if or running only if -race flag is provided/not provided
  go/internal/testutil/skip.go
  go/internal/testutil/skip_norace.go
  go/internal/testutil/skip_race.go
  go/internal/testutil/skip_test.go
Labels: chore

#3121 feat: shared-media
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/components/chat/MultiMemberSettings.tsx
  js/packages/components/chat/OneToOneSettings.tsx
  js/packages/components/chat/SharedMedias.tsx
  js/packages/components/chat/index.ts
  js/packages/components/chat/message/UserMessageComponents.tsx
  js/packages/navigation/hook.ts
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
Labels: enhancement
