Repository berty/berty, pull requests merged in 2021-05, with the labels that each got.

#3296 feat: berty service-key helper command, for replication and token service
  go/cmd/berty/main.go
  go/cmd/berty/servicekey.go
Labels: enhancement

#3288 feat: enable button add member in multiMemberSettings
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/components/chat/MultiMemberSettings.tsx
  js/packages/components/chat/MultiMembersSettingsAddMembers.tsx
  js/packages/components/chat/index.ts
  js/packages/components/main/CreateGroupAddMembers.tsx
  js/packages/components/shared-components/ContactPicker.tsx
  js/packages/components/shared-components/index.ts
  js/packages/navigation/hook.ts
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
Labels: enhancement

#3308 fix: remove jcenter (shutdown) and replace it by mavenCentral
  js/android/build.gradle
  js/ios/OpenSSL-Universal-Override.podspec
  js/ios/Podfile
  js/ios/Podfile.lock
  js/package.json
  js/yarn.lock
Labels: bug

#3311 chore: improve macos fresh-install support
  js/Makefile
  tool/go.mod
  tool/go.sum
Labels: chore

#3309 feat: auto make app deps from gradle
  js/Makefile
  js/android/app/build.gradle
  js/android/gradle/wrapper/gradle-wrapper.properties
  js/android/settings.gradle
  js/package.json
Labels: enhancement

#3302 fix: android footer and status bar
  js/packages/components/chat/ContactSettings.tsx
  js/packages/components/chat/OneToOneSettings.tsx
  js/packages/components/chat/common.tsx
  js/packages/components/main/Scan.tsx
Labels: bug

#3329 fix: rexml gem is missing when running project on a fresh install
  js/ios/Gemfile
  js/ios/Gemfile.lock
Labels: bug

#3304 fix: navigation crash issue
  js/packages/components/avatars.tsx
Labels: bug

#3334 chore: use standard initutil.Manager's initializer
  go/pkg/bertyaccount/service_account.go
Labels: chore

#3333 fix: group chat text color
  js/packages/components/chat/message/UserMessage.tsx
Labels: bug

#3337 chore: v8 jit
  go/pkg/bertyaccount/service_account.go
  js/android/app/build.gradle
  js/android/build.gradle
  js/package.json
  js/yarn.lock
Labels: chore

#3344 fix: use `initutil.New` in service_account
  go/pkg/bertyaccount/service_account.go
Labels: bug

#3345 fix: revert "use `initutil.New` in service_account"
  go/pkg/bertyaccount/service_account.go
Labels: bug

#3348 fix(messenger): remove useless locks
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/db_test.go
  go/pkg/bertymessenger/service.go
Labels: bug

#3347 chore: update rdvp flags' order
  go/cmd/rdvp/main.go
  tool/deployments/rdvp-dev/docker-compose.yml
Labels: chore

#3298 feat: refactor file-logging, and enable it by default
  go.mod
  go.sum
  go/cmd/berty-integration/main.go
  go/cmd/berty/daemon.go
  go/cmd/berty/groupinit.go
  go/cmd/berty/gui.go
  go/cmd/berty/mini.go
  go/cmd/berty/omnisearch.go
  go/cmd/berty/replication.go
  go/cmd/berty/shareinvite.go
  go/cmd/berty/systeminfo.go
  go/internal/initutil/datastore.go
  go/internal/initutil/logger.go
  go/internal/initutil/manager.go
  go/internal/ipfsutil/helpers.go
  go/internal/logutil/file.go
  go/internal/logutil/file_test.go
  go/internal/logutil/logutil.go
  go/internal/logutil/logutil_test.go
  go/internal/logutil/stream.go
  go/pkg/bertyaccount/service_account.go
  tool/tyber/go/go.sum
  tool/tyber/go/parser/header.go
Labels: enhancement

#3360 fix: android white screens emoji
  js/android/app/build.gradle
  js/ios/Podfile.lock
  js/package.json
  js/yarn.lock
Labels: bug
