Repository berty/berty, pull requests merged in 2021-10, with the labels that each got.

#3571 fix: ios permission mic
  js/packages/components/chat/record/RecordComponent.tsx
Labels: bug, 🔍 Ready for Review

#3572 fix: ack not being sent
  go/pkg/bertymessenger/service.go
  go/pkg/bertymessenger/service_test.go
  go/pkg/bertypush/push_test.go
Labels: bug, 🔍 Ready for Review

#3576 chore: fix dummy sign
  js/ios/Berty/AppDelegate.m
  tool/build/dummy-identity/berty-dummy.p12
Labels: 🔍 Ready for Review, chore

#3575 fix: conversation related issues
  go/internal/messengerdb/db.go
  go/internal/messengerdb/db_test.go
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertymessenger/service_test.go
  js/gen.sum
  js/ios/Podfile.lock
  js/packages/components/chat/MessageList.tsx
Labels: bug, ✅ Approved

#3614 fix: bump go-ipfs-repo-encrypted
  go.mod
  go.sum
Labels: bug, 🔍 Ready for Review

#3615 fix(go): close app storage
  go/pkg/bertyaccount/service.go
Labels: bug, 🔍 Ready for Review
