Repository berty/berty, pull requests merged in 2021-03, with the labels that each got.

#2729 feat: import v1 android BLE driver
  go/framework/bertybridge/bridge.go
  go/framework/bertybridge/config.go
  go/framework/bertybridge/driver_ble.go
  go/internal/ble-driver/BertyDevice_darwin.h
  go/internal/ble-driver/BertyDevice_darwin.m
  go/internal/ble-driver/BleInterface_darwin.m
  go/internal/ble-driver/BleManager_darwin.m
  go/internal/ble-driver/bridge_android.go
  go/internal/ble-driver/bridge_darwin.go
  go/internal/ble-driver/bridge_unsupported.go
  go/internal/initutil/ipfs.go
  go/internal/initutil/manager.go
  go/internal/initutil/node.go
  go/internal/multipeer-connectivity-driver/bridge_darwin.go
  go/internal/multipeer-connectivity-driver/bridge_unsupported.go
  go/internal/proximity-transport/connmgr.go
  go/internal/proximity-transport/discovery.go
  go/internal/proximity-transport/transport.go
  go/internal/proximitytransport/addr.go
  go/internal/proximitytransport/conn.go
  go/internal/proximitytransport/example_test.go
  go/internal/proximitytransport/listener.go
  go/internal/proximitytransport/mplex.go
  go/internal/proximitytransport/nativedriver.go
  go/internal/proximitytransport/ringBuffer_map.go
  go/internal/proximitytransport/transport.go
  go/pkg/bertyaccount/service.go
  go/pkg/bertyaccount/service_account.go
  js/Makefile
  js/android/app/src/main/AndroidManifest.xml
  js/android/app/src/main/java/tech/berty/gobridge/GoBridgeModule.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/Advertiser.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/BleDriver.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/BleInterface.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/BleQueue.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/DeviceManager.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/GattServer.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/GattServerCallback.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/Peer.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/PeerDevice.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/PeerManager.java
  js/android/app/src/main/java/tech/berty/gobridge/bledriver/Scanner.java
  js/android/build.gradle
  js/gen.sum
  js/ios/Podfile
  js/ios/Podfile.lock
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/berty-i18n/locale/fr-FR/messages.json
  js/packages/components/onboarding/SetupFinished.js
  js/packages/components/settings/Bluetooth.tsx
  js/packages/go-bridge/defaults.ts
Labels: echoes/users, enhancement, 🚧 WIP

#3099 fix: play sound notifications depending on notif setting
  js/packages/components/NotificationBody.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/common.tsx
  js/packages/components/main/CreateGroupFinalize.tsx
  js/packages/components/main/home/Requests.tsx
  js/packages/components/modals/ForwardToBertyContactModal.tsx
  js/packages/components/settings/DevTools.tsx
  js/packages/store/context.ts
  js/packages/store/provider.tsx
  js/packages/store/sounds.ts
Labels: bug

#3136 fix: android ui issues
  js/android/app/build.gradle
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/MultiMemberQR.tsx
  js/packages/components/chat/MultiMemberSettings.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/SharedMedias.tsx
  js/packages/components/chat/common.tsx
  js/packages/components/chat/message/index.tsx
  js/packages/components/debug/AppInspector.tsx
  js/packages/components/main/CreateGroupAddMembers.tsx
  js/packages/components/main/CreateGroupFinalize.tsx
  js/packages/components/main/home/Header.tsx
  js/packages/components/main/home/Home.tsx
  js/packages/components/modals/AddBot.js
  js/packages/components/modals/DeleteAccount.tsx
  js/packages/components/modals/WelcomeConfiguration.tsx
  js/packages/components/onboarding/CreateAccount.js
  js/packages/components/onboarding/GetStarted.tsx
  js/packages/components/onboarding/OnboardingWrapper.js
  js/packages/components/onboarding/ServicesAuth.tsx
  js/packages/components/settings/DevTools.tsx
  js/packages/components/settings/Help.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/MyBertyId.tsx
  js/packages/components/settings/NetworkMap.tsx
Labels: bug

#3025 fix: ui stream screen
  js/package.json
  js/packages/components/gates.tsx
  js/packages/store/context.ts
  js/packages/store/providerEffects.ts
  js/yarn.lock
Labels: bug

#3149 fix: network config navigation
  js/packages/components/main/bluetooth.ts
Labels: bug

#3150 fix: responsive screens
  js/packages/components/main/NetworkOptions.tsx
  js/packages/components/onboarding/ChoosePreset.tsx
  js/packages/components/shared-components/SettingsButtons.tsx
Labels: bug

#3151 fix: align conversation and desc
  js/packages/components/main/home/Conversations.tsx
Labels: bug

#3153 fix: modals positions and alignements
  js/packages/components/modals/AddBot.js
  js/packages/components/modals/WelcomeConfiguration.tsx
Labels: bug

#3132 feat: paginate interactions and medias fetch during app init
  api/messengertypes.proto
  api/messengertypes.yaml
  docs/apis/messengertypes.md
  docs/apis/messengertypes.swagger.json
  docs/gen.sum
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/db_test.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertyprotocol/api_group.go
  go/pkg/messengertypes/messengertypes.pb.go
  go/pkg/messengertypes/messengertypes.pb.gw.go
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  js/packages/components/InfosChat.tsx
  js/packages/components/chat/InfosMultiMember.tsx
  js/packages/components/chat/MessageList.tsx
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/SharedMedias.tsx
  js/packages/components/chat/common.tsx
  js/packages/components/chat/message/UserMessage.tsx
  js/packages/components/chat/message/index.tsx
  js/packages/components/main/home/Search.tsx
  js/packages/components/notifications/MessageReceived.tsx
  js/packages/grpc-bridge/welsh-clients.gen.ts
  js/packages/store/context.ts
  js/packages/store/hooks.ts
  js/packages/store/providerEffects.ts
  js/packages/store/providerReducer.ts
  js/packages/store/types.gen.ts
Labels: enhancement

#3154 fix: create group UI
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/components/main/CreateGroupAddMembers.tsx
  js/packages/components/main/CreateGroupFinalize.tsx
  js/packages/components/main/CreateGroupFooter.tsx
  js/packages/components/settings/DevTools.tsx
  js/packages/components/shared-components/DropDownPicker.tsx
Labels: bug

#3156 fix(app): reply options rendering
  js/packages/components/chat/MessageList.tsx
Labels: bug

#3159 fix: header settings harmonization
  js/packages/components/settings/Home.tsx
  js/packages/components/shared-components/Header.tsx
Labels: bug

#3100 feat: new conversation footer
  api/errcode.proto
  api/messengertypes.proto
  api/messengertypes.yaml
  docs/apis/messengertypes.md
  docs/apis/messengertypes.swagger.json
  docs/gen.sum
  go/gen.sum
  go/internal/initutil/node.go
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/service.go
  go/pkg/errcode/errcode.pb.go
  go/pkg/messengertypes/messengertypes.pb.go
  go/pkg/messengertypes/messengertypes.pb.gw.go
  js/__mocks__/react-native-device-info.js
  js/gen.sum
  js/ios/Podfile.lock
  js/package.json
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/berty-i18n/locale/fr-FR/messages.json
  js/packages/components/chat/common.tsx
  js/packages/components/chat/file-uploads/AddFileMenu.tsx
  js/packages/components/chat/message/AudioMessage.tsx
  js/packages/components/chat/record/PreviewComponent.tsx
  js/packages/components/chat/record/RecordComponent.tsx
  js/packages/components/chat/record/RecordingComponent.tsx
  js/packages/components/shared-components/KeyboardAvoidingView.tsx
  js/packages/components/shared-components/StickyMusicPlayer.tsx
  js/packages/grpc-bridge/welsh-clients.gen.ts
  js/packages/messenger-app/custom-icons-svgs/bertyzzz.svg
  js/packages/messenger-app/custom-icons-svgs/camera-footer.svg
  js/packages/messenger-app/custom-icons-svgs/microphone-footer.svg
  js/packages/messenger-app/custom-icons.tsx
  js/packages/music-player/index.tsx
  js/packages/store/sounds.ts
  js/packages/store/types.gen.ts
  js/yarn.lock
Labels: enhancement

#3165 fix: android app icon
  assets/xxxhdpi.png
  js/android/app/src/debug/AndroidManifest.xml
  js/android/app/src/debug/berty-debug.png
  js/android/app/src/debug/res/mipmap-hdpi/ic_launcher.png
  js/android/app/src/debug/res/mipmap-mdpi/ic_launcher.png
  js/android/app/src/debug/res/mipmap-xhdpi/ic_launcher.png
  js/android/app/src/debug/res/mipmap-xxhdpi/ic_launcher.png
  js/android/app/src/debug/res/mipmap-xxxhdpi/ic_launcher.png
  js/android/app/src/main/AndroidManifest.xml
  js/android/app/src/main/berty-yolo.png
  js/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  js/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  js/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  js/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  js/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
Labels: bug

#3170 fix: TextInput alignment / color / multiline auto expanding
  js/packages/components/chat/common.tsx
  js/packages/components/chat/record/RecordComponent.tsx
Labels: bug

#3171 fix: ui create group and conversations
  js/packages/components/avatars.tsx
  js/packages/components/chat/MessageList.tsx
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/MultiMemberSettings.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/OneToOneSettings.tsx
  js/packages/components/chat/common.tsx
  js/packages/components/chat/message/UserMessageComponents.tsx
  js/packages/components/main/CreateGroupAddMembers.tsx
  js/packages/components/main/home/Conversations.tsx
  js/packages/components/main/home/Footer.tsx
  js/packages/components/main/home/Header.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/shared-components/Header.tsx
  js/packages/components/shared-components/SettingsButtons.tsx
Labels: bug

#3175 feat(messenger): Initials avatars
  js/Makefile
  js/global.d.ts
  js/package.json
  js/packages/components/avatars.tsx
  js/packages/components/chat/MultiMemberQR.tsx
  js/packages/components/modals/AddThisContact.tsx
  js/packages/components/modals/ManageGroupInvitation.tsx
  js/packages/components/settings/BlockedContacts.tsx
  js/packages/components/shared-components/CircleAvatar.tsx
  js/packages/components/shared-components/ProceduralCircleAvatar.tsx
  js/packages/components/shared-components/Request.tsx
  js/packages/components/shared-components/SettingsButtons.tsx
  js/packages/components/shared-components/index.ts
  js/yarn.lock
Labels: enhancement

#3181 chore: bump gofumpt
  go.mod
  go.sum
  go/internal/testutil/testutil.pb.go
  go/pkg/bertyaccount/bertyaccount.pb.go
  go/pkg/bertybridge/bertybridge.pb.go
  go/pkg/bertyprotocol/bertyreplication.pb.go
  go/pkg/messengertypes/messengertypes.pb.go
  go/pkg/protocoltypes/protocoltypes.pb.go
Labels: chore

#3172 fix: ui sticky player
  js/packages/components/shared-components/StickyMusicPlayer.tsx
  js/packages/messenger-app/custom-icons-svgs/next.svg
  js/packages/messenger-app/custom-icons-svgs/plus.svg
  js/packages/messenger-app/custom-icons-svgs/prev.svg
  js/packages/messenger-app/custom-icons-svgs/volume.svg
  js/packages/messenger-app/custom-icons.tsx
Labels: bug

#3177 feat: refactor logutil to support multiple loggers (std, ring, lumberjack)
  go.mod
  go.sum
  go/cmd/rdvp/main.go
  go/internal/initutil/logger.go
  go/internal/initutil/manager.go
  go/internal/logutil/encoders.go
  go/internal/logutil/example_test.go
  go/internal/logutil/logutil.go
  go/internal/logutil/logutil_test.go
  go/internal/logutil/stream.go
  go/internal/testutil/logging.go
  go/internal/tools/tools.go
  go/pkg/bertyprotocol/services_replication_test.go
  tool/go.sum
Labels: enhancement

#3106 chore: add go1.16, remove go1.14
  .github/workflows/android.yml
  .github/workflows/go.yml
  .github/workflows/integration.yml
  .github/workflows/ios.yml
  .github/workflows/js.yml
  .github/workflows/protobuf.yml
  .github/workflows/release.yml
  docs/Makefile
  docs/gen.sum
  go.mod
  go.sum
  go/Makefile
  go/gen.sum
  go/internal/handshake/handshake.pb.go
  go/internal/tinder/records.pb.go
  go/pkg/bertyaccount/bertyaccount.pb.go
  go/pkg/bertybridge/bertybridge.pb.go
  go/pkg/errcode/errcode.pb.go
  go/pkg/protocoltypes/protocoltypes.pb.go
  js/Makefile
  js/gen.sum
  js/go.mod
  tool/docker-protoc/Dockerfile
  tool/docker-protoc/Makefile
  tool/go.mod
  tool/go.sum
Labels: chore

#3190 chore: moved go-libtor download out of js/Makefile + curl/wget support
  .github/workflows/ios.yml
  js/Makefile
  tool/build/shell/dl-go-libtor-ios.sh
Labels: chore

#3163 feat: add issue templates
  .github/CONTRIBUTING.md
  docs/CONTRIBUTING.md
  docs/ISSUE_TEMPLATE/bug_template.md
  docs/ISSUE_TEMPLATE/feature_template.md
  docs/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: enhancement

#3188 feat(messenger): replies and reactions backend
  .github/workflows/go.yml
  Makefile
  api/errcode.proto
  api/messengertypes.proto
  api/messengertypes.yaml
  api/protocoltypes.proto
  docs/apis/messengertypes.md
  docs/apis/messengertypes.swagger.json
  docs/apis/protocoltypes.md
  docs/apis/protocoltypes.swagger.json
  docs/gen.sum
  go/cmd/berty/mini/view_group.go
  go/cmd/berty/mini/view_group_outgoing.go
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/db_test.go
  go/pkg/bertymessenger/handlers.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertymessenger/service_test.go
  go/pkg/bertymessenger/testing.go
  go/pkg/bertyprotocol/api_app.go
  go/pkg/errcode/errcode.pb.go
  go/pkg/messengertypes/messengertypes.pb.go
  go/pkg/messengertypes/messengertypes.pb.gw.go
  go/pkg/messengertypes/types.go
  go/pkg/protocoltypes/protocoltypes.pb.go
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  js/packages/components/settings/BlockedContacts.tsx
  js/packages/grpc-bridge/welsh-clients.gen.ts
  js/packages/store/context.ts
  js/packages/store/provider.tsx
  js/packages/store/providerCallbacks.ts
  js/packages/store/types.gen.ts
Labels: enhancement

#3193 fix: pull issue template
  .github/ISSUE_TEMPLATE/bug_template.md
  .github/ISSUE_TEMPLATE/feature_template.md
  .github/pull_request_template.md
Labels: bug

#3187 fix: ConnectAll and ConnectInLine in scenario_test
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/bertyprotocol/testing.go
Labels: bug

#3138 feat: exposing a message text search method from go
  .github/workflows/go.yml
  api/messengertypes.proto
  api/messengertypes.yaml
  docs/apis/messengertypes.md
  docs/apis/messengertypes.swagger.json
  docs/gen.sum
  go/Makefile
  go/gen.sum
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/db.go
  go/pkg/bertymessenger/db_test.go
  go/pkg/bertymessenger/db_utils.go
  go/pkg/bertymessenger/db_utils_test.go
  go/pkg/bertymessenger/handlers.go
  go/pkg/bertyprotocol/service.go
  go/pkg/messengertypes/messengertypes.pb.go
  go/pkg/messengertypes/messengertypes.pb.gw.go
  go/pkg/messengertypes/types.go
  js/Makefile
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  js/packages/components/main/home/Home.tsx
  js/packages/components/main/home/Search.tsx
  js/packages/grpc-bridge/welsh-clients.gen.ts
  js/packages/store/providerReducer.ts
  js/packages/store/types.gen.ts
  js/packages/store/utils.ts
Labels: enhancement

#3199 chore: fix PR template
  .github/pull_request_template.md
Labels: chore

#3198 chore: setup logging sampler
  go/internal/logutil/logutil.go
Labels: chore

#3189 feat: add a way to stream remote node's logs
  api/messengertypes.proto
  api/messengertypes.yaml
  docs/apis/messengertypes.md
  docs/apis/messengertypes.swagger.json
  docs/gen.sum
  go/cmd/berty/main.go
  go/cmd/berty/remotelogs.go
  go/gen.sum
  go/internal/initutil/logger.go
  go/internal/initutil/manager.go
  go/internal/initutil/manager_test.go
  go/internal/initutil/node.go
  go/internal/logutil/logutil.go
  go/internal/testutil/logging.go
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/api_test.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertymessenger/testing.go
  go/pkg/messengertypes/messengertypes.pb.go
  go/pkg/messengertypes/messengertypes.pb.gw.go
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  js/packages/grpc-bridge/welsh-clients.gen.ts
Labels: enhancement

#3135 feat:Android Nearby implementation
  go/framework/bertybridge/bridge.go
  go/framework/bertybridge/config.go
  go/framework/bertybridge/proximity_driver.go
  go/internal/androidnearby/bridge_android.go
  go/internal/androidnearby/bridge_unsupported.go
  go/internal/androidnearby/const.go
  go/internal/androidnearby/example_test.go
  go/internal/androidnearby/init.go
  go/internal/androidnearby/multiaddr.go
  go/internal/initutil/ipfs.go
  go/internal/initutil/manager.go
  go/internal/initutil/node.go
  go/internal/proximitytransport/transport.go
  go/pkg/bertyaccount/service.go
  go/pkg/bertyaccount/service_account.go
  js/android/app/build.gradle
  js/android/app/src/main/AndroidManifest.xml
  js/android/app/src/main/java/tech/berty/gobridge/BertyNearbyDriver.java
  js/android/app/src/main/java/tech/berty/gobridge/GoBridgeModule.java
  js/android/app/src/main/java/tech/berty/gobridge/proximitydriverssdk/base/NearbyDriverSDK.java
  js/android/app/src/main/java/tech/berty/gobridge/proximitydriverssdk/lifecycle/UserAcceptCallback.java
  js/android/app/src/main/java/tech/berty/gobridge/proximitydriverssdk/lifecycle/UserConnectionCallback.java
  js/android/app/src/main/java/tech/berty/gobridge/proximitydriverssdk/lifecycle/UserMessageCallback.java
  js/android/app/src/main/java/tech/berty/gobridge/proximitydriverssdk/lifecycle/UserRequestCallback.java
  js/android/app/src/main/java/tech/berty/gobridge/proximitydriverssdk/lifecycle/UserSearchCallback.java
  js/android/app/src/main/java/tech/berty/gobridge/proximitydriverssdk/model/Endpoint.java
  js/android/app/src/main/java/tech/berty/gobridge/proximitydriverssdk/util/BertyLogger.java
  js/android/build.gradle
  js/android/gradle/wrapper/gradle-wrapper.properties
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/berty-i18n/locale/fr-FR/messages.json
  js/packages/components/onboarding/SetupFinished.js
  js/packages/components/settings/Bluetooth.tsx
  js/packages/store/context.ts
Labels: 🔍 Ready for Review

#3174 fix: new home settings
  js/global.d.ts
  js/package.json
  js/packages/components/main/home/Header.tsx
  js/packages/components/onboarding/ChoosePreset.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/Mode.tsx
  js/packages/components/shared-components/DropDownPicker.tsx
  js/yarn.lock
Labels: bug

#3202 feat(messenger): default group avatars
  js/package.json
  js/packages/components/InfosChat.tsx
  js/packages/components/avatars.tsx
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/MultiMemberSettings.tsx
  js/packages/components/chat/message/MessageInvitation.tsx
  js/packages/components/modals/AddThisContact.tsx
  js/packages/components/modals/ManageGroupInvitation.tsx
  js/yarn.lock
Labels: enhancement

#3212 fix(messenger): android bootsplash screen
  js/android/app/src/debug/AndroidManifest.xml
  js/android/app/src/main/bootsplash-yolo.svg
  js/android/app/src/main/java/tech/berty/android/MainActivity.java
  js/android/app/src/main/res/drawable/bootsplash.xml
  js/android/app/src/main/res/mipmap-hdpi/bootsplash_logo.png
  js/android/app/src/main/res/mipmap-mdpi/bootsplash_logo.png
  js/android/app/src/main/res/mipmap-xhdpi/bootsplash_logo.png
  js/android/app/src/main/res/mipmap-xxhdpi/bootsplash_logo.png
  js/android/app/src/main/res/mipmap-xxxhdpi/bootsplash_logo.png
Labels: bug

#3209 fix(messenger): android footer animation
  js/ios/Podfile.lock
  js/package.json
  js/packages/components/chat/common.tsx
  js/yarn.lock
Labels: bug
