Repository berty/berty, pull requests merged in 2022-04, with the labels that each got.

#4040 feat: view titles
  .editorconfig
  js/packages/components/settings/Appearance.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/index.ts
  js/packages/i18n/locale/en-US/messages.json
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
Labels: ✅ Approved, enhancement

#4039 fix: copy to clipboard instead of share in web
  js/packages/components/chat/MultiMemberQR.tsx
  js/packages/components/chat/SharedMedias.tsx
  js/packages/components/main/Share.tsx
  js/packages/components/settings/MyBertyId.tsx
Labels: bug, 🔍 Ready for Review

#4042 feat(electron): context menu + alert when unable to start berty daemon
  js/web/package.json
  js/web/src-main/main.ts
  js/web/yarn.lock
Labels: 🔍 Ready for Review, enhancement

#4048 fix: improve message cache
  .github/workflows/go.yml
  go/pkg/bertyprotocol/group.go
  go/pkg/bertyprotocol/store_message.go
  go/pkg/bertyprotocol/store_message_queue.go
  go/pkg/bertyprotocol/store_message_test.go
Labels: bug, ✅ Approved

#4044 fix: backup feature
  js/.eslintignore
  js/packages/components/settings/Accounts.tsx
  js/packages/components/settings/ContactAndConversations.tsx
  js/packages/i18n/locale/en-US/messages.json
  js/packages/store/effectableCallbacks.ts
  js/packages/store/providerCallbacks.ts
Labels: bug, 🔍 Ready for Review

#4047 fix: hide useless buttons on web
  js/packages/components/chat/MultiMemberSettings.tsx
  js/packages/components/chat/OneToOneSettings.tsx
  js/packages/components/chat/footer/ChatFooter.tsx
  js/packages/components/chat/footer/record/RecordComponent.tsx
  js/packages/components/onboarding/GetStarted.tsx
  js/packages/components/settings/Accounts.tsx
  js/packages/components/settings/Faq.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/Network.tsx
  js/packages/components/settings/PrivacyPolicy.tsx
  js/packages/components/settings/Roadmap.tsx
  js/packages/components/shared-components/WebViews.tsx
Labels: bug, 🔍 Ready for Review

#4033 fix: front settings fixes
  js/packages/components/chat/EnableNotificationsButton.tsx
  js/packages/components/chat/footer/ChatFooter.tsx
  js/packages/components/chat/footer/record/RecordComponent.tsx
  js/packages/components/chat/modals/add-file-modal/AddFileMenu.modal.tsx
  js/packages/components/chat/modals/add-file-modal/SecurityAccess.tsx
  js/packages/components/main/Permissions.tsx
  js/packages/components/main/Share.tsx
  js/packages/components/onboarding/Accordion.tsx
  js/packages/components/onboarding/CreateAccount.tsx
  js/packages/components/onboarding/CustomModeSettings.tsx
  js/packages/components/onboarding/OnBoardingAccorion.tsx
  js/packages/components/providers/modal.provider.tsx
  js/packages/components/settings/Accordion.tsx
  js/packages/components/settings/Accounts.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/Network.tsx
  js/packages/i18n/locale/en-US/messages.json
  js/packages/navigation/stacks.tsx
  js/packages/redux/reducers/networkConfig.reducer.ts
  js/packages/rnutil/checkPermissions.ts
Labels: bug, 🔍 Ready for Review

#4055 fix: use webpack for electron's main package
  js/packages/components/main/Share.tsx
  js/packages/components/onboarding/CustomModeSettings.tsx
  js/web/package.json
  js/web/src-main/main.ts
  js/web/src-main/preload.ts
  js/web/webpack.main.config.js
  js/web/yarn.lock
Labels: bug, 🔍 Ready for Review

#3977 feat: replace react-native-qrcode-scanner by expo-barcode-scanner
  js/android/build.gradle
  js/ios/Podfile.lock
  js/ios/berty.yaml
  js/package.json
  js/packages/components/main/Permissions.tsx
  js/packages/components/main/Scan.tsx
  js/packages/components/main/Share.tsx
  js/packages/components/main/index.ts
  js/packages/i18n/locale/en-US/messages.json
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
  js/packages/rnutil/checkPermissions.ts
  js/tsconfig.json
  js/web/src/polyfill/react-native-qrcode-scanner/index.tsx
  js/yarn.lock
Labels: 🔍 Ready for Review, enhancement

#4064 fix: remove sakul forked repositories
  js/package.json
  js/patches/@react-native-community+audio-toolkit+2.0.3.patch
  js/patches/react-native-qrcode-svg+6.1.1.patch
  js/yarn.lock
Labels: bug, ✅ Approved

#4073 feat: add game bundler (merge css/html/js/img and compress)
  tool/bundle-game/inline-compress.js
  tool/bundle-game/package.json
  tool/bundle-game/yarn.lock
Labels: 🔍 Ready for Review, enhancement

#4065 Debounce draft save
  js/packages/components/chat/footer/ChatFooter.tsx
  js/packages/components/chat/footer/ChatTextInput.tsx
  js/packages/rnutil/constants.ts
  js/packages/store/effectableCallbacks.ts
Labels: ✅ Approved

#4069 chore: move debugMode to redux
  js/packages/components/debug/AppInspector.tsx
  js/packages/components/error.tsx
  js/packages/components/settings/DevTools.tsx
  js/packages/redux/reducers/ui.reducer.ts
  js/packages/store/context.ts
  js/packages/store/provider.tsx
  js/packages/store/types.ts
Labels: 🔍 Ready for Review, chore

#4074 fix: disable debug mode by default
  js/packages/redux/reducers/ui.reducer.ts
Labels: bug, 🔍 Ready for Review

#4071 chore: move playSound out of react context
  js/packages/components/InfosChat.tsx
  js/packages/components/NotificationBody.tsx
  js/packages/components/chat/footer/ChatFooter.tsx
  js/packages/components/chat/message/UserMessage.tsx
  js/packages/components/chat/modals/EmojiKeyboard.modal.tsx
  js/packages/components/main/CreateGroupFinalize.tsx
  js/packages/components/main/home/Requests.tsx
  js/packages/components/modals/ForwardToBertyContactModal.tsx
  js/packages/components/settings/DevTools.tsx
  js/packages/hooks/index.ts
  js/packages/hooks/ui.hooks.ts
  js/packages/store/context.ts
  js/packages/store/provider.tsx
  js/packages/store/types.ts
Labels: ✅ Approved, chore

#4087 fix: scan qr with expo-camera
  js/packages/components/main/Share.tsx
Labels: bug, 🔍 Ready for Review, ✅ Approved

#4077 fix: move accounts to redux
  js/packages/components/gates.tsx
  js/packages/components/main/home/MultiAccount.tsx
  js/packages/components/modals/EditProfile.tsx
  js/packages/components/onboarding/CustomModeSettings.tsx
  js/packages/components/onboarding/DefaultMode.tsx
  js/packages/components/onboarding/GetStarted.tsx
  js/packages/components/pickerUtils.ts
  js/packages/components/settings/Accounts.tsx
  js/packages/components/settings/DeleteAccount.tsx
  js/packages/hooks/accounts.hooks.ts
  js/packages/hooks/index.ts
  js/packages/redux/reducers/ui.reducer.ts
  js/packages/store/context.ts
  js/packages/store/effectableCallbacks.ts
  js/packages/store/index.ts
  js/packages/store/provider.tsx
  js/packages/store/providerCallbacks.ts
  js/packages/store/providerEffects.ts
  js/packages/store/types.ts
Labels: bug, 🔍 Ready for Review

#4078 chore: move getUsername out of context
  js/packages/components/onboarding/CreateAccount.tsx
  js/packages/store/context.ts
  js/packages/store/effectableCallbacks.ts
  js/packages/store/provider.tsx
  js/packages/store/types.ts
Labels: 🔍 Ready for Review, chore

#4076 chore: move daemonAddress to redux
  js/packages/components/gates.tsx
  js/packages/components/settings/DevTools.tsx
  js/packages/messenger-app/App.tsx
  js/packages/redux/reducers/ui.reducer.ts
  js/packages/store/context.ts
  js/packages/store/index.ts
  js/packages/store/provider.tsx
  js/packages/store/reducer/uiReducer.ts
  js/packages/store/types.ts
Labels: 🔍 Ready for Review, chore

#4082 chore: move handledLink to redux
  js/packages/navigation/stacks.tsx
  js/packages/redux/reducers/ui.reducer.ts
  js/packages/store/context.ts
  js/packages/store/provider.tsx
  js/packages/store/types.ts
Labels: 🔍 Ready for Review, chore

#4079 chore: move eventEmitter into own context
  js/packages/components/providers/notification.provider.tsx
  js/packages/contexts/eventEmitter.context.ts
  js/packages/store/context.ts
  js/packages/store/provider.tsx
  js/packages/store/types.ts
Labels: 🔍 Ready for Review, chore

#4080 chore: move notificationsInhibitors to redux
  js/packages/components/NotificationBody.tsx
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/main/home/Home.tsx
  js/packages/redux/reducers/ui.reducer.ts
  js/packages/store/context.ts
  js/packages/store/hooks.ts
  js/packages/store/reducer/uiReducer.ts
  js/packages/store/types.ts
Labels: 🔍 Ready for Review, chore

#4088 chore: remove unused context parts
  js/packages/components/modals/AddThisContact.tsx
  js/packages/hooks/accounts.hooks.ts
  js/packages/store/context.ts
  js/packages/store/effectableCallbacks.ts
  js/packages/store/hooks.ts
  js/packages/store/provider.tsx
  js/packages/store/providerCallbacks.ts
  js/packages/store/providerEffects.ts
  js/packages/store/reducer/index.ts
  js/packages/store/reducer/uiReducer.ts
  js/packages/store/types.ts
Labels: 🔍 Ready for Review, chore

#4089 chore: un-uppercase en-US i18n values and use textTransform instead
  js/packages/components/InfosChat.tsx
  js/packages/components/chat/message/MessageInvitation.tsx
  js/packages/components/main/CreateGroupAddMembers.tsx
  js/packages/components/main/CreateGroupFinalize.tsx
  js/packages/components/main/CreateGroupFooter.tsx
  js/packages/components/modals/InvalidScan.tsx
  js/packages/components/modals/ManageGroupInvitation.tsx
  js/packages/components/modals/ThemeColorName.tsx
  js/packages/components/onboarding/Button.tsx
  js/packages/components/onboarding/GetStarted.tsx
  js/packages/components/onboarding/SetupFinished.tsx
  js/packages/components/onboarding/SwiperCard.tsx
  js/packages/components/settings/BertyServices.tsx
  js/packages/components/settings/DeleteAccount.tsx
  js/packages/i18n/locale/en-US/messages.json
Labels: ✅ Approved, chore

#4098 feat: add optimization for mp3 and png assets
  js/packages/assets/images/1_berty_picto.png
  js/packages/assets/images/Avatar_Group_Copy_19.png
  js/packages/assets/images/berty_bot_orange_bg.png
  js/packages/assets/images/berty_bot_pink_bg.png
  js/packages/assets/images/berty_dev_blue_bg.png
  js/packages/assets/images/berty_dev_green_bg.png
  js/packages/assets/sound/contact_request_accepted.mp3
  js/packages/assets/sound/contact_request_received.mp3
  js/packages/assets/sound/contact_request_sent.mp3
  js/packages/assets/sound/group_created.mp3
  js/packages/assets/sound/message_received.mp3
Labels: enhancement

#4094 fix: network settings
  js/packages/components/onboarding/CustomModeSettings.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/Network.tsx
  js/packages/hooks/index.ts
  js/packages/hooks/networkConfig.hooks.ts
  js/packages/hooks/ui.hooks.ts
  js/packages/redux/reducers/networkConfig.reducer.ts
Labels: bug, 🔍 Ready for Review

#4092 feat: add i18n types for autocompletion
  js/packages/components/chat/DeviceList.tsx
  js/packages/components/chat/footer/ChatTextInput.tsx
  js/packages/components/chat/message/UserMessage.tsx
  js/packages/components/onboarding/GetStarted.tsx
  js/packages/components/settings/AddDevConversations.tsx
  js/packages/components/shared-components/SettingsButtons.tsx
  js/packages/components/utils.ts
  js/packages/i18n/index.ts
  js/packages/i18n/locale/en-US/messages.json
  js/packages/redux/reducers/theme.reducer.ts
  js/packages/store/hooks.ts
  js/tsconfig.json
Labels: 🔍 Ready for Review, ✅ Approved, enhancement

#4101 fix: android keystoredriver performance
  js/android/app/src/main/java/tech/berty/gobridge/GoBridgeModule.java
  js/android/app/src/main/java/tech/berty/gobridge/KeystoreDriver.java
Labels: bug, ✅ Approved

#4099 fix: auth template when a single service is selected
  go/pkg/bertyauth/services_auth_templates.go
Labels: bug, 🔍 Ready for Review

#4103 fix: break dependency cycle in messenger reducer
  js/packages/redux/reducers/messenger.reducer.ts
Labels: bug, ✅ Approved
