Repository berty/berty, pull requests merged in 2022-10, with the labels that each got.

#4444 chore: remove reactions front feature
  js/e2e-tests/lib.js
  js/package.json
  js/packages/components/chat/message/reactions/EmojiNumber.tsx
  js/packages/components/chat/message/reactions/ReactionItem.tsx
  js/packages/components/chat/message/reactions/Reactions.tsx
  js/packages/components/chat/message/user-message/UserMessage.tsx
  js/packages/components/chat/message/user-message/interfaces.ts
  js/packages/components/chat/message/user-message/user-message-box/UserMessageBox.tsx
  js/packages/components/chat/modals/EmojiKeyboard.modal.tsx
  js/packages/components/chat/modals/MessageMenu.modal.tsx
  js/packages/components/chat/modals/reactions-modal/MemberList.modal.priv.tsx
  js/packages/components/chat/modals/reactions-modal/ReactionList.modal.tsx
  js/packages/utils/emojis/emojis.ts
  js/patches/react-native-scrollable-tab-view+1.0.0.patch
  js/web/craco.config.js
  js/yarn.lock
Labels: 🔍 Ready for Review, chore

#4456 ci: add the PR number to the product name
  js/Makefile
  js/ios/berty.yaml
Labels: 🔍 Ready for Review, ci

#4464 fix: make doctor panic if hang too much time
  go/cmd/berty-doctor/main.go
  go/cmd/berty-doctor/rdvp.go
Labels: bug, 🔍 Ready for Review

#4336 fix: js: In README, bump Node requirement to 14.x
  js/README.md
Labels: bug, ✅ Approved

#4472 feat: select a remote node from mobile app
  go/framework/bertybridge/blackbox_test.go
  go/framework/bertybridge/bridge.go
  go/framework/bertybridge/bridge_config.go
  go/framework/bertybridge/config.go
  go/framework/bertybridge/config_android.go
  go/framework/bertybridge/const.go
  go/framework/bertybridge/remote_bridge.go
  go/framework/bertybridge/remote_bridge_config.go
  go/framework/bertybridge/service_client.go
  js/__mocks__/@react-native-async-storage/async-storage.ts
  js/__mocks__/@react-native-community/async-storage.js
  js/android/app/src/main/java/tech/berty/gobridge/GoBridgeModule.java
  js/ios/Berty/Sources/Bridge/GoBridge.m
  js/ios/Berty/Sources/Bridge/GoBridge.swift
  js/ios/Podfile.lock
  js/package.json
  js/packages/hooks/accounts.hooks.ts
  js/packages/i18n/locale/en-US/messages.json
  js/packages/native-modules/GoBridge/GoBridge.ts
  js/packages/native-modules/GoBridge/GoBridgeInterface.ts
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
  js/packages/screens/account/GoToLogInOrCreate/GoToLogInOrCreate.tsx
  js/packages/screens/account/GoToLogInOrCreate/goToLogInOrCreate.effect.ts
  js/packages/screens/account/SelectNode/SelectNode.test.tsx
  js/packages/screens/account/SelectNode/SelectNode.tsx
  js/packages/screens/account/SelectNode/__snapshots__/SelectNode.test.tsx.snap
  js/packages/screens/account/SelectNode/components/LabelInput.tsx
  js/packages/screens/account/index.ts
  js/packages/screens/settings/DevTools/DevTools.tsx
  js/packages/screens/settings/DevTools/__snapshots__/DevTools.test.tsx.snap
  js/packages/utils/accounts/openAccount.ts
  js/packages/utils/async-storage/async-storage.ts
  js/packages/utils/bridge/bridge.ts
  js/packages/utils/global-persistent-options/defaults.ts
  js/packages/utils/messenger/clients.ts
  js/yarn.lock
Labels: ✅ Approved, enhancement
