Repository berty/berty, pull requests merged in 2022-08, with the labels that each got.

#4309 fix: modify Valist workflow
  .github/workflows/valist.yml
Labels: bug, ✅ Approved

#4327 ci: fix finding most recent e2e build
  .github/workflows/ios.yml
  .github/workflows/monitor-runners.yml
Labels: 🔍 Ready for Review, ci

#4328 ci: fix find latest e2e build
  .github/workflows/ios.yml
Labels: 🔍 Ready for Review, ci

#4280 feat: rework contact request manager
  go/internal/omnisearch/berty-engine.go
  go/internal/tinder/driver_localdiscovery.go
  go/pkg/bertyprotocol/contact_request_manager.go
  go/pkg/bertyprotocol/store_metadata.go
  go/pkg/bertyprotocol/tinder_swiper.go
  go/pkg/bertyprotocol/tinder_swiper_test.go
  js/e2e-tests/basic.js
Labels: 🔍 Ready for Review, enhancement

#4333 chore(README.md): add links to Google Play and App Store.
  README.md
Labels: 🔍 Ready for Review, chore

#4324 feat: implement message part from chat
  .gitignore
  js/packages/components/chat/message/AudioMessage.tsx
  js/packages/components/chat/message/MessageInvitation.tsx
  js/packages/components/chat/message/MessageMonitorMetadata.tsx
  js/packages/components/chat/message/MessageSystemWrapper.tsx
  js/packages/components/chat/message/UserMessage.tsx
  js/packages/components/chat/message/audio/AudioPreview.priv.tsx
  js/packages/components/chat/message/audio/AudioWrapper.priv.tsx
  js/packages/components/chat/message/index.tsx
  js/packages/components/chat/message/user-message/GestureHandler.tsx
  js/packages/components/chat/message/user-message/RepliedTo.tsx
  js/packages/components/chat/message/user-message/SenderName.tsx
  js/packages/components/chat/message/user-message/TimestampStatus.tsx
  js/packages/components/chat/message/user-message/UserMessage.tsx
  js/packages/components/chat/message/user-message/UserMessageWrapper.tsx
  js/packages/components/chat/message/user-message/getUserMessageState.ts
  js/packages/components/chat/message/user-message/interfaces.ts
  js/packages/components/chat/message/user-message/user-message-box/AudioMessage.tsx
  js/packages/components/chat/message/user-message/user-message-box/FileMessage.tsx
  js/packages/components/chat/message/user-message/user-message-box/HyperlinkUserMessage.tsx
  js/packages/components/chat/message/user-message/user-message-box/PictureMessage.tsx
  js/packages/components/chat/message/user-message/user-message-box/UserMessageBox.tsx
  js/packages/screens/chat/SharedMedias/SharedMedias.tsx
Labels: ✅ Approved, enhancement

#4352 chore: update valist release tag
  .github/workflows/valist.yml
Labels: 🔍 Ready for Review, chore

#4335 fix: reduce noisy logs
  go/pkg/bertyprotocol/service.go
Labels: bug, 🔍 Ready for Review

#4330 feat: rdv server, sync mode via emitter.io server
  go.mod
  go.sum
  go/cmd/rdvp/main.go
  go/internal/rendezvous/emitterio_sync_client.go
  go/internal/rendezvous/emitterio_sync_provider.go
  go/internal/rendezvous/emitterio_sync_test.go
  go/pkg/bertyprotocol/scenario_test.go
  tool/emitter-server/docker-compose.yml
  tool/go.sum
Labels: ✅ Approved, enhancement

#4323 feat: implement messenger peer status event
  go/cmd/berty/mini/view_group.go
  go/cmd/berty/mini/view_group_incoming.go
  go/cmd/berty/mini/view_tabbed_groups.go
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertyprotocol/api_group.go
  go/pkg/bertyprotocol/connectedness_manager.go
  go/pkg/bertyprotocol/service.go
  go/pkg/messengertypes/types.go
  js/ios/Gemfile.lock
  js/ios/Podfile.lock
  js/packages/components/chat/member-bar/AvatarWrapper.tsx
  js/packages/components/chat/member-bar/MemberBar.tsx
  js/packages/components/chat/message/MessageMonitorMetadata.tsx
  js/packages/components/chat/message/index.tsx
  js/packages/components/dropdowns/members/MemberAvatarWithStatus.priv.tsx
  js/packages/components/dropdowns/members/MemberName.priv.tsx
  js/packages/components/dropdowns/members/MembersDropdown.tsx
  js/packages/redux/reducers/messenger.reducer.ts
  js/packages/screens/settings/DevTools/DevTools.tsx
Labels: 🔍 Ready for Review, enhancement

#4345 ci: cleanup and fixes for release on stores
  .github/workflows/ios.yml
  .github/workflows/mac.yml
  .github/workflows/monitor-runners.yml
  .github/workflows/release.yml
  .github/workflows/utils/get-self-hosted-runner-status.js
  .github/workflows/utils/mac-runner-matrix-builder.js
  js/Makefile
  js/ios/Configs/GoogleService/GoogleService-Info-tech.berty.ios.debug.plist
  js/ios/Configs/GoogleService/GoogleService-Info-tech.berty.ios.plist
  js/ios/Configs/GoogleService/GoogleService-Info-tech.berty.ios.staff.plist
  js/ios/Configs/GoogleService/GoogleService-Info-tech.berty.ios.yolo.plist
  js/ios/Entitlements/Prod.entitlements
  js/ios/Entitlements/ProdNS.entitlements
  js/ios/berty.yaml
  tool/ci-self-hosted/Makefile
  tool/ci-self-hosted/inventory.yml
  tool/ci-self-hosted/m1_setup_runner.yml
  tool/ci-self-hosted/mac_disable_remote_desktop.yml
  tool/ci-self-hosted/mac_enable_remote_desktop.yml
  tool/ci-self-hosted/mac_install_xcode_version.yml
  tool/ci-self-hosted/mac_start_runner_service.yml
  tool/ci-self-hosted/mac_stop_runner_service.yml
  tool/ci-self-hosted/mac_switch_to_xcode_version.yml
  tool/ci-self-hosted/roles/actions_daemon/tasks/start.yml
  tool/ci-self-hosted/roles/actions_service/tasks/main.yml
  tool/ci-self-hosted/roles/actions_service/tasks/start.yml
  tool/ci-self-hosted/roles/actions_service/tasks/stop.yml
  tool/ci-self-hosted/roles/actions_service/templates/service.plist.j2
  tool/ci-self-hosted/roles/actions_service/vars/main.yml
  tool/ci-self-hosted/roles/actions_setup/tasks/main.yml
  tool/ci-self-hosted/roles/asdf_setup/files/tool-versions
  tool/ci-self-hosted/roles/xcode_setup/tasks/main.yml
Labels: 🔍 Ready for Review, ci

#4316 fix: refacto permissions screens
  js/e2e-tests/basic.js
  js/packages/components/chat/footer/CameraButton.tsx
  js/packages/components/chat/footer/ChatFooter.tsx
  js/packages/components/chat/footer/recorder/RecorderButton.tsx
  js/packages/components/chat/modals/add-file-modal/AddFileMenu.modal.tsx
  js/packages/components/chat/modals/add-file-modal/GallerySection.tsx
  js/packages/components/chat/modals/add-file-modal/SecurityAccess.tsx
  js/packages/components/permissions/Permission.tsx
  js/packages/contexts/permissions.context.tsx
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
  js/packages/screens/chat/NotificationAndProximityPermissions/NotificationAndProximityPermissions.tsx
  js/packages/screens/chat/Permissions/Permissions.tsx
  js/packages/screens/chat/Share/Share.tsx
  js/packages/screens/chat/index.ts
  js/packages/screens/onboarding/CreateAccount/CreateAccount.tsx
  js/packages/screens/onboarding/CustomModeSettings/CustomModeSettings.tsx
  js/packages/screens/settings/Network/Network.tsx
  js/packages/screens/settings/Permissions/Permissions.tsx
  js/packages/screens/settings/SettingsHome/SettingsHome.tsx
  js/packages/screens/settings/index.ts
  js/packages/utils/notification/notif-push.ts
  js/packages/utils/permissions/checkPermissions.ts
  js/packages/utils/permissions/handle-press-permissions/handlePressCamera.ts
  js/packages/utils/permissions/handle-press-permissions/handlePressFiles.ts
  js/packages/utils/permissions/handle-press-permissions/handlePressGallery.ts
  js/packages/utils/permissions/handle-press-permissions/index.ts
  js/packages/utils/permissions/handle-press-permissions/interfaces.ts
  js/packages/utils/permissions/handle-press-permissions/prepareMediaAndSend.ts
  js/packages/utils/permissions/permissions.ts
  js/packages/utils/react-native/index.ts
Labels: bug, 🔍 Ready for Review, wip

#4366 chore(bot): remove trailing space in commands
  go/pkg/bertybot/handlers.go
Labels: ✅ Approved, chore

#4365 fix: account create then import flow
  go/pkg/bertyaccount/service_account.go
Labels: bug, ✅ Approved

#4378 chore(ci): upgrade Valist GitHub Action to v2.5.6
  .github/workflows/valist.yml
Labels: ✅ Approved, chore

#4150 Add additional quote
  go/pkg/banner/quote.go
Labels: 🔍 Ready for Review

#4382 feat: add emitter public addr argument
  go/cmd/rdvp/main.go
  go/internal/rendezvous/emitterio_sync_provider.go
Labels: 🔍 Ready for Review, enhancement

#4383 chore(ci): add runners' lambda
  tool/scw-funcs/ghrunners/.gitignore
  tool/scw-funcs/ghrunners/Makefile
  tool/scw-funcs/ghrunners/README.md
  tool/scw-funcs/ghrunners/go.mod
  tool/scw-funcs/ghrunners/go.sum
  tool/scw-funcs/ghrunners/handler.go
  tool/scw-funcs/ghrunners/handler_test.go
  tool/scw-funcs/ghrunners/package.json
  tool/scw-funcs/ghrunners/serverless.yml
Labels: 🔍 Ready for Review, chore

#4384 ci: fix url path (orgs vs repo)
  .github/workflows/ios.yml
  .github/workflows/mac.yml
  .github/workflows/monitor-runners.yml
  .github/workflows/utils/get-self-hosted-runner-status.js
  .github/workflows/utils/mac-runner-matrix-builder.js
  tool/ci-self-hosted/Makefile
Labels: 🔍 Ready for Review, ci

#4251 fix: backgound crash on iOS
  go.mod
  go.sum
  go/cmd/berty-integration/main.go
  go/cmd/berty/account_daemon.go
  go/cmd/berty/mini/main.go
  go/cmd/berty/scenario_test.go
  go/framework/bertybridge/blackbox_test.go
  go/framework/bertybridge/bridge.go
  go/framework/bertybridge/config.go
  go/internal/accountutils/keystore.go
  go/internal/accountutils/utils.go
  go/internal/initutil/datastore.go
  go/internal/initutil/ipfs.go
  go/internal/initutil/logger.go
  go/internal/initutil/manager.go
  go/internal/initutil/node.go
  go/internal/initutil/orbitdb.go
  go/internal/ipfsutil/repo.go
  go/internal/migrations/0_to_1.go
  go/internal/migrations/migration.go
  go/internal/migrations/migration_test.go
  go/internal/migrationsaccount/0_to_1.go
  go/internal/migrationsaccount/account_migration_test.go
  go/internal/migrationsaccount/migration.go
  go/internal/migrationutils/migrationutils.go
  go/pkg/bertyaccount/blackbox_test.go
  go/pkg/bertyaccount/service.go
  go/pkg/bertyaccount/service_account.go
  go/pkg/bertyaccount/service_log.go
  go/pkg/bertyaccount/service_storage.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertymessenger/subscriptions.go
  go/pkg/bertyprotocol/api_group.go
  go/pkg/bertyprotocol/orbitdb_test.go
  go/pkg/bertypush/push_opener.go
  go/pkg/bertypush/push_test.go
  go/pkg/bertyreplication/services_replication_test.go
  js/android/app/src/main/java/tech/berty/gobridge/GoBridgeModule.java
  js/ios/Berty/Sources/Bridge/GoBridge.swift
  tool/go.sum
  tool/infra/infra.yml
Labels: bug, 🔍 Ready for Review

#4369 fix: deactivate group
  go/cmd/berty/main.go
  go/internal/initutil/manager.go
  go/internal/initutil/manager_test.go
  go/internal/initutil/node.go
  go/internal/omnisearch/manager.go
  go/pkg/bertyaccount/service_account.go
  go/pkg/bertymessenger/service_non_mocked_test.go
  go/pkg/bertyprotocol/api_multimember.go
  go/pkg/bertyprotocol/blackbox_test.go
  go/pkg/bertyprotocol/deactivate_test.go
  go/pkg/bertyprotocol/group_context.go
  go/pkg/bertyprotocol/orbitdb.go
  go/pkg/bertyprotocol/orbitdb_many_adds_berty_test.go
  go/pkg/bertyprotocol/orbitdb_test.go
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertyprotocol/service_group.go
  go/pkg/bertyprotocol/store_metadata_test.go
  go/pkg/bertyprotocol/testing.go
  go/pkg/bertyprotocol/testing_test.go
  go/pkg/bertyreplication/services_replication_test.go
Labels: bug, 🔍 Ready for Review, wip

#4387 fix: multiple fixes
  api/messengertypes.proto
  api/protocoltypes.proto
  api/protocoltypes.yaml
  config/config.gen.json
  config/config.yml
  docs/apis/messengertypes.md
  docs/apis/messengertypes.swagger.json
  docs/apis/protocoltypes.md
  docs/apis/protocoltypes.swagger.json
  docs/gen.sum
  go.mod
  go/gen.sum
  go/internal/config/config.gen.go
  go/internal/initutil/ipfs.go
  go/internal/ipfsutil/testing.go
  go/internal/tinder/discovery_monitor.go
  go/internal/tinder/service.go
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertymessenger/subscriptions.go
  go/pkg/bertyprotocol/api_app.go
  go/pkg/bertyprotocol/api_group.go
  go/pkg/bertyprotocol/deactivate_test.go
  go/pkg/bertyprotocol/group_context.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertyprotocol/service_group.go
  go/pkg/bertyprotocol/tinder_swiper.go
  go/pkg/messengertypes/messengertypes.pb.go
  go/pkg/messengertypes/types.go
  go/pkg/protocoltypes/protocoltypes.pb.go
  go/pkg/protocoltypes/protocoltypes.pb.gw.go
  js/gen.sum
  js/ios/Podfile.lock
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  js/packages/components/chat/MessageList.tsx
  js/packages/config/global.gen.js
  js/packages/grpc-bridge/welsh-clients.gen.ts
  js/packages/mock-services/mockedServicesInterfaces.gen.ts
  js/packages/screens/chat/SharedMedias/SharedMedias.tsx
  js/packages/utils/accounts/defaultCLIArgs.ts
  js/packages/utils/api/gen-type-utils.js
  js/packages/utils/api/types.gen.ts
Labels: bug, 🔍 Ready for Review
