Repository berty/berty, pull requests merged in 2022-07, with the labels that each got.

#4240 fix: remove any from several files
  js/packages/components/InfosChat.tsx
  js/packages/components/chat/audioMessageCommon.tsx
  js/packages/components/chat/footer/record/PreviewComponent.tsx
  js/packages/components/chat/message/FileMessage.tsx
  js/packages/components/chat/message/MessageSystemWrapper.tsx
  js/packages/components/chat/message/PictureMessage.tsx
  js/packages/components/chat/message/UserMessage.tsx
  js/packages/components/chat/message/UserMessageComponents.tsx
  js/packages/components/chat/modals/add-file-modal/AddFileMenu.modal.tsx
  js/packages/components/chat/modals/add-file-modal/GallerySection.tsx
  js/packages/components/create-group/CreateGroupHeader.tsx
  js/packages/components/debug/AppInspector.tsx
  js/packages/components/error.tsx
  js/packages/components/shared-components/ContactPicker.tsx
  js/packages/components/shared-components/SettingsButtons.tsx
  js/packages/messenger-app/custom-icons.tsx
  js/packages/navigation/stacks.tsx
  js/packages/screens/account/Opening/prepareAccount.effect.ts
  js/packages/screens/chat/ContactRequest/components/Request.tsx
  js/packages/screens/chat/CreateGroupFinalize/CreateGroupFinalize.tsx
  js/packages/screens/chat/Home/Home.tsx
  js/packages/screens/chat/Home/components/Header.tsx
  js/packages/screens/chat/Home/components/Requests.tsx
  js/packages/screens/chat/Home/components/Search.tsx
  js/packages/screens/chat/ImageView/ImageView.tsx
  js/packages/screens/chat/ManageDeepLink/components/InvalidScan.tsx
  js/packages/screens/chat/ManageDeepLink/components/ManageGroupInvitation.tsx
  js/packages/screens/chat/NotificationAndProximityPermissions/NotificationAndProximityPermissions.tsx
  js/packages/screens/chat/Permissions/Permissions.tsx
  js/packages/screens/chat/SharedMedias/SharedMedias.tsx
  js/packages/screens/onboarding/CustomMode/CustomMode.tsx
  js/packages/screens/onboarding/DefaultMode/DefaultMode.tsx
  js/packages/screens/onboarding/SetupFinished/SetupFinished.tsx
  js/packages/screens/settings/Accounts/Accounts.tsx
  js/packages/screens/settings/Appearance/Appearance.tsx
  js/packages/screens/settings/BertyServices/BertyServices.tsx
  js/packages/screens/settings/ContactAndConversations/ContactAndConversations.tsx
  js/packages/screens/settings/DevTools/DevTools.tsx
  js/packages/utils/accounts/accountUtils.ts
Labels: bug, ✅ Approved

#4250 feat: add common icon for new members ui
  js/packages/assets/custom-icons/transport-icons/transport-4g.svg
  js/packages/assets/custom-icons/transport-icons/transport-ble.svg
  js/packages/assets/custom-icons/transport-icons/transport-node.svg
  js/packages/assets/custom-icons/transport-icons/transport-wifi.svg
  js/packages/messenger-app/custom-icons.tsx
Labels: ✅ Approved, enhancement

#4253 fix: retry button contact request behavior
  js/packages/components/InfosChat.tsx
Labels: bug, 🔍 Ready for Review

#4255 docs: Add GitHub issues Feature Request form
  .github/ISSUE_TEMPLATE/feature_template.md
  .github/ISSUE_TEMPLATE/feature_template.yml
Labels: 🔍 Ready for Review, ✅ Approved, documentation

#4180 feat: run e2e basic test on CI
  .github/workflows/ios.yml
  js/e2e-tests/README.md
  js/e2e-tests/lib.js
Labels: 🔍 Ready for Review, enhancement

#4265 feat: implem peer network status redux models
  js/packages/mock-services/fakeGeneration.ts
  js/packages/mock-services/static/messengerServiceMock.ts
  js/packages/redux/reducers/messenger.reducer.ts
  js/packages/utils/testing/mockServices.test.ts
Labels: 🔍 Ready for Review, enhancement, wip

#4243 chore: new Crowdin updates
  js/packages/i18n/locale/af-ZA/messages.json
  js/packages/i18n/locale/ar-SA/messages.json
  js/packages/i18n/locale/bg-BG/messages.json
  js/packages/i18n/locale/ca-ES/messages.json
  js/packages/i18n/locale/cs-CZ/messages.json
  js/packages/i18n/locale/da-DK/messages.json
  js/packages/i18n/locale/de-DE/messages.json
  js/packages/i18n/locale/el-GR/messages.json
  js/packages/i18n/locale/es-ES/messages.json
  js/packages/i18n/locale/et-EE/messages.json
  js/packages/i18n/locale/fi-FI/messages.json
  js/packages/i18n/locale/fr-FR/messages.json
  js/packages/i18n/locale/he-IL/messages.json
  js/packages/i18n/locale/hi-IN/messages.json
  js/packages/i18n/locale/hu-HU/messages.json
  js/packages/i18n/locale/id-ID/messages.json
  js/packages/i18n/locale/it-IT/messages.json
  js/packages/i18n/locale/ja-JP/messages.json
  js/packages/i18n/locale/ka-GE/messages.json
  js/packages/i18n/locale/ko-KR/messages.json
  js/packages/i18n/locale/my-MM/messages.json
  js/packages/i18n/locale/nl-NL/messages.json
  js/packages/i18n/locale/no-NO/messages.json
  js/packages/i18n/locale/pl-PL/messages.json
  js/packages/i18n/locale/pt-BR/messages.json
  js/packages/i18n/locale/pt-PT/messages.json
  js/packages/i18n/locale/ro-RO/messages.json
  js/packages/i18n/locale/ru-RU/messages.json
  js/packages/i18n/locale/sl-SI/messages.json
  js/packages/i18n/locale/sr-Cyrl/messages.json
  js/packages/i18n/locale/sv-SE/messages.json
  js/packages/i18n/locale/te-IN/messages.json
  js/packages/i18n/locale/tr-TR/messages.json
  js/packages/i18n/locale/uk-UA/messages.json
  js/packages/i18n/locale/vi-VN/messages.json
  js/packages/i18n/locale/zh-CN/messages.json
  js/packages/i18n/locale/zh-TW/messages.json
Labels: ✅ Approved, chore

#4228 feat: add testing for 10 chat screens
  js/__mocks__/react-native-gesture-handler.js
  js/jest-setup.js
  js/packages/components/chat/footer/emojis/EmojiBanner.tsx
  js/packages/components/chat/message/MessageSystemWrapper.tsx
  js/packages/i18n/locale/en-US/messages.json
  js/packages/screens/chat/ContactSettings/ContactSettings.test.tsx
  js/packages/screens/chat/ContactSettings/__snapshots__/ContactSettings.test.tsx.snap
  js/packages/screens/chat/CreateGroupAddMembers/CreateGroupAddMembers.test.tsx
  js/packages/screens/chat/CreateGroupAddMembers/__snapshots__/CreateGroupAddMembers.test.tsx.snap
  js/packages/screens/chat/CreateGroupFinalize/CreateGroupFinalize.test.tsx
  js/packages/screens/chat/CreateGroupFinalize/__snapshots__/CreateGroupFinalize.test.tsx.snap
  js/packages/screens/chat/MultiMember/MultiMember.tsx
  js/packages/screens/chat/MultiMemberQR/MultiMemberQR.test.tsx
  js/packages/screens/chat/MultiMemberQR/__snapshots__/MultiMemberQR.test.tsx.snap
  js/packages/screens/chat/MultiMemberSettings/MultiMemberSettings.test.tsx
  js/packages/screens/chat/MultiMemberSettings/__snapshots__/MultiMemberSettings.test.tsx.snap
  js/packages/screens/chat/MultiMemberSettingsAddMembers/MultiMemberSettingsAddMembers.test.tsx
  js/packages/screens/chat/MultiMemberSettingsAddMembers/MultiMemberSettingsAddMembers.tsx
  js/packages/screens/chat/MultiMemberSettingsAddMembers/__snapshots__/MultiMemberSettingsAddMembers.test.tsx.snap
  js/packages/screens/chat/OneToOne/OneToOne.tsx
  js/packages/screens/chat/OneToOneSettings/OneToOneSettings.test.tsx
  js/packages/screens/chat/OneToOneSettings/__snapshots__/OneToOneSettings.test.tsx.snap
  js/packages/screens/chat/index.ts
  js/packages/utils/testing/helpers/index.ts
  js/packages/utils/testing/helpers/messengerStore.test.ts
Labels: 🔍 Ready for Review, enhancement, wip

#4279 feat: add forceMock value in redux store
  js/packages/i18n/locale/en-US/messages.json
  js/packages/redux/reducers/persistentOptions.reducer.ts
  js/packages/screens/account/Opening/OpeningAccount.tsx
  js/packages/screens/settings/DevTools/DevTools.tsx
Labels: ✅ Approved, enhancement

#4281 ci: add m1 self hosted runner and setup asdf
  .github/workflows/android.yml
  .github/workflows/go.yml
  .github/workflows/integration.yml
  .github/workflows/ios.yml
  .github/workflows/js.yml
  .github/workflows/mac.yml
  .github/workflows/protobuf.yml
  .github/workflows/release.yml
  .github/workflows/ssh-runner.yml
  .github/workflows/utils/get-self-hosted-runner-status.js
  .github/workflows/utils/mac-runner-matrix-builder.js
  .github/workflows/utils/variables.json
  .tool-versions
  Makefile
  go/Makefile
  go/cmd/berty/vc_issuer.go
  go/gen.sum
  go/internal/cryptoutil/keystore_message_utils.go
  go/internal/initutil/ipfs.go
  go/internal/proximitytransport/conn.go
  go/internal/testutil/skip.go
  go/internal/tinder/watchdogs_advertiser.go
  go/pkg/bertyauth/auth_session.go
  go/pkg/bertyauth/services_auth.go
  go/pkg/bertyprotocol/api_push.go
  go/pkg/bertypush/push_handler.go
  js/Makefile
  js/gen.sum
  js/ios/.gitignore
  js/ios/.ruby-version
  js/ios/Gemfile
  js/ios/Gemfile.lock
  js/ios/Podfile.lock
  js/ios/XcodeGen.version
  tool/ci-runner/.gitignore
  tool/ci-runner/Makefile
  tool/ci-runner/inventory.yml
  tool/ci-runner/m1_setup_runner.yml
  tool/ci-runner/mac_start_runner_daemon.yml
  tool/ci-runner/mac_stop_runner_daemon.yml
  tool/ci-runner/roles/actions_daemon/tasks/main.yml
  tool/ci-runner/roles/actions_daemon/tasks/start.yml
  tool/ci-runner/roles/actions_daemon/tasks/stop.yml
  tool/ci-runner/roles/actions_daemon/templates/daemon.plist.j2
  tool/ci-runner/roles/actions_daemon/vars/main.yml
  tool/ci-runner/roles/actions_setup/tasks/main.yml
  tool/ci-runner/roles/actions_setup/vars/main.yml
  tool/ci-runner/utils/check_arm64.yml
  tool/ci-runner/utils/check_m1.yml
  tool/ci-runner/utils/check_macos.yml
Labels: 🔍 Ready for Review, ci

#4285 docs: remove icon from bug template title
  .github/ISSUE_TEMPLATE/bug_template.yml
Labels: 🔍 Ready for Review, documentation

#4270 feat: new member ui, member list in conversation settings
  js/packages/assets/custom-icons/transport-icons/transport-wifi.svg
  js/packages/components/chat/DeviceList.tsx
  js/packages/components/dropdowns/Dropdown.priv.tsx
  js/packages/components/dropdowns/members/AddConversationBoosterButton.priv.tsx
  js/packages/components/dropdowns/members/MemberAvatarWithStatus.priv.tsx
  js/packages/components/dropdowns/members/MemberName.priv.tsx
  js/packages/components/dropdowns/members/MemberTransport.priv.tsx
  js/packages/components/dropdowns/members/MembersDropdown.tsx
  js/packages/components/dropdowns/members/MembersDropdownHeader.priv.tsx
  js/packages/components/dropdowns/members/interfaces.ts
  js/packages/components/inputs/index.ts
  js/packages/components/inputs/small/SmallClearableInput.tsx
  js/packages/i18n/locale/en-US/messages.json
  js/packages/messenger-app/App.tsx
  js/packages/screens/chat/MultiMemberSettings/MultiMemberSettings.tsx
  js/packages/screens/chat/MultiMemberSettings/__snapshots__/MultiMemberSettings.test.tsx.snap
Labels: 🔍 Ready for Review, enhancement

#4286 ci: fixes few problems on mac runners
  .github/workflows/go.yml
  .github/workflows/ios.yml
  js/Makefile
  js/ios/.xcode-version
  tool/ci-runner/.gitignore
  tool/ci-runner/Makefile
  tool/ci-runner/inventory.yml
  tool/ci-runner/mac_install_xcode_version.yml
  tool/ci-runner/mac_switch_to_xcode_version.yml
  tool/ci-runner/roles/actions_setup/tasks/main.yml
  tool/ci-runner/roles/asdf_setup/files/tool-versions
  tool/ci-runner/roles/asdf_setup/tasks/main.yml
  tool/ci-runner/roles/xcode_setup/tasks/main.yml
  tool/ci-runner/roles/xcode_setup/tasks/setup_installer.yml
  tool/ci-runner/roles/xcode_setup/tasks/switch.yml
  tool/ci-runner/roles/xcode_setup/vars/main.yml
  tool/ci-runner/xcode-cookie/.bundle/config
  tool/ci-runner/xcode-cookie/Gemfile
  tool/ci-runner/xcode-cookie/Gemfile.lock
  tool/ci-runner/xcode-cookie/gen_cookie.sh
Labels: 🔍 Ready for Review, ci

#4304 feat: add devicePK exchange head
  api/protocoltypes.proto
  docs/apis/protocoltypes.md
  docs/gen.sum
  go.mod
  go/gen.sum
  go/pkg/bertyprotocol/group.go
  go/pkg/bertyprotocol/message_marshaler.go
  go/pkg/bertyprotocol/message_marshaler_test.go
  go/pkg/bertyprotocol/orbitdb.go
  go/pkg/protocoltypes/protocoltypes.pb.go
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  tool/berty-mini-local-helper/Makefile
Labels: 🔍 Ready for Review, enhancement

#4307 feat: implement GroupDeviceStatus
  api/protocoltypes.proto
  go/cmd/berty/mini/view_group.go
  go/cmd/berty/mini/view_group_incoming.go
  go/gen.sum
  go/pkg/bertyprotocol/api_group.go
  go/pkg/bertyprotocol/message_marshaler_test.go
  go/pkg/bertyprotocol/orbitdb.go
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/bertyprotocol/service.go
  go/pkg/protocoltypes/protocoltypes.pb.go
Labels: 🔍 Ready for Review, enhancement

#4293 fix: UI front fixes
  go/internal/messengerdb/db.go
  go/pkg/bertymessenger/api.go
  js/packages/components/chat/footer/ChatFooter.tsx
  js/packages/components/chat/footer/emojis/EmojiBanner.tsx
  js/packages/components/chat/message/UserMessage.tsx
  js/packages/components/chat/message/UserMessageComponents.tsx
  js/packages/components/chat/message/reactions/EmojiNumber.tsx
  js/packages/components/chat/message/reactions/ReactionItem.tsx
  js/packages/components/chat/message/reactions/Reactions.tsx
  js/packages/components/chat/modals/EmojiKeyboard.modal.tsx
  js/packages/components/chat/modals/MessageMenu.modal.tsx
  js/packages/components/chat/modals/add-file-modal/AddFileMenu.modal.tsx
  js/packages/components/chat/modals/reactions-modal/MemberList.modal.priv.tsx
  js/packages/components/chat/modals/reactions-modal/ReactionList.modal.tsx
  js/packages/components/dropdowns/members/MembersDropdown.tsx
  js/packages/i18n/locale/en-US/messages.json
  js/packages/i18n/locale/fr-FR/messages.json
  js/packages/redux/reducers/chatInputsVolatile.reducer.ts
  js/packages/screens/chat/Home/components/HintBody.tsx
  js/packages/screens/chat/MultiMemberSettings/MultiMemberSettings.tsx
  js/packages/screens/settings/DeleteAccount/DeleteAccount.tsx
  js/packages/screens/settings/DevTools/DevTools.tsx
  js/packages/screens/settings/SettingsHome/SettingsHome.tsx
  js/packages/utils/emojis/emojis.ts
Labels: bug, 🔍 Ready for Review, wip

#4318 ci: try to fix setup asdf actions error
  .github/workflows/ios.yml
  .github/workflows/mac.yml
Labels: 🔍 Ready for Review, ci

#4319 chore: rename folder to ci-self-hosted
  .github/workflows/ios.yml
  .github/workflows/mac.yml
Labels: 🔍 Ready for Review, chore

#4320 chore: rename folder to ci-self-hosted
  .github/CODEOWNERS
  .github/workflows/ios.yml
  tool/ci-runner/inventory.yml
  tool/ci-self-hosted/.gitignore
  tool/ci-self-hosted/Makefile
  tool/ci-self-hosted/inventory.yml
  tool/ci-self-hosted/m1_setup_runner.yml
  tool/ci-self-hosted/mac_install_xcode_version.yml
  tool/ci-self-hosted/mac_start_runner_daemon.yml
  tool/ci-self-hosted/mac_stop_runner_daemon.yml
  tool/ci-self-hosted/mac_switch_to_xcode_version.yml
  tool/ci-self-hosted/roles/actions_daemon/tasks/main.yml
  tool/ci-self-hosted/roles/actions_daemon/tasks/start.yml
  tool/ci-self-hosted/roles/actions_daemon/tasks/stop.yml
  tool/ci-self-hosted/roles/actions_daemon/templates/daemon.plist.j2
  tool/ci-self-hosted/roles/actions_daemon/vars/main.yml
  tool/ci-self-hosted/roles/actions_setup/tasks/main.yml
  tool/ci-self-hosted/roles/actions_setup/vars/main.yml
  tool/ci-self-hosted/roles/asdf_setup/files/tool-versions
  tool/ci-self-hosted/roles/asdf_setup/tasks/main.yml
  tool/ci-self-hosted/roles/xcode_setup/tasks/main.yml
  tool/ci-self-hosted/roles/xcode_setup/tasks/setup_installer.yml
  tool/ci-self-hosted/roles/xcode_setup/tasks/switch.yml
  tool/ci-self-hosted/roles/xcode_setup/vars/main.yml
  tool/ci-self-hosted/utils/check_arm64.yml
  tool/ci-self-hosted/utils/check_m1.yml
  tool/ci-self-hosted/utils/check_macos.yml
  tool/ci-self-hosted/xcode-cookie/.bundle/config
  tool/ci-self-hosted/xcode-cookie/Gemfile
  tool/ci-self-hosted/xcode-cookie/Gemfile.lock
  tool/ci-self-hosted/xcode-cookie/gen_cookie.sh
Labels: 🔍 Ready for Review, chore

#4321 ci: fix cocoapods encoding
  .github/workflows/ios.yml
Labels: 🔍 Ready for Review, ci

#4322 ci: disable yolo build on ios workflow
  .github/workflows/ios.yml
  js/Makefile
Labels: 🔍 Ready for Review, ci

#4314 feat: implementation atomic chat (message field, action, helpers)
  js/ios/Podfile.lock
  js/packages/components/chat/ChatDate.tsx
  js/packages/components/chat/DeviceList.tsx
  js/packages/components/chat/ImageCounter.tsx
  js/packages/components/chat/InfosMultiMember.tsx
  js/packages/components/chat/WaveForm.tsx
  js/packages/components/chat/audioMessageCommon.tsx
  js/packages/components/chat/footer/CameraButton.tsx
  js/packages/components/chat/footer/ChatFooter.tsx
  js/packages/components/chat/footer/ChatFooterButtons.tsx
  js/packages/components/chat/footer/ChatTextInput.tsx
  js/packages/components/chat/footer/interface.ts
  js/packages/components/chat/footer/record/PreviewComponent.tsx
  js/packages/components/chat/footer/record/RecordComponent.tsx
  js/packages/components/chat/footer/recorder/HelpMessage.tsx
  js/packages/components/chat/footer/recorder/RecorderButton.tsx
  js/packages/components/chat/footer/recorder/RecorderPreview.tsx
  js/packages/components/chat/footer/recorder/RecorderWrapper.tsx
  js/packages/components/chat/footer/recorder/audio-preview/AudioPreview.tsx
  js/packages/components/chat/footer/recorder/audio-preview/AudioPreviewWrapper.tsx
  js/packages/components/chat/footer/recorder/audio-preview/interfaces.ts
  js/packages/components/chat/footer/recorder/constant.ts
  js/packages/components/chat/footer/recorder/recorderWrapper.helper.ts
  js/packages/components/chat/footer/reply/CancelReply.priv.tsx
  js/packages/components/chat/footer/reply/ReplyMessageBar.priv.tsx
  js/packages/components/chat/footer/reply/ReplyTargetAuthor.priv.tsx
  js/packages/components/chat/footer/reply/interface.ts
  js/packages/components/chat/footer/reply/reply-message/ReplyMessage.priv.tsx
  js/packages/components/chat/footer/reply/reply-message/ReplyMessageWithAttachment.priv.tsx
  js/packages/components/chat/message/AudioMessage.tsx
  js/packages/components/chat/message/FileMessage.tsx
  js/packages/components/chat/message/PictureMessage.tsx
  js/packages/components/chat/modals/add-file-modal/AddFileMenu.modal.tsx
  js/packages/components/chat/modals/add-file-modal/GallerySection.tsx
  js/packages/components/chat/modals/add-file-modal/ListItemMenu.tsx
  js/packages/components/chat/modals/add-file-modal/SecurityAccess.tsx
  js/packages/components/chat/modals/add-file-modal/types.ts
  js/packages/components/inputs/index.ts
  js/packages/screens/chat/OneToOne/OneToOne.tsx
  js/packages/utils/audio/index.ts
  js/packages/utils/react-native/useStateWithRef.ts
Labels: 🔍 Ready for Review, enhancement
