Repository berty/berty, pull requests merged in 2022-12, with the labels that each got.

#4509 chore: update go readme
  go/README.md
Labels: 🔍 Ready for Review

#4204 feat: verified credentials support in berty protocol
  api/bertyverifiablecreds.proto
  api/protocoltypes.proto
  api/protocoltypes.yaml
  docs/apis/protocoltypes.md
  docs/apis/protocoltypes.swagger.json
  docs/gen.sum
  go.mod
  go.sum
  go/cmd/berty/mini/view_group.go
  go/cmd/berty/mini/view_group_outgoing.go
  go/gen.sum
  go/pkg/bertydirectory/api.go
  go/pkg/bertyprotocol/api_verified_credentials.go
  go/pkg/bertyprotocol/events.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertyprotocol/store_metadata.go
  go/pkg/bertyprotocol/store_metadata_index.go
  go/pkg/bertyvcissuer/client.go
  go/pkg/bertyvcissuer/code_sender_stub.go
  go/pkg/bertyvcissuer/issuer.go
  go/pkg/bertyvcissuer/issuer_test.go
  go/pkg/bertyvcissuer/verifiable.go
  go/pkg/bertyvcissuer/verifiable_public_key_fetcher.go
  go/pkg/protocoltypes/events_account.go
  go/pkg/protocoltypes/protocoltypes.pb.go
  go/pkg/protocoltypes/protocoltypes.pb.gw.go
  go/pkg/verifiablecredstypes/bertyverifiablecreds.pb.go
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  js/packages/grpc-bridge/welsh-clients.gen.ts
  js/packages/hooks/methods/methods.gen.ts
  js/packages/mock-services/mockedServicesInterfaces.gen.ts
Labels: ✅ Approved, enhancement

#4498 feat(ci): generate pprof visualizations
  .github/workflows/benchmark.yml
  tool/scw-funcs/benchs-hook-proxy/.env.template
  tool/scw-funcs/benchs-hook-proxy/.gitignore
  tool/scw-funcs/benchs-hook-proxy/Makefile
  tool/scw-funcs/benchs-hook-proxy/README.md
  tool/scw-funcs/benchs-hook-proxy/dispatch.go
  tool/scw-funcs/benchs-hook-proxy/go.mod
  tool/scw-funcs/benchs-hook-proxy/go.sum
  tool/scw-funcs/benchs-hook-proxy/handler.go
  tool/scw-funcs/benchs-hook-proxy/handler_test.go
  tool/scw-funcs/benchs-hook-proxy/package.json
  tool/scw-funcs/benchs-hook-proxy/serverless.yml
Labels: 🔍 Ready for Review, enhancement

#4532 fix: benchmark on master
  .github/workflows/benchmark.yml
Labels: 🔍 Ready for Review
