Repository berty/berty, pull requests merged in 2022-11, with the labels that each got.

#4490 fix: android and ios builds
  js/ios/Podfile
  js/ios/Podfile.lock
  js/ios/berty.yaml
  js/package.json
  js/patches/expo-constants+13.0.2.patch
  js/patches/react-native+0.64.4.patch
  js/yarn.lock
Labels: bug, 🔍 Ready for Review

#4494 chore(benchmark): compare against master branch
  .github/workflows/benchmark.yml
Labels: ✅ Approved, chore

#4496 ci: fix ssh workflow for windows
  .github/workflows/ssh-runner.yml
Labels: 🔍 Ready for Review, ci

#4497 ci: fix go install (asdf) on windows
  .github/workflows/go.yml
  .github/workflows/release.yml
  .github/workflows/ssh-runner.yml
Labels: ✅ Approved, ci

#4469 chore: upgrade appium
  .github/workflows/ios.yml
  js/Makefile
  js/e2e-tests/basic.js
  js/e2e-tests/lib.js
  js/e2e-tests/package-lock.json
  js/e2e-tests/package.json
  js/ios/Podfile.lock
  js/package.json
  js/yarn.lock
Labels: 🔍 Ready for Review, chore, wip

#4483 feat: update relay config
  config/config.gen.json
  config/config.yml
  go/internal/config/config.gen.go
  js/packages/config/global.gen.js
Labels: ✅ Approved, enhancement

#4462 chore: move multi account features in devtools
  js/e2e-tests/lib.js
  js/packages/hooks/accounts.hooks.ts
  js/packages/i18n/locale/en-US/messages.json
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
  js/packages/screens/account/GoToLogInOrCreate/GoToLogInOrCreate.tsx
  js/packages/screens/account/GoToLogInOrCreate/goToLogInOrCreate.effect.ts
  js/packages/screens/chat/Home/Home.tsx
  js/packages/screens/chat/Home/components/Header.tsx
  js/packages/screens/chat/Home/components/MultiAccount.tsx
  js/packages/screens/settings/Accounts/Accounts.tsx
  js/packages/screens/settings/Accounts/__snapshots__/Accounts.test.tsx.snap
  js/packages/screens/settings/DevTools/DevTools.tsx
  js/packages/screens/settings/DevTools/__snapshots__/DevTools.test.tsx.snap
  js/packages/utils/accounts/closeAccount.ts
Labels: ✅ Approved, chore
