Repository berty/berty, pull requests merged in 2022-03, with the labels that each got.

#3935 feat: increase size of app font
  js/packages/components/InfosChat.tsx
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/MultiMemberSettings.tsx
  js/packages/components/chat/SharedMedias.tsx
  js/packages/components/chat/audioMessageCommon.tsx
  js/packages/components/chat/footer/ChatTextInput.tsx
  js/packages/components/chat/message/MessageInvitation.tsx
  js/packages/components/chat/message/MessageMonitorMetadata.tsx
  js/packages/components/chat/message/Reactions.tsx
  js/packages/components/chat/message/UserMessage.tsx
  js/packages/components/chat/message/UserMessageComponents.tsx
  js/packages/components/chat/message/index.tsx
  js/packages/components/main/Permissions.tsx
  js/packages/components/main/home/Conversations.tsx
  js/packages/components/main/home/Header.tsx
  js/packages/components/main/home/Requests.tsx
  js/packages/components/modals/AddBot.tsx
  js/packages/components/modals/AddThisContact.tsx
  js/packages/components/modals/EditProfile.tsx
  js/packages/components/modals/ManageGroupInvitation.tsx
  js/packages/components/modals/ThemeColorName.tsx
  js/packages/components/onboarding/AdvancedSettings.tsx
  js/packages/components/onboarding/CreateAccountBox.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/Mode.tsx
  js/packages/components/settings/WelcomeChecklist.tsx
  js/packages/components/shared-components/ContactPicker.tsx
  js/packages/components/shared-components/SettingsButtons.tsx
  js/packages/components/shared-components/WebViews.tsx
  js/packages/navigation/stacks.tsx
  js/packages/store/hooks.ts
  js/packages/styles/hook.tsx
  js/packages/styles/map-declaration.ts
Labels: ✅ Approved, enhancement

#3932 fix: front bug fixes for release
  js/ios/Podfile.lock
  js/packages/components/chat/EnableNotificationsButton.tsx
  js/packages/components/chat/MultiMemberSettings.tsx
  js/packages/components/chat/footer/ChatTextInput.tsx
Labels: bug, ✅ Approved

#3939 feat: update orbit-db to 1.14.2
  go.mod
  go.sum
Labels: ✅ Approved, enhancement

#3941 chore: cleanup wrongly generated crowdin lproj
  js/ios/Localization/af.lproj.lproj/Localizable.strings
  js/ios/Localization/ar.lproj.lproj/Localizable.strings
  js/ios/Localization/bg.lproj.lproj/Localizable.strings
  js/ios/Localization/ca.lproj.lproj/Localizable.strings
  js/ios/Localization/cs.lproj.lproj/Localizable.strings
  js/ios/Localization/da.lproj.lproj/Localizable.strings
  js/ios/Localization/de.lproj.lproj/Localizable.strings
  js/ios/Localization/el.lproj.lproj/Localizable.strings
  js/ios/Localization/en.lproj.lproj/Localizable.strings
  js/ios/Localization/es.lproj.lproj/Localizable.strings
  js/ios/Localization/et.lproj.lproj/Localizable.strings
  js/ios/Localization/fi.lproj.lproj/Localizable.strings
  js/ios/Localization/fr.lproj.lproj/Localizable.strings
  js/ios/Localization/he.lproj.lproj/Localizable.strings
  js/ios/Localization/hi.lproj.lproj/Localizable.strings
  js/ios/Localization/hu.lproj.lproj/Localizable.strings
  js/ios/Localization/id.lproj.lproj/Localizable.strings
  js/ios/Localization/it.lproj.lproj/Localizable.strings
  js/ios/Localization/ja.lproj.lproj/Localizable.strings
  js/ios/Localization/ka.lproj.lproj/Localizable.strings
  js/ios/Localization/ko.lproj.lproj/Localizable.strings
  js/ios/Localization/my.lproj.lproj/Localizable.strings
  js/ios/Localization/nl.lproj.lproj/Localizable.strings
  js/ios/Localization/no.lproj.lproj/Localizable.strings
  js/ios/Localization/pl.lproj.lproj/Localizable.strings
  js/ios/Localization/pt-BR.lproj.lproj/Localizable.strings
  js/ios/Localization/pt.lproj.lproj/Localizable.strings
  js/ios/Localization/ro.lproj.lproj/Localizable.strings
  js/ios/Localization/ru.lproj.lproj/Localizable.strings
  js/ios/Localization/sl.lproj.lproj/Localizable.strings
  js/ios/Localization/sr-Cyrl.lproj.lproj/Localizable.strings
  js/ios/Localization/sv.lproj.lproj/Localizable.strings
  js/ios/Localization/te.lproj.lproj/Localizable.strings
  js/ios/Localization/tr.lproj.lproj/Localizable.strings
  js/ios/Localization/uk.lproj.lproj/Localizable.strings
  js/ios/Localization/vi.lproj.lproj/Localizable.strings
  js/ios/Localization/zh-Hans.lproj.lproj/Localizable.strings
  js/ios/Localization/zh-Hant.lproj.lproj/Localizable.strings
Labels: 🔍 Ready for Review, chore

#3940 fix: share qr in multimember qr screen
  js/packages/components/chat/MultiMemberQR.tsx
Labels: bug, ✅ Approved

#3944 chore: fix crowdin config
  .crowdin.yml
Labels: 🔍 Ready for Review, chore

#3946 fix: remove apex localization import to app
  js/ios/berty.yaml
Labels: bug, 🔍 Ready for Review

#3958 fix: ios background crash
  go.mod
  go.sum
  go/internal/accountutils/utils.go
  go/internal/initutil/datastore.go
  go/internal/initutil/ipfs.go
  go/internal/initutil/node.go
  go/internal/ipfsutil/repo.go
  go/pkg/bertyaccount/service.go
  go/pkg/bertyaccount/service_account.go
  go/pkg/bertyaccount/service_storage.go
  go/pkg/bertyprotocol/orbitdb_many_adds_berty_test.go
  go/pkg/bertyprotocol/orbitdb_test.go
  go/pkg/bertypush/push_opener.go
Labels: bug, 🔍 Ready for Review

#3959 feat: setup Expo + submit button for bug reporting
  js/android/app/src/main/java/tech/berty/android/MainActivity.java
  js/android/app/src/main/java/tech/berty/android/MainApplication.java
  js/android/settings.gradle
  js/gen.sum
  js/ios/Berty/AppDelegate.h
  js/ios/Berty/AppDelegate.m
  js/ios/Podfile
  js/ios/Podfile.lock
  js/ios/berty.yaml
  js/package.json
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/berty-i18n/locale/fr-FR/messages.json
  js/packages/components/settings/Home.tsx
  js/packages/store/gen-type-utils.js
  js/packages/store/types.gen.ts
  js/yarn.lock
Labels: 🔍 Ready for Review, enhancement

#3961 fix: change off grid communication button logic
  js/package.json
  js/packages/components/settings/Home.tsx
  js/packages/messenger-app/App.tsx
  js/packages/messenger-app/lucide-icons.tsx
  js/yarn.lock
Labels: bug, ✅ Approved

#3966 ci: fix multiple jobs
  .github/workflows/android.yml
  .github/workflows/go.yml
  .github/workflows/integration.yml
  .github/workflows/ios.yml
  .github/workflows/js.yml
  .github/workflows/mac.yml
  .github/workflows/protobuf.yml
  .github/workflows/release.yml
  .github/workflows/variables.json
  js/ios/Podfile.lock
  js/packages/scripts/extract-pods-hashes.js
  js/packages/scripts/restore-pods-hashes.js
  js/patches/react-native+0.64.2.patch
  tool/check-dead-i18n/check.js
  tool/check-dead-i18n/check.sh
  tool/check-dead-i18n/list_i18n_keys.js
Labels: 🔍 Ready for Review, ci

#3967 fix: push notif button
  js/packages/components/chat/EnableNotificationsButton.tsx
Labels: bug, ✅ Approved

#3878 build: add `clean` to the top-level `Makefile`
  Makefile
Labels: 🔍 Ready for Review, build

#3975 fix: tinder swiper
  go/internal/omnisearch/berty-engine.go
  go/internal/testutil/logging.go
  go/internal/tinder/watchdogs_discoverer.go
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertyprotocol/tinder_swiper.go
  go/pkg/bertyprotocol/tinder_swiper_test.go
  go/pkg/tyber/log.go
Labels: bug, 🔍 Ready for Review

#3973 feat: implement nodelists and replace existing modals
  .gitignore
  js/android/app/build.gradle
  js/android/app/proguard-rules.pro
  js/android/app/src/main/java/tech/berty/android/MainApplication.java
  js/babel.config.js
  js/index.ts
  js/ios/Podfile.lock
  js/jest-setup.js
  js/package.json
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/berty-i18n/locale/fr-FR/messages.json
  js/packages/components/chat/ConversationModalContext.tsx
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/ReplyReactionContext.tsx
  js/packages/components/chat/footer/ChatFooter.tsx
  js/packages/components/chat/footer/ChatTextInput.tsx
  js/packages/components/chat/message/AudioMessage.tsx
  js/packages/components/chat/message/Popover.tsx
  js/packages/components/chat/message/Reactions.tsx
  js/packages/components/chat/message/UserMessage.tsx
  js/packages/components/chat/modals/EmojiKeyboard.modal.tsx
  js/packages/components/chat/modals/MessageMenu.modal.tsx
  js/packages/components/chat/modals/add-file-modal/AddFileMenu.modal.tsx
  js/packages/components/chat/modals/add-file-modal/GallerySection.tsx
  js/packages/components/chat/modals/add-file-modal/ListItemMenu.tsx
  js/packages/components/chat/modals/add-file-modal/SecurityAccess.tsx
  js/packages/components/chat/modals/add-file-modal/types.tsx
  js/packages/components/modals/AccordionAdd.modal.tsx
  js/packages/components/modals/AccordionEdit.modal.tsx
  js/packages/components/modals/EditProfile.tsx
  js/packages/components/onboarding/Button.tsx
  js/packages/components/onboarding/CustomModeSettings.tsx
  js/packages/components/onboarding/OnBoardingAccorion.tsx
  js/packages/components/providers/modal.provider.tsx
  js/packages/components/providers/musicPlayer.provider.tsx
  js/packages/components/providers/notification.provider.tsx
  js/packages/components/settings/Accordion.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/Network.tsx
  js/packages/components/shared-components/SettingsButtons.tsx
  js/packages/components/shared-components/TextInput.tsx
  js/packages/messenger-app/App.test.tsx
  js/packages/messenger-app/App.tsx
  js/packages/navigation/stacks.tsx
  js/packages/redux/reducers/chatInputs.reducer.ts
  js/packages/redux/reducers/chatInputsVolatile.reducer.ts
  js/packages/redux/reducers/networkConfig.reducer.ts
  js/patches/react-native-reanimated+2.3.1.patch
  js/tsconfig.json
  js/yarn.lock
Labels: 🔍 Ready for Review, enhancement

#3980 ci: optimize and reduce queueing
  .github/workflows/android.yml
  .github/workflows/cancel.yml
  .github/workflows/go.yml
  .github/workflows/integration.yml
  .github/workflows/ios.yml
  .github/workflows/js.yml
  .github/workflows/mac-runner-matrix-builder.js
  .github/workflows/mac.yml
  .github/workflows/monitor-runners.yml
  .github/workflows/protobuf.yml
  .github/workflows/release.yml
  .github/workflows/ssh-runner.yml
  .github/workflows/utils/get-selfhosted-runner-status.js
  .github/workflows/utils/mac-runner-matrix-builder.js
  .github/workflows/utils/variables.json
Labels: 🔍 Ready for Review, ci

#3981 ci: multiple fixes
  .github/workflows/monitor-runners.yml
  .github/workflows/ssh-runner.yml
  .github/workflows/utils/get-selfhosted-runner-status.js
Labels: 🔍 Ready for Review, ci

#3982 ci: small bash fix
  .github/workflows/monitor-runners.yml
Labels: 🔍 Ready for Review, ci

#3983 ci: small bash fix
  .github/workflows/monitor-runners.yml
Labels: 🔍 Ready for Review, ci

#3984 ci: small bash fix
  .github/workflows/monitor-runners.yml
Labels: 🔍 Ready for Review, ci

#3978 chore: publish js api
  .github/workflows/release.yml
  go.mod
  go.sum
  go/cmd/publish-npm-package/main.go
  js/packages/api/.gitignore
  js/packages/api/README.md
  js/packages/api/index.d.ts
  js/packages/api/index.js
  js/packages/api/package.template.json
  js/packages/api/tsconfig.json
Labels: 🚧 WIP, chore

#3739 chore: replaced leaved -> left everywhere
  go/internal/ipfsutil/pubsub_monitor.go
  go/pkg/bertyprotocol/api_group.go
  js/packages/components/chat/message/MessageMonitorMetadata.tsx
Labels: ✅ Approved, chore

#3993 fix: fix multi member screen
  js/packages/components/chat/MultiMember.tsx
Labels: bug, 🔍 Ready for Review

#3992 fix: enable localdiscover
  go/internal/initutil/ipfs.go
  go/internal/initutil/manager.go
  go/internal/tinder/driver_localdiscovery.go
  go/internal/tinder/filter_discovery.go
  go/internal/tinder/tinder_options.go
  go/internal/tinder/watchdogs_advertiser.go
  go/internal/tinder/watchdogs_discoverer.go
  go/pkg/bertyprotocol/tinder_swiper.go
Labels: bug, 🚧 WIP

#3994 chore: configure goreleaser to publish various OS and archs
  .goreleaser.yml
Labels: ✅ Approved, chore

#3991 New Crowdin updates
  js/packages/berty-i18n/locale/fr-FR/messages.json
Labels: ✅ Approved

#3952 feat: update orbitdb 1.15.0
  go.mod
  go.sum
  go/internal/initutil/orbitdb.go
  go/pkg/bertyprotocol/api_debug.go
  go/pkg/bertyprotocol/api_event.go
  go/pkg/bertyprotocol/contact_request_manager.go
  go/pkg/bertyprotocol/group.go
  go/pkg/bertyprotocol/orbitdb.go
  go/pkg/bertyprotocol/orbitdb_many_adds_berty_test.go
  go/pkg/bertyprotocol/orbitdb_utils_test.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertyprotocol/store_message.go
  go/pkg/bertyprotocol/store_metadata.go
  go/pkg/bertyprotocol/store_metadata_index.go
  go/pkg/bertyreplication/services_replication.go
Labels: 🔍 Ready for Review, enhancement

#4003 chore: bump goreleaser's golang version
  .github/workflows/release.yml
Labels: 🔍 Ready for Review, chore

#4009 ci: monitor runner ci job detailed output
  .github/workflows/monitor-runners.yml
Labels: 🔍 Ready for Review, ci

#4015 fix(ci): repair broken steps + various improvements
  .github/workflows/go.yml
  .github/workflows/integration.yml
  .github/workflows/release.yml
  Dockerfile
  go.mod
  go.sum
  tool/go.mod
  tool/go.sum
  tool/publish-npm-package/main.go
Labels: bug, 🔍 Ready for Review

#4017 fix(ci): fix semantic-release output filtering
  .github/workflows/ios.yml
  .github/workflows/release.yml
Labels: bug, 🔍 Ready for Review

#4018 fix(ci): unshallow git before calling goreleaser
  .github/workflows/release.yml
Labels: bug, 🔍 Ready for Review

#4019 fix(ci): fix goreleaser config for darwin
  .github/workflows/utils/.goreleaser.darwin.yml
  .github/workflows/utils/.goreleaser.linux.yml
  .github/workflows/utils/.goreleaser.windows.yml
Labels: bug, 🔍 Ready for Review

#3996 feat: rework localdiscovery
  go.mod
  go/internal/initutil/ipfs.go
  go/internal/initutil/manager.go
  go/internal/tinder/driver_localdiscovery.go
  go/pkg/bertyprotocol/contact_request_manager.go
Labels: ✅ Approved, enhancement

#4023 chore: web build on ci
  .github/workflows/js.yml
  js/Makefile
  js/gen.sum
Labels: ✅ Approved, chore

#4027 fix: double Unlock in ProximityTransport
  go/internal/proximitytransport/ringBuffer_map.go
Labels: bug, ✅ Approved

#4029 feat: add web modal
  js/packages/components/providers/modal.provider.tsx
  js/packages/polyfill/bottom-sheet.web.tsx
Labels: ✅ Approved, enhancement

#4016 feat: encrypt group payload
  api/protocoltypes.proto
  docs/apis/protocoltypes.md
  docs/gen.sum
  go.mod
  go.sum
  go/gen.sum
  go/internal/initutil/ipfs.go
  go/internal/initutil/manager.go
  go/internal/initutil/node.go
  go/internal/initutil/orbitdb.go
  go/internal/logutil/private_field.go
  go/internal/omnisearch/berty-engine.go
  go/internal/rendezvous/rotation.go
  go/internal/tinder/options.go
  go/internal/tinder/rotation.go
  go/pkg/bertyprotocol/contact_request_manager.go
  go/pkg/bertyprotocol/message_marshaler.go
  go/pkg/bertyprotocol/message_marshaler_test.go
  go/pkg/bertyprotocol/orbitdb.go
  go/pkg/bertyprotocol/orbitdb_topic.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertyprotocol/store_options.go
  go/pkg/bertyprotocol/tinder_swiper.go
  go/pkg/bertyprotocol/tinder_swiper_test.go
  go/pkg/protocoltypes/protocoltypes.pb.go
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  tool/berty-mini-local-helper/Makefile
  tool/go.sum
Labels: ✅ Approved, enhancement

#4037 ci: install emacs and remove timeout from ssh job
  .github/workflows/ssh-runner.yml
Labels: 🔍 Ready for Review, ci

#3997 feat: update EventEmitter with EventBus from orbitdb + fix cache
  go.mod
  go.sum
  go/cmd/berty/mini/view_group.go
  go/internal/cryptoutil/keystore_message.go
  go/internal/handshake/request.go
  go/internal/ipfsutil/repo.go
  go/internal/ipfsutil/testing.go
  go/pkg/bertyprotocol/api_debug.go
  go/pkg/bertyprotocol/api_event.go
  go/pkg/bertyprotocol/contact_request_manager.go
  go/pkg/bertyprotocol/events.go
  go/pkg/bertyprotocol/group.go
  go/pkg/bertyprotocol/orbitdb.go
  go/pkg/bertyprotocol/orbitdb_many_adds_berty_test.go
  go/pkg/bertyprotocol/orbitdb_many_adds_test.go
  go/pkg/bertyprotocol/orbitdb_signed_entry_accesscontroller.go
  go/pkg/bertyprotocol/orbitdb_utils_test.go
  go/pkg/bertyprotocol/scenario_test.go
  go/pkg/bertyprotocol/store_message.go
  go/pkg/bertyprotocol/store_message_queue.go
  go/pkg/bertyprotocol/store_message_test.go
  go/pkg/bertyprotocol/store_metadata.go
  go/pkg/bertyprotocol/store_metadata_index.go
  go/pkg/bertyreplication/services_replication.go
  go/pkg/bertyreplication/services_replication_test.go
  tool/go.sum
Labels: ✅ Approved, enhancement

#4035 feat: electron app with web content
  .github/workflows/mac.yml
  js/Makefile
  js/README.md
  js/electron-app/README.md
  js/electron-app/craco.config.js
  js/electron-app/package.json
  js/electron-app/public/favicon.ico
  js/electron-app/public/index.html
  js/electron-app/public/logo192.png
  js/electron-app/public/logo512.png
  js/electron-app/src-main/main.ts
  js/electron-app/src/App.css
  js/electron-app/src/App.test.tsx
  js/electron-app/src/App.tsx
  js/electron-app/src/index.css
  js/electron-app/src/index.tsx
  js/electron-app/src/react-app-env.d.ts
  js/electron-app/src/setupTests.ts
  js/electron-app/tsconfig.json
  js/electron-app/yarn.lock
  js/metro.config.js
  js/package.json
  js/tsconfig.json
  js/web/.gitignore
  js/web/package.json
  js/web/public/favicon.ico
  js/web/public/icon.icns
  js/web/public/index.html
  js/web/public/logo192.png
  js/web/public/logo512.png
  js/web/public/manifest.json
  js/web/public/robots.txt
  js/web/src-main/main.ts
  js/web/src-main/preload.ts
  js/web/tsconfig.json
  js/web/tsconfig.main.json
  js/web/yarn.lock
Labels: 🔍 Ready for Review, enhancement
