Repository berty/berty, pull requests merged in 2022-09, with the labels that each got.

#4404 chore: moved gomobile from aeddi's fork to berty's one
  go.mod
  go.sum
Labels: 🔍 Ready for Review, chore

#4405 ci: add post/pre checkout cleanup on macos build job
  .github/workflows/ios.yml
  .github/workflows/mac.yml
Labels: 🔍 Ready for Review, ci

#4394 feat: directory service initial implementation
  api/bertydirectory.proto
  api/bertydirectory.yaml
  api/errcode.proto
  docs/gen.sum
  go/Makefile
  go/gen.sum
  go/pkg/bertydirectory/api.go
  go/pkg/bertydirectory/api_test.go
  go/pkg/bertyvcissuer/issuer.go
  go/pkg/bertyvcissuer/verifiable.go
  go/pkg/bertyvcissuer/verifiable_public_key_fetcher.go
  go/pkg/directorytypes/bertydirectory.pb.go
  go/pkg/directorytypes/bertydirectory.pb.gw.go
  go/pkg/errcode/errcode.pb.go
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
Labels: ✅ Approved, enhancement

#4364 feat: implement settings snapshot tests
  js/ios/Podfile.lock
  js/packages/components/dropdowns/network/AddButton.priv.tsx
  js/packages/components/dropdowns/network/bootstrap/BootstrapItems.priv.tsx
  js/packages/components/dropdowns/network/relay/RelayItems.priv.tsx
  js/packages/components/dropdowns/network/rendezvous/RendezvousItems.priv.tsx
  js/packages/screens/onboarding/CustomModeSettings/__snapshots__/CustomModeSettings.test.tsx.snap
  js/packages/screens/settings/AboutBerty/AboutBerty.test.tsx
  js/packages/screens/settings/AboutBerty/__snapshots__/AboutBerty.test.tsx.snap
  js/packages/screens/settings/Accounts/Accounts.test.tsx
  js/packages/screens/settings/Accounts/__snapshots__/Accounts.test.tsx.snap
  js/packages/screens/settings/AddDevConversations/AddDevConversations.test.tsx
  js/packages/screens/settings/AddDevConversations/__snapshots__/AddDevConversations.test.tsx.snap
  js/packages/screens/settings/Appearance/Appearance.test.tsx
  js/packages/screens/settings/Appearance/__snapshots__/Appearance.test.tsx.snap
  js/packages/screens/settings/ContactAndConversations/ContactAndConversations.test.tsx
  js/packages/screens/settings/ContactAndConversations/__snapshots__/ContactAndConversations.test.tsx.snap
  js/packages/screens/settings/DeleteAccount/DeleteAccount.test.tsx
  js/packages/screens/settings/DeleteAccount/__snapshots__/DeleteAccount.test.tsx.snap
  js/packages/screens/settings/DevText/DevText.test.tsx
  js/packages/screens/settings/DevText/__snapshots__/DevText.test.tsx.snap
  js/packages/screens/settings/DevTools/DevTools.test.tsx
  js/packages/screens/settings/DevTools/__snapshots__/DevTools.test.tsx.snap
  js/packages/screens/settings/FakeData/FakeData.test.tsx
  js/packages/screens/settings/FakeData/__snapshots__/FakeData.test.tsx.snap
  js/packages/screens/settings/Faq/Faq.test.tsx
  js/packages/screens/settings/Faq/__snapshots__/Faq.test.tsx.snap
  js/packages/screens/settings/IpfsWebUI/IpfsWebUI.test.tsx
  js/packages/screens/settings/IpfsWebUI/__snapshots__/IpfsWebUI.test.tsx.snap
  js/packages/screens/settings/Network/Network.test.tsx
  js/packages/screens/settings/Network/Network.tsx
  js/packages/screens/settings/Network/__snapshots__/Network.test.tsx.snap
  js/packages/screens/settings/Notifications/Notifications.test.tsx
  js/packages/screens/settings/Notifications/__snapshots__/Notifications.test.tsx.snap
  js/packages/screens/settings/Permissions/Permissions.test.tsx
  js/packages/screens/settings/Permissions/__snapshots__/Permissions.test.tsx.snap
  js/packages/screens/settings/PrivacyPolicy/PrivacyPolicy.test.tsx
  js/packages/screens/settings/PrivacyPolicy/__snapshots__/PrivacyPolicy.test.tsx.snap
  js/packages/screens/settings/Roadmap/Roadmap.test.tsx
  js/packages/screens/settings/Roadmap/__snapshots__/Roadmap.test.tsx.snap
  js/packages/screens/settings/SystemInfo/SystemInfo.test.tsx
  js/packages/screens/settings/SystemInfo/__snapshots__/SystemInfo.test.tsx.snap
  js/packages/screens/settings/TermsOfUse/TermsOfUse.test.tsx
  js/packages/screens/settings/TermsOfUse/__snapshots__/TermsOfUse.test.tsx.snap
  js/packages/screens/settings/ThemeEditor/ThemeEditor.test.tsx
  js/packages/screens/settings/ThemeEditor/__snapshots__/ThemeEditor.test.tsx.snap
Labels: ✅ Approved, enhancement

#4400 fix: delete Bertypush.xcframework in js Makefile clean rule
  js/Makefile
Labels: bug, ✅ Approved

#4440 fix: Tyber build
  tool/tyber/Makefile
  tool/tyber/go/go.mod
  tool/tyber/go/go.sum
Labels: bug, ✅ Approved

#4442 fix: Activate logs by default in Debug, Staff and Yolo build variants
  js/android/app/build.gradle
  js/android/app/src/main/java/tech/berty/gobridge/GoBridgeModule.java
  js/ios/Berty/Sources/Bridge/GoBridge.swift
  js/ios/Podfile.lock
  js/ios/berty.yaml
  js/packages/utils/global-persistent-options/defaults.ts
Labels: bug, ✅ Approved

#4445 chore: bump gomobile version
  go.mod
  go.sum
Labels: 🔍 Ready for Review, chore
