Repository berty/berty, pull requests merged in 2022-01, with the labels that each got.

#3840 refactor: move redux hooks to react-redux package
  js/packages/components/avatars.tsx
  js/packages/components/chat/ContactSettings.tsx
  js/packages/components/chat/MessageList.tsx
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/MultiMemberQR.tsx
  js/packages/components/chat/MultiMemberSettings.tsx
  js/packages/components/chat/MultiMembersSettingsAddMembers.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/OneToOneSettings.tsx
  js/packages/components/chat/ReplicateGroupSettings.tsx
  js/packages/components/chat/footer/ChatFooter.tsx
  js/packages/components/chat/message/MessageInvitation.tsx
  js/packages/components/chat/message/UserMessage.tsx
  js/packages/components/main/CreateGroupAddMembers.tsx
  js/packages/components/main/home/Conversations.tsx
  js/packages/components/main/home/Home.tsx
  js/packages/components/main/home/Search.tsx
  js/packages/components/modals/EditProfile.tsx
  js/packages/components/modals/ImageView.tsx
  js/packages/components/notifications/ContactRequestReceived.tsx
  js/packages/components/notifications/ContactRequestSent.tsx
  js/packages/components/notifications/MessageReceived.tsx
  js/packages/components/onboarding/AdvancedSettings.tsx
  js/packages/components/onboarding/CreateAccountBox.tsx
  js/packages/components/settings/DevTools.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/MyBertyId.tsx
  js/packages/components/shared-components/ContactPicker.tsx
  js/packages/components/shared-components/Request.tsx
  js/packages/react-redux/hooks/messenger.hooks.ts
  js/packages/redux/reducers/messenger.reducer.ts
  js/packages/store/hooks.ts
  js/packages/store/provider.tsx
  js/packages/store/services.tsx
  js/packages/web-dev-app/src/App.tsx
Labels: 🔍 Ready for Review, refactor

#3807 fix: remove footer conversation excessive padding
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
Labels: bug, 🔍 Ready for Review

#3815 Home redirection
  js/packages/components/modals/AddThisContact.tsx
  js/packages/components/modals/ManageGroupInvitation.tsx
Labels: 🔍 Ready for Review

#3844 fix(js): convert removed hooks usage to new hooks
  js/packages/components/modals/AddThisContact.tsx
  js/packages/components/modals/ManageGroupInvitation.tsx
Labels: bug, 🔍 Ready for Review

#3824 chore: increase ipfs debugging verbosity
  go/internal/logutil/logutil.go
Labels: ✅ Approved, chore

#3767 fix: change camera permission text in english and french
  js/ios/info.yaml
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/berty-i18n/locale/fr-FR/messages.json
Labels: bug, 🔍 Ready for Review

#3836 fix: more notification messages cases
  go/localization/locales/en-US/localization.json
  go/localization/locales/fr-FR/localization.json
  go/pkg/bertypush/push_format.go
  go/pkg/bertypush/push_opener.go
Labels: bug, 🔍 Ready for Review

#3845 feat: move theme to redux store
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/berty-i18n/locale/fr-FR/messages.json
  js/packages/components/modals/ThemeColorName.tsx
  js/packages/components/settings/Mode.tsx
  js/packages/components/settings/ThemeEditor.tsx
  js/packages/redux/reducers/theme.reducer.ts
  js/packages/redux/store.ts
  js/packages/store/context.ts
  js/packages/store/hooks.ts
  js/packages/store/providerEffects.ts
  js/packages/store/types.ts
Labels: 🔍 Ready for Review, enhancement

#3859 chore: avoid ipfs/go-log to run in debug mode when unecessary
  docs/apis/messengertypes.md
  docs/gen.sum
  go.mod
  go.sum
  go/internal/logutil/logutil.go
Labels: 🔍 Ready for Review, chore

#3727 feat: push i18n fallback message
  .crowdin.yml
  go/pkg/bertypushrelay/services_push_apns.go
  js/ios/Berty/AppDelegate.m
  js/ios/Berty/Sources/Bridge/KeystoreDriver.swift
  js/ios/Berty/Sources/RootDir/RootDir.swift
  js/ios/Localization/Base.lproj/Localizable.strings
  js/ios/Localization/en.lproj/Localizable.strings
  js/ios/Localization/fr.lproj/Localizable.strings
  js/ios/NotificationService/Common.swift
  js/ios/NotificationService/NotificationService.swift
  js/ios/Podfile.lock
  js/ios/berty.yaml
Labels: ✅ Approved, enhancement

#3852 fix: crash when iOS BLE driver stops
  go/internal/ble-driver/BertyDevice_darwin.m
  go/internal/ble-driver/BleInterface_darwin.m
  go/internal/ble-driver/BleManager_darwin.m
  go/internal/ble-driver/BleQueue.m
  go/internal/ble-driver/CountDownLatch_darwin.h
  go/internal/ble-driver/CountDownLatch_darwin.m
  go/internal/ble-driver/PeerManager.m
Labels: bug, ✅ Approved

#3858 feat: auth i18n + service selection by user
  go/cmd/berty/token.go
  go/localization/locales/en-US/localization.json
  go/localization/locales/fr-FR/localization.json
  go/pkg/bertyauth/services_auth_server.go
  go/pkg/bertyauth/services_auth_server_test.go
  go/pkg/bertyauth/services_auth_templates.go
Labels: 🔍 Ready for Review, enhancement

#3849 feat: disable push token auto-sharing
  api/messengertypes.proto
  api/messengertypes.yaml
  docs/apis/messengertypes.md
  docs/apis/messengertypes.swagger.json
  docs/gen.sum
  go/Makefile
  go/gen.sum
  go/internal/messengerdb/db.go
  go/internal/messengerdb/db_test.go
  go/internal/messengerpayloads/handlers.go
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertymessenger/service_post_actions.go
  go/pkg/messengertypes/messengertypes.pb.go
  go/pkg/messengertypes/messengertypes.pb.gw.go
  js/gen.sum
  js/ios/Berty/Sources/PushTokenRequester/PushTokenRequester.swift
  js/ios/Podfile.lock
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/components/chat/ChatSettingsMemberDetail.tsx
  js/packages/components/chat/ContactSettings.tsx
  js/packages/components/chat/DeviceList.tsx
  js/packages/components/chat/EnableNotificationsButton.tsx
  js/packages/components/chat/MultiMemberSettings.tsx
  js/packages/components/chat/OneToOneSettings.tsx
  js/packages/components/chat/index.ts
  js/packages/components/main/Permissions.tsx
  js/packages/components/onboarding/CreateAccountBox.tsx
  js/packages/components/settings/ServicesAuth.tsx
  js/packages/grpc-bridge/welsh-clients.gen.ts
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
  js/packages/store/providerEffects.ts
  js/packages/store/services.tsx
  js/packages/store/types.gen.ts
Labels: 🔍 Ready for Review, enhancement

#3864 feat: move uiReducer to redux
  js/ios/Podfile.lock
  js/packages/components/AttachmentImage.tsx
  js/packages/components/chat/DeviceList.tsx
  js/packages/components/chat/EnableNotificationsButton.tsx
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/MultiMemberSettings.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/ReplicateGroupSettings.tsx
  js/packages/components/chat/SharedMedias.tsx
  js/packages/components/chat/footer/record/RecordComponent.tsx
  js/packages/components/chat/message/AudioMessage.tsx
  js/packages/components/chat/message/FileMessage.tsx
  js/packages/components/chat/message/PictureMessage.tsx
  js/packages/components/chat/message/QuickReplyOptions.tsx
  js/packages/components/chat/message/UserMessage.tsx
  js/packages/components/error.tsx
  js/packages/components/gates.tsx
  js/packages/components/main/Permissions.tsx
  js/packages/components/main/home/Home.tsx
  js/packages/components/main/home/MultiAccount.tsx
  js/packages/components/modals/EditProfile.tsx
  js/packages/components/music-player.tsx
  js/packages/components/onboarding/AdvancedSettings.tsx
  js/packages/components/settings/BertyServices.tsx
  js/packages/components/settings/DevTools.tsx
  js/packages/components/settings/Home.tsx
  js/packages/components/settings/Mode.tsx
  js/packages/components/settings/ServicesAuth.tsx
  js/packages/messenger-app/App.tsx
  js/packages/navigation/stacks.tsx
  js/packages/redux/reducers/ui.reducer.ts
  js/packages/redux/store.ts
  js/packages/store/context.ts
  js/packages/store/effectableCallbacks.ts
  js/packages/store/hooks.ts
  js/packages/store/methods.ts
  js/packages/store/provider.tsx
  js/packages/store/providerCallbacks.ts
  js/packages/store/providerEffects.ts
  js/packages/store/reducer/index.ts
  js/packages/store/reducer/uiReducer.ts
  js/packages/store/services.tsx
  js/packages/store/types.ts
  js/packages/web-dev-app/src/App.tsx
Labels: 🔍 Ready for Review, enhancement

#3861 feat: bump to ipfs 0.11
  go.mod
  go.sum
  go/cmd/berty-doctor/rdvp.go
  go/cmd/berty/scenario_test.go
  go/cmd/rdvp/main.go
  go/framework/bertybridge/blackbox_test.go
  go/framework/bertybridge/bridge.go
  go/framework/bertybridge/driver_net.go
  go/internal/accountutils/utils.go
  go/internal/cryptoutil/group_store.go
  go/internal/cryptoutil/keystore_message.go
  go/internal/cryptoutil/keystore_message_utils_test.go
  go/internal/initutil/ipfs.go
  go/internal/initutil/manager.go
  go/internal/initutil/manager_test.go
  go/internal/initutil/node.go
  go/internal/initutil/tor_embedded.go
  go/internal/initutil/tor_unembedded.go
  go/internal/ipfsutil/helpers_test.go
  go/internal/ipfsutil/inet.go
  go/internal/ipfsutil/keystore_datastore.go
  go/internal/ipfsutil/mdns.go
  go/internal/ipfsutil/repo.go
  go/internal/ipfsutil/testing.go
  go/internal/messengerdb/db_test_utils.go
  go/pkg/bertyaccount/blackbox_test.go
  go/pkg/bertyaccount/service_account.go
  go/pkg/bertyaccount/service_storage.go
  go/pkg/bertyprotocol/api_contactrequest.go
  go/pkg/bertyprotocol/api_group.go
  go/pkg/bertyprotocol/api_multimember.go
  go/pkg/bertyprotocol/api_push.go
  go/pkg/bertyprotocol/api_push_test.go
  go/pkg/bertyprotocol/group.go
  go/pkg/bertyprotocol/orbitdb.go
  go/pkg/bertyprotocol/orbitdb_datastore_cache.go
  go/pkg/bertyprotocol/orbitdb_signed_entry_identity_provider.go
  go/pkg/bertyprotocol/orbitdb_signed_entry_keystore.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertyprotocol/service_group.go
  go/pkg/bertyprotocol/store_message.go
  go/pkg/bertyprotocol/store_message_test.go
  go/pkg/bertyprotocol/store_metadata.go
  go/pkg/bertyprotocol/store_options.go
  go/pkg/bertypush/push.go
  go/pkg/bertypush/push_handler.go
  go/pkg/bertypush/push_opener.go
  js/android/app/src/main/java/tech/berty/gobridge/GoBridgeModule.java
  js/android/app/src/main/java/tech/berty/gobridge/NetDriver.java
Labels: 🔍 Ready for Review, enhancement, WIP

#3882 fix(go): bump encrepo
  go.mod
  go.sum
Labels: bug, 🔍 Ready for Review

#3774 fix: async load of messenger
  go/pkg/bertymessenger/service.go
  go/pkg/bertyprotocol/events.go
Labels: bug, ✅ Approved, WIP

#3875 feat: add emoji suggestion modal
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/berty-i18n/locale/fr-FR/messages.json
  js/packages/components/chat/footer/ChatFooter.tsx
  js/packages/components/chat/footer/ChatTextInput.tsx
  js/packages/components/chat/footer/emojis/EmojiBanner.tsx
  js/packages/components/chat/footer/record/RecordComponent.tsx
  js/packages/components/main/home/Conversations.tsx
  js/packages/components/main/home/Header.tsx
  js/packages/components/main/home/Home.tsx
  js/packages/components/shared-components/DropDownPicker.tsx
  js/packages/components/utils.ts
  js/packages/redux/reducers/chatInputsVolatile.reducer.ts
  js/packages/redux/reducers/theme.reducer.ts
  js/packages/styles/types.ts
  js/yarn.lock
Labels: ✅ Approved, enhancement
