Repository berty/berty, pull requests merged in 2022-05, with the labels that each got.

#4104 fix: prevent closing add screen when camera permission is granted
  js/packages/screens/chat/Share/Share.tsx
Labels: bug, ✅ Approved

#4105 fix(app): removed shadow on group creation hints
  js/packages/screens/chat/CreateGroupFinalize/CreateGroupFinalize.tsx
Labels: bug, ✅ Approved

#4117 fix: mini: Trim command spaces after TrimPrefix
  go/cmd/berty/mini/view_group.go
Labels: bug, 🔍 Ready for Review

#4083 feat: push notification settings enhancements
  api/messengertypes.proto
  api/messengertypes.yaml
  api/protocoltypes.proto
  api/pushtypes.proto
  docs/apis/messengertypes.md
  docs/apis/messengertypes.swagger.json
  docs/apis/protocoltypes.md
  docs/apis/protocoltypes.swagger.json
  docs/gen.sum
  go/gen.sum
  go/internal/messengerdb/db.go
  go/localization/locales/en-US/localization.json
  go/localization/locales/fr-FR/localization.json
  go/pkg/bertymessenger/api.go
  go/pkg/bertymessenger/service.go
  go/pkg/bertyprotocol/api_services_auth.go
  go/pkg/bertypush/push.go
  go/pkg/bertypush/push_format.go
  go/pkg/bertypush/push_opener.go
  go/pkg/messengertypes/messengertypes.pb.go
  go/pkg/messengertypes/messengertypes.pb.gw.go
  go/pkg/protocoltypes/protocoltypes.pb.go
  go/pkg/pushtypes/pushtypes.pb.go
  js/android/app/src/main/java/tech/berty/notification/NotificationService.java
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  js/packages/components/NotificationBody.tsx
  js/packages/components/chat/EnableNotificationsButton.tsx
  js/packages/components/chat/footer/ChatFooter.tsx
  js/packages/components/chat/footer/record/RecordComponent.tsx
  js/packages/components/chat/modals/add-file-modal/AddFileMenu.modal.tsx
  js/packages/components/chat/modals/add-file-modal/SecurityAccess.tsx
  js/packages/components/providers/permissions.provider.tsx
  js/packages/components/shared-components/SettingsButtons.tsx
  js/packages/contexts/permissions.context.ts
  js/packages/grpc-bridge/welsh-clients.gen.ts
  js/packages/i18n/locale/en-US/messages.json
  js/packages/messenger-app/App.tsx
  js/packages/navigation/types.ts
  js/packages/redux/reducers/messenger.reducer.ts
  js/packages/rnutil/checkPermissions.ts
  js/packages/rnutil/permissions.ts
  js/packages/screens/chat/BlePermission/BlePermission.tsx
  js/packages/screens/chat/Permissions/Permissions.tsx
  js/packages/screens/chat/ReplicateGroupSettings/ReplicateGroupSettings.tsx
  js/packages/screens/chat/Share/Share.tsx
  js/packages/screens/onboarding/CreateAccount/CreateAccount.tsx
  js/packages/screens/onboarding/CustomModeSettings/CustomModeSettings.tsx
  js/packages/screens/settings/Notifications/Notifications.tsx
  js/packages/screens/settings/SettingsHome/SettingsHome.tsx
  js/packages/store/convert.ts
  js/packages/store/push.ts
  js/packages/store/services.tsx
  js/packages/store/types.gen.ts
Labels: ✅ Approved, enhancement

#4113 feat: add get started documentation for web
  js/Makefile
  js/README.md
Labels: 🔍 Ready for Review, enhancement

#4112 feat: add qr code on web
  js/web/craco.config.js
  js/web/src/polyfill/react-native-qrcode-svg/index.tsx
Labels: 🔍 Ready for Review, enhancement

#4120 Update README.md
  README.md
Labels: ✅ Approved

#4122 chore: remove default codeowners
  .github/CODEOWNERS
Labels: ✅ Approved, chore

#4127 chore: refacto @berty/i18n
  js/index.ts
  js/packages/i18n/index.ts
  js/packages/screens/settings/DevTools/DevTools.tsx
  js/packages/store/effectsImplem.ts
Labels: 🔍 Ready for Review, chore

#4134 chore: bump gomobile fork
  Dockerfile
  go.mod
  go.sum
  js/Makefile
  tool/go.sum
Labels: 🔍 Ready for Review, chore

#4124 misc front renaming and removal
  assets/Buck_Berty_Icon_Card.svg
  assets/logo.svg
  assets/xxxhdpi.png
  go/internal/initutil/notification.go
  js/Makefile
  js/packages/components/MiniGame.tsx
  js/packages/components/debug/AppInspector.tsx
  js/packages/components/providers/notification.provider.tsx
  js/packages/grpc-bridge/README.md
  js/packages/grpc-bridge/bridge.ts
  js/packages/grpc-bridge/grpc-web-react-native-transport.ts
  js/packages/grpc-bridge/grpc-web-websocket-transport.ts
  js/packages/grpc-bridge/index.ts
  js/packages/grpc-bridge/rpc/rpc.bridge.ts
  js/packages/grpc-bridge/rpc/utils.ts
  js/packages/grpc-bridge/service.test.ts
  js/packages/grpc-bridge/service.ts
  js/packages/hooks/networkConfig.hooks.ts
  js/packages/i18n/README.md
  js/packages/navigation/README.md
  js/packages/redux/persistStorage.ts
  js/packages/screens/chat/Permissions/Permissions.tsx
  js/packages/screens/onboarding/CreateAccount/CreateAccount.tsx
  js/packages/screens/onboarding/CreateAccount/components/CreateAccountBox.tsx
  js/packages/screens/onboarding/CustomModeSettings/CustomModeSettings.tsx
  js/packages/screens/onboarding/DefaultMode/DefaultMode.tsx
  js/packages/screens/onboarding/GetStarted/GetStarted.tsx
  js/packages/screens/settings/DevTools/DevTools.tsx
  js/packages/screens/settings/SettingsHome/SettingsHome.tsx
  js/packages/screens/settings/SystemInfo/SystemInfo.tsx
  js/packages/store/README.md
  js/packages/store/effectsImplem.ts
  js/packages/store/utils.ts
  js/packages/utils/accounts/accountBackup.ts
  js/packages/utils/accounts/accountClient.ts
  js/packages/utils/accounts/accountUtils.ts
  tool/game-utils/game-dev-app/App.tsx
  tool/game-utils/game-dev-app/metro.config.js
Labels: ✅ Approved

#4125 chore: move contexts to @berty/contexts
  js/.eslintrc.js
  js/packages/components/chat/footer/ChatFooter.tsx
  js/packages/components/chat/message/AudioMessage.tsx
  js/packages/components/chat/message/UserMessage.tsx
  js/packages/components/chat/modals/EmojiKeyboard.modal.tsx
  js/packages/components/chat/modals/MessageMenu.modal.tsx
  js/packages/contexts/modal.context.tsx
  js/packages/contexts/musicPlayer.context.tsx
  js/packages/contexts/notification.context.tsx
  js/packages/contexts/permissions.context.ts
  js/packages/contexts/permissions.context.tsx
  js/packages/contexts/uiKitten.context.tsx
  js/packages/messenger-app/App.tsx
  js/packages/screens/onboarding/CustomModeSettings/CustomModeSettings.tsx
  js/packages/screens/settings/Network/Network.tsx
  js/packages/screens/settings/SettingsHome/SettingsHome.tsx
  js/packages/screens/settings/SettingsHome/components/EditProfile.tsx
Labels: ✅ Approved, chore

#4126 chore: move native modules to @berty/native-modules and remove dead code
  js/Makefile
  js/index.ts
  js/packages/go-bridge/.gitattributes
  js/packages/go-bridge/.gitignore
  js/packages/go-bridge/.npmignore
  js/packages/go-bridge/defaults.ts
  js/packages/go-bridge/index.ts
  js/packages/grpc-bridge/rpc/rpc.native.ts
  js/packages/native-modules/GoBridge/GoBridge.native.ts
  js/packages/native-modules/GoBridge/GoBridge.ts
  js/packages/native-modules/GoBridge/GoBridgeInterface.ts
  js/packages/native-modules/GoBridge/index.ts
  js/packages/native-modules/GoBridge/logger.ts
  js/packages/native-modules/PushTokenRequester/PushTokenRequester.native.ts
  js/packages/native-modules/PushTokenRequester/PushTokenRequester.ts
  js/packages/native-modules/PushTokenRequester/PushTokenRequesterInterface.ts
  js/packages/native-modules/PushTokenRequester/index.ts
  js/packages/screens/settings/DevTools/DevTools.tsx
  js/packages/store/effectsImplem.ts
  js/packages/utils/accounts/defaultCLIArgs.ts
  js/packages/utils/notification/notif-push.ts
Labels: ✅ Approved, chore

#4136 Move screen-specific components to @berty/screens
  js/packages/components/modals/AccordionAdd.modal.tsx
  js/packages/components/modals/AccordionEdit.modal.tsx
  js/packages/components/onboarding/SwiperCard.tsx
  js/packages/components/shared-components/Button.tsx
  js/packages/components/shared-components/Card.tsx
  js/packages/components/shared-components/index.ts
  js/packages/screens/chat/ContactRequest/components/Modal.tsx
  js/packages/screens/chat/ContactRequest/components/Request.tsx
  js/packages/screens/chat/Home/components/FromNow.tsx
  js/packages/screens/chat/Home/components/HintBody.tsx
  js/packages/screens/chat/Home/components/Requests.tsx
  js/packages/screens/chat/Home/components/Search.tsx
  js/packages/screens/onboarding/GetStarted/GetStarted.tsx
Labels: 🔍 Ready for Review

#4139 fix: go bridge
  js/packages/native-modules/GoBridge/GoBridge.native.ts
Labels: bug, 🔍 Ready for Review

#4135 fix: add support go 1.18
  Dockerfile
  go.mod
  go.sum
Labels: bug, ✅ Approved

#4130 fix: react-native-inappbrowser-reborn android build
  .github/workflows/utils/variables.json
  js/Makefile
  js/android/build.gradle
  js/patches/react-native-inappbrowser-reborn+3.6.3.patch
Labels: bug, 🔍 Ready for Review

#4141 fix: gradle version code and name generation
  js/android/app/build.gradle
Labels: bug, ✅ Approved

#4144 feat: add start/stop method to infra testing tool
  tool/infra-testing-tool/Makefile
  tool/infra-testing-tool/go/cmd/auxilaryFunctions.go
  tool/infra-testing-tool/go/cmd/root.go
  tool/infra-testing-tool/go/cmd/test.go
  tool/infra-testing-tool/go/cmd/test_run_and_stop.go
  tool/infra-testing-tool/go/cmd/test_start.go
  tool/infra-testing-tool/go/cmd/test_stop.go
  tool/infra-testing-tool/go/server/grpc/server.proto
  tool/infra-testing-tool/go/server/grpc/server/messaging.go
  tool/infra-testing-tool/go/server/grpc/server/server.go
  tool/infra-testing-tool/go/server/grpc/server/server.pb.go
  tool/infra-testing-tool/go/server/grpc/server/server_grpc.pb.go
  tool/infra-testing-tool/go/server/main.go
  tool/infra-testing-tool/go/server/testclient/main.go
Labels: 🔍 Ready for Review, enhancement

#4145 feat: Add a CLI to Tyber
  go.mod
  go/internal/messengerpayloads/handlers.go
  tool/go.mod
  tool/go.sum
  tool/tyber/go/bridge/bridge.go
  tool/tyber/go/cmd/manager.go
  tool/tyber/go/config/config.go
  tool/tyber/go/go.mod
  tool/tyber/go/go.sum
  tool/tyber/go/main.go
  tool/tyber/go/parser/parser.go
  tool/tyber/go/parser/persistence.go
Labels: 🔍 Ready for Review, enhancement

#4133 chore: new Crowdin updates
  go/localization/locales/ja-JP/localization.json
  js/packages/i18n/locale/ja-JP/messages.json
  js/packages/i18n/locale/zh-CN/messages.json
Labels: 🔍 Ready for Review, chore

#4155 fix: await messenger events stream
  js/packages/screens/account/Opening/openClients.effect.ts
Labels: bug, ✅ Approved

#4161 fix: no click mode in auth services
  go/pkg/bertyauth/services_auth_server.go
  go/pkg/bertyauth/services_auth_server_test.go
  go/pkg/bertyauth/services_auth_templates.go
  go/pkg/bertyauth/templates/authorize.html.tmpl
  go/pkg/bertyauth/templates/redirect.html.tmpl
Labels: bug, 🔍 Ready for Review, ✅ Approved
