Repository berty/berty, pull requests merged in 2022-06, with the labels that each got.

#4168 feat: add relay and p2p cmd to berty main command
  go/cmd/berty/main.go
  go/cmd/berty/p2p.go
  go/cmd/berty/relay.go
  go/cmd/berty/utils.go
Labels: 🔍 Ready for Review, enhancement

#4169 fix: js: In README, remove unneeded/outdated gomobile install instructions
  js/README.md
Labels: bug, 🔍 Ready for Review

#4157 fix: enable push notif by default
  go/pkg/bertymessenger/api.go
  js/ios/Podfile.lock
  js/package.json
  js/packages/components/chat/EnableNotificationsButton.tsx
  js/packages/i18n/locale/en-US/messages.json
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
  js/packages/redux/reducers/persistentOptions.reducer.ts
  js/packages/screens/account/Creating/CreatingAccount.tsx
  js/packages/screens/account/Deleting/DeletingAccount.tsx
  js/packages/screens/account/Opening/OpeningAccount.tsx
  js/packages/screens/account/Opening/prepareAccount.effect.ts
  js/packages/screens/chat/BlePermission/BlePermission.tsx
  js/packages/screens/chat/MultiMemberSettings/MultiMemberSettings.tsx
  js/packages/screens/chat/NotificationAndProximityPermissions/NotificationAndProximityPermissions.tsx
  js/packages/screens/chat/OneToOneSettings/OneToOneSettings.tsx
  js/packages/screens/chat/index.ts
  js/packages/screens/onboarding/CustomModeSettings/CustomModeSettings.tsx
  js/packages/screens/onboarding/DefaultMode/DefaultMode.tsx
  js/packages/screens/settings/Network/Network.tsx
  js/packages/screens/settings/Notifications/Notifications.tsx
  js/packages/screens/settings/SettingsHome/SettingsHome.tsx
  js/packages/utils/messenger/clients.ts
  js/packages/utils/notification/notif-push.ts
  js/packages/utils/react-native/asyncAlert.ts
  js/packages/utils/react-native/checkPermissions.ts
  js/packages/utils/react-native/index.ts
  js/packages/utils/remote-services/remote-services.ts
  js/patches/react-native-inappbrowser-reborn+3.6.3.patch
  js/web/craco.config.js
  js/web/src/polyfill/react-native-inappbrowser-reborn/index.tsx
  js/yarn.lock
Labels: bug, ✅ Approved

#4181 feat: ios notification filtering
  js/ios/Entitlements/ProdNS.entitlements
  js/ios/NotificationService/NotificationService.swift
  js/packages/utils/notification/notif-push.ts
Labels: 🔍 Ready for Review, enhancement

#4163 feat: implementation atomic input
  js/packages/components/create-group/CreateGroupFooter.priv.tsx
  js/packages/components/create-group/CreateGroupHeader.tsx
  js/packages/components/index.ts
  js/packages/components/inputs/ClearTouchable.priv.tsx
  js/packages/components/inputs/Icon.priv.tsx
  js/packages/components/inputs/Input.priv.tsx
  js/packages/components/inputs/InputWithIcon.priv.tsx
  js/packages/components/inputs/index.ts
  js/packages/components/inputs/interfaces.ts
  js/packages/components/inputs/large/LargeInput.tsx
  js/packages/components/inputs/large/LargeInputWithIcon.tsx
  js/packages/components/inputs/medium/MediumClearableInput.tsx
  js/packages/components/inputs/medium/MediumInput.tsx
  js/packages/components/inputs/small/SmallInput.tsx
  js/packages/components/inputs/wrapper/TouchableWrapper.priv.tsx
  js/packages/components/inputs/wrapper/TouchableWrapperWithIcon.priv.tsx
  js/packages/components/modals/AccordionAdd.modal.tsx
  js/packages/components/onboarding/SwiperCard.tsx
  js/packages/components/shared-components/Button.tsx
  js/packages/components/shared-components/ContactPicker.tsx
  js/packages/i18n/locale/en-US/messages.json
  js/packages/screens/chat/CreateGroupAddMembers/CreateGroupAddMembers.tsx
  js/packages/screens/chat/CreateGroupFinalize/CreateGroupFinalize.tsx
  js/packages/screens/chat/Home/components/Header.tsx
  js/packages/screens/chat/MultiMemberSettingsAddMembers/MultiMembersSettingsAddMembers.tsx
  js/packages/screens/onboarding/CreateAccount/components/CreateAccountBox.tsx
  js/packages/screens/settings/DeleteAccount/DeleteAccount.tsx
  js/packages/screens/settings/DeleteAccount/components/DeleteAccountContent.tsx
  js/packages/screens/settings/SettingsHome/components/EditMyProfile.tsx
  js/packages/screens/settings/SettingsHome/components/EditProfile.tsx
  js/packages/screens/settings/SettingsHome/components/ImagePic.tsx
  js/packages/screens/settings/SettingsHome/components/ImagePlaceholder.tsx
  js/packages/screens/settings/ThemeEditor/components/ThemeColorName.tsx
Labels: 🔍 Ready for Review, enhancement

#4164 feat: implementation atomic dropdown
  js/packages/components/dropdowns/Dropdown.priv.tsx
  js/packages/components/dropdowns/accounts/AccountsDropdown.tsx
  js/packages/components/dropdowns/index.ts
  js/packages/components/dropdowns/members/MembersDropdown.tsx
  js/packages/components/dropdowns/textual/TextualDropdown.tsx
  js/packages/components/index.ts
  js/packages/hooks/messenger.hooks.ts
  js/packages/redux/reducers/messenger.reducer.ts
  js/packages/redux/reducers/theme.reducer.ts
  js/packages/screens/chat/MultiMemberSettings/MultiMemberSettings.tsx
  js/packages/screens/settings/Accounts/Accounts.tsx
  js/packages/screens/settings/ThemeEditor/ThemeEditor.tsx
Labels: 🔍 Ready for Review, enhancement

#4182 feat: implementation atomic items
  js/packages/components/chat/EnableNotificationsButton.tsx
  js/packages/components/dropdowns/Dropdown.priv.tsx
  js/packages/components/dropdowns/accounts/AccountsDropdown.tsx
  js/packages/components/index.ts
  js/packages/components/items/DividerItem.tsx
  js/packages/components/items/IconWithText.priv.tsx
  js/packages/components/items/ItemSection.tsx
  js/packages/components/items/MenuItem.priv.tsx
  js/packages/components/items/Text.priv.tsx
  js/packages/components/items/floating/FloatingContainer.priv.tsx
  js/packages/components/items/floating/FloatingMenuItem.tsx
  js/packages/components/items/floating/FloatingMenuItemWithIcon.priv.tsx
  js/packages/components/items/floating/FloatingMenuItemWithIcon.tsx
  js/packages/components/items/floating/FloatingMenuItemWithPrimaryIcon.tsx
  js/packages/components/items/floating/FloatingMenuToggle.priv.tsx
  js/packages/components/items/floating/FloatingMenuToggle.tsx
  js/packages/components/items/floating/FloatingMenuToggleAlt.tsx
  js/packages/components/items/index.ts
  js/packages/components/items/interfaces.ts
  js/packages/components/items/section/MenuItem.tsx
  js/packages/components/items/section/MenuItemWithIcon.priv.tsx
  js/packages/components/items/section/MenuItemWithIcon.tsx
  js/packages/components/items/section/MenuToggle.tsx
  js/packages/components/items/section/MenuToggleWithIcon.priv.tsx
  js/packages/components/items/section/MenuToggleWithIcon.tsx
  js/packages/components/shared-components/SettingsButtons.tsx
  js/packages/i18n/locale/en-US/messages.json
  js/packages/navigation/stacks.tsx
  js/packages/navigation/types.ts
  js/packages/screens/chat/MultiMemberSettings/MultiMemberSettings.tsx
  js/packages/screens/chat/Share/Share.tsx
  js/packages/screens/onboarding/CustomModeSettings/CustomModeSettings.tsx
  js/packages/screens/settings/AboutBerty/AboutBerty.tsx
  js/packages/screens/settings/Accounts/Accounts.tsx
  js/packages/screens/settings/Appearance/Appearance.tsx
  js/packages/screens/settings/DevicesAndBackup/DevicesAndBackup.tsx
  js/packages/screens/settings/Network/Network.tsx
  js/packages/screens/settings/Notifications/Notifications.tsx
  js/packages/screens/settings/Security/Security.tsx
  js/packages/screens/settings/SettingsHome/SettingsHome.tsx
  js/packages/screens/settings/ThemeEditor/ThemeEditor.tsx
  js/packages/screens/settings/index.ts
Labels: 🔍 Ready for Review, enhancement

#4190 feat: add onboarding snapshot tests
  js/__mocks__/@react-navigation/elements.js
  js/__mocks__/lottie-react-native.js
  js/__mocks__/react-native-svg.js
  js/packages/components/shared-components/Toggle.tsx
  js/packages/components/shared-components/WebViews.tsx
  js/packages/screens/onboarding/CreateAccount/CreateAccount.test.tsx
  js/packages/screens/onboarding/CreateAccount/__snapshots__/CreateAccount.test.tsx.snap
  js/packages/screens/onboarding/CustomMode/CustomMode.test.tsx
  js/packages/screens/onboarding/CustomMode/__snapshots__/CustomMode.test.tsx.snap
  js/packages/screens/onboarding/CustomModeSettings/CustomModeSettings.test.tsx
  js/packages/screens/onboarding/CustomModeSettings/CustomModeSettings.tsx
  js/packages/screens/onboarding/CustomModeSettings/__snapshots__/CustomModeSettings.test.tsx.snap
  js/packages/screens/onboarding/DefaultMode/DefaultMode.test.tsx
  js/packages/screens/onboarding/DefaultMode/__snapshots__/DefaultMode.test.tsx.snap
  js/packages/screens/onboarding/GetStarted/__snapshots__/GetStarted.test.tsx.snap
  js/packages/screens/onboarding/SetupFinished/SetupFinished.test.tsx
  js/packages/screens/onboarding/SetupFinished/SetupFinished.tsx
  js/packages/screens/onboarding/SetupFinished/__snapshots__/SetupFinished.test.tsx.snap
  js/packages/screens/onboarding/WebViews/WebViews.test.tsx
  js/packages/screens/onboarding/WebViews/__snapshots__/WebViews.test.tsx.snap
  js/packages/screens/settings/MyBertyId/__snapshots__/MyBertyId.test.tsx.snap
  js/packages/utils/testing/renderScreen.test.tsx
Labels: ✅ Approved, enhancement

#4189 feat: add a tyber analyzer module
  go/internal/messengerdb/db.go
  go/pkg/bertyprotocol/api_app.go
  go/pkg/bertyprotocol/api_contactrequest.go
  go/pkg/bertyprotocol/store_message.go
  go/pkg/bertyprotocol/store_metadata.go
  tool/go.mod
  tool/go.sum
  tool/tyber/go/analyzer/analyzer.go
  tool/tyber/go/analyzer/contactrequest.go
  tool/tyber/go/analyzer/message.go
  tool/tyber/go/analyzer/report.go
  tool/tyber/go/cmd/manager.go
  tool/tyber/go/go.mod
  tool/tyber/go/go.sum
  tool/tyber/go/main.go
  tool/tyber/go/parser/parser.go
Labels: 🔍 Ready for Review, enhancement

#4194 feat: implement atomic chat input
  js/packages/components/chat/footer/ChatFooter.tsx
  js/packages/components/chat/footer/ChatTextInput.tsx
  js/packages/components/inputs/Input.priv.tsx
  js/packages/components/inputs/InputWithIcon.priv.tsx
  js/packages/components/inputs/StyledInput.priv.tsx
  js/packages/components/inputs/chat/ChatTextInput.tsx
  js/packages/components/inputs/chat/interface.ts
  js/packages/components/inputs/chat/reply/CancelReply.priv.tsx
  js/packages/components/inputs/chat/reply/ReplyMessageBar.priv.tsx
  js/packages/components/inputs/chat/reply/ReplyTargetAuthor.priv.tsx
  js/packages/components/inputs/chat/reply/interface.ts
  js/packages/components/inputs/chat/reply/reply-message/ReplyMessage.priv.tsx
  js/packages/components/inputs/chat/reply/reply-message/ReplyMessageWithAttachment.priv.tsx
  js/packages/components/inputs/index.ts
  js/packages/components/inputs/large/LargeInput.tsx
  js/packages/components/inputs/small/SmallInput.tsx
Labels: 🔍 Ready for Review, enhancement

#4202 fix: blue background on pending message
  js/packages/components/chat/message/UserMessage.tsx
  js/packages/components/inputs/large/LargeInput.tsx
  js/packages/components/inputs/large/LargeInputWithIcon.tsx
  js/packages/components/inputs/medium/MediumClearableInput.tsx
  js/packages/components/inputs/medium/MediumInput.tsx
  js/packages/components/inputs/small/SmallInput.tsx
  js/packages/screens/settings/DeleteAccount/components/DeleteAccountContent.tsx
Labels: bug, 🔍 Ready for Review

#4203 feat: analyze multimembergroups in Tyber
  go/internal/messengerpayloads/handlers.go
  tool/tyber/go/analyzer/analyzer.go
  tool/tyber/go/analyzer/contactrequest.go
  tool/tyber/go/analyzer/group.go
  tool/tyber/go/analyzer/message.go
  tool/tyber/go/analyzer/report.go
Labels: ✅ Approved, enhancement

#4198 feat: implementation atomic controls
  js/packages/components/Accordion.tsx
  js/packages/components/account/StreamProgress.tsx
  js/packages/components/account/index.ts
  js/packages/components/buttons/primary/PrimaryButton.priv.tsx
  js/packages/components/controls/index.ts
  js/packages/components/controls/progress-bar/StreamProgress.priv.tsx
  js/packages/components/controls/progress-bar/StreamProgress.tsx
  js/packages/components/controls/progress-bar/StreamProgressError.priv.tsx
  js/packages/components/controls/progress-bar/interfaces.ts
  js/packages/components/controls/tab-bar/TabBar.tsx
  js/packages/components/controls/tab-bar/TabBarItem.priv.tsx
  js/packages/components/controls/tab-bar/getTabList.ts
  js/packages/components/controls/tab-bar/interfaces.ts
  js/packages/components/controls/toggle/AltToggle.tsx
  js/packages/components/controls/toggle/Toggle.priv.tsx
  js/packages/components/controls/toggle/Toggle.tsx
  js/packages/components/controls/toggle/interfaces.ts
  js/packages/components/dropdowns/Dropdown.priv.tsx
  js/packages/components/dropdowns/accounts/AccountsDropdown.tsx
  js/packages/components/dropdowns/members/MembersDropdown.tsx
  js/packages/components/dropdowns/textual/TextualDropdown.tsx
  js/packages/components/index.ts
  js/packages/components/items/MenuItem.priv.tsx
  js/packages/components/items/Text.priv.tsx
  js/packages/components/items/interfaces.ts
  js/packages/components/items/section/MenuItem.tsx
  js/packages/components/items/section/MenuItemWithIcon.priv.tsx
  js/packages/components/items/section/MenuToggle.tsx
  js/packages/components/items/section/MenuToggleWithIcon.priv.tsx
  js/packages/components/shared-components/SettingsButtons.tsx
  js/packages/components/shared-components/TabBar.tsx
  js/packages/components/shared-components/Toggle.tsx
  js/packages/i18n/locale/en-US/messages.json
  js/packages/screens/account/Closing/ClosingAccount.tsx
  js/packages/screens/account/Importing/ImportingAccount.tsx
  js/packages/screens/account/Opening/OpeningAccount.tsx
  js/packages/screens/chat/ContactRequest/components/Request.tsx
  js/packages/screens/chat/ContactSettings/ContactSettings.tsx
  js/packages/screens/chat/ManageDeepLink/components/AddThisContact.tsx
  js/packages/screens/chat/ManageDeepLink/components/ManageGroupInvitation.tsx
  js/packages/screens/chat/SharedMedias/SharedMedias.tsx
  js/packages/screens/chat/SharedMedias/components/TabSwitch.tsx
  js/packages/screens/onboarding/CustomModeSettings/CustomModeSettings.tsx
  js/packages/screens/onboarding/CustomModeSettings/__snapshots__/CustomModeSettings.test.tsx.snap
  js/packages/screens/settings/MyBertyId/MyBertyId.test.tsx
  js/packages/screens/settings/MyBertyId/MyBertyId.tsx
  js/packages/screens/settings/MyBertyId/__snapshots__/MyBertyId.test.tsx.snap
Labels: 🔍 Ready for Review, enhancement

#4211 feat: remove members auto-generated display name
  go/internal/messengerdb/db.go
  js/packages/redux/reducers/messenger.reducer.ts
Labels: ✅ Approved, enhancement

#4213 fix: update /tool go.sum
  tool/go.sum
Labels: bug, 🔍 Ready for Review

#4207 Update README.md
  go/cmd/welcomebot/README.md
Labels: ✅ Approved

#4215 fix: push notifications
  go/pkg/bertymessenger/api.go
  go/pkg/bertyprotocol/api_push.go
  js/packages/utils/notification/notif-push.ts
Labels: bug, 🔍 Ready for Review

#4220 fix: dependabot labels and ssh workflow
  .github/dependabot.yml
  .github/workflows/ssh-runner.yml
Labels: bug, 🔍 Ready for Review

#4217 feat: implementation atomic suggestion
  js/packages/screens/chat/Home/components/Conversations.tsx
  js/packages/screens/chat/Home/components/conversation/ConversationButton.tsx
  js/packages/screens/chat/Home/components/conversation/ConversationDescStatus.tsx
  js/packages/screens/chat/Home/components/conversation/ConversationItem.tsx
  js/packages/screens/chat/Home/components/conversation/ConversationTitle.tsx
  js/packages/screens/chat/Home/components/conversation/MessageStatus.tsx
  js/packages/screens/chat/Home/components/suggestion/SuggestionButton.tsx
  js/packages/screens/chat/Home/components/suggestion/SuggestionDescStatus.tsx
  js/packages/screens/chat/Home/components/suggestion/SuggestionItem.tsx
  js/packages/screens/chat/Home/components/suggestion/SuggestionTitle.tsx
  js/packages/screens/chat/Home/components/suggestion/interfaces.ts
Labels: ✅ Approved, enhancement

#4210 feat: implementation atomic dropdowns 2
  js/packages/components/Accordion.tsx
  js/packages/components/dropdowns/Dropdown.priv.tsx
  js/packages/components/dropdowns/accounts/AccountsDropdown.tsx
  js/packages/components/dropdowns/index.ts
  js/packages/components/dropdowns/interfaces.ts
  js/packages/components/dropdowns/network/AddButton.priv.tsx
  js/packages/components/dropdowns/network/MenuToggleWithEdit.priv.tsx
  js/packages/components/dropdowns/network/NetworkAltDropdown.priv.tsx
  js/packages/components/dropdowns/network/NetworkDropdown.priv.tsx
  js/packages/components/dropdowns/network/bootstrap/BootstrapAltDropdown.tsx
  js/packages/components/dropdowns/network/bootstrap/BootstrapDropdown.tsx
  js/packages/components/dropdowns/network/bootstrap/BootstrapItems.priv.tsx
  js/packages/components/dropdowns/network/interfaces.ts
  js/packages/components/dropdowns/network/relay/RelayAltDropdown.tsx
  js/packages/components/dropdowns/network/relay/RelayDropdown.tsx
  js/packages/components/dropdowns/network/relay/RelayItems.priv.tsx
  js/packages/components/dropdowns/network/rendezvous/RendezvousAltDropdown.tsx
  js/packages/components/dropdowns/network/rendezvous/RendezvousDropdown.tsx
  js/packages/components/dropdowns/network/rendezvous/RendezvousItems.priv.tsx
  js/packages/components/dropdowns/textual/TextualDropdown.tsx
  js/packages/components/items/Text.priv.tsx
  js/packages/i18n/locale/en-US/messages.json
  js/packages/screens/onboarding/CustomModeSettings/CustomModeSettings.tsx
  js/packages/screens/onboarding/CustomModeSettings/__snapshots__/CustomModeSettings.test.tsx.snap
  js/packages/screens/onboarding/CustomModeSettings/components/Accordion.tsx
  js/packages/screens/settings/Network/Network.tsx
Labels: 🔍 Ready for Review, enhancement

#4185 fix: go/mini: Clarify message for compatibility with the app.
  go/README.md
  go/cmd/berty/mini.go
Labels: bug, ✅ Approved

#4219 feat: add version + devmode buttons in settings
  js/packages/components/items/interfaces.ts
  js/packages/components/items/section/MenuItemWithIcon.priv.tsx
  js/packages/i18n/locale/en-US/messages.json
  js/packages/redux/reducers/ui.reducer.ts
  js/packages/screens/settings/SettingsHome/SettingsHome.tsx
Labels: ✅ Approved, enhancement

#4231 chore: new Crowdin updates
  js/packages/i18n/locale/af-ZA/messages.json
  js/packages/i18n/locale/ar-SA/messages.json
  js/packages/i18n/locale/bg-BG/messages.json
  js/packages/i18n/locale/ca-ES/messages.json
  js/packages/i18n/locale/cs-CZ/messages.json
  js/packages/i18n/locale/da-DK/messages.json
  js/packages/i18n/locale/de-DE/messages.json
  js/packages/i18n/locale/el-GR/messages.json
  js/packages/i18n/locale/es-ES/messages.json
  js/packages/i18n/locale/et-EE/messages.json
  js/packages/i18n/locale/fi-FI/messages.json
  js/packages/i18n/locale/fr-FR/messages.json
  js/packages/i18n/locale/he-IL/messages.json
  js/packages/i18n/locale/hi-IN/messages.json
  js/packages/i18n/locale/hu-HU/messages.json
  js/packages/i18n/locale/id-ID/messages.json
  js/packages/i18n/locale/it-IT/messages.json
  js/packages/i18n/locale/ja-JP/messages.json
  js/packages/i18n/locale/ka-GE/messages.json
  js/packages/i18n/locale/ko-KR/messages.json
  js/packages/i18n/locale/my-MM/messages.json
  js/packages/i18n/locale/nl-NL/messages.json
  js/packages/i18n/locale/no-NO/messages.json
  js/packages/i18n/locale/pl-PL/messages.json
  js/packages/i18n/locale/pt-BR/messages.json
  js/packages/i18n/locale/pt-PT/messages.json
  js/packages/i18n/locale/ro-RO/messages.json
  js/packages/i18n/locale/ru-RU/messages.json
  js/packages/i18n/locale/sl-SI/messages.json
  js/packages/i18n/locale/sr-Cyrl/messages.json
  js/packages/i18n/locale/sv-SE/messages.json
  js/packages/i18n/locale/te-IN/messages.json
  js/packages/i18n/locale/tr-TR/messages.json
  js/packages/i18n/locale/uk-UA/messages.json
  js/packages/i18n/locale/vi-VN/messages.json
  js/packages/i18n/locale/zh-CN/messages.json
  js/packages/i18n/locale/zh-TW/messages.json
Labels: 🔍 Ready for Review, chore

#4233 fix: quick fix for StringOptionInput component
  js/packages/components/shared-components/SettingsButtons.tsx
Labels: bug, ✅ Approved

#4216 feat: use DiscoverAsync in tinder
  go/internal/tinder/driver_rdv.go
  go/internal/tinder/options.go
  go/pkg/bertyprotocol/tinder_swiper.go
Labels: 🔍 Ready for Review, enhancement

#4236 docs: update label name for bug template
  .github/ISSUE_TEMPLATE/bug_template.yml
Labels: ✅ Approved, documentation

#4227 feat: implement refresh contact method
  api/protocoltypes.proto
  api/protocoltypes.yaml
  docs/apis/protocoltypes.md
  docs/apis/protocoltypes.swagger.json
  docs/gen.sum
  go/cmd/berty/mini/view_group_incoming.go
  go/cmd/berty/mini/view_group_outgoing.go
  go/gen.sum
  go/internal/ipfsutil/conn_logger.go
  go/internal/ipfsutil/mdns.go
  go/internal/tinder/driver_localdiscovery.go
  go/internal/tinder/options.go
  go/internal/tinder/watchdogs_discoverer.go
  go/pkg/bertyprotocol/api_contact.go
  go/pkg/bertyprotocol/contact_request_manager.go
  go/pkg/bertyprotocol/service.go
  go/pkg/bertyprotocol/tinder_swiper.go
  go/pkg/protocoltypes/protocoltypes.pb.go
  go/pkg/protocoltypes/protocoltypes.pb.gw.go
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  js/packages/components/InfosChat.tsx
  js/packages/grpc-bridge/welsh-clients.gen.ts
  js/packages/hooks/methods/methods.gen.ts
  js/packages/hooks/ui.hooks.ts
  js/packages/i18n/locale/en-US/messages.json
  js/packages/mock-services/mockedServicesInterfaces.gen.ts
  tool/berty-mini-local-helper/Makefile
Labels: 🔍 Ready for Review, enhancement
