Repository berty/berty, pull requests merged in 2022-02, with the labels that each got.

#3891 feat(go): add GetInteractionReactionsForEmoji to messenger service
  api/messengertypes.proto
  api/messengertypes.yaml
  config/config.gen.json
  docs/apis/messengertypes.md
  docs/apis/messengertypes.swagger.json
  docs/gen.sum
  go/gen.sum
  go/internal/config/config.gen.go
  go/internal/messengerdb/db.go
  go/internal/messengerdb/db_test.go
  go/pkg/bertymessenger/api.go
  go/pkg/messengertypes/messengertypes.pb.go
  go/pkg/messengertypes/messengertypes.pb.gw.go
  js/gen.sum
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  js/packages/config/global.gen.js
  js/packages/grpc-bridge/welsh-clients.gen.ts
  js/packages/store/types.gen.ts
Labels: 🔍 Ready for Review, enhancement

#3888 fix: fix scroll problems on Android messages in conversations
  js/packages/components/chat/MessageList.tsx
  js/packages/components/chat/message/UserMessage.tsx
  js/packages/store/hooks.ts
Labels: bug, ✅ Approved

#3869 feat: account daemon + electron showcase
  .github/workflows/mac.yml
  api/accounttypes.proto
  api/accounttypes.yaml
  docs/gen.sum
  go/Makefile
  go/cmd/berty/account_daemon.go
  go/cmd/berty/main.go
  go/cmd/berty/scenario_test.go
  go/framework/bertybridge/bridge.go
  go/gen.sum
  go/internal/grpcserver/grpc_server.go
  go/internal/initutil/logger.go
  go/internal/initutil/manager.go
  go/internal/initutil/node.go
  go/internal/logutil/grpc_logger.go
  go/pkg/accounttypes/accounttypes.pb.go
  go/pkg/accounttypes/accounttypes.pb.gw.go
  go/pkg/bertyaccount/service.go
  go/pkg/bertyaccount/service_account.go
  go/pkg/bertyauth/services_auth.go
  js/Makefile
  js/electron-app/.gitignore
  js/electron-app/README.md
  js/electron-app/craco.config.js
  js/electron-app/package.json
  js/electron-app/public/favicon.ico
  js/electron-app/public/icon.icns
  js/electron-app/public/index.html
  js/electron-app/public/logo192.png
  js/electron-app/public/logo512.png
  js/electron-app/public/manifest.json
  js/electron-app/public/robots.txt
  js/electron-app/src-main/main.ts
  js/electron-app/src-main/preload.ts
  js/electron-app/src/App.css
  js/electron-app/src/App.test.tsx
  js/electron-app/src/App.tsx
  js/electron-app/src/index.css
  js/electron-app/src/index.tsx
  js/electron-app/src/react-app-env.d.ts
  js/electron-app/src/setupTests.ts
  js/electron-app/tsconfig.json
  js/electron-app/tsconfig.main.json
  js/electron-app/yarn.lock
  js/gen.sum
  js/package.json
  js/packages/api/root.pb.d.ts
  js/packages/api/root.pb.js
  js/packages/grpc-bridge/rpc/rpc.native.web.ts
  js/packages/grpc-bridge/welsh-clients.gen.ts
  js/yarn.lock
Labels: 🔍 Ready for Review, enhancement

#3896 chore: update go-orbit-db to 1.14.1
  go.mod
  go.sum
  go/internal/initutil/orbitdb.go
  go/pkg/bertyprotocol/service.go
Labels: 🔍 Ready for Review, chore

#3907 fix: improve and fix integration test
  go/internal/tinder/watchdogs_discoverer.go
  tool/compose-integration/docker-compose.yml
Labels: bug, ✅ Approved

#3889 feat: jump to a group after accepting group invitation
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/berty-i18n/locale/fr-FR/messages.json
  js/packages/components/chat/message/MessageInvitation.tsx
Labels: 🔍 Ready for Review, enhancement

#3908 chore(ci): ruby pinning and simpler caching
  .github/workflows/ios.yml
  js/ios/.ruby-version
Labels: ✅ Approved, chore

#3853 chore(deps): bump bundletool from 1.2.0 to 1.8.2
  .github/workflows/android.yml
Labels: 🔍 Ready for Review, dependencies

#3893 feat: remove console methods calls in production
  js/babel.config.js
  js/package.json
  js/yarn.lock
Labels: 🔍 Ready for Review, enhancement

#3884 feat: add spinner at group creation
  js/packages/components/main/CreateGroupFinalize.tsx
  js/packages/components/main/CreateGroupFooter.tsx
  js/packages/store/methods.ts
  js/packages/store/types.gen.ts
Labels: 🔍 Ready for Review, enhancement

#3885 fix: scrollview not filling up the whole screen on android
  js/packages/components/main/home/Home.tsx
Labels: bug, 🔍 Ready for Review

#3919 fix: ruby missing ImageOS version
  .github/workflows/ios.yml
Labels: bug, ✅ Approved

#3895 feat: interaction's reactions
  js/.svgrrc
  js/packages/assets/add_emoji.svg
  js/packages/components/chat/ConversationModalContext.tsx
  js/packages/components/chat/MultiMember.tsx
  js/packages/components/chat/OneToOne.tsx
  js/packages/components/chat/ReplyReactionContext.tsx
  js/packages/components/chat/message/Reactions.tsx
  js/packages/components/chat/message/UserMessage.tsx
  js/packages/components/shared-components/AnimatedNumber.tsx
  js/packages/redux/reducers/messenger.reducer.ts
  js/yarn.lock
Labels: ✅ Approved, enhancement

#3892 fix: request camera and gallery permissions in chat menu footer
  js/packages/berty-i18n/locale/en-US/messages.json
  js/packages/berty-i18n/locale/fr-FR/messages.json
  js/packages/components/chat/EnableNotificationsButton.tsx
  js/packages/components/chat/footer/ChatFooter.tsx
  js/packages/components/chat/footer/file-uploads/AddFileMenu.tsx
  js/packages/components/chat/footer/record/RecordComponent.tsx
  js/packages/components/main/Permissions.tsx
  js/packages/components/main/home/Home.tsx
  js/packages/components/onboarding/AdvancedSettings.tsx
  js/packages/components/onboarding/CreateAccount.tsx
  js/packages/navigation/types.ts
  js/packages/rnutil/checkPermissions.ts
  js/packages/store/effectableCallbacks.ts
Labels: bug, 🔍 Ready for Review

#3920 fix: remove multiple subscribe
  go/pkg/bertyreplication/services_replication.go
Labels: bug, ✅ Approved

#3916 chore(ci): disable self-hosted runners until fixed
  .github/workflows/ios.yml
Labels: ⚠️ Changes requested, chore

#3933 fix: do not start mdns service if no multicast interface is found
  go/internal/initutil/ipfs.go
  go/internal/ipfsutil/mdns.go
Labels: bug, ✅ Approved

#3934 chore: debug integration
  go/cmd/berty-integration/main.go
  tool/compose-integration/Makefile
  tool/compose-integration/docker-compose.yml
Labels: 🔍 Ready for Review, chore, WIP
